### ISSUE TITLE
[question] HASS Discovery and door locks 

### ISSUE THREAD

**Issue by brettyj** [OpenZWave/Zwave2Mqtt#101]
Hey,

I've been playing with the hass discovery, and it works well. The problem is my door lock is reported as a binary sensor, so it reports its state to HASS but I can't control it from HASS. How do I fix this? 

Thanks

**Comment by thundergreen** [comment]
Has been fixed here apparently. https://github.com/OpenZWave/Zwave2Mqtt/issues/93

did not het the time t check this. maybe you can give it a shot?

**Comment by robertsLando** [comment]
@brettyj This is fixed now, check latest commits :)

**Comment by thundergreen** [comment]
@robertsLando  could you please push a new release then as hassio needs release to update its component automatically

**Comment by brettyj** [comment]
@robertsLando unfortunately this doesn't seem to have fixed the issue for me - my lock is still reporting as a binary_sensor

**Comment by thundergreen** [comment]
ok "good" to know ... do you think it will be possible and be fixed?

**Comment by robertsLando** [comment]
Try to check the discovery payload on hass devices table and paste it there

Daniel

**Comment by thundergreen** [comment]
As I never used Zwave2MQTT I don't know what you mean in fact. BUt i am willing to help to get this running. Where do i have to watch?

**Comment by robertsLando** [comment]
You need to install zwave2mqtt and than after scan is complete select the node with the lock value, and go to hassdevices table of the node to check the discovery payload that has been sent for the lock. 

Daniel

**Comment by x99percent** [comment]
Here's mine. Shows up as a binary_sensor.

`{
  "type": "binary_sensor",
  "object_id": "lock",
  "discovery_payload": {
    "payload_on": false,
    "payload_off": true,
    "value_template": "{{ value_json.value }}",
    "device_class": "lock",
    "state_topic": "homeassistant/kitchen/side_door_lock/98/1/0",
    "json_attributes_topic": "homeassistant/kitchen/side_door_lock/98/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_kitchen-side_door_lock"
      ],
      "manufacturer": "Assa Abloy",
      "model": "0x0000",
      "name": "Yale Touchscreen Deadbolt (YRD220)",
      "sw_version": "80.32"
    },
    "name": "kitchen-side_door_lock_lock",
    "unique_id": "zwave2mqtt_kitchen-side_door_lock_3-98-1-0"
  },
  "discoveryTopic": "binary_sensor/kitchen-side_door_lock/lock/config",
  "values": [
    "98-1-0"
  ],
  "persistent": false,
  "id": "binary_sensor_lock"
}`

**Comment by robertsLando** [comment]
@brettyj @x99percent Please be sure you are using latest version from master, I have checked the code and it should work. 

Here I make the check https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L670
Here are the constants (98 command class is 62 in hex) https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Constants.js#L137

**Comment by thundergreen** [comment]
@robertsLando As I am using Hassio addon I need aa new release to test. Maybe you could make a beta repo to test it?

**Comment by robertsLando** [comment]
@thundergreen It is present in the last release 2.0.3

**Comment by thundergreen** [comment]
OK thanks .. I will ask hassio devs to pull latest release.. I'll report if it works

**Comment by x99percent** [comment]
Shows up as a switch in 2.0.3

```
{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "homeassistant/kitchen/side_door/98/1/0/set",
    "state_topic": "homeassistant/kitchen/side_door/98/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_kitchen-side_door"
      ],
      "manufacturer": "Assa Abloy",
      "model": "0x0000",
      "name": "Yale Touchscreen Deadbolt (YRD220)",
      "sw_version": "80.32"
    },
    "name": "kitchen-side_door_switch",
    "unique_id": "zwave2mqtt_kitchen-side_door_3-98-1-0"
  },
  "discoveryTopic": "switch/kitchen-side_door/switch/config",
  "values": [
    "98-1-0"
  ],
  "persistent": false,
  "id": "switch_switch"
}
```

**Comment by brettyj** [comment]
Hey,

Sorry I thought I had 2.0.3 but the docker hadn't updated - it is coming up as a switch now

Sorry to be that guy though, but this seems wrong. In HASS you can mark something as a "lock" and it will show up like this (this is how I have it setup manually in HASS)
![image](https://user-images.githubusercontent.com/1395855/63613474-c62daa00-c5d8-11e9-87c9-cd6ac175a484.png)
![image](https://user-images.githubusercontent.com/1395855/63613485-ce85e500-c5d8-11e9-90fb-9245e7755169.png)
![image](https://user-images.githubusercontent.com/1395855/63613505-d5145c80-c5d8-11e9-884d-4570375a7d72.png)

Is it possible to use this with the auto discovery? A switch doesn't feel right for a door lock.

**Comment by robertsLando** [comment]
Hi @brettyj , You are right, I don't use hass so I didn't even know locks exists :) I will fix this, just a question, I don't understand why you have used that value template, why don't just use `{{value_json.value}}` ?

**Comment by robertsLando** [comment]
@brettyj Check it now, and thanks for providing your working template :)
