### ISSUE TITLE
[question] Setting up Fibaro Dimmer with Home Assistant

### ISSUE THREAD

**Issue by foxy82** [OpenZWave/Zwave2Mqtt#104]
I'm on zwave2mqtt 2.0.2 and i'm trying to setup a Fibaro Dimmer 2 and seem to hit some problem.

The documentation isn't clear but if using home assistant auto discovery do I need to set the Payload Type to "Entire Z-Wave Value Object"? As it seems that the auto discovery template that appears on a node is expecting a JSON object? 

It seems that changing this setting in the gateway config doesn't force a new publish instead I have to restart the docker container each time this value is changed - can that be fixed? Or a restart option added? 

Also on a restart where this setting is changed and retain is on then the old message is retained until you toggle every light. Can a status be republished on zwave2mqtt restart when this setting is changed?

**Comment by robertsLando** [comment]
@foxy82 Hass integration works with all gateway types as it parse discovery templates based on the gateway type. Changing that configuration should force a new publish as when you click on "Update" from settings all connections are closed and a new scan starts on zwave network like at start.
