### ISSUE TITLE
[bug] Fibaro Roller Shutter HA integration - discovers as a light

### ISSUE THREAD

**Issue by foxy82** [OpenZWave/Zwave2Mqtt#105]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2
Openzwave Version: 1.4.1

**Describe the bug**

I have added a Fibaro Roller Shutter 2 to my network with HA inegration enabled. The roller shutter is reported as a light to HA.

**Expected behavior**

Expect it to be reported as a cover

**Comment by foxy82** [comment]
This config works for the position.

`
cover:
  - platform: mqtt
    name: "MyWindow"
    command_topic: "zwave2mqtt/MyWindow/38/1/0/set"
    position_topic: "zwave2mqtt/MyWindow/38/1/0"
    set_position_topic: "zwave2mqtt/MyWindow/38/1/0/set"
    value_template: "{{ (value_json.value / 99 * 100) | round(0) }}"
    position_open: 99
    position_closed: 0
    #payload_open: "up"
    #payload_close: "down"
    #payload_stop: "stop"
    payload_open: "99"
    payload_close: "0"
`

However open/close/stop buttons don't really work - they will just open the window all the way/shut it all the way and close doesn't work. Which is possibly related to figuring out the Bright/Dim from my other question. https://github.com/OpenZWave/Zwave2Mqtt/issues/106

**Comment by robertsLando** [comment]
To choose the correct type of a value I use [this](https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml) file that contains all specifications for value classes and indexes. Unfortunally not all devices respect this specification, this is why I have created the hassDevices section where you can customize the discovery payload of each value. Remember to press on save at the end to make the changes persistents so the values will be automatically rediscovered at next retart

**Comment by Fishwaldo** [comment]
I’m sure how the discover component works but Jayne another option is the Device Classes? Available via the Generic/Specific and Plus types in the API?

**Comment by robertsLando** [comment]
Is there a way I can get device classes using ozw-shared?

**Comment by Fishwaldo** [comment]
GetNodeBasic/GetNodeGeneric/GetNodeSpecific are what you are looking for. 
Also GetNodeDeviceType/GetNodePlusType May help.

**Comment by rflx18** [comment]
@foxy82  did you fix the issue? i have the same issues in my setup

**Comment by foxy82** [comment]
No - at the point where I had to remove/add it from the network it became a real hassle so I haven't done it yet. See here: https://github.com/OpenZWave/Zwave2Mqtt/issues/123

**Comment by rflx18** [comment]
> No - at the point where I had to remove/add it from the network it became a real hassle so I haven't done it yet. See here: #123

if we remove and add it again the issue is fixed? i tried old docker verison with openzwave 1.4 and the issue is the same

**Comment by foxy82** [comment]
The suggestion is to try 1.6 so use a newer docker and remove/readd.

**Comment by spierenburg** [comment]
just did a fresh install with 1.6.. doesn't work unfortunately
