### ISSUE TITLE
[question] What do I need to do to call BRIGHT / DIM buttons?

### ISSUE THREAD

**Issue by foxy82** [OpenZWave/Zwave2Mqtt#106]
In the UI I can see Bright / Dim buttons for my Fibaro Rollershutter. When I click them it opens/closes the shutter. What do I need to send on MQTT to do the same?

I've tried ON, OFF, on, off, On, Off, TRUE, True, true, FALSE, False, false, 0, 1, BRIGHT, Bright, bright, DIM, Dim, dim. None of them seem to work.

**Comment by robertsLando** [comment]
For buttons send boolean `true`. Example: `{value: true}`

**Comment by foxy82** [comment]
Does it have to be a JSON object or will a message of just "true" work?

**Comment by robertsLando** [comment]
Try with a json object because if you send a raw value it will be read as a string

Daniel
