### ISSUE TITLE
Hass discovery thermostat and garage doors

### ISSUE THREAD

**Issue by rafale77** [OpenZWave/Zwave2Mqtt#109]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.3
Openzwave Version: 1.6

**Describe the bug**
Thermostat (Remotec ZTS500) shows reported device to Hass as only a temperature
Garage door opener reports no device at all.

**To Reproduce**

Build from master repo for both openzwave library and zwave2mqtt

**Expected behavior**
zwave2mqtt to recognize the devices and transmit the device discovery info through json

**Comment by robertsLando** [comment]
For the thermostat you need to provide me the device id of the device
Fot the garage door opener reports the valueid of the reports
