### ISSUE TITLE
[feat] Remove redundant bits of entity names

### ISSUE THREAD

**Issue by x99percent** [OpenZWave/Zwave2Mqtt#110]
If I have a lock that is named `front_door`, Zwave2MQTT will want to add it to Home Assistant as `lock.front_door_lock`, instead of just `lock.front_door`. 

Is there any way to work around this behavior? Manual edits to the discovery JSON don't aren't saved between container restarts.

**Comment by robertsLando** [comment]
Ti make manual edits persistent between restarts you need to press in store button 

Daniel

**Comment by robertsLando** [comment]
In readme.md everything is well documented (almost everything) and this is documented, I suggest you to search the answer in readme before asking or before trying things to prevent errors and time lost

Daniel

**Comment by robertsLando** [comment]
They are part of material deisgn: 

https://vuetifyjs.com/en/components/buttons#flat


Daniel

**Comment by robertsLando** [comment]
@x99percent Did you fixed your problem?

**Comment by x99percent** [comment]
Yeah, I got everything straightened out.
