### ISSUE TITLE
ZMNHCDx Flush Shutter mapping for HA

### ISSUE THREAD

**Issue by DavZero** [OpenZWave/Zwave2Mqtt#111]
Hi,

All my window cover are recognize as dimmer in HA with the discovery activated.
All my device is "ZMNHCDx Flush Shutter (Qubino (Goap))" (correctly identify in Zwave2Mqtt interface)
If I check the JSon send to mqtt, Il find 7 "subdevice" :
4 powers sensor, 1 water sensor, 1 switch_switch and 1 dimmer_ligth.

Where must I change something to correctly map this device to a cover instead of dimmer_ligth?

Thanks

**Comment by robertsLando** [comment]
Go to hass devices table, manually edit it and than press store to make changes persistent. My suggestion is to add your device to `/hass/devices` file and send a pull request with your changes. So you don't need to edit all your devices. More info here: https://github.com/OpenZWave/Zwave2Mqtt#custom-components

**Comment by DavZero** [comment]
Thanks for your response,

So I start to manually integrate this "entity" in HA in order to validate the json to send to the discovery topic.

But I encoutered a problem, HA MQTT COVER allow user to define a command_topic and a position_topic. It allow too to define paylod to send to each topic (value for position_open, position_close and paylod for open,close and stop command)

For the position topic, all works as excpected because there is only on topic for that in ZWaveToMQTT and send the position to the set subtopics works, but for the command topic, there is no equivalence in ZWave2MQTT. 
We could use the position topic as command topic and send 0 for closing and 99 for opening but I haven't find any way to define the stop command).

In order to acheive this, I think that the MQTT cover component in HA should provide a open_topic/close_topic and stop_topic. By doing this, we could map theses topics with the topics 38/1/1, 38/1/2 and 38/1/1 (or 38/1/2, because send an order when moving stop the cover).
Do you agree with that or there is some tricks I haven't seen which allow us to do this kind of thing without changing anything in HA MQTT Cover component?

**Comment by robertsLando** [comment]
> Command_Class 38 are define as ligth not depending to the specific device class

To answer this question please check [FAQ](https://github.com/OpenZWave/Zwave2Mqtt#question-faq) section in readme (question 2)

This is the map I use for covers in `hass/devices.js`

```json
{
  type: 'cover',
  object_id: 'position',
  values: ['38-1-0'],
  discovery_payload: {
    command_topic: "38-1-0",
    position_topic: "38-1-0",
    set_position_topic: "38-1-0",
    value_template: "{{ (value_json.value / 99 * 100) | round(0) }}",
    position_open: 99,
    position_closed: 0,
    payload_open: "99",
    payload_close: "0"
  }
}
```
