### ISSUE TITLE
Can I only setup Z-Wave (and not MQTT and Gateway)?

### ISSUE THREAD

**Issue by Tazintosh** [OpenZWave/Zwave2Mqtt#112]
Hi,

I'm using Node-RED with node-red-contrib-homekit-bridged palette to control my non-officials HomeKit devices.
I'm planning to communicate with my Z-Wave devices using the node-red-contrib-openzwave-am palette.
Now, I'm searching for a nice way to configure my Z-Wave devices and network  (and only that).
I found Zwave2Mqtt and after successful installation, I'm trying to apply my Z-Wave settings.
But it won't allow me to proceed because "my configuration contains errors".
I guess that's because it wants me to configure both the MQTT and Gateway (I see required fields).
Can I only setup Z-Wave (and not MQTT and Gateway)?

Thanks for your input.

**Comment by robertsLando** [comment]
Just fill all mqtt options with dummy values. If the broker doesn't exists it will never publish any value but all zwave stuff will still work
