### ISSUE TITLE
Schlage Door Lock change user codes

### ISSUE THREAD

**Issue by ksuclipse** [OpenZWave/Zwave2Mqtt#113]
trying to figure out how to get back the ability to change door lock codes.  i see nothing under the gui but on the mqtt side there is a topic 99/1 that seems to hold the data.  i believe its supposed to be in hex but its returning an array of numbers.  Any thoughts on how to get into this functionality?

**Comment by robertsLando** [comment]
Never got a device that uses that class so I don't know how to handle that (should be COMMAND_CLASS_USER_CODE 0x63) Maybe @Fishwaldo could help?

**Comment by Fishwaldo** [comment]
In 1.4 it’s exposed as a Raw Byte string. For some devices you can convert to ASCII to get the value, for others like Tag Readers it’s a series of bytes. There was ambiguity from the specs in how data should be represented. 

In 1.6 by default it’s exposed as a ValueString. This works for 75% of the devices on the market. For those 25% we can set a option in the config file to also expose the value as a Raw Bytes. (To handle those devices that don’t follow the specifications exactly now that it’s clarified). 

Also the way codes are “cleared” has changed in 1.6. The release notes has details.

**Comment by ksuclipse** [comment]
So would you recommend i build my own image of zwave2mqtt w/ 1.6 instead of 1.4?

**Comment by Fishwaldo** [comment]
Forward thinking 1.6 is the best, but @robertlando has to confirm if the CC is supported and if ValueRAW works for those “weird” devices.

**Comment by robertsLando** [comment]
I think @ksuclipse could give a try with his own built image using ozw 1.6 and than tell if it works

**Comment by ksuclipse** [comment]
still going to try this, unfortunately havent had time

**Comment by ksuclipse** [comment]
build new docker image off of most recent commit and swapped out for 1.6.  unfortunately no go, nothing came up like it should have so theres still a lot of inconsistencies w/ 1.6 and openzwave

**Comment by robertsLando** [comment]
Need to make 1.6 fully supported on openzwave-shared in order to make it supported on zwave2mqtt 

Daniel

**Comment by visnaut** [comment]
@ksuclipse Using the [latest commits of Zwave2Mqtt & OZW](https://github.com/robertsLando/Zwave2Mqtt-docker/issues/12#issuecomment-578588029), and with two BE469's and one BE469ZP, I am able to:
- See all 30 user code fields (Class ID 99, Instance 1)
- Set individual codes as numbers in the UI (i.e.: "9999")
- Unset codes

Curiously, the older BE469s do not report the actual values of each user code when they are polled. Just "******" for each one. But the newer BE469ZP shows the user codes as-is directly in the UI.

**Comment by robertsLando** [comment]
@visnaut Thanks
