### ISSUE TITLE
[help] - custom devices - Eurotronics Spirit Z - HomeAssistant 

### ISSUE THREAD

**Issue by Munsio** [OpenZWave/Zwave2Mqtt#114]
Hi,

I use hass.io and downloaded the zwave2mqtt addon and modified it (rebuilt on NUC) to symlink the devices.js into the config file so that i am able to customize the devices.

But unfortunately home assistant does not recognize them as climate devices.

Here is my custom devices.js
```
/* eslint-disable quotes */

// Place here repeated patterns
var FAN_DIMMER = {
  type: 'fan',
  object_id: 'dimmer',
  values: ['38-1-0'],
  discovery_payload: {
    command_topic: "38-1-0",
    speed_command_topic: "38-1-0",
    speed_state_topic: "38-1-0",
    state_topic: "38-1-0",
    speeds: ["off", "low", "medium", "high"],
    payload_low_speed: 24,
    payload_medium_speed: 50,
    payload_high_speed: 99,
    payload_off: 0,
    payload_on: 255,
    state_value_template: "{% if (value_json.value | int) == 0 %} 0 {% else %} 255 {% endif %}",
    speed_value_template: "{% if (value_json.value | int) == 0 %}  0  {% elif (value_json.value | int) <= 32 %}  24  {% elif (value_json.value | int) <= 66 %} 50 {% elif (value_json.value | int) <= 99 %} 99 {% endif %}"
  }
}

var CLIMATE_SPIRITZ = {
  type: 'climate',
  object_id: 'thermostat',
  values: ['64-1-0', '49-1-1', '67-1-1', '67-1-7', '67-1-11'],
  mode_map: {
      'off': 'Off', 
      'heat': 'Heat (Default)',
      'heat_eco': 'Heat Eco',
      'heat_power': 'Heat Power'
  },
  setpoint_topic: { "Heat (Default)": '67-1-1', "Heat Eco": '67-1-11', "Heat Power": '67-1-7' },
  default_setpoint: '67-1-1',
  discovery_payload: {
      min_temp: 15,
      max_temp: 30,
      modes: ['off', 'heat', 'heat_eco', 'heat_power'],
      mode_state_topic: '64-1-0',
      mode_command_topic: true,
      current_temperature_topic: '49-1-1',
      current_temperature_template: '{{ value_json.value }}',
      temperature_state_template: '{{ value_json.value }}',
      temperature_command_topic: true
  }
}

module.exports = {
  '411-1-1': [
    { // Heatit Thermostat TF 021 (ThermoFloor AS)
      type: 'climate',
      object_id: 'thermostat',
      values: ['64-1-0', '49-1-1', '67-1-1', '67-1-2'],
      mode_map: { 'off': 'Off', 'heat': 'Heat (Default)', 'cool': 'Cool' },
      setpoint_topic: { "Heat (Default)": '67-1-1', "Cool": '67-1-2' },
      default_setpoint: '67-1-1',
      discovery_payload: {
        min_temp: 15,
        max_temp: 30,
        modes: ['off', 'heat', 'cool'],
        mode_state_topic: '64-1-0',
        mode_command_topic: true,
        current_temperature_topic: '49-1-1',
        current_temperature_template: '{{ value_json.value }}',
        temperature_state_template: '{{ value_json.value }}',
        temperature_command_topic: true
      }
    }
  ],
  '148-1-3': [CLIMATE_SPIRITZ],
  '148-2-3': [CLIMATE_SPIRITZ],
  '148-3-3': [CLIMATE_SPIRITZ],
  '99-12340-18756': [FAN_DIMMER], // GE 1724 Dimmer
  '99-12593-18756': [FAN_DIMMER] // GE 1724 Dimmer
}

```

I used your thermostat config file and modified it so it should work with the spirit-z ones.
I got the manufacturer ids from here:
https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L515

Hope you could help me.

Thanks in advance

**Comment by arjenhiemstra** [comment]
I was trying the same thing this weekend, after a few iterations ended up with something like this (see my temporary fork for the full code):

  '328-1-3': [
    { // EUROtronic Spirit
      type: 'climate',
      object_id: 'thermostat',
      values: ['64-1-0', '49-1-1', '67-1-1', '67-1-11'],
      mode_map: { 'off': 'Off', 'heat': 'Heat', 'auto': 'Heat Eco' },
      setpoint_topic: { "Heat": '67-1-1', "Heat Eco": '67-1-11' },
      default_setpoint: '67-1-1',
      discovery_payload: {
        min_temp: 11,
        max_temp: 25,
        modes: ['off', 'heat', 'auto'],
        mode_state_topic: '64-1-0',
        mode_command_topic: true,
        current_temperature_topic: '49-1-1',
        current_temperature_template: '{{ value_json.value }}',
        temperature_state_template: '{{ value_json.value }}',
        temperature_command_topic: true
      }
    }
  ],  

Note that you need to translate de manufacturer code from HEX in "manufacturer_specific.xml" to DEC in this file, otherwise your device will never be recognized.

The MQTT implementation of HASS is somewhat limited:
- The mode map can only contain these or a subset of these values: [“auto”, “off”, “cool”, “heat”, “dry”, “fan_only”], so not all options of the spirit device translate to a HASS MQTT HVAC device.
- HASS always posts one of these mope map values as command in the command topic. You need to do some translation in HASS of Node-red to circumvent this (until HASS implements a more complete MQTT HVAC solution).


For now I ended up with a manual config of all my spiritz in HASS like this:

  - platform: mqtt
    name: "Thermostaat Badkamer"
    unique_id: "thermostaat_badkamer"    
    qos: 0
    modes:
      - heat
      - 'off'
    mode_state_topic: "zwave2mqtt/badkamer/thermostaat/64/1/0" 
    mode_state_template: >
      {% set values = {'Off':'off','Heat':'heat'} %} 
      {{ values[value_json.value] if value_json.value in values.keys() else 'failed' }}
    mode_command_topic: "nodered/badkamer/thermostaat/mode/set"
    current_temperature_template: "{{ value_json.value }}"
    current_temperature_topic: "zwave2mqtt/badkamer/thermostaat/49/1/1"
    min_temp: 11
    max_temp: 25
    temp_step: 0.5
    temperature_state_topic: "zwave2mqtt/badkamer/thermostaat/67/1/1"
    temperature_state_template: "{{ value_json.value }}"
    temperature_command_topic: "zwave2mqtt/badkamer/thermostaat/67/1/1/set"

**Comment by Munsio** [comment]
> Note that you need to translate de manufacturer code from HEX in "manufacturer_specific.xml" to DEC in this file, otherwise your device will never be recognized.

This should be in the Readme.
Will try again later that day if it is working
Thanks @arjenhiemstra

**Comment by robertsLando** [comment]
Actually I’m on vacation, will answer to all questions/issues next week. Please feel free to open a PR if you have supported new devices or even for docs improents. Thanks 

Daniel

**Comment by robertsLando** [comment]
@Munsio  You find the full device Id in the ui when you add a value to gateway values table

@arjenhiemstra Thanks for your solution, It is not easy to map thermostats in hass that is why a "manual" editing is needed, I think hass should make this easier

**Comment by Munsio** [comment]
FYI
@arjenhiemstra - it seems that through the latest update in home assistant it is not needed anymore to use the custom properties on the thermostat - everything gets detected and works automatically as long as the thermostat is defined in the device.js
