### ISSUE TITLE
[help] Strange entities created

### ISSUE THREAD

**Issue by daanvb** [OpenZWave/Zwave2Mqtt#115]
I’m try to transition to this system and I have managed to configure the component on a RPi3 running HASSIO. I use Aeotec devices along with the Aeotec Gen5 gateway. It has found all my devices however my Aeotec Smart Switch plug sockets don’t seem quite right.

For example, a couple of the entities are named very strangely such as “sensor_gas_density" and “sensor_generic” and "sensor_water" instead of Voltage and Curren and "power_1," "power_2," and "power_8" for Wattage, seconds and kWh. 

The Units of measurements are mostly correct but labelling is off. It also seems to think it has light function too (or a a light switch) as there is a switch to turn/off and and dim an RGB light.

**Comment by robertsLando** [comment]
Please check [FAQ](https://github.com/OpenZWave/Zwave2Mqtt#question-faq) question 2
