### ISSUE TITLE
Home Assistant Discovery - Light Control

### ISSUE THREAD

**Issue by CaCu15** [OpenZWave/Zwave2Mqtt#116]
First of all I would like to thank you for developing this great tool. 
I just installed the docker version (latest) an everything works fine incl. MQTT discovery in Home Assistant (0.94.3). 
I've just 1 question/problem: My ZWAVE network contains some Fibaro Dimmer 2 devices'. If I trigger this devices from e.g. from a Node-Red flow by sending a MQTT message like "zwave2mqtt/Flur/Deckenlicht/38/1/0/set with a payload of "99" this or "0" I can switch the dimmer on and off as expected. In addition I get some additional MQTT messages updating the new status of the device,e .g. if I send `zwave2mqtt/Flur/Deckenlicht/38/1/0/set : msg.payload : string[2] "99"`

I get the following messages: 

```
8.9.2019, 12:18:50node: 371a8346.4c1f74zwave2mqtt/Flur/Deckenlicht/38/1/0 : msg.payload : string[2] "99"
8.9.2019, 12:18:51node: 371a8346.4c1f74zwave2mqtt/Flur/Deckenlicht/49/1/4 : msg.payload : string[4] "15.5"
8.9.2019, 12:18:51node: 371a8346.4c1f74zwave2mqtt/Flur/Deckenlicht/38/1/0 : msg.payload : string[2] "99"
8.9.2019, 12:18:56node: 371a8346.4c1f74zwave2mqtt/Flur/Deckenlicht/49/1/4 : msg.payload : string[4] "61.8"
```

But if I trigger the the same action using the Home Assistant GUI I can see that the same MQTT message is send to trigger the actual status change `zwave2mqtt/Flur/Deckenlicht/38/1/0/set : msg.payload : string[2] "99"`, but there are no follow-up messages to update the status as shown above.
As a result Home Assistant does not reflect the status correctly: The switch in the GUI moves to the "ON" position, but jumps back after 1-2 seconds. 

Any ideas, why the status update messages are missing?

Thanks in advance, Carsten

**Comment by InstigatorX** [comment]
Same issue here. Got it all working for most part, but light status flips OFF and back ON when turning light off.

homeassistant/Kitchen/Bar_Pendants/38/1/0/set 0
homeassistant/Kitchen/Bar_Pendants/38/1/0 {"value_id":"2-38-1-0","node_id":2,"class_id":38,"type":"byte","genre":"user","instance":1,"index":0,"label":"Level","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":255,"is_polled":false,"value":47}

**Comment by robertsLando** [comment]
Try to add that value in gateway values table and enable the switch `verify changes`. It is not a problem related to this tool but from underlying levels of openzwave

**Comment by InstigatorX** [comment]
Sorry, can you elaborate on exactly what I should enter? Not an expert yet. 😁

**Comment by CaCu15** [comment]
OK, thank you for your hint, Daniel. I will test this today in the evening and post my feedback as soon as I can.

**Comment by InstigatorX** [comment]
I had to enable polling and set intensity to 1. Seems to work well.

**Comment by CaCu15** [comment]
For me it does not work: If I switch the gateway to "Configured Manually" and define a gateway value "Level" then I would expect ZWave2MQTT to send a message `zwave2mqtt/Flur/Deckenlicht/Level/set`, but instead the gateway keeps sending 
`zwave2mqtt/Flur/Deckenlicht/**38/1/0**/set`.  If I check in the "Home Assistant - Devices" list than the HASS Device JSON contains `"command_topic": "zwave2mqtt/Flur/Deckenlicht/38/1/0/set"`. It seems to ignore the GW value definition. Do I need to change the Device JSON manually?

**Comment by robertsLando** [comment]
You don't need to set confgured manually, you just have to add the value you want to the table without specify the topic and set the verify changes switch to true

**Comment by CaCu15** [comment]
I think I found my problem. In the HA log I found entries like:
`JSON result was not a dictionary`
and
`Error parsing value: 'int object' has no attribute 'value' (value: 0, template: {{ (value_json.value / 99 * 255) | round(0) }})`


I'm using the gateway with payload type "Just Values". The state_template and brightness_template generated for HA discovery looked this way:  

`"brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",`
`"state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",`

As the MQTT messages do only contain a plain value (not a JSON), this seems wrong to me.  Hence I changed the templates manually to 
   
  ` "brightness_template": "{{ (value|int / 99 * 255) | round(0) }}"`
  ` "state_template": "{{  \"off\" if value|int == 0 else \"on\"  }}"`
   
Now everything works fine, even without enabling value validation or polling.   I can control the light from the HA GUI as well as from node-red using MQTT. 

Maybe this is a bug in the generation of the templates? The templates currently generated look OK for JSON payloads, but not for plain values?

**Comment by robertsLando** [comment]
Nope it should be handled in this lines https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L537

**Comment by CaCu15** [comment]
I'm using version 2.03 running as a docker container.

**Comment by robertsLando** [comment]
@CaCu15 Ok so it should work :( Didn't know why it doesn't, will check this, thanks! Can I close this issue now?

**Comment by CaCu15** [comment]
Yes, you can close this issue. Thanks for your support. 
If you want me to perform any tests to find the root cause for the malformed templates, than please don't hesitate to contact me. I will be happy to support.

**Comment by robertsLando** [comment]
Sure, thanks @CaCu15 !
