### ISSUE TITLE
ZW095 Home Energy Meter Gen5 doesn't update values

### ISSUE THREAD

**Issue by barisahmet** [OpenZWave/Zwave2Mqtt#117]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
My energy meter was reporting values (watts, kWh, volts, amper) in my home assistant setup. I recently moved my z-wave to z2m. Everything works as expected, except my energy meter. When I push wake up button or restart z2m, it reports correct values. But it doesn't report on thresolds.

**Comment by barisahmet** [comment]
Additionally, when I add `poll_intensity="1"` to ozwcache file, it sends correct value on time interval, but I think it should send values on thresold, not time intervals.

**Comment by robertsLando** [comment]
@barisahmet It is most likely a problem with the device config or something with underlying libs that I can't fix on my side. Sorry
