### ISSUE TITLE
Device discovered incorrectly 

### ISSUE THREAD

**Issue by InstigatorX** [OpenZWave/Zwave2Mqtt#118]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.3
Openzwave Version: Whatever version is in your docker build

**Describe the bug**

Some devices discovered improperly. Not sure why. Light dimmer switch discovered as Multilevel power switch 

**To Reproduce**

No idea

**Expected behavior**

Proper discovery 

**Additional context**

**Comment by robertsLando** [comment]
Please check [Faq](https://github.com/OpenZWave/Zwave2Mqtt#question-faq) section on readme @InstigatorX

**Comment by thucar** [comment]
I'm having this very same issue. I've migrated my whole Z-Wave setup from nodered-openzwave to zwave2mqtt. I have almost 60 devices included to the controller. I currently have a number of devices (15 in total) showing up just as "Routing Slave" and a couple more devices that show up as incorrect types. All of the "Routing Slave" devices are detected as "Alive" but they all lack any information. User, Configuration and System sections are empty on all of them. All of these devices are either Fibaro dimmers or relays. At the same time I have a number of Fibaro dimmers and relays (with exactly the same firmware versions) correctly detected by the system.

Is there a way to query the device information again, other than restarting the whole service? With 60 devices it takes a while after each restart to get through polling all available devices.

**Comment by thucar** [comment]
I ended up using the API to resend refreshNodeInfo commands to those nodes, which worked fine. Maybe it would be beneficial to have the refreshNodeInfo option available in the Node actions dropdown in the UI as well?

**Comment by robertsLando** [comment]
That is there 

Daniel

**Comment by thucar** [comment]
It is? I can't seem to be able to find it... Is it called something else?

**Comment by robertsLando** [comment]
@Fishwaldo ever expected this kinf of issues? 

@thucar You right my fault I just checked and there is only `sendNodeInfo` that is the one I remember. I will add it now

**Comment by Fishwaldo** [comment]
It can happen occasionally if you have a unclean shutdown or if the interview process doesn’t complete.
