### ISSUE TITLE
[question] refresh node option missing?

### ISSUE THREAD

**Issue by RezzZ** [OpenZWave/Zwave2Mqtt#120]
Hi, I am trying to migrate my zwave from HA to zwave2mqtt. My network exists mostly out of power plugs (switches) that can report energy, and I have two fibaro heat controllers.

The docker container is running for half an hour now, but I noticed not all devices are properly identified (I mostly have Binary Power Switches but some are identified as On/Off Power Switches and others are not showing all available sensors/attributes, also product name is missing.
I know I had a similar issue in HomeAssistant and by refreshing the nodes that were not loaded completely I could get the remaining information / sensors etc.

I can't find this option in zwave2mqtt anywhere. Am I missing something? can this option be added? Any other suggestions getting all device properly loaded without removing them from the zwcfg.xml and trying again?

Almost forgot to mention my system. Running on a raspberry pi 3b+, hasbian buster, docker (robertslando/zwave2mqtt:latest)

edit: removed some text, I didnt understand the gateway part properly

**Comment by RezzZ** [comment]
I now restored the zwcfg.xml from Homeassistant and it looks like all data is there. I do have all on/off switches now instead of binary power switches but i guess that doesn't matter.

**Comment by robertsLando** [comment]
@RezzZ This kind of things could happen sometimes but is surely not something about this plugin but with underlying libs

**Comment by RezzZ** [comment]
aren't the underlying libs part of the dockercontainer?

**Comment by robertsLando** [comment]
@RezzZ Sure but they are out of my hands, they are not a part of this project so I cannot do anything to fix them
