### ISSUE TITLE
[bug]Hass Device JSON

### ISSUE THREAD

**Issue by towerhand** [OpenZWave/Zwave2Mqtt#121]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.3
Openzwave Version: 1.4.1

**Describe the bug**
Failure to change  "persistent": true back to false in Hass Device JSON after storing the values.

**To Reproduce**

Starting with:
```{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave2mqtt/office_lights/37/1/0/set",
    "state_topic": "zwave2mqtt/office_lights/37/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_office_lights"
      ],
      "manufacturer": "Inovelli",
      "model": "0x1e00",
      "name": "NZW30 Smart Switch (w/Scene)",
      "sw_version": "1.03"
    },
    "name": "office_lights_switch",
    "unique_id": "zwave2mqtt_office_lights_2-37-1-0"
  },
  "discoveryTopic": "switch/office_lights/switch/config",
  "values": [
    "37-1-0"
  ],
  "persistent": false,
  "id": "switch_switch"
}
```
1. Change "persistent": false, to "persistent": true
2. Click on 'update'
3. Click on 'rediscover'
4. Click on 'store'
5. The device shows as switch_switch | switch | switch | Persistent: Yes
6 Repeat the steps to change it back to false and it doesn't change it.
 
**Expected behavior**
Should change back to false or switch_switch | switch | switch | Persistent: No

**Comment by robertsLando** [comment]
@towerhand check latest commit. I have added the possibility to add/remove devices from nodes.json

**Comment by towerhand** [comment]
Ok thanks, I’ll wait for the next release to test. I’ll close this now.

**Comment by robertsLando** [comment]
Will release new version after fixing some little things, maybe will release it next week

Daniel
