### ISSUE TITLE
[feat] config/ topic

### ISSUE THREAD

**Issue by towerhand** [OpenZWave/Zwave2Mqtt#126]
**Is your feature request related to a problem? Please describe.**
I was away from home and zwave2mqtt stopped talking to my Mqtt server so my HA instance couldn't control any of my wave devices, I couldn't do anything to fix it until I got home.

**Describe the solution you'd like**
I didn't find anything in the docs, but it would be nice to have zwave2mqtt listen to a config topic  where you can send Mqtt messages to control basic functions of zwave2mqtt like restart, test network, heal node {node id}.

monitor uses ```monitor/scan/restart```
zigbee2mqtt uses it to receive a few basic commands like reset, permit_join, remove, etc.
 https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html

**Describe alternatives you've considered**
Setting up a VPN so I have full access to my network while away from home could be an option.

**Comment by robertsLando** [comment]
@towerhand Interesting feature! What actions do you think need to be acessible from mqtt? Actually for test network and heal node you can use [MQTT APIs](https://github.com/OpenZWave/Zwave2Mqtt#gift-mqtt-apis) but there is no way to restart application using mqtt, do you think that is there any other action like restart that could be usefull?

**Comment by towerhand** [comment]
Sorry but as a regular user I didn’t really understand the mqtt api when I first read the docs but looks like mostly can do what I was thinking.

Since restart is not an option then maybe listening to simple topics for fixing basic problems in the nodes and mesh could be beneficial. Hopefully someone with more knowledge can voice their opinion. 

Maybe empty message to:
/config/heal network 
/config/refresh [node id]
/config/remove failed node

Just a suggestion from my limited understanding of zwave and mqtt.

Thanks for all your hard work.

**Comment by towerhand** [comment]
Yea the mqtt API in the docs you linked seems to do everything I’m asking. I’ll try to update the docs to make it a little bit easier to understand. Thanks.
