### ISSUE TITLE
cannot set values for fibaro heat controller

### ISSUE THREAD

**Issue by RezzZ** [OpenZWave/Zwave2Mqtt#127]
Hi, I've recently started using zwave2mqtt and all seem to be working fine now, until I try to control my fibaro heat controllers.

I setup my mqtt gateway to publish values for heating and mode to the topics 'heating' and 'mode' and I ticked the option to publish under the node names instead of the node_id's. All values are nicely published. I get the correct temperature and mode, but when I try to set a new value via mqtt it is failing. Strange thing is, it works just fine when I set these values directly in the 'Contol Panel' of zwave2mqtt. The error I receive is:

```
2019-09-23T08:55:09.250Z z2m:Mqtt Message received on zwave2mqtt/Bedroom/HeatController1/heating/set
OpenZWave Error, Node044, Cannot find endpoint map to instance for Command Class COMMAND_CLASS_APPLICATION_STATUS endpoint 0
```
any thoughts?

**Comment by robertsLando** [comment]
Could you paste here the payload you sent? Could you also specify the model of your fibaro heat controller?

**Comment by RezzZ** [comment]
my payload is probably the issue. But I can't seem to find the correct syntax. i've tried several payloads so far, using mqtt fx:
plain numbers, like '20', enclosed in quotes, adding json brackets {}
```
20
"20"
[20]
{"value": 20}
{"value": "20"}
{"value": [20]}
{"args": 20}
{"args": "20"}
{"args": [20]}
```

The controller type is:
FGT001 Heat Controller (FIBARO System)

**Comment by robertsLando** [comment]
So you have tried to publish those payloads to `zwave2mqtt/Bedroom/HeatController1/heating/set`. I need to know the gateway payload configuration and also how you have configured values in gateway values table, send me a screenshot of gateway settings

**Comment by RezzZ** [comment]
correct. Here the screenshots of my settings. Should I disable the "verified changes"? The documentation is not very clear (at least to me) about what this setting does.
![image](https://user-images.githubusercontent.com/70499/65496895-9adcfa00-deb9-11e9-86ea-0f9ed3b504b3.png)

![image](https://user-images.githubusercontent.com/70499/65496462-cc08fa80-deb8-11e9-94a5-1ed415c3b664.png)

**Comment by robertsLando** [comment]
With this settings sending a value of `20` to `zwave2mqtt/Bedroom/HeatController1/heating/set` should work. About `verifyChanges` try to disable it and tell me if it works, it is used when there are multiple state change when sending new values but I don't think it's your case

**Comment by robertsLando** [comment]
That's strange because I never got errors like this, If you are able to control changes from the control panel you should also been able to control them via mqtt, the api used is the same. Are you using the latest version from master or docker?

Remeber that once you set a new mode in the control panel you need to hit the send button to send the update

**Comment by robertsLando** [comment]
Try with latest version 2.0.4 just released on docker
