### ISSUE TITLE
[bug] MQTT Retained Message

### ISSUE THREAD

**Issue by ksuclipse** [OpenZWave/Zwave2Mqtt#130]
**Version**

Build/Run method
- [X ] Docker
- [ ] PKG
- [X ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.3
Openzwave Version: 1.4.1

**Describe the bug**
Not using discovery, retain turned on, messages are not retained.
![image](https://user-images.githubusercontent.com/4250828/65652329-99e9bc80-dfce-11e9-9f76-4c8f1cd24adc.png)

example of retained msg:
![image](https://user-images.githubusercontent.com/4250828/65652425-fa78f980-dfce-11e9-871e-266f2f0e8085.png)

picture of switch topic with no retain:
![image](https://user-images.githubusercontent.com/4250828/65652545-6196ae00-dfcf-11e9-978e-6cd8d1baad77.png)

**To Reproduce**
No error just isnt working

**Expected behavior**
expect this to be a retained message to survive home assistant reboots

**Comment by robertsLando** [comment]
How do you see that is not retained? It seems that it has the retained flag to me

Daniel

**Comment by ksuclipse** [comment]
i was using MQTT explorer separately to see the mqtt server topics.  also if i reboot hass it loses state information.  where is the source of mqtt publishing in the package? i can dig around

**Comment by robertsLando** [comment]
@ksuclipse https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/MqttClient.js#L295

**Comment by ksuclipse** [comment]
I do show with the latest release Retained messages.
