### ISSUE TITLE
[question] Post operations

### ISSUE THREAD

**Issue by jarvih** [OpenZWave/Zwave2Mqtt#131]
Is there a way to use post operations to map number values to string.

like 0 -> false
and 1 -> true

**Comment by robertsLando** [comment]
Actually nope, why you need this feature?

**Comment by jarvih** [comment]
Some dimmers don't handle some logical commands very well.

I have mixed dimmers and normal switches and if i try to issue command for ex zwave/dimmer/light/set true it only set it to minimum level of 1.

So it would be nice to be map values to words.

**Comment by robertsLando** [comment]
@jarvih For this kind of things (and lot more) check my other project [Mqtt2Mqtt](https://github.com/robertsLando/Mqtt2Mqtt)
