### ISSUE TITLE
[bug] Problems after changing gateway from Named Topics to ValueID

### ISSUE THREAD

**Issue by RualdOrdelman** [OpenZWave/Zwave2Mqtt#137]
**Version**

Build/Run method
- [X] Docker compose

Zwave2Mqtt version: 2.0.4
Openzwave Version: ?

**Describe the bug**
I worked with Zwave2Mqtt for several months. First with a gateway configured with type NamedTopics and after that with Configured Manually. Now I changed to ValueID's but it looks that the software did't picked up that change correctly. After changing the setting tot ValueID's I've restarted the Zwave2Mqtt container several times. 

When I looked at the MQTT queue with mosquitto_sub I saw a lot of ValueID topics. BUT sometimes a Named topic. For example:
`zwave2mqtt/46/50/1/32 false
zwave2mqtt/46/50/1/20 0
zwave2mqtt/46/50/1/21 0
zwave2mqtt/46/50/1/22 85
zwave2mqtt/neo_powerplug_woonkamer_linksachter/Switch true
zwave2mqtt/48/50/1/32 false
zwave2mqtt/48/50/1/0 0.68
zwave2mqtt/48/50/1/1 0.68
zwave2mqtt/48/50/1/16 232.49`

When I change an topic manually from the Zwave2Mqtt interface and set a switch to On I expect an ValueID topic on the mosquitto_sub screen, BUT I received an Named version. For example, I set an Dimmer to Level 20. I expect so see something like 
`zwave2mqtt/54/38/1/0 20` 
but I see
`zwave2mqtt/fibaro_dimmer2_keukentafel/Level 20`

<img width="440" alt="image" src="https://user-images.githubusercontent.com/1227427/66068879-afbb2c80-e54e-11e9-92b4-e770bd0d0b0c.png">

**Comment by robertsLando** [comment]
Are you sure that there are not still values in gateway values table. Those values are used even if the gateway is not in manual mode to override some desired topics

**Comment by RualdOrdelman** [comment]
Aiii that would be the problem. I will try to delete that values in table and will report the outcome.

**Comment by RualdOrdelman** [comment]
I've tested your suggestion and that fixed the problem. So this bug can be closed.
