### ISSUE TITLE
Docker image version?

### ISSUE THREAD

**Issue by InstigatorX** [OpenZWave/Zwave2Mqtt#138]
Are the docker images always the latest version? i.e. v2.0.4 today

**Comment by robertsLando** [comment]
Yes

**Comment by robertsLando** [comment]
I'm releaseing 2.0.6 version now will be available in 1/2 hours. Starting from now images will have the version in their tag name:

`2.0.6-dev` and `2.0.6`. The `dev` tag has OZW 1.6 installed
