### ISSUE TITLE
Does not reattach to controller after softreset

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#14]
After sending a softreset command the USB device gets briefly detached and reattached.
This results in zwave2mqtt talking to a no longer valid fd? for the serial device. Restart zwave2mqtt fixes this.

Reopening the device after sending a softreset should have the same effect.

**Comment by robertsLando** [comment]
Need to investigate, I think is something related with `node-openzwave-shared` library, it has some problems with disconnect too

**Comment by robertsLando** [comment]
Here more info: https://github.com/OpenZWave/node-openzwave-shared/issues/182

**Comment by sjorge** [comment]
So shall we close this then until the upstream issue is resolved and retest then?

**Comment by robertsLando** [comment]
Leave it here so we prevent someone else to create another one until it will be fixed

**Comment by robertsLando** [comment]
I think it is related to #17
