### ISSUE TITLE
[question] unknown device Aeotec Indoor Siren 6

### ISSUE THREAD

**Issue by jerepeer** [OpenZWave/Zwave2Mqtt#142]
Hi,

Since my Zwave2Mqtt was updated to 2.0.4, my Aeotec Indoor Siren 6 (ZW164) is not recognized anymore. The product is shown as "Unknown: type=0003, id=00a4 (Aeotec Limited)". I re-included the device without any results. The device is alive but can't be configured.

I know there are some known issues with the indoor siren but is there something wrong with my installation of did you exclude the product? Thx

Raspberry pi3b, Raspbian Buster, docker >> Hass.io & Zwave2Mqtt

**Comment by robertsLando** [comment]
@jerepeer Are you using docker?

**Comment by jerepeer** [comment]
Yes, I am.

com.docker.compose.version | 1.24.1

**Comment by robertsLando** [comment]
Try to send “refreshNodeInfo” command to the wrong discovered nodes. It has been added as command some commits ago if you don’t find it you can send it with mqtt apis

Daniel

**Comment by jerepeer** [comment]
Sorry, no custom build here. Do you have a nightly build with the refreshNodeInfo command?

No experience with calling a Zwave API (JSON object). Even my fellow zwave2mqtt friends don't know ;)

**Comment by robertsLando** [comment]
I will release 2.0.5 version soon

Daniel

**Comment by jerepeer** [comment]
Great! I'll wait for the release and let you know if it worked !

**Comment by jerepeer** [comment]
Got the update, thnx! Ran the refreshNodeInfo command but still no luck..... "Unknown: type=0003, id=00a4 (Aeotec Limited)"

Here's the log..

OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x3b, 0x00, 0x00, 0x0f, 0xdf
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x3b received (expected 0x3b)
OpenZWave Info, Node017, Request RTT 149 Average Request RTT 148
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x11, 0x05, 0x8e, 0x03, 0x09, 0x05, 0x00, 0x65
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 227 Average Response RTT 226
OpenZWave Info, Node017, Received Multi Instance Association report from node 17, group 9
OpenZWave Info, Node017, The group contains:
OpenZWave Info, Node017, Querying associations for node 17 is complete.
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: Group
OpenZWave Detail, Node017, Query Stage Complete (Associations)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Neighbors live=1
OpenZWave Detail, Node017, QueryStage_Neighbors
OpenZWave Detail, Requesting routing info (neighbor list) for Node 17
OpenZWave Detail, Node017, Queuing (Command) Get Routing Info (Node=17): 0x01, 0x07, 0x00, 0x80, 0x11, 0x00, 0x00, 0x03, 0x6a
OpenZWave Detail, Node017, Queuing (Query) Query Stage Complete (Neighbors)
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Command) message (Callback ID=0x00, Expected Reply=0x80) - Get Routing Info (Node=17): 0x01, 0x07, 0x00, 0x80, 0x11, 0x00, 0x00, 0x03, 0x6a
OpenZWave Detail, Node017, Received: 0x01, 0x20, 0x01, 0x80, 0xcf, 0xf7, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x62
OpenZWave Detail,
OpenZWave Info, Node017, Received reply to FUNC_ID_ZW_GET_ROUTING_INFO
OpenZWave Info, Node017, Neighbors of this node are:
OpenZWave Info, Node017, Node 1
OpenZWave Info, Node017, Node 2
OpenZWave Info, Node017, Node 3
OpenZWave Info, Node017, Node 4
OpenZWave Info, Node017, Node 7
OpenZWave Info, Node017, Node 8
OpenZWave Info, Node017, Node 9
OpenZWave Info, Node017, Node 10
OpenZWave Info, Node017, Node 11
OpenZWave Info, Node017, Node 13
OpenZWave Info, Node017, Node 14
OpenZWave Info, Node017, Node 15
OpenZWave Info, Node017, Node 16
OpenZWave Info, Node017, Node 19
OpenZWave Detail, Node247, Expected reply was received
OpenZWave Detail, Node247, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Query Stage Complete (Neighbors)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Session live=1
OpenZWave Detail, Node017, QueryStage_Session
OpenZWave Detail, Node017, Queuing (Query) PowerlevelCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x73, 0x02, 0x25, 0x3c, 0x9e
OpenZWave Detail, Node017, Queuing (Query) Query Stage Complete (Session)
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Query) message (Callback ID=0x3c, Expected Reply=0x04) - PowerlevelCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x73, 0x02, 0x25, 0x3c, 0x9e
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x3c, 0x00, 0x00, 0x09, 0xde
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x3c received (expected 0x3c)
OpenZWave Info, Node017, Request RTT 92 Average Request RTT 120
OpenZWave Detail, Expected callbackId was received
2019-10-31T18:58:26.280Z z2m:Zwave zwave node 17: changed: 115-1-0:Powerlevel:Normal -> Normal
2019-10-31T18:58:26.285Z z2m:Zwave zwave node 17: changed: 115-1-1:Timeout:0 -> 0
OpenZWave Detail, Node017, Received: 0x01, 0x0a, 0x00, 0x04, 0x00, 0x11, 0x04, 0x73, 0x03, 0x00, 0x00, 0x94
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 170 Average Response RTT 198
OpenZWave Info, Node017, Received a PowerLevel report: PowerLevel=Normal, Timeout=0
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=list
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Query Stage Complete (Session)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Dynamic live=1
OpenZWave Detail, Node017, QueryStage_Dynamic
OpenZWave Detail, Node017, Queuing (Send) BasicCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x20, 0x02, 0x25, 0x3d, 0xcc
OpenZWave Detail, Node017, Queuing (Send) AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x07, 0x01, 0x25, 0x3e, 0x9c
OpenZWave Detail, Node017, Queuing (Send) AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x3f, 0x92
OpenZWave Detail, Node017, Queuing (Send) MultiChannel Encapsulated (instance=4): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x03, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x40, 0x92
OpenZWave Detail, Node017, Queuing (Send) MultiChannel Encapsulated (instance=5): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x04, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x41, 0x94
OpenZWave Detail, Node017, Queuing (Send) MultiChannel Encapsulated (instance=6): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x42, 0x96
OpenZWave Detail, Node017, Queuing (Query) Query Stage Complete (Dynamic)
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x3d, Expected Reply=0x04) - BasicCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x20, 0x02, 0x25, 0x3d, 0xcc
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x3d, 0x00, 0x00, 0x11, 0xc7
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x3d received (expected 0x3d)
OpenZWave Info, Node017, Request RTT 168 Average Request RTT 144
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x09, 0x00, 0x04, 0x00, 0x11, 0x03, 0x20, 0x03, 0x00, 0xc3
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 246 Average Response RTT 222
2019-10-31T18:58:26.530Z z2m:Zwave zwave node 17: changed: 32-1-0:Basic:0 -> 0
OpenZWave Info, Node017, Received Basic report from node 17: level=0
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x3e, Expected Reply=0x04) - AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x07, 0x01, 0x25, 0x3e, 0x9c
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x3e, 0x00, 0x00, 0x0b, 0xde
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x3e received (expected 0x3e)
OpenZWave Info, Node017, Request RTT 111 Average Request RTT 127
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x11, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x07, 0xfe, 0x00, 0x9e
2019-10-31T18:58:26.721Z z2m:Zwave zwave node 17: changed: 113-1-0:Alarm Type:0 -> 0
2019-10-31T18:58:26.724Z z2m:Zwave zwave node 17: changed: 113-1-1:Alarm Level:0 -> 0
2019-10-31T18:58:26.729Z z2m:Zwave zwave node 17: changed: 113-1-2:SourceNodeId:0 -> 0
2019-10-31T18:58:26.733Z z2m:Zwave zwave node 17: changed: 113-1-10:Burglar:254 -> 254
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 189 Average Response RTT 205
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Burglar event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x3f, Expected Reply=0x04) - AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x3f, 0x92
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x3f, 0x00, 0x00, 0x0b, 0xdf
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x3f received (expected 0x3f)
OpenZWave Info, Node017, Request RTT 110 Average Request RTT 118
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x11, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x08, 0xfe, 0x00, 0x91
OpenZWave Detail,
2019-10-31T18:58:26.926Z z2m:Zwave zwave node 17: changed: 113-1-0:Alarm Type:0 -> 0
2019-10-31T18:58:26.931Z z2m:Zwave zwave node 17: changed: 113-1-1:Alarm Level:0 -> 0
2019-10-31T18:58:26.937Z z2m:Zwave zwave node 17: changed: 113-1-2:SourceNodeId:0 -> 0
2019-10-31T18:58:26.944Z z2m:Zwave zwave node 17: changed: 113-1-11:Power Management:254 -> 254
OpenZWave Info, Node017, Response RTT 189 Average Response RTT 197
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Power Management event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x40, Expected Reply=0x04) - MultiChannel Encapsulated (instance=4): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x03, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x40, 0x92
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x40, 0x00, 0x00, 0x0b, 0xa0
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x40 received (expected 0x40)
OpenZWave Info, Node017, Request RTT 115 Average Request RTT 116
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x13, 0x00, 0x04, 0x00, 0x11, 0x0d, 0x60, 0x0d, 0x03, 0x01, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x08, 0xfe, 0x00, 0xe6
OpenZWave Detail,
2019-10-31T18:58:27.122Z z2m:Zwave zwave node 17: changed: 113-4-0:Alarm Type:0 -> 0
2019-10-31T18:58:27.126Z z2m:Zwave zwave node 17: changed: 113-4-1:Alarm Level:0 -> 0
2019-10-31T18:58:27.130Z z2m:Zwave zwave node 17: changed: 113-4-2:SourceNodeId:0 -> 0
2019-10-31T18:58:27.134Z z2m:Zwave zwave node 17: changed: 113-4-11:Power Management:254 -> 254
OpenZWave Info, Node017, Response RTT 193 Average Response RTT 195
OpenZWave Info, Node017, Received a MultiChannelEncap from node 17, endpoint 3 for Command Class COMMAND_CLASS_ALARM
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Power Management event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x41, Expected Reply=0x04) - MultiChannel Encapsulated (instance=5): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x04, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x41, 0x94
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x41, 0x00, 0x00, 0x0c, 0xa6
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x41 received (expected 0x41)
OpenZWave Info, Node017, Request RTT 120 Average Request RTT 118
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x13, 0x00, 0x04, 0x00, 0x11, 0x0d, 0x60, 0x0d, 0x04, 0x01, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x08, 0xfe, 0x00, 0xe1
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 198 Average Response RTT 196
OpenZWave Info, Node017, Received a MultiChannelEncap from node 17, endpoint 4 for Command Class COMMAND_CLASS_ALARM
2019-10-31T18:58:27.326Z z2m:Zwave zwave node 17: changed: 113-5-0:Alarm Type:0 -> 0
2019-10-31T18:58:27.329Z z2m:Zwave zwave node 17: changed: 113-5-1:Alarm Level:0 -> 0
2019-10-31T18:58:27.333Z z2m:Zwave zwave node 17: changed: 113-5-2:SourceNodeId:0 -> 0
2019-10-31T18:58:27.337Z z2m:Zwave zwave node 17: changed: 113-5-11:Power Management:254 -> 254
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Power Management event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x42, Expected Reply=0x04) - MultiChannel Encapsulated (instance=6): AlarmCmd_Get (Node=17): 0x01, 0x10, 0x00, 0x13, 0x11, 0x09, 0x60, 0x0d, 0x01, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x42, 0x96
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x42, 0x00, 0x00, 0x0b, 0xa2
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x42 received (expected 0x42)
OpenZWave Info, Node017, Request RTT 117 Average Request RTT 117
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x13, 0x00, 0x04, 0x00, 0x11, 0x0d, 0x60, 0x0d, 0x05, 0x01, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x08, 0xfe, 0x00, 0xe0
2019-10-31T18:58:27.522Z z2m:Zwave zwave node 17: changed: 113-6-0:Alarm Type:0 -> 0
2019-10-31T18:58:27.526Z z2m:Zwave zwave node 17: changed: 113-6-1:Alarm Level:0 -> 0
2019-10-31T18:58:27.530Z z2m:Zwave zwave node 17: changed: 113-6-2:SourceNodeId:0 -> 0
2019-10-31T18:58:27.533Z z2m:Zwave zwave node 17: changed: 113-6-11:Power Management:254 -> 254
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 194 Average Response RTT 195
OpenZWave Info, Node017, Received a MultiChannelEncap from node 17, endpoint 5 for Command Class COMMAND_CLASS_ALARM
2019-10-31T18:58:27.582Z z2m:Zwave node 17 ready: Aeotec Limited - Unknown: type=0003, id=00a4 (Unknown)
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Power Management event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Query Stage Complete (Dynamic)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Configuration live=1
OpenZWave Detail, Node017, QueryStage_Configuration
OpenZWave Detail, Node017, QueryStage_Complete
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=0 sleepingOnly=1
OpenZWave Detail, Node017, Notification: NodeQueriesComplete

**Comment by 917huB** [comment]
Not that it helps but mines been discovered and working fine from 2.0.4, 2.05 and 2.0.6, although I have had issues  setting most of the chime/volume related values. When I've seen problems like yours before forgetting the item and re-adding it usually clears it up 

![aeotecdoorbell6](https://user-images.githubusercontent.com/22522964/68036477-fea9ce00-fc82-11e9-9e15-11bf4f2d921f.jpg)

**Comment by jerepeer** [comment]
Thanks for the input 917HuB. Tried to delete and add a new node but no luck.
I'll contact Aeotec. This is annoying. We have the same device (minus the doorbell)

![2019-11-02 18_49_05-Greenshot](https://user-images.githubusercontent.com/56473045/68074936-8d147180-fda1-11e9-90f3-463acc07e775.jpg)

**Comment by enobrev** [comment]
@917huB have you had any luck setting the volume or chime in any way?  I was trying to figure out how to do so for a few hours and got absolutely nowhere.  I'd hoped maybe using `ozwcp` would allow it, but no luck there either.

**Comment by Fishwaldo** [comment]
These devices use a new command class called SoundSwitch. That’s only supported in OZW 1.6. So make sure your using that variant.

**Comment by 917huB** [comment]
@enobrev Im using a build of 1.6 from a few weeks ago but setting volume or tone doesn't make any difference. I haven't had the time to debug in any detail yet to be able to provide any details though.

**Comment by enobrev** [comment]
Thanks @Fishwaldo @917huB , I had been using 1.6.  I had tried the release as well as pulling from master and compiling, but was never able to adjust volume or chimes.  It's been a few weeks since I tried, so I don't remember what I was seeing in the logs, but the doorbell remains on a shelf until I can change the ridiculous default volume on this thing.

_Sorry for hijacking this thread - I couldn't find a way to contact @917huB elsewhere._

**Comment by tetienne** [comment]
So to sum up, can we setup the volume of the ZW162 correctly with the latest release?

**Comment by enobrev** [comment]
I haven't had a chance to test.  The doorbell version is stupid loud by default and if I can't change the volume, I don't even want to take it back out of the box.  Besides, if you move the stupid thing, the tamper alarm goes off, which is also obnoxiously loud. I haven't returned it because I legitimately want the thing, I'm just waiting to hear if anyone has had success with it before I touch the box and wake the whole neighborhood.

**Comment by 917huB** [comment]
Still wasn't working when I last tested, I'l grab latest and verify this weekend. 
Like you I wanted a wifi doorbell so worked around the problem by mounting the siren in a box stuffed with rags, that attenuates the siren & doorbell volume to something bearable whilst the code geniuses figure out how to tame this thing.

**Comment by robertsLando** [comment]
I’m sorry for this but as it is not a problem caused by z2m I can’t really help with this, try to reopen the same issue on openzwave library and reference this issue for more information. Let me know if you fix this

Daniel

**Comment by jerepeer** [comment]
Finally got it up and running under OZW 1.6 (v2.1.0)   Trying to adjust the volume with the Z-wave PC controller but still no luck. Keep u guys updated.

![Doorbell Config Change](https://user-images.githubusercontent.com/56473045/72672171-b4044a80-3a56-11ea-88b9-eaded8b65a4d.png)

**Comment by robertsLando** [comment]
Thanks @jerepeer

**Comment by Fishwaldo** [comment]
@jreaper I believe there was a few firmware updates since it was released. Make sure it’s the latest (as I can adjust the volume on mine)

**Comment by 917huB** [comment]
@Fishwaldo Can you confirm what version you have on yours please? thanks for confirming yours is working.

**Comment by Fishwaldo** [comment]
Mines in a box but it was the latest version a few months ago.

**Comment by jerepeer** [comment]
@Fishwaldo ... I asked Aeotec for the latest FW... this is their reply 🤔🤔

“Thank you for inquiry.

No new firmware is currently available for Siren 6.

Best regards
Sebastian Putz
Field Application Engineer
Aeotec”

**Comment by jreaper** [comment]
Why am I included ?

**Comment by robertsLando** [comment]
@jreaper I think someone has typo @jerepeer name and has wrongly tagged you

**Comment by jerepeer** [comment]
@robertsLando FYI ... it all works like a charm now with the latest release 2.2.0  including setting the volume.

Thx for the update !
