### ISSUE TITLE
[feat] Remove the retain flag from node events

### ISSUE THREAD

**Issue by towerhand** [OpenZWave/Zwave2Mqtt#143]
**Is your feature request related to a problem? Please describe.**
Zwave2mqtt and Home Assistant user.

In the MQTT settings of Zwave2mqtt  I have turned on the retain option so the outgoing messages have the retain flag, this helps keeping the state of the different zwave devices in sync with home assistant. I have tested turning off that setting and under certain circumstances HA shows the incorrect state so with my limited knowledge I believe the retain flag is indispensable.

That brings me to my problem. With the retain option turned on, the node events that are published to <mqtt_prefix>/<?node_location>/<node_name>/event have the retain flag too, which trigger automations after a Home Assistant restart or automation list refresh. This is causing couple  automations I have set up for the events (double click up/down) in my GE/Jasco switches to trigger erratically.

**Describe the solution you'd like**
Always remove the retain flag from node events <mqtt_prefix>/<?node_location>/<node_name>/event regardless of the retain option in the MQTT settings, or have a setting to only remove the retain flag from the node events.

**Additional context**
I'm assuming the scene events <mqtt_prefix>/<?node_location>/<node_name>/scene/event will have the same behavior when added in the next version.

**Comment by robertsLando** [comment]
@towerhand Done, thanks

**Comment by towerhand** [comment]
Wow you are fast, thanks.

**Comment by robertsLando** [comment]
It is on master not on zwave docker so use master version or create a custom docker image

Daniel

**Comment by towerhand** [comment]
I’ll wait for 2.0.5 since I’m using docker compose and I have no clue how to set up a custom docker container. Thanks.

**Comment by towerhand** [comment]
Never done this before but following your guide it should look like this:
```git clone https://github.com/robertsLando/Zwave2Mqtt-docker.git
cd Zwave2Mqtt-docker
sed -i "s|2007c748a96366b291c448078373a6c653e4f3c1|6ce97ce22ea465faec7634577abf000ed690f10e|g" Dockerfile
docker build -t robertslando/zwave2mqtt:latest .
```

**Comment by robertsLando** [comment]
Yess that’s simple :) 

Daniel

**Comment by towerhand** [comment]
ummmm silly question, after following the guide I get:
```
Successfully built 1167df283c20
Successfully tagged robertslando/zwave2mqtt:latest
```
what do I need to do after that? I tried docker compose pull.

**Comment by towerhand** [comment]
Never mind, I think I got it figured out. Copied all setting files from my zwave2mqtt folders to the corresponding zwave2mqtt-docker folders and ran the docker-compose.yml from that new folder.

**Comment by robertsLando** [comment]
Is it working now?

Daniel

**Comment by towerhand** [comment]
Will do some testing after work and let you know. Thanks.

**Comment by towerhand** [comment]
Hi Daniel, I did a quick testing before going to work and it didn’t do what I was thinking, the automations still triggered during an HA restart. I’ll do more testing after work to make sure I’m not wasting your time. I do think removing the retain flag on the events was a move in the right direction.

**Comment by robertsLando** [comment]
Yes because you firstly need to remove retained messages from your broker. Now messages are not retained for sure but the messages you are receiving must be from previous version

Daniel

**Comment by towerhand** [comment]
I did remove the message with mqtt explorer and checked the new one didn’t have a retain flag, I was in a rush so I planning to try that again first, then I’m thinking to restart the mqtt broker, then clear all messages for zwave2mqtt and restart it too. Testing in between every step.

**Comment by robertsLando** [comment]
You just have to remove the retained messages from broker and restart z2m

Daniel

**Comment by towerhand** [comment]
Tried it multiple times removing the messages, restarting zwave2mqtt, triggering the event, restarted HA and the automations still trigger. The retain flag appeared to still be on for the events if the toggle is on for retain in the mqtt settings.

To confirm I tried this a few times too, with mqtt explorer connected I triggered the event (double tap on the switch), checked the message was received, closed mqtt explorer and reopen it, the message should have been gone but the message was still there with the retain flag.

I don't know, maybe I failed to set up the custom container properly.

Thanks

**Comment by towerhand** [comment]
@robertsLando Yup, just installed 2.0.5 and removing the retain flag works as intended. Now I gotta figure out how I messed up setting up the custom build so I can help testing in the future.

Thanks a lot for fixing this and the patience.
