### ISSUE TITLE
zwcfg file not saved / devices have to be discovered on each restart

### ISSUE THREAD

**Issue by derelict** [OpenZWave/Zwave2Mqtt#144]
i don't know if this is "normal" or not .. however .. no matter what i do .. the zwcfg file is not saved during restart / normal operation.

I have enabled "Save Configuration" for ZWave .. but nothing gets saved.

From my understanding, the zwcfg config file is used to "cache" device information.

So when i restart Z2M .. all devices  remain dead for a very long time (especially battery operated motion sensors ... i let Z2M run for at least 12 hours .. but they were still dead) ... until i manually wake them up locally using the "button".

I am migrating the zwave "stack" from homeassistant to Z2M ... and from my experience in homeassistant .. all the motion sensors were working after the zwave network was ready (normally took about 15-30 Minutes) ... but with Z2M they remain dead.

Could this be because of the missing/not saved zwcfg file ? ... or is this the normal behaviour ?

I'm running Z2M using the provided Docker Image.

Thanks for any hints

**Comment by robertsLando** [comment]
Try to send an action 'testNode' to dead nodes to see if they come alive

**Comment by derelict** [comment]
i have rebuilt the docker container using the latest commit .. but zwcfg still does not get written.

i do see "Scan completed" in the logs .. and according to me that's the point where the file should be saved. not ?

anything else i can test / try ?

**Comment by robertsLando** [comment]
Yes it should be saved on close and on scan complete event, if it doesn’t save there should be something else wrong like permissions on folder ? Are you using docker or what else? 

Daniel

**Comment by derelict** [comment]
I'm using docker (custom build using your Dockerfile) ... all files a owned by root and are writeable (nodes.json is working fine for instance).

I'm no programmer ... but "this.client.writeConfig === 'function'" looks to me like it's related to that "save button" which has been removed. could it be related to that ?

Thanks

**Comment by robertsLando** [comment]
The button has been removed because I’m working to make the application ozw 1.6 compatibile and writeConfig has beem removed in ozw 1.6. If the config isn’t written the only explain could be that the flag “saveConfiguration” isn’t true on zwave settings. Try to export in json the settings and check if that setting is true 

Daniel

**Comment by derelict** [comment]
it's set to "true":

`{"port":"/dev/zwavestick","pollInterval":60000,"logging":true,"saveConfig":true}}`

**Comment by robertsLando** [comment]
It is working on all my docker instances sincerly I can’t understand where the problem is in your case... it also should be automatically saved even before the last commit on close event... try to enable logging on zwave settings and check if you see something there that could explain why zwcfg is not correctly saved. 

Daniel

**Comment by derelict** [comment]
Logging is already enabled.. but i don't see anything special.

am i supposed to specify a config path ?

![image](https://user-images.githubusercontent.com/2826671/67720546-80c09b00-f9d4-11e9-8a64-065838c0b83a.png)

**Comment by robertsLando** [comment]
No, config path is the path to the devices db, don’t change that

Daniel

**Comment by derelict** [comment]
ok.

This is what i have tried (again .. i'm not a developer ;-) )

i have adapted "ZwaveClient.js"

`function scanComplete () {
  this.scanComplete = true

  var nodes = this.nodes.filter(n => !n.failed)

  // popolate groups (just for active nodes)
  for (var i = 0; i < nodes.length; i++) {
    this.getGroups(nodes[i].node_id)
    nodes[i].neighborns = this.client.getNodeNeighbors(nodes[i].node_id)
  }

  if (this.cfg.saveConfig && typeof this.client.writeConfig === 'function') {
    debug('Saving ozwcfg')
    this.client.writeConfig()
  }
  
  this.client.writeConfig()

  debug('Network scan complete. Found:', nodes.length, 'nodes')
}
`
So i write the config on Scan Complete ... and also show some info if the "if" part is ran.

This is what i've got on "Scan Complete":

`2019-10-28T22:44:24.626Z z2m:Zwave ValueAdded: 57-112-1-16 Saving state before power failure
2019-10-28T22:44:46.102Z z2m:Zwave ValueAdded: 102-112-1-16 Saving state before power failure
2019-10-28T22:47:33.267Z z2m:Zwave ValueAdded: 91-112-1-16 Saving state before power failure
events.js:106
    handler.call(self);
            ^

TypeError: undefined is not a function
    at ZwaveClient.scanComplete (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at emitNone (events.js:106:13)
    at OZW.emit (events.js:208:7)
`

i have no idea ... but shouldn't writeconfig be a function in order to work ?

**Comment by robertsLando** [comment]
Ok got it. The problem is that node-openzwave-shared has made that function deprecated un 1.5.x versions. You should compile openzwave-shared and set the OPENZWAVE_DEPRECATED16 pre processor 

Daniel

**Comment by robertsLando** [comment]
Add to docker file after npm install:

npm install openzwave-shared —OPENZWAVE_DEPRECATED16=true

Than rebuild the image and the function should work

Daniel

**Comment by derelict** [comment]
;-) Thank you for that hint ... i was just going to ask how to do it .. because i felt a little bit lost :-)

I'll give it a try tonight. Thank you very much !

Just wondering: when do you expect Z2M to be 1.6 compatible ?

**Comment by robertsLando** [comment]
Sorry I don’t know as it depends on my free time and I don’t have much :( 

Daniel

**Comment by derelict** [comment]
> Sorry I don’t know as it depends on my free time and I don’t have much :( Daniel
No Worries ... i was just wondering ... if it still makes sense to get this current "issue" solved .. or just wait for the new Version with 1.6 support.

**Comment by derelict** [comment]
ok .. i gave it a try. this is the relevant part in the dockerfiler:

`# Clone Zwave2Mqtt build pkg files and move them to /dist/pkg
RUN npm config set unsafe-perm true && npm install -g pkg@4.3.8 \
    && cd /root \
    && git clone https://github.com/OpenZWave/Zwave2Mqtt.git  \
    && cd Zwave2Mqtt \
    && git checkout \
    && npm install \
    && npm install openzwave-shared --OPENZWAVE_DEPRECATED16=true \
    && npm run build
`
I'm not quite sure if i specified the commandline switch correctly (the dashes "--").

But it looks like it's still not working.

**Comment by robertsLando** [comment]
It’s correct, I don’t know if maybe it even works by just adding --OPENZWAVE_DEPRECATED16=true to the npm install command, try with that one than let me know :)

Daniel

**Comment by derelict** [comment]
does still not work :-(

**Comment by derelict** [comment]
if i use my modified version of ZwaveClient i still get the same error:

`2019-10-29T14:01:09.277Z z2m:Zwave node 28 ready: FIBARO System - FGS221 Double Relay Switch 2x1.5kW (Binary Power Switch)
events.js:106
    handler.call(self);
            ^

TypeError: undefined is not a function
    at ZwaveClient.scanComplete (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at emitNone (events.js:106:13)
    at OZW.emit (events.js:208:7)
`

**Comment by derelict** [comment]
Cool. Thanks.

Is there anything i can help you with? ... i prefer to offer as much help as possible from my side!

**Comment by robertsLando** [comment]
Atm the solution would be to manually edit gyp file

```
# Clone Zwave2Mqtt build pkg files and move them to /dist/pkg
RUN npm config set unsafe-perm true && npm install -g pkg@4.3.8 \
    && cd /root \
    && git clone https://github.com/OpenZWave/Zwave2Mqtt.git  \
    && cd Zwave2Mqtt \
    && git checkout \
    && npm install \
    && npm run build
    && cd node_modules/openzwave-shared \
    && sed -i 's/"defines": \[/"defines": \[\n\t\t\t\t"OPENZWAVE16_DEPRECATED=<!@(echo 1)",/' binding.gyp \
    && npm install \
```

Unfortunally actually seems something is broken with scenes so this will throw errors on build

**Comment by derelict** [comment]
so should i give this a try for the time being ? i don't "care" or use scenes at the moment .. will it only throw errors but still compile and work fine ?

**Comment by robertsLando** [comment]
Try to create a custom docker build with latest commit and everything should work. 

Just repace the commit id in dockerfile, you don't need to enit npm install script

**Comment by derelict** [comment]
ok (currently i don't reference a commit i just checkout like you do in the example above)

**Comment by robertsLando** [comment]
@derelict Yes I mean that :)

**Comment by derelict** [comment]
so i also do NOT need to add "--OPENZWAVE_DEPRECATED16=true" right ?

**Comment by derelict** [comment]
@robertsLando nevermind .. i just saw the release note for node-openzwave-shared 1.5.9 ...

.... building as we speak :-)

**Comment by robertsLando** [comment]
Thanks to you for the bug report, you welcome 🙏🏻 

Daniel

**Comment by robertsLando** [comment]
Could you close the issue? 

Daniel

**Comment by derelict** [comment]
sure!

Thanks !
