### ISSUE TITLE
[feat] On-Demand Home Assistant Discovery

### ISSUE THREAD

**Issue by derelict** [OpenZWave/Zwave2Mqtt#153]
**Is your feature request related to a problem? Please describe.**
This could also be interpreted as a Bug. I find the Name / Location very usefull to identify and find all my devices. Therefore .. i also prefer to use the location and name for home assistant discovery/device names (so i have nice descriptive entity names in home assistant). However ... when you add a new device to the zwave network ... that device has no location and name set yet. Due to that .. it gets discovered by homeassistant using the default nodeid. When i set the location and name for the device afterwards.. a new discovery message is NOT sent to the mqtt broker (or so to speak to home assistant).

If i click on "rediscover" on an object id (i have to do that per object) ... Z2M still uses the nodeid based topic/information instead of the new name/location information for the discover message ... however ... device state changes in fact do get sent to the new name/location based topic already ... therefore causing an inconsistency between what has been discoverd by homeassistant .. and where actual state changes get sent.

**Describe the solution you'd like**
This is what i would do ... if i had the knowledge to code this up ("the higher the number" the lowest "Priority"):

1. Fix the "Bug" (i consider this to be a bug ?!) of the inconsistent behavior once you adapt the name and or location (send correct discovery message when you click on rediscover per object)
2. Add a button per device in order to send/resend a complete autodiscover message for the whole device using the new/correct name/location values
3. If "Use nodes name instead of numeric nodeID's" and "HASS Discovery" are enabled ... DO NOT sent a discovery message at an addition of a new device (which .. "worst case" could also be retained .. if the user has specified "Retained Topic" !) instead send the discovery message once the name and location has been set (taking into account that the user may has choosen to enable "Ignore Location" ... in that case send the discovery message as soon as only the name has been set).
4. Alternative to Point 3: If "Use nodes name instead of numeric nodeID's" and "HASS Discovery" are enabled ... DO NOT sent a discovery message at an addition of a new device. Instead let the User decide when to send the discovery message manually by using the Button at Point 2

This would be awesome. because right now its quite a mess .. if you add a new device.

**Comment by derelict** [comment]
Additionally:

If you can make sure that Name/Location combinations are enforced to be unique (if enabled for HASS discovery) ... then this would even make zwave device replacements much easier.

Because this way .. a user can replace a zwave device ... set the name and location of the new zwave device .. then send the discovery message manually (again ... this would be Point 2,3 or 4 above) ... and home assistant would be fine with just "using" the new zwave device as it was.

**Comment by derelict** [comment]
> 
> 
> Additionally:
> 
> If you can make sure that Name/Location combinations are enforced to be unique (if enabled for HASS discovery) ... then this would even make zwave device replacements much easier.
> 
> Because this way .. a user can replace a zwave device ... set the name and location of the new zwave device .. then send the discovery message manually (again ... this would be Point 2,3 or 4 above) ... and home assistant would be fine with just "using" the new zwave device as it was.

Actually ... i rethought about that one ... in fact .. rediscovery isn't needed anyway .. as home assistant has discovered that name/location already from the old device ... and state changes are sent to the correct topic still .. once you change the name and location back to what the previous zwave device used.

But still ... HASS Discovery of the newly added device should still be prevented in order to not have "stale" and inconsistent devices in HASS.

This would all be "fixed" by implementing point 1,2 and 3 or 4

**Comment by Dinth** [comment]
I second this. Last few versions of Z2M have greatly improved things, but also made a lot of changes in terms of how values are discovered. The payloads for many of the values must have changed, as i have ended up with literally dozens of unused/unavailable sensors in HA. It would be really nice if Z2M could clean up after itself, but ive got no idea how or even if this is possible in MQTT.

**Comment by robertsLando** [comment]
@Dinth I have keep this as last because it could break some existing things. Needs some thoughts it is in my TODOs btw

**Comment by robertsLando** [comment]
@derelict @Dinth COuld you check latest commit?
