### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by Lineaire** [OpenZWave/Zwave2Mqtt#155]
Hello, I'm having trouble installing the library. I install deb open-zwave but the problem persists ...

Error: libopenzwave.so.1.4: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:680:18)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/Zwave2Mqtt/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:595:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/module.js:11:18)

**Comment by robertsLando** [comment]
Try with 
sudo ldconfig

And if you are on an arm/amd64 also
export LD_LIBRARY_PATH=/usr/local/lib64

Daniel

**Comment by Fishwaldo** [comment]
The Debian OZW package is extremely old. I’ve asked them to either update to a current version or remove it. 

You should install OZW from source.

**Comment by Lineaire** [comment]
I try but compilation failed. What do you communicate in node js zwave?

```
root@DebianVm:/home/sofian/openzwave-1.4.1# make
CPPFLAGS= make -C /home/sofian/openzwave-1.4.1/cpp/build/ -
make[1] : on entre dans le répertoire « /home/sofian/openzwave-1.4.1/cpp/build »
Building OpenZWave Version
Building hid.o
Building aeskey.o
Building aescrypt.o
Building aestab.o
Building aes_modes.o
Building Security.o
Building Proprietary.o
Building SensorAlarm.o
Building ThermostatFanMode.o
Building ControllerReplication.o
Building CRC16Encap.o
Building ZWavePlusInfo.o
Building UserCode.o
Building Language.o
Building MeterPulse.o
Building SensorBinary.o
Building SwitchBinary.o
Building CentralScene.o
Building Configuration.o
Building SwitchToggleBinary.o
Building Hail.o
Building MultiInstance.o
Building ClimateControlSchedule.o
Building Color.o
Building TimeParameters.o
Building ManufacturerSpecific.o
Building ThermostatSetpoint.o
Building EnergyProduction.o
Building Lock.o
Building ApplicationStatus.o
Building SwitchToggleMultilevel.o
Building DoorLockLogging.o
/home/sofian/openzwave-1.4.1/cpp/src/command_classes/DoorLockLogging.cpp: In member function ‘virtual bool OpenZWave::DoorLockLogging::HandleMsg(const uint8*, uint32, uint32)’:
/home/sofian/openzwave-1.4.1/cpp/src/command_classes/DoorLockLogging.cpp:312:15: error: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Werror=restrict]
      snprintf(usercode, sizeof(usercode), "%s %d", usercode, (int)_data[12+i]);
               ^~~~~~~~                             ~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [/home/sofian/openzwave-1.4.1/cpp/build/support.mk:119: /home/sofian/openzwave-1.4.1/.lib/DoorLockLogging.o] Error 1
make[1] : on quitte le répertoire « /home/sofian/openzwave-1.4.1/cpp/build »
make: *** [Makefile:20: all] Error 2
```

**Comment by robertsLando** [comment]
This is not a problem with my lib so I'm going to close this issue. To install OZW from master just use this commands: 

```bash
git clone -b 1.4 https://github.com/OpenZWave/open-zwave.git
cd open-zwave
make && sudo make install
```
