### ISSUE TITLE
[question] get Battery Level

### ISSUE THREAD

**Issue by Qaldak** [OpenZWave/Zwave2Mqtt#157]
I would like to call the battery level of my motion sensor periodicaly (e.g. all two weeks). Because Fibaro Motion Sensor does not deliver on wake up or on other events.

How can I do that with zwave2mqtt? Is there a posibility?

I already tried with a topic .../128/1/0 and an JSON payload. ... but that's just try n error.

**Comment by Qaldak** [comment]
I've got it!

Topic: 
`zwave/_CLIENTS/ZWAVE_GATEWAY-<name>/api/refreshValue/set`

Payload:
`{"args":[2,128,1,0]}`
--> args: node_id, class_id, instance_id, index_id

**Comment by robertsLando** [comment]
You can also set refresh value automatically in gateway values table on settings tab. 

Daniel
