### ISSUE TITLE
Fibaro FGS221 Double Relay Switch

### ISSUE THREAD

**Issue by DyArt** [OpenZWave/Zwave2Mqtt#158]
The FGS221 Double Relay Switch 2x1.5kW (FIBARO System) is detected by Zwave2Mqtt but it is an dual switch and only 1 of the 2 is visible. When I select this device there is only under user 1 switch (2-37-1-0). I thinks there should be also the switch (1-37-1-0). How can I add this extra info to add this switch?

**Comment by robertsLando** [comment]
You should check on Openzwave github project the switch xml file configuration of your device 

Daniel

**Comment by DyArt** [comment]
Just got it working tot set some API calls to the device and then node actions refresh node and the second relay is now also vissible and working

**Comment by robertsLando** [comment]
Perfect, close the issue so :)

Daniel

**Comment by T-Grave** [comment]
I had the same issue, refresh node action did not work for me, but excluding and including again fixed it for me.
