### ISSUE TITLE
[question] Nano Shutter (firmware v3) is not recognized

### ISSUE THREAD

**Issue by Tazintosh** [OpenZWave/Zwave2Mqtt#159]
Good evening,
I've today updated my Aeotec Nano Shutter to v3 (this firmware provide support for the configuration of specific position and not only 0 / 100).
Sadly after upgrade (hopefully successful), I need to use Zwave2Mqtt to setup my device parameters (like physical buttons behaviors) but the device is unknown thus no parameters are available: Unknown: type=0003, id=008d (Unknown: id=0371)
From my understanding, Zwave2Mqtt relies on Open-Zwave, but the config for the shutter zw141.xml have not been updated since June (https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw141.xml).
Node-RED (that I'm using) also relies on Open-Zwave.
Is there any place to grab an updated config?

Thanks in advance for the support.

**Comment by Fishwaldo** [comment]
By default Z2m is using 1.4 version of OZW which is no longer being maintained. You need to change the container configuration to use 1.6 version.

**Comment by Tazintosh** [comment]
Hi @Fishwaldo,
Sorry, I'm quite not used with what you're talking about.
I've installed open-zave with Homebrew, the version is 1.6:
```
brew info open-zwave
open-zwave: stable 1.6 (bottled)
```
I guess Zwave2Mqtt should use this version by no?
Plus, on the above xml link, I'm pointing out the fact the device config (on 1.6) haven't been update since June, thus the Nano Shutter with firmware v3 (out a few days ago) is unknown.

**Comment by Tazintosh** [comment]
From what I know by discussing on OpenHab forum, is that the manufacturer ID have been changed with the last firmware. Aeotec support provided me this link yesterday for the Z-Wave Certification:
https://products.z-wavealliance.org/products/3693
And this is the complete xml:
https://products.z-wavealliance.org/Products/3693/XML

**Comment by robertsLando** [comment]
@Tazintosh If you are using Z2M with pkg or by cloning this repo yes it will use the installed version. If you are using docker it will use the version installed in the docker image (1.4)

**Comment by Tazintosh** [comment]
Yes @robertsLando, I'm using the .zip directly downloaded here (https://github.com/OpenZWave/Zwave2Mqtt/archive/master.zip)
The changed manufacturer ID seems to be the main issue for the device being unknown.

**Comment by Fishwaldo** [comment]
For updating config files please see this: https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

There is no way I can maintain the 900 or so devices that are in the database myself.

**Comment by Fishwaldo** [comment]
By the way - that homebrew is using a very old version of 1.6. You should install from source.

**Comment by Tazintosh** [comment]
Sorry if I seems newbie here (and I am), but as far as I understand, isn't a "version number" maint to define a "version" of something? How can it be a "very old version of 1.6"?? Does it mean there is an "actual" version of 1.6, shouldn't it be 1.6.3 for instance?

**Comment by Tazintosh** [comment]
Ok, cook else this would have drove me crazy lol.
How/Where to you see open-zwave version 1.6.962 here? https://github.com/OpenZWave/open-zwave/

**Comment by petergebruers** [comment]
> How/Where to you see open-zwave version 1.6.962 here? https://github.com/OpenZWave/open-zwave/

It is not there ;)

That is the number of commits since the 1.6 tag was added to the repo. I think the most accurate reply to your response is this, if you have the repo on your system:

git describe --tags
v1.6-962-gcbe2b60f
