### ISSUE TITLE
0x66 not supported - Barrier in OZW 1.4 [feat]

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#160]
**Is your feature request related to a problem? Please describe.**
0x66 barrier class not supported in OZW 1.4

**Describe the solution you'd like**
secondary or tertiary tags for the docker instance
zwave2mqtt:1.4_dev
zwave2mqtt:1.6

**Describe alternatives you've considered**
The challenge is 1.4 dev contains barrier command class
1.6 containers barrier command class, but config files are different

**Comment by Fishwaldo** [comment]
There is no 1.4Dev branch. Only 1.6 has Barrier class.

**Comment by jaburges** [comment]
before HomeAssistant made their own fork, OZW 1.4 Dev was used to include zwave garage/cover. In docker most folks would build a custom docker with ozw 1.4 dev.

@Fishwaldo Here is the Dev branch, and barrier is listed:
https://github.com/OpenZWave/open-zwave/tree/Dev/cpp/src/command_classes

**Comment by Fishwaldo** [comment]
That is Dev of 1.6, not 1.4.  As I said, 1.4 isn’t maintained anymore.

**Comment by jaburges** [comment]
ok, cool - so is there a possibility to add a zwave2mqtt docker image to include OZW 1.6 and have a 1.6 tag?

**Comment by Fishwaldo** [comment]
I believe so - searching here might reveal the answer. - that being said z2m (and the underlying Node library are not 100% compatible with all the features in 1.6)

**Comment by robertsLando** [comment]
Maybe I will create a separate docker tag named `dev` with OZW 1.6

**Comment by jaburges** [comment]
Yes please! That would be super helpful! Thank you
I also understand that there was a user lock code issue in 1.4 that was resolved in 1.6.

**Comment by robertsLando** [comment]
@jaburges I'm releaseing 2.0.6 version now will be available in 1/2 hours. There will be 2 tags:

`2.0.6-dev` and `2.0.6`. The `dev` tag has OZW 1.6 installed

**Comment by jaburges** [comment]
What a HERO, that was super fast - i'll test asap.
Worked out all the kinks by the way (most of which are Z-wave gremlins, and re-pairing solved)

Thank you for your continued hard work!

**Comment by jaburges** [comment]
![image](https://user-images.githubusercontent.com/14154875/69303561-5b3d4080-0bd2-11ea-81a5-19f2c24228f7.png)
