### ISSUE TITLE
[feat] Turn off changed value logs on stdout

### ISSUE THREAD

**Issue by T-Grave** [OpenZWave/Zwave2Mqtt#162]
**Is your feature request related to a problem? Please describe.**
With large and very active zwave networks, the stdout of the container produces a lot of logs (value changed, etc) which aren't very useful unless you're debugging.

**Describe the solution you'd like**
You're already using the `debug` package, which allows enabling/disabling logs using `DEBUG` env variable, but you're also using the `debug.enable` function, which completely overrides the DEBUG value.

I don't see a problem with logs being on by default, but it would be great if we could set the `DEBUG` value. This could easily be achieved by checking `process.env.DEBUG` before calling the `debug.enable` method and skipping it if the env var is detected. That way, the `debug` package is able to parse the `DEBUG` env var and we have complete control over the logging.

If you'd like I could create a PR.

**Describe alternatives you've considered**
An interface toggle would work for me as well, but is obviously a lot more work :)

**Comment by robertsLando** [comment]
@T-Grave Thanks for pointing this out, fell free to create a PR than I will be review it :)
