### ISSUE TITLE
[feat] Controller status over MQTT

### ISSUE THREAD

**Issue by thucar** [OpenZWave/Zwave2Mqtt#164]
**Is your feature request related to a problem? Please describe.**
I'm trying to create a very simple reusable tool for building Z-Wave networks. I would just connect a USB controller to a Raspberry and have a very minimalistic and simple mobile UI for quickly adding devices, setting parameters and associations.

I can achieve most of that already but it would help greatly if I could have feedback from the Controller itself on what's it doing at any given moment in time.

**Describe the solution you'd like**
A precise overview of the controllers status. Is the Inclusion mode currently active? Is Network Heal in progress? Etc.

**Comment by robertsLando** [comment]
Which operations would you like to track? Example:

`scanning`
`running`
`inclusion`
`exclusion`
`healing`

Or what else? Could you provide me a list of useful controller status to keep track?

**Comment by towerhand** [comment]
#140

**Comment by robertsLando** [comment]
@towerhand @thucar latest commit should fit your needs. Now all zwave events are sent to mqtt with all the datas so you can catch controller status updates and more. Just enable the flag on gateway settings to send zwave events via MQTT
