### ISSUE TITLE
[bug] Device is re-added to HA after changing name/location

### ISSUE THREAD

**Issue by RobertMe** [OpenZWave/Zwave2Mqtt#165]
**Version**

Build/Run method
- Docker
- ~PKG~
- ~Manually built (git clone - npm install - npm run build )~

Zwave2Mqtt version: 2.0.6
Openzwave Version: ? (don't know which is used in Docker image)

**Describe the bug**
When using Home Assistant discovery both the `identifier` of the device as the `unique_id` of the entity are based on the location and name of the device. This means that if you rename (or "move"/change location) a device that the device will be rediscovered in Home Assistant as the `identifier`/`unique_id` changed. So persistent ids must be used, this most likely could be the node id which will be unique in the network.  Preferably prefixed with something else (either some unique identifier of the Z-Wave network, or something like the MQTT prefix). This so the id will also be unique when you're running multiple instances of Zwave2Mqtt / having multiple ZWave networks. So the `identifier` of the device will then be some prefix with the node id, and the `unique_id` of the entity will then be the same (prefix + node id) but having the ValueID (I believe it's called) appended to it, which already is the case.

**To Reproduce**
I'm not sure if these are the proper steps, but I believe they are
1. Make sure you have Home Assistant discovery enabled
2. Check that the device is also shown in Home Assistant (so auto discovery works)
3. In Zwave2Mqtt change either the location, or name, of one of the devices/nodes
4. Restart Zwave2Mqtt / change settings and apply them (this will re-send the Home Assistant discovery messages)

**Expected behavior**
When checking Home Assistant again there still is only one device shown. But instead two devices are shown, one for the node were all entity ids etc have the old name/location, and one where the entity ids etc have the new name/location.

**Additional context**
Changing this behavior would be a backwards incompatible change as after an upgrade all devices a user has will be rediscovered by Home Assistant (because of the new `identifier` for the device and `unique_id` of the entity). But this at last makes sure that the same device will never be rediscovered (/show up twice, and one being "dead"). But I believe that's acceptable, and Home Assistant already has done changes like such many more times, where the automatically generated entity ids are changed after an upgrade to have more consistent and reliable ids from then on so they never have to change again. Furthermore the automatically generated entity id can still be changed in Home Assistant so the user doesn't have to use those awkward names anyway (when changing them manually) and other integrations, like zigbee2mqtt also use those kind of "random numbers" as unique id and thus generated entity ids (zigbee2mqtt does use the serial of the device)

**Comment by robertsLando** [comment]
@RobertMe Thanks for this issue, I think you are right and this should be fixed. Would you like to submit a PR to fix this? I can point you where the Ids is calculated in the code

**Comment by RobertMe** [comment]
Hi @robertsLando fixing the bug isn't a problem for me. But testing it is. As I'm running it on a RPi(2) in Docker I need to build the Docker image on the Pi which I guess will take hours, so that makes developing it kinda troublesome. So if you could fix it that would be greatly appreciated :slightly_smiling_face:

**Comment by robertsLando** [comment]
@RobertMe I understand. The valueID of a value is in the format: `<commandClass>-<valueInstance>-<valueIndex>` so based on what you told me it could become:

unique_id : `<mqttName>_<nodeId>-<commandClass>-<valueInstance>-<valueIndex>`

I think mqttName is better than mqtt prefix as maybe someone would like to use the same prefix when having multiple instances on zwave2mqtt.

What do you think?

**Comment by RobertMe** [comment]
@robertsLando I guess it would be best to use the home id (or derivate like the HEX), if I've seen it correctly? As that's bound to the hardware controller and only changes after a hard reset. Then it will always be consistent and no change on the users end could create the duplicate devices, unless doing the hard reset.

I've seen that zigbee2mqtt uses the MQTT prefix, but I'm not sure if Zigbee has something comparable to the home id so not sure if one is preferable over the other. But IMO using something fixed like the home id (+ node id) which the user can't change would be best. (Unless there is some option to get a unique code from the node itself like an embedded serial number. Than even resetting the controller or removing and re-adding the device won't create a duplicate in Home Assistant).

By the way, just to be sure, it's not only about the `unique_id` as set on the entity, but also the `identifier` of the device (so `<entity>.device.identifier`).

**Comment by robertsLando** [comment]
@RobertMe you're absolutely right, never thought about the homeid, in fact it would be the best for this use case. I will implement this in next major release. Thanks

**Comment by robertsLando** [comment]
Hi @RobertMe ! I have just submitted a commit for this, could you check it?
