### ISSUE TITLE
[question] Possible to set a template for Hass discovery for "simple" type

### ISSUE THREAD

**Issue by foxy82** [OpenZWave/Zwave2Mqtt#166]
Hi,

I have several Fibaro Dimmers in my house and discovery for Home Assistant works but I don't want all the paramters of the dimmer. In fact I only want 3 of them below (light_dimmer, sensor_power, sensor_power_O).

![image](https://user-images.githubusercontent.com/7756020/69493606-8791df00-0ea8-11ea-9a6b-b75f699d38b0.png)

Instead of modifying each one individually is in possible to add these to hass/devices.js the same way complex types are? I can find the manufacture id, product id, product type from my zwave cfg xml however all the examples only really show a single set of config, is it possible to have all 3 of the above under a custom config?

**Comment by robertsLando** [comment]
@foxy82 That is why devices.js is here, it is like a database where every user can contribute with his devices. So if you are interested you could send a PR :)

**Comment by foxy82** [comment]
Sure but my question is how do I do that? 

It looks like devices.js will have a single entry per manufacture/product id/product type? I think I need to have 3 entries - one for the switch, one for the current power in W and one for total power used in kwh? The examples all point to only being able to create a single HASS discovery payload per manufacture/product/type?

**Comment by robertsLando** [comment]
@foxy82 You have to create one for each manufacture/product/type

**Comment by foxy82** [comment]
But they are all part of the same product - or am I missing something?

**Comment by robertsLando** [comment]
@foxy82 Oh that is not possible ATM sorry

**Comment by robertsLando** [comment]
What you can do is manually create them on hass side, https://www.home-assistant.io/docs/configuration/devices/

**Comment by robertsLando** [comment]
@foxy82 Sorry I misunderstood your question... Yes you can do what you want, if you check `hass/devices.js` you would see that each product has an array assigned, just add your 3 hass entities there in the correct format
