### ISSUE TITLE
[question] Fibaro Door Window Sensor 2 not reporting open/closed state

### ISSUE THREAD

**Issue by T-Grave** [OpenZWave/Zwave2Mqtt#168]
Hi

I have multiple Fibaro Door/Window Sensor 2 (FGDW-002) devices, but neither of then report any updates if the door is open or not. Back when I used the Home Assistant Zwave controller, they worked fine; they had an `Access Control` and `Access Level` property that I was able to determine if a door is open or closed.

After using them with zwave2mqtt instead, they don't have those properties anymore. Not that I'd want those properties specifically, but the regular `Sensor` value (which is recognized as a binary / contact sensor) doesn't update either.

The only things updating correctly are battery and temperature.

One last clue:
I redid my entire zwave network, because the first time I used zwave2mqtt some of my devices reported being added insecure and I had a lot of removed / dead devices. One of the door sensors wasn't added Secure and that one specifically did actually have an Access Level property that corresponded with the correct sensor state. In HA all of my devices were added Secure as well, so this shouldn't be causing an issue imo.

Any ideas on how to further troubleshoot this?

**Comment by robertsLando** [comment]
This kind of problem are strictly related to the OZW version/database you are using

**Comment by T-Grave** [comment]
I'm using https://github.com/robertsLando/Zwave2Mqtt-docker (non `-dev` image) so it should be version 1.4 right? Which is also the version currently used by HA, so I think the versions are the same (unless there are minor versions I'm not aware from).

So is there anything else that might differ that I'm missing here? Should I try the `-dev` image which has 1.6? Is it stable?

**Comment by T-Grave** [comment]
Tried the 2.0.6-dev tag of your docker image, which uses OZW 1.6.x.

I sure noticed it being an updated version of OZW (different controller status messages etc), but no difference when using the Door Sensor. It only shows 3 properties of all properties it used to show when I used it in HA directly.

Any pointers on how I might try and fix the door sensors?

**Comment by poudenes** [comment]
Hi All, 

Im done with add all my devices. Also 2 FGDW002 Fibaro Door Sensors.
They don't have any MQTT part to send OPEN/CLOSE

Zwave2MQTT is installed using Add-ON of Home Assistant.
Version: Openzwave 1.6.974

What can I do to let those 2 devices work correct?

**Comment by robertsLando** [comment]
@poudenes Open this kind of questions on OZW library

**Comment by poudenes** [comment]
Sure? Because before I use Z2M all my nodes where in HA itself with OpenZwave and it worked correct. OZW 1.4.x version instead of Z2M Openzwave version 1.6.974

**Comment by robertsLando** [comment]
@poudenes Unfortunally hass was maintaining a separete branch of OZW 1.4 with some fixes, now ozw 1.4 is deprecated and 1.6 is the only one maintained so there could have been some breaking change or else. It's not something on my side

**Comment by poudenes** [comment]
@robertsLando when I check the OZW version then I see 1.6.974
Im not using ZWave part inside HA itself, that is OZW 1.4 indeed. Fibaro was working correct.

So to let this work good, will be the best to install Z2M in a docker outside the HA option to install Z2M in a docker?

**Comment by robertsLando** [comment]
> So to let this work good, will be the best to install Z2M in a docker outside the HA option to install Z2M in a docker?

Yes, sure

**Comment by poudenes** [comment]
Ehmm but it is in a docker already. When I stop or restart HA, ZwaveMqtt is still working.
I access it with https://192.168.100.xxx:8091
```
CONTAINER ID        IMAGE                                                COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
5b7921515617        hassioaddons/zwave2mqtt-armv7:0.6.0                  "/init"                  23 hours ago        Up 23 hours         0.0.0.0:8091->8091/tcp                                               addon_a0d7b954_zwave2mqtt
```

**Comment by robertsLando** [comment]
Yes but it is from an addon and I don't know how it handles OZW versions

**Comment by poudenes** [comment]
Clear. So when I install on different RPi and connect the ZWave Dongle to it, it will load the whole mesh network, or do I remove all nodes and add them again?
(Im not sure)
