### ISSUE TITLE
[bug] Adjusting HASS Discovery Topic does not update on existing nodes

### ISSUE THREAD

**Issue by Flight777** [OpenZWave/Zwave2Mqtt#169]
Build/Run method
- HASSIO add-on

Zwave2Mqtt version: 2.0.6

**Describe the bug**

At first set-up I’ve called the MQTT topic “ zwave2mqtt” and left the HASS discovery topic setting blank, thus it would use the general MQTT topic. However, I wanted to change the discovery topic to “ homeassistant”. This is all well, but it does not update the discovery topic for existing nodes, even not when I click “Rediscover” it retains the old discovery topic.

**To Reproduce**
See above

**Expected behavior**

After click “Rediscover” on existing nodes that it would update the discovery topic to the latest on as set in the Settings tab.

**Comment by robertsLando** [comment]
Did you press `UPDATE` after changing the discovery topic in settings?

**Comment by Flight777** [comment]
Does not work,shows JSON test failed and an empty JSON box.

**Comment by robertsLando** [comment]
That’s strange, try to open dev tools on your browser and check the response of the call please

Daniel

**Comment by robertsLando** [comment]
The JSON test failed error is thrown when your device JSON configuration is not valid. You are editing the hass discovery payload and not settings, go to settings tab and set the prefix there and press `UPDATE`

**Comment by Flight777** [comment]
Not sure if I completely follow :P

What I'm doing, I change the discovery topic here in the settings page (I don't see any update button, only save):

![image](https://user-images.githubusercontent.com/5236143/70506274-2e71ae80-1b2a-11ea-95bc-8bdc224659ba.png)

This sends Zwave2Mqtt into a kind of processing mode (all nodes are also not visible anymore) and occasionally "Reconnecting" icon which only is gone when I restart Zwave2Mqtt:

![image](https://user-images.githubusercontent.com/5236143/70506199-05e9b480-1b2a-11ea-8455-7a9799028b42.png)

Chrome console:

![image](https://user-images.githubusercontent.com/5236143/70506362-5d882000-1b2a-11ea-95ef-8423f9eaa91d.png)

After restart I can see everything again (just starting to set-up so only one node available):

![image](https://user-images.githubusercontent.com/5236143/70506463-a344e880-1b2a-11ea-9202-78f1a4bdb4b4.png)

Then I go to the node and I click on for the hass devices (only place I can find with update button):

![image](https://user-images.githubusercontent.com/5236143/70506503-c079b700-1b2a-11ea-9e55-82715d25912e.png)

If I do that, I get the following warning:

![image](https://user-images.githubusercontent.com/5236143/70506533-d4251d80-1b2a-11ea-9655-5bf5871c97ce.png)

**Comment by robertsLando** [comment]
Why are you pressing update on the device json? 

Why don’t just press on “rediscover”?

Anyway all the procedure is good, after you press save everything is disconnected and reconnected and zwave star a new scan of the network (this is why your nodes disappear). Once the scan completes you should see that new discovery payloads are sent with the correct prefix setted in settings 

Daniel

**Comment by Flight777** [comment]
Hi Daniel,

I started this issue that the "rediscover" would not produce the new discovery topic, then you said I should use "update" :P

Again, if this is the correct procedure, it is not working because it keeps retaining the old discovery topic (see screenshot). Also the network scan is kind of stuck, because even after 10-15 minutes it remains in a "processing" state. Only a reboot of Zwave2MQTT brings it to life again.

Kind regards,

Rob

**Comment by Flight777** [comment]
To add: I just tried "Rediscover" again, but also here it jump to the JSON Test Failed warning.

**Comment by robertsLando** [comment]
I will investigate on this. 

About the test failed. It appears just because after you hit rediscover the text area containing the json is cleared and a new test is triggered with “” as value that results in a fail JSON parse, not an error so, need to clarify the UI 

Daniel

**Comment by Flight777** [comment]
Thanks!

**Comment by robertsLando** [comment]
Fixed in latest releases (starting from 3.0.1)
