### ISSUE TITLE
Zwave2Mqtt not sending MQTT message of device status after change confirmation

### ISSUE THREAD

**Issue by nellering** [OpenZWave/Zwave2Mqtt#171]
I am using Home Assistant in HassIO.  I can see the Home Assistant command to change a light from off to on in MQTT Explorer.  I then see Zwave2MQTT debug show it receive the MQTT and send a command to turn the light on.  Everything functions nearly instantly.  The issue is that after Zwave2MQTT confirms that the light actually turned on, it does not send a status update via MQTT that Home Assistant can use to change the status of the light.  

Please let me know what other information is needed to debug.  I can send config settings, logs, etc.

**Comment by robertsLando** [comment]
I don't understand very well your question, does z2m correctly sends the mqtt message but hass doesn't catch it or what else? Do you see the 'response' command from z2m in mqtt exlorer?

**Comment by nellering** [comment]
It appears to started working.  I am still working on migrating from Home Assistant to Zwave2MQTT.  Closing issue.
