### ISSUE TITLE
[question] When viewing the logs/debug output, what is the meaning of the +time at the end?

### ISSUE THREAD

**Issue by DanielWinks** [OpenZWave/Zwave2Mqtt#176]
When viewing the logs/debug output, I've noted there's a +time at the end, such as "115ms". What is this measuring? I'm trying to trace down some latency issues in my network and don't know if this is indicative of an issue or not. I've notice that some messages have ridiculous numbers at the end, such as "+3m" (I'm assuming this is minutes, as opposed to the usual 'milliseconds'), and sometime I see ones like "+51s" (also assuming this is seconds). I couldn't find anywhere this +time thing seems to be documented, so if I missed it, I apologize.

Thanks.

**Comment by robertsLando** [comment]
It’s the time difference from the preceeding log

Daniel

**Comment by DanielWinks** [comment]
Thanks for the quick reply. Not sure how I never put 2 and 2 together that the only time there were stamps in the minutes was after a long break in log messages. Now to get back to troubleshooting why there's sometimes hundreds of milliseconds between sending a command to a Zwave+ switch and getting a response. Thanks again.

**Comment by Fishwaldo** [comment]
Just FYI - you probably want to watch the RTT (Round Trip Time) logged (or exposed via the statistics) - that shows latency on the RF portion of Z-Wave.
