### ISSUE TITLE
[bug] 2.0.6-dev crashes 

### ISSUE THREAD

**Issue by docbobo** [OpenZWave/Zwave2Mqtt#178]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.6-dev
Openzwave Version: 1.6.962

**Describe the bug**
I just noticed that Z2M was crashing from time to time, trying to re-add a node that is currently marked as dead. No step to reproduce, but the following stacktrace:

> zwave2mqtt    |   z2m:Zwave ValueAdded: 7-134-1-2 Application Version +1ms
> zwave2mqtt    |   z2m:Zwave Notification from node 17: Notification - Node Dead (5) +26ms
> zwave2mqtt    | events.js:116
> zwave2mqtt    |     handler.call(self, arg1);
> zwave2mqtt    |             ^
> zwave2mqtt    |
> zwave2mqtt    | TypeError: Cannot read property 'length' of undefined
> zwave2mqtt    |     at Gateway.publishDiscovery (/snapshot/Zwave2Mqtt/lib/Gateway.js:0:0)
> zwave2mqtt    |     at Gateway.onNodeStatus (/snapshot/Zwave2Mqtt/lib/Gateway.js:0:0)
> zwave2mqtt    |     at emitOne (events.js:116:13)
> zwave2mqtt    |     at ZwaveClient.emit (events.js:211:7)
> zwave2mqtt    |     at ZwaveClient.nodeReady (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
> zwave2mqtt    |     at emitTwo (events.js:126:13)
> zwave2mqtt    |     at OZW.emit (events.js:214:7)

**Comment by docbobo** [comment]
Okay, this might be a dupe of #99. Looking into it, it is cause by a node hat I modified according to your suggestion in #177. It seems that for each component that I set to {}, I will get a callback where hassDevice.values is null. Does that make any sense?

**Comment by robertsLando** [comment]
I have no way to check it today but it could be caused by the change I suggested to you yesterday (set the discoverPayload to {}). Try edit the file nodes.json and remove the hassDevices

Daniel
