### ISSUE TITLE
[bug] Name & location not reflected in ozwcache

### ISSUE THREAD

**Issue by docbobo** [OpenZWave/Zwave2Mqtt#182]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.6
Openzwave Version: 1.4 & 1.6

**Describe the bug**
I has assumed that updating name and location via Z2M UI would be reflected in zwcfg or ozwcache. So far, I never saw those attributes being updated there.

I do have some devices that respond with e.g. "Motion Detected at Unknown Location". I was assuming that this message were to change if the location was set correctly on the OZW layer.

**Comment by robertsLando** [comment]
Name and location are stored in nodes.json file. Initially they were stored in cache using setNodeName and setNodeLocation apis but as not all devices support this apis I have moved them to nodes.json. Same thing with scenes, all scenes are handled by z2m and not openzwave 

Daniel

**Comment by robertsLando** [comment]
Anyway this is well documented in docs readme

Daniel

**Comment by docbobo** [comment]
Indeed. Must have missed that piece of information. Out of curiosity, wouldn’t it be possible to forward that information to the node anyway?

**Comment by robertsLando** [comment]
Using mqtt apis for sure, check docs, you can send mqtt messages with args on payload to call zwave apis (in your case apis are setNodeName and setNodeLocation) 

Daniel
