### ISSUE TITLE
[question] Aeon Labs minimote Support

### ISSUE THREAD

**Issue by jei1965** [OpenZWave/Zwave2Mqtt#183]
I am currently running 2.06:latest image in docker and using the Zooz ZST-10 Z-wave stick. I removed the remote from my previous controller and reset the remote. I initially added the device and I could see the device correctly and it was sending the messages correctly, but the home assistant integration did not show all the devices. Next I tried the 2.06-dev to see if the entities show up correctly in Home Assistant but I so no difference. Next I reset everything and went back to the latest image. Ever since I did this I can add the device  and it shows correctly but its status is always sleep and I don't get any message when I press any of the buttons.

Any help would be appreciated 

My settings are:
![Screenshot at 2019-12-26 09-17-30](https://user-images.githubusercontent.com/52546228/71484321-af82a400-27c0-11ea-825a-91435c1e8ce5.png)
![Screenshot at 2019-12-26 09-18-07](https://user-images.githubusercontent.com/52546228/71484324-b27d9480-27c0-11ea-9232-fb19b06d8018.png)

**Comment by robertsLando** [comment]
Hass integration is still beta and doesn't support all devices classes, for ozw 1.6 sleeping devices that is an already known bug, try to open an issue on openzwave library
