### ISSUE TITLE
Jasco/GE 17724 HASS not working correctly

### ISSUE THREAD

**Issue by arraylabs** [OpenZWave/Zwave2Mqtt#184]
Hello, have a couple Jasco/GE 12724 dimmers that HASS doesn't like the mapping from zwave2mqtt. Here is what is mapped:
```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "state_topic": "homeassistant/living_room_ceiling_light/38/1/0",
    "state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "command_topic": "homeassistant/living_room_ceiling_light/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_living_room_ceiling_light"
      ],
      "manufacturer": "Jasco Products",
      "model": "0x3031",
      "name": "12724 3-Way Dimmer Switch",
      "sw_version": "3.37"
    },
    "name": "living_room_ceiling_light_dimmer",
    "unique_id": "zwave2mqtt_living_room_ceiling_light_14-38-1-0"
  },
  "discoveryTopic": "light/living_room_ceiling_light/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "id": "light_dimmer"
}
```
Watching the command topic in node-red via debug I see:
Turning "on" the dimmer via HASS it sends 255, slider in HASS stays at 0 (all the way left), toggle turns on,light full brightness
Turning "off" the dimmer via HASS it sends 0, HASS toggle goes off momentarily then back to on, slider moves to 50%
Turning "off" again via HASS it sends 0, HASS toggle goes to off, stays off slider goes to 0 (all the way left)
Using HASS slider to 50% it sends 50, slider shows 50
Using Hass toggle off, it sends 50, slider stays at 50, toggle switches off momentarily then back to on

Any ideas?

**Comment by robertsLando** [comment]
Could you append hass log too? Maybe it could tell you what is wrong with the payload sent

Daniel

**Comment by jshridha** [comment]
@arraylabs The 12724 dimmers do not report their state after they've been set. You'll need to set up polling for the devices to get their states to update properly like below:
![image](https://user-images.githubusercontent.com/11232787/71522335-45d2ca80-2892-11ea-9ff1-b9219937a273.png)


I set the polling interval to 10000 ms (10 sec) because I only have a few of these devices. You shouldn't set it any lower than 1000 per device. So if you have 3 12724's you shouldn't set it any lower than 3000.

**Comment by robertsLando** [comment]
Thanks @jshridha
