### ISSUE TITLE
[bug] Aeotec Smart Switch 7 (ZW175) wrongly advertised as RGBW switch to Hass

### ISSUE THREAD

**Issue by gertvdijk** [OpenZWave/Zwave2Mqtt#185]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually builgit clone - npm install - npm run build ) 

Docker tagged 2.0.6-dev

**Describe the bug**
The Aeotec Smart Switch 7 (wall socket switch, type ZW175) is working properly in the Z-Wave control center, all expected configuration options and controls are available. However, the device is shown as RGBW switch in Home Assistant, but it's a binary switch. The JSON shows control 37 (switch) with an RGB value_template, but that should be for control 51 (the very tiny night light on the device).

**To Reproduce**
1. Add an Aeotec Smart Switch 7
2. See exported devices for HASS.
3. Observe missing control for main switch.

**Expected behavior**
Both the main switch (binary) and the night light (RGB) are exposed to HASS.

**Additional context**
Adding the following JSON **manually** makes it work with discovery in Home Assistant:

```
{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "state_topic": "myprefix/22/37/1/0",
    "command_topic": "myprefix/22/37/1/0/set",
    "device": {
      "identifiers": [
        "zwave2mqtt_nodeID_22"
      ],
      "manufacturer": "Aeotec Limited",
      "model": "0x00af",
      "name": "ZW175 Smart Switch 7",
      "sw_version": "1.02"
    },
    "name": "nodeID_22_switch",
    "unique_id": "zwave2mqtt_nodeID_22_22-37-1-0"
  },
  "discoveryTopic": "switch/nodeID_22/switch/config",
  "values": [
    "37-1-0"
  ],
  "persistent": false,
  "id": "switch_switch"
}
```

The device JSONs which are not working:

```
{
  "type": "light",
  "object_id": "rgb_dimmer",
  "discovery_payload": {
    "state_topic": "myprefix/22/38/1/0",
    "command_topic": "myprefix/22/38/1/0/set",
    "brightness_state_topic": "myprefix/22/38/1/0",
    "brightness_command_topic": "myprefix/22/38/1/0/set",
    "on_command_type": "first",
    "state_value_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "brightness_value_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "rgb_command_template": "{{ \"#%02x%02x%02x\" | format(blue, green, red)}}",
    "rgb_command_topic": "myprefix/22/51/1/0/set",
    "rgb_state_topic": "myprefix/22/51/1/0",
    "rgb_value_template": "{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}",
    "device": {
      "identifiers": [
        "zwave2mqtt_nodeID_22"
      ],
      "manufacturer": "Aeotec Limited",
      "model": "0x00af",
      "name": "ZW175 Smart Switch 7",
      "sw_version": "1.02"
    },
    "name": "nodeID_22_rgb_dimmer",
    "unique_id": "zwave2mqtt_nodeID_22_22-38-1-0"
  },
  "discoveryTopic": "light/nodeID_22/rgb_dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": true,
  "id": "light_rgb_dimmer"
}
```

```
{
  "type": "light",
  "object_id": "rgb_switch",
  "discovery_payload": {
    "state_topic": "myprefix/22/37/1/0",
    "command_topic": "myprefix/22/37/1/0/set",
    "rgb_command_template": "{{ '#%02x%02x%02x' | format(blue, green, red)}}",
    "rgb_command_topic": "myprefix/22/51/1/0/set",
    "rgb_state_topic": "myprefix/22/51/1/0",
    "rgb_value_template": "{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}",
    "device": {
      "identifiers": [
        "zwave2mqtt_nodeID_22"
      ],
      "manufacturer": "Aeotec Limited",
      "model": "0x00af",
      "name": "ZW175 Smart Switch 7",
      "sw_version": "1.02"
    },
    "name": "nodeID_22_rgb_switch",
    "unique_id": "zwave2mqtt_nodeID_22_22-37-1-0"
  },
  "discoveryTopic": "light/nodeID_22/rgb_switch/config",
  "values": [
    "37-1-0"
  ],
  "persistent": true,
  "id": "light_rgb_switch"
}
```

Both have a wrong mix of control 51 with 37/38 here.

Here's how it looks in the user control section (which is working OK):

![Screenshot from 2019-12-29 18-46-34](https://user-images.githubusercontent.com/1550527/71560664-4d020000-2a6d-11ea-9013-7d748fc53599.png)

**Comment by robertsLando** [comment]
That's because your device also has a valueID with command class 51, in this case z2m identifies it as a rgb light. Unfortunally z2m doesn't know how to automatically map all devices in hass but tries to to its best, when it doens't succeed you can manually fix it and store the configuration by pressing store button on hass devices section of the ui to make it persistent between reboots

**Comment by gertvdijk** [comment]
Yeah, I understand it's just an attempt to map it appropriately, but I still consider this a bug, because I see two different switches in one device, but online one of them is exposed to the HASS autodiscovery. Moreover, it's the least important of the two. It's just quite user unfriendly to not add both switches to the HASS autodiscovery.

I.e. my request is to change the logic of hiding a switch to prevent issues like this, with the downside of just one extra entity for actual RGB lights (which I would consider a minor issue).

**Comment by robertsLando** [comment]
I only see one, the 22-37-1-0,  where is the second? @gertvdijk

**Comment by gertvdijk** [comment]
(Apologies for the late reply)

I see your point now; not a bug but more of a lacking feature. I will try to come up with a fix for this in `hass/devices.js`, would that be acceptable?

I'll also look into a similar error for Hank Motion sensor MS02 where only the tamper sensor is exported, not the motion sensor.

Just need some time to test this and to create a PR, closing this in the meantime.

**Comment by maxenced** [comment]
@gertvdijk do you have any new for this ? It looks like I have the very same issue with aeotec smart switch 6 (ZW096), and can't really understand how I'm supposed to fix it ?

**Comment by robertsLando** [comment]
> That's because your device also has a valueID with command class 51, in this case z2m identifies it as a rgb light. Unfortunally z2m doesn't know how to automatically map all devices in hass but tries to to its best, when it doens't succeed you can manually fix it and store the configuration by pressing store button on hass devices section of the ui to make it persistent between reboots

**Comment by maxenced** [comment]
Thx @robertsLando , So I just need to take the json from @gertvdijk  and try to store it ?  He was talking about a possible fix in hass/devices.js so I wondered if anything has been done here :)

**Comment by robertsLando** [comment]
> So I just need to take the json from @gertvdijk and try to store it

That's the correct way to start, then you can edit it based on your needs :)  Paste it here and send a PR once it works! And also if you need help

**Comment by blhoward2** [comment]
Has anyone managed to fix this? I have the same issue with my Aeotec Switch 6s except the relay also rarely changes when I flip the dimmer in HA on/off, and it doesn’t show the correct state in HA most of the time.

**Comment by robertsLando** [comment]
@blhoward2 Have you tried with: https://github.com/zwave-js/zwavejs2mqtt?

**Comment by blhoward2** [comment]
> @blhoward2 Have you tried with: https://github.com/zwave-js/zwavejs2mqtt?

I have not because after months of dealing with ozw I’m frankly ready for something more stable that just works. How far along is that effort?

**Comment by robertsLando** [comment]
> How far along is that effort?

It depends, what I can tell you is that I don't plan to keep both project maintained, I know that switch costs time but I see no future with OZW for many reasons

**Comment by blhoward2** [comment]
> > How far along is that effort?
> 
> It depends, what I can tell you is that I don't plan to keep both project maintained, I know that switch costs time but I see no future with OZW for many reasons

Understand that. And the development of qt-openzwave has seemingly stalled since July with critical bugs left unaddressed so I appreciate that you’re active at all. How comprehensive is the device database? The only reason that I didn’t start there is that I saw your question about using the ozw device database hasn’t been answered in a while.

**Comment by robertsLando** [comment]
> How comprehensive is the device database? The only reason that I didn’t start there is that I saw your question about using the ozw device database hasn’t been answered in a while.

It already have most devices, if some is missing open a PR and we will help you or add it in few days or even in some hour if it's easy. About the question, it's not answered because Justin isn't active for more then 4 months and he is the man behind all ozw stuff even the last ozw daemon. I don't want to waste my time anymore with ozw, we have created a nice community in slack with the author of zwave js and we are always active to help with problems
