### ISSUE TITLE
[bug] `TypeError: wrong value type!` from bad mqtt message kills console output

### ISSUE THREAD

**Issue by sdwilsh** [OpenZWave/Zwave2Mqtt#186]
**robertslando/zwave2mqtt:latest**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2 (per web ui)
Openzwave Version: ?

**Describe the bug**
When an mqtt message contains a wrongly typed payload, the console terminates (at least from running with docker).  In my case, I was trying to send `True` instead of `true` to a "Bright" entity to simulate pressing and holding down on the brighten direction of my GE z-wave dimmer.

Note: This had given me the impression that the server had died, but it turns out it didn't.

**To Reproduce**
1. Send `True` to a topic that expects `true`/`false`
2. See error

**Expected behavior**
The exception should be handed more gracefully, but still logged.  I wasn't even sure what type I was missing up until I fired up another console and saw what was being sent over mqtt.

**Additional context**
Full exception stack here:
```
zwave2mqtt    |   z2m:Mqtt Message received on zwave2mqtt/Office/3/38/1/1/set +23s
zwave2mqtt    | events.js:126
zwave2mqtt    |     handler.call(self, arg1, arg2);
zwave2mqtt    |             ^
zwave2mqtt    |
zwave2mqtt    | TypeError: wrong value type!
zwave2mqtt    |     at ZwaveClient.writeValue (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
zwave2mqtt    |     at Gateway.onWriteRequest (/snapshot/Zwave2Mqtt/lib/Gateway.js:0:0)
zwave2mqtt    |     at emitTwo (events.js:126:13)
zwave2mqtt    |     at MqttClient.emit (events.js:214:7)
zwave2mqtt    |     at MqttClient.onMessageReceived (/snapshot/Zwave2Mqtt/lib/MqttClient.js:0:0)
zwave2mqtt    |     at emitThree (events.js:136:13)
zwave2mqtt    |     at MqttClient.emit (events.js:217:7)
zwave2mqtt    |     at MqttClient._handlePublish (/snapshot/Zwave2Mqtt/node_modules/mqtt/lib/client.js:987:12)
zwave2mqtt    |     at MqttClient._handlePacket (/snapshot/Zwave2Mqtt/node_modules/mqtt/lib/client.js:336:12)
zwave2mqtt    |     at work (/snapshot/Zwave2Mqtt/node_modules/mqtt/lib/client.js:292:12)
zwave2mqtt    |     at Writable.MqttClient._setupStream.writable._write (/snapshot/Zwave2Mqtt/node_modules/mqtt/lib/client.js:302:5)
zwave2mqtt    |     at doWrite (/snapshot/Zwave2Mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
zwave2mqtt    |     at writeOrBuffer (/snapshot/Zwave2Mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
zwave2mqtt    |     at Writable.write (/snapshot/Zwave2Mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
zwave2mqtt    |     at Socket.ondata (_stream_readable.js:639:20)
zwave2mqtt    |     at emitOne (events.js:116:13)
```

**Comment by sdwilsh** [comment]
I think this just might need a try-catch with some logging added here: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/MqttClient.js#L212

**Comment by robertsLando** [comment]
Thanks @sdwilsh, fixed on master
