### ISSUE TITLE
[bug] Fibaro Dimmer & HA autodiscovery?

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#188]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.6-dev
Openzwave Version: 1.6.962

**Describe the bug**
Autodiscovered HA light entity for a Fibaro Dimmer 2 device doesnt work in HA. While i can adjust brightness, i cannot switch the device on and off. The switch is stuck in off position regardless of light being on and off. 
When im trying to manipulate the HA entity to switch the light on, i can see 

```
Jan 01 17:38:05 zwave/Backyard/6/38/1/0/set 255
Jan 01 17:38:05 zwave/Backyard/6/38/1/0 99
Jan 01 17:38:05 zwave/Backyard/6/38/1/0 99

```
being posted to mqtt. But besides brightness, Fibaro Dimmer should also have on and off, as it does in HA zwave implementation.

I cannot see any on/off switch in web interface either, but i can switch off the light by submitting value "0" to "Instance 1: Level (6-38-1-0)".
![Screenshot from 2020-01-01 17-39-43](https://user-images.githubusercontent.com/313674/71644302-36061c80-2cbe-11ea-9ab7-e296e74b0768.png)

**Comment by robertsLando** [comment]
If your device doens't have a switch valueID this is not possibile, however you could edit hass discovery payload to manually manage this, just remember to set max an min vaule to 100 and not 255. Here an example: 

```js
discovery_payload: {
      schema: 'template',
      brightness_template: '{{ (value_json.value ) | round(0) }}',
      state_template: '{{ "off" if value_json.value == 0 else "on" }}',
      command_on_template: '{{ ((brightness) if brightness is defined else 255 }}',
      command_off_template: '0'
    }
```

**Comment by Dinth** [comment]
Thanks @robertsLando. How can i check if it doesnt have ValueID though? My Dimmers were always presenting on/off switches in HA/OZW1.4. Also the descriptions of config options in OZW1.6 xml file mention that the device should have on/off capability in addition to dimming.

**Comment by robertsLando** [comment]
@Dinth It should show up on the screenshot you posted under user section, If it doesn't it's not a problem related to z2m but someting on openzwave side :(

**Comment by Dinth** [comment]
@robertsLando Thanks. Could you please say something more about editing discovery_payload? I couldnt find any documentation about that in HA wiki

**Comment by robertsLando** [comment]
@Dinth Here: https://www.home-assistant.io/docs/mqtt/discovery/ 

If you need help with sometinh specific post it here :)

**Comment by Dinth** [comment]
Weirdly, while all my other nodes have "Home Assistant Devices" tab, the Dimmer 2 doesnt have it. 
![Screenshot from 2020-01-04 10-12-21](https://user-images.githubusercontent.com/313674/71764054-ccaf2500-2eda-11ea-8256-b91c8f73df8e.png)

**Comment by robertsLando** [comment]
@Dinth It could mean that it hasn't found any associated device to create, try the manual way so: 
https://selfhostedhome.com/migrating-to-zwave2mqtt-for-home-assistant/

**Comment by Dinth** [comment]
Thanks @robertsLando, it is helpful. 
Would it be possible to make Z2M discover if its dealing with Switch or Dimmer and act accordingly.
BTW. I have just found out that normal switches (just on/off states) are also advertised as dimmers to HA.

**Comment by robertsLando** [comment]
@Dinth Unfortunally it's not that easy to identify devices in zwave and create hass instances according to this, this is why I have created `hass/devices.js` file, it would become like a database where users can contribute to identify 'non-standard' devices that z2m isn't able to identify automatically

**Comment by Dinth** [comment]
@robertsLando that's really weird, because Z2M actually identifies a device an on/off switch correctly:
![Screenshot 2020-01-19 at 19 36 01](https://user-images.githubusercontent.com/313674/72687144-fa0eec00-3af2-11ea-822d-3638be93b2a4.png)
but then creates dimmers for it:
![Screenshot 2020-01-19 at 19 37 57](https://user-images.githubusercontent.com/313674/72687167-393d3d00-3af3-11ea-881e-9dfc1093c311.png)
This only happens with Fibaro switches, both single and dual. 
Is hass/devices.js only changing what's in "Hass device JSON" field? If so i can play with it by using Qubino JSON as a template and and if its gonna work can contribute to hass/devices.js, but i dont have a testing environment where i could play with running my own builds of Z2M.

**Comment by robertsLando** [comment]
> Is hass/devices.js only changing what's in "Hass device JSON" field

It describes how to create the discovery payload that is sent to hass so yes you can play with it to fix this. If you make it work please send a pr with the edits to devices.js file

**Comment by Dinth** [comment]
Hi @robertsLando.
Following up on the original issue with dimmers. Have you made any commits recently to fix it?
I just noticed that my HASS Device JSON started showing up for my dimmers. 
Also it already contains the following code:
```
    "brightness_template": "{{ (value / 99 * 255) | round(0) }}",
    "state_topic": "zwave/Backyard/Light/38/1/0",
    "state_template": "{{ \"off\" if value == 0 else \"on\" }}",
    "command_topic": "zwave/Backyard/Light/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
```
Basically what you've advised me to add above.
This being said the behaviour of dimmer didnt change. 
1. I can use Z2M control panel to control the light. My Zwave network now works way better than few weeks ago due to me rebuilding it but also due to recent changes to Z2M, so controlling the light is almost instant.
![Screenshot from 2020-01-22 18-52-36](https://user-images.githubusercontent.com/313674/72924371-b8777e80-3d48-11ea-8798-d167c4e0180d.png)
But there's still a small issue. While clicking "On" button instantly switches the light on, clicking "Off" button changes Level to 1 and the light still dims. Manually changing level to 0 switches the light off. 
Will adjusting the devices.js fix this issue? Im still not sure if devices.js changes the way Z2M sees the device, or just the way it's presented to HA. 
2. While this works in Z2M, the entities discovered in HA dont work at all - its either constantly showing On regardless of the state the light is in and cannot be changed (immediately changes back) or its constantly off, switching it On in HA changes light level to 1 (light dims), but the switch immediately goes back to Off while light stays on level 1. 

Here is my actual HA autodiscovery:
```
homeassistant/light/Front_garden-Light/dimmer_0_2/config {"schema":"template","brightness_template":"{{ (value / 99 * 255) | round(0) }}","state_topic":"zwave/Front_garden/Light/38/2/0","state_template":"{{ \"off\" if value == 0 else \"on\" }}","command_topic":"zwave/Front_garden/Light/38/2/0/set","command_on_template":"{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}","command_off_template":"0","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_dimmer_0_2","unique_id":"zwave2mqtt_Front_garden-Light_16-38-2-0"}
homeassistant/sensor/Front_garden-Light/power/config {"unit_of_measurement":"W","icon":"mdi:flash","value_template":"{{ value }}","state_topic":"zwave/Front_garden/Light/49/1/4","json_attributes_topic":"zwave/Front_garden/Light/49/1/4","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_power","unique_id":"zwave2mqtt_Front_garden-Light_16-49-1-4"}
homeassistant/sensor/Front_garden-Light/power_0/config {"unit_of_measurement":"kWh","icon":"mdi:flash","value_template":"{{ value }}","state_topic":"zwave/Front_garden/Light/50/1/0","json_attributes_topic":"zwave/Front_garden/Light/50/1/0","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_power_0","unique_id":"zwave2mqtt_Front_garden-Light_16-50-1-0"}
homeassistant/sensor/Front_garden-Light/power_8/config {"unit_of_measurement":"W","icon":"mdi:flash","value_template":"{{ value }}","state_topic":"zwave/Front_garden/Light/50/1/8","json_attributes_topic":"zwave/Front_garden/Light/50/1/8","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_power_8","unique_id":"zwave2mqtt_Front_garden-Light_16-50-1-8"}
homeassistant/sensor/Front_garden-Light/water/config {"value_template":"{{ value }}","icon":"mdi:water","state_topic":"zwave/Front_garden/Light/50/1/32","json_attributes_topic":"zwave/Front_garden/Light/50/1/32","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_water","unique_id":"zwave2mqtt_Front_garden-Light_16-50-1-32"}
homeassistant/sensor/Front_garden-Light/alarm_type/config {"icon":"mdi:alarm-light","value_template":"{{ value }}","state_topic":"zwave/Front_garden/Light/113/1/0","json_attributes_topic":"zwave/Front_garden/Light/113/1/0","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_alarm_type","unique_id":"zwave2mqtt_Front_garden-Light_16-113-1-0"}
homeassistant/sensor/Front_garden-Light/alarm_level/config {"icon":"mdi:alarm-light","value_template":"{{ value }}","state_topic":"zwave/Front_garden/Light/113/1/1","json_attributes_topic":"zwave/Front_garden/Light/113/1/1","device":{"identifiers":["zwave2mqtt_Front_garden-Light"],"manufacturer":"FIBARO System","model":"0x1000","name":"FGD212 Dimmer 2","sw_version":"Unknown"},"name":"Front_garden-Light_alarm_level","unique_id":"zwave2mqtt_Front_garden-Light_16-113-1-1"}
```
and my Hass Autodiscovery JSON is:
```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value / 99 * 255) | round(0) }}",
    "state_topic": "zwave/Backyard/Light/38/1/0",
    "state_template": "{{ \"off\" if value == 0 else \"on\" }}",
    "command_topic": "zwave/Backyard/Light/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_Backyard-Light"
      ],
      "manufacturer": "FIBARO System",
      "model": "0x1000",
      "name": "FGD212 Dimmer 2",
      "sw_version": "Unknown"
    },
    "name": "Backyard-Light_dimmer",
    "unique_id": "zwave2mqtt_Backyard-Light_6-38-1-0"
  },
  "discoveryTopic": "light/Backyard-Light/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "id": "light_dimmer"
}
```

**Comment by robertsLando** [comment]
> Will adjusting the devices.js fix this issue? Im still not sure if devices.js changes the way Z2M sees the device, or just the way it's presented to HA

That file just describes how the device is created in hass and how it should receive/send commands with z2m. So based on what you said I think it's the device that doesn't handle correctly the 'off' command (if sent from control panel). If this happens when you send the off from hass it means there is something not working with hass discovery payload.

```js
"brightness_template": "{{ (value / 99 * 255) | round(0) }}",
    "state_topic": "zwave/Backyard/Light/38/1/0",
    "state_template": "{{ \"off\" if value == 0 else \"on\" }}",
    "command_topic": "zwave/Backyard/Light/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0"
```

[Here](https://www.home-assistant.io/integrations/light.mqtt/) You find a spec of how the discovery payload of a light is composed. 

https://www.home-assistant.io/integrations/light.mqtt/#brightness_template
https://www.home-assistant.io/integrations/light.mqtt/#state_topic
https://www.home-assistant.io/integrations/light.mqtt/#command_topic
https://www.home-assistant.io/integrations/light.mqtt/#command_on_template
https://www.home-assistant.io/integrations/light.mqtt/#command_off_template

Maybe an hass update has break something?

**Comment by robertsLando** [comment]
@Dinth Any news?

**Comment by Dinth** [comment]
Sorry @robertsLando i havent had a chance to test it yet, something came up at work and i will be extremely busy for next few weeks. I will try to test that in next couple of days, weekend latest.

**Comment by robertsLando** [comment]
@Dinth Don't worry let me know :)

**Comment by Dinth** [comment]
Hi @robertsLando 
Ive just noticed that when i run light.turn_on or light_turn_off service in HA (which both work) or manually switch the light using a physical switch im getting the following error in HA:
```
2020-02-03 21:46:09 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zwave/Backyard/Light/38/1/0': '99'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_template.py", line 241, in state_received
    ].async_render_with_possible_json_value(msg.payload)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 276, in async_render_with_possible_json_value
    return self._compiled.render(variables).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "
TypeError: unsupported operand type(s) for /: 'str' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_template.py", line 241, in state_received
    ].async_render_with_possible_json_value(msg.payload)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 276, in async_render_with_possible_json_value
    return self._compiled.render(variables).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "
```

**Comment by robertsLando** [comment]
@Dinth Please set the payload to JSON time value or Entire zwave object
