### ISSUE TITLE
Enabeling/disabling zwave logging does not take effect on save.

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#19]
When enabling or disabling the logging toggle and hitting safe, logging is not enabled|disabled.

**Comment by robertsLando** [comment]
I know this, I'm still sure that this is something wrong with node-openzwave-shared connection management. Something strange in connect and disconnect methods. I'm not very friendly with C++, could you check connect and disconnect methods of node-openzwave-shared and check if options are inited/reset correctly? I think that when something is not reinited on disconnect and this causes to connect using the previous options...

**Comment by robertsLando** [comment]
Check the OpenZwave constructor too, here is where I pass the options and seems that options can be set only once: 

https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave.cc#233

Daniel

**Comment by robertsLando** [comment]
Check this, it is the constructor of OpenZwave and seems that options can be inited only once: 

https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave.cc#233

How can this be fixed?

**Comment by sjorge** [comment]
I think the only way to do the change is to destroy the entire object and create a fresh one?
Like do the cleanup as you do now, then complete reinitialize the entire client object? Seems a bit wasteful resource wise though... then again it is not something you will do often.

**Comment by robertsLando** [comment]
This is not possible in javascript, the only way to do this would be start zwave in a separate process an kill the process but this is such an hard solution for a simple problem in my opinion. I think things need to be fixed on the library side, I will open an issue on node-openzwave shared about this problem

**Comment by sjorge** [comment]
SGTM

**Comment by robertsLando** [comment]
@sjorge  the response from the author: 

> quick short answer: the C++ plugin currently only reads config upon init
time. It will need some refactoring to make it able to reread and apply new
options at runtime.

Need to check the code and see we can do something

**Comment by robertsLando** [comment]
Hi @sjorge. I have tried to check the code here: https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave.cc#L203 but sincerly I don't understand why options can be inited just one time. Maybe you are more familiar than me with C++ could you check that code? I don't think the fix would be much hard just need to know where to start...

**Comment by sjorge** [comment]
Aside from forcing it to compile I have limited understanding of c++ code.

This bit is very confusing as it seems to be building and arg list for a process... which does not make much sense.

**Comment by sjorge** [comment]
Are there any clues in the other program where you got the other fix from?

**Comment by robertsLando** [comment]
Just submitted a PR that seems to work from my tests, let's wait to check what happens 

https://github.com/OpenZWave/node-openzwave-shared/pull/277

**Comment by robertsLando** [comment]
Error on app veyor: 

```
C:\projects\node-openzwave-shared\lib\install-ozw.js:147
  throw err;
  ^
Error: invalid signature: 0x4f44213c
    at C:\Users\appveyor\AppData\Local\Temp\1\ozwinstall-0pm1a\node_modules\unzip\lib\parse.js:59:13
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```
