### ISSUE TITLE
[question] Migrate from HA to Zwave2MQTT

### ISSUE THREAD

**Issue by stich86** [OpenZWave/Zwave2Mqtt#191]
Hi guys,

i want to migrate my Z-Wave devices from HA to this project, currently I own just 16 nodes divided into:

- Fibaro FGS-223 and 213 (Single and Double Relay Switch) using S2 security (4x) -- used for light
- Fibaro Roller Shutter FGR-222 (5x) -- cover
- Qubino ZMNHCD1 (3x) -- cover
- Philo PB01 (1x) -- energy meter from 
- Neocool Plugs (2x) -- plugs

Controller is a ZME-UZB stick

What's the best way to do this migration? I want to avoid repairing all nodes, because some devices are not easy to reach.

Thanks in advance

**Comment by robertsLando** [comment]
https://selfhostedhome.com/migrating-to-zwave2mqtt-for-home-assistant/

**Comment by robertsLando** [comment]
Copy your zwcfg_<homeHex>.xml inside z2m store folder than start the app. If you was using ozw 1.4 in hass you should use the latest version tag on docker (if you choose docker) anyway the ozw version must be the same used in hass or the zwcfg file will be not compatible

**Comment by stich86** [comment]
But if I want to migrate to OZW 1.6, after first migration from 1.4 is it possible?

Thanks

**Comment by robertsLando** [comment]
Yes but that requires you to remove all nodes from your controller and add them all back bacouse they will likely not work when you update the ozw version

Daniel
