### ISSUE TITLE
[bug] Export of nodes.json fails with "Error: Invalid string length"

### ISSUE THREAD

**Issue by docbobo** [OpenZWave/Zwave2Mqtt#192]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.6-dev

**Describe the bug**
When trying to export the nodes.json, nothing gets downloaded. The console shows:

```
GET /api/exportConfig NaN - Error: Invalid string length
GET /api/exportConfig 302 2.818 ms - 23
GET / 304 0.531 ms - -
```

I am getting a similar error, when trying to execute setNodeLocation (discussed in a different ticket). Not sure how to get more debug info out of the system.

**Comment by robertsLando** [comment]
Will dig into this on Thuesday, thanks for the issue 

Daniel

**Comment by docbobo** [comment]
Just as an additional information: I was trying to execute a setNodeLocation before and that produced the exact same error. After restarting Z2M the problem on export went away. Maybe the setNodeLocation put the system into a weird state.

**Comment by robertsLando** [comment]
@docbobo Just pushed a commit to allow you to call setNodeName and setNodeLocation apis because by checking the code even when you call this methods using mqtt apis the custom method is used instead of the zwave client method. 

Just another info, could you show me the topic/payload you sent to call the setNodeLocation/setNodeName apis using mqtt?

**Comment by robertsLando** [comment]
About the bug I'm not able to reproduce it, I can successfully import/export my nodes.json configuration

**Comment by docbobo** [comment]
I believe I first tried this:

> {
>   "args": [ "<home_id>", "<device_id>", "<location>"
> }

which produced some other error. Afterwards, I made the leave of faith that maybe Z2M was adding the home_id itself, and got rid of that. This resulted in "Invalid String Length".

**Comment by robertsLando** [comment]
yes homeid should not be specified in calls. Does an application restart resolve the problem? If you restart the app are you able to export nodes?

**Comment by docbobo** [comment]
Restarting fixes the problem. If you don't want to spent much time on that, I'd be totally fine with that.

**Comment by robertsLando** [comment]
@docbobo Would be for sure an inconsistent state caused by the first api request
