### ISSUE TITLE
[bug] Fibaro Single Switch 2 incorrectly recognized

### ISSUE THREAD

**Issue by Munsio** [OpenZWave/Zwave2Mqtt#193]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: v2.0.6
Hassio Docker Container

**Describe the bug**
After adding a Fibaro single switch 2 (FGS213) the device list shows the product as: `Unknown: type=0403, id=1000 (Unknown: id=010f)`

Also under the user values there are now 3 switches instead of 1.
And only 1 of them is working correctly

**To Reproduce**
1. Add Fibaro single switch 2

**Expected behavior**
Product gets recognized as FGS213 with a single switch

**Additional context**
I re added this device in older versions it got recognized correctly, unfortunately i don't know which version i used where it successfully worked

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by Fishwaldo** [comment]
You need to see if it exists in manufacture_specific, if not:
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
(if this is using OZW 1.4, we are no longer updating the device database for it. Only 1.6)

**Comment by Munsio** [comment]
The docker image from hassio is running ozw 1.6
https://github.com/hassio-addons/addon-zwave2mqtt/blob/master/zwave2mqtt/Dockerfile#L16

The strange thing is that the switch worked in zwave2mqtt. Only after exclution and inclusion the problem appeared

**Comment by Munsio** [comment]
If you can tell me how i can aggregate debug information for you i will post it here.

**Comment by Dinth** [comment]
@Munsio post OZW_Log.txt
It should be stored where the Z2M config directory is mapped on your drive. 

I've got a couple of Fibaro Single Switches 2, actually paired them today and they are being discovered fine (although Z2M thinks those are dimmers for some reason)

**Comment by Dinth** [comment]
@Munsio, one more thing. 
By "device is not being discovered" do you mean that after adding a node, you're getting a dead device in Z2M without empty "Type" and "Product" fields? 
This happened to me few times with different Fibaro devices, it seems that the inclusion process doesnt always finishes correctly (although i dont have logs to post upstream). Re-adding the node (reset the switch, add it again) works for me in those cases.

**Comment by Munsio** [comment]
@Dinth, the device is not dead - it is actually working but there is no product/manufacturer information and instead of 1 switch there are 3 switches available and in general all fields are doubled etc.

About the log, the hassio addon does not provide the OZW log in a shared folder and I didn't have time for that yet, but i am trying to get all the information you need including screenshots this weekend.

**Comment by Dinth** [comment]
Hmm that's more than odd. 
For me nodes were being discovered without product/type before, but i had a big zwave network with some underlying issues. Ive been told that i need to rebuild my network from scratch and since then the problem went away. 
Three switches is also very weird, you should see two switches with Fibaro single switch and three with Fibaro Double Switch. Additionally, Z2M also generates two light dimmers for each switch, which is a glitch and hopefully will soon get resolved.

Would you mind trying to re-add your device and check if that's something repetitive or it was just one time off issue. Also are you running the latest version of Z2M? Things have been changing pretty quickly over last couple of weeks.

**Comment by Munsio** [comment]
So today i got finally some spare time to look at it again, and i feel really really dumb cause it is working now.

The first time i tried docker daemon restarts or just simple container restarts an nothing worked. 
Today after a Kernel update i rebooted the whole thing and now the switch get recognized as it should.

So i think that this wasn't a failure of openZwave or so but more like a failure of the z-wave usb-controller!?

**Comment by robertsLando** [comment]
It could be yes, or something docker related too

Daniel

**Comment by Munsio** [comment]
My bet is on the controller cause I restarted the docker container and daemon several times.

Nevertheless should i upload my OZWLog so you can take a look at it or should we close this issue now that it is resolved.

**Comment by robertsLando** [comment]
@Munsio Such things are hard to debug when things don't work and than start working so I prefer to close this issue for now and I will reopen it if you get some errors again that could help to debug this

**Comment by Dinth** [comment]
@Munsio theres no need to "feel dump", there's definitely something on the plate with Fibaro switches - i had a very similar problem few times, except ive been re-including such devices

**Comment by Fishwaldo** [comment]
FYI - There is a bug in the interview process, after adding a new device, not all its capabilities are "exposed". You just need to restart OZW and it will correct itself. Its possible your hitting this bug.
