### ISSUE TITLE
[bug] /src/node_buffer.cc:210:char* node::Buffer::Data(v8::Local<v8::Value>): Assertion `val->IsArrayBufferView()' failed.

### ISSUE THREAD

**Issue by ksuclipse** [OpenZWave/Zwave2Mqtt#194]
**Version**

Build/Run method
- [ X] Docker
- [ ] PKG
- [ X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.1
Openzwave Version: 1.4.1

**Describe the bug**
when sending an MQTT message to 99/1/3/set of schlage door lock i get error listed above.  It seems that as its converting mqtt is sending string data but node is looking for buffer data.  This is when i try to set a usercode.  

**To Reproduce**
schlage door lock (or maybe any door lock), publish to 99/1/3/set of that node, zwave2mqtt will crash

**Expected behavior**
should receive command

**Additional context**
i've tried json, and raw with multiple formats of hex, dec, buffer type and the same message currently in 99/1/3:
{"value_id":"37-99-1-28","node_id":37,"class_id":99,"type":"raw","genre":"user","instance":1,"index":28,"label":"Code 28:","units":"","help":"","read_only":false,"write_only":false,"min":0,"max":0,"is_polled":false,"value":{"type":"Buffer","data":[0,0,0,0,0,0,0,0,0,0]}}

**Comment by robertsLando** [comment]
Could you paste here the payload you are trying to send?
