### ISSUE TITLE
[question] How do you send the duration for SwitchMultilevel::Set ?

### ISSUE THREAD

**Issue by beanz** [OpenZWave/Zwave2Mqtt#196]
I have tried sending many different json payloads to the set topic - such as `{"value": 99, "duration": 128 }` (i.e. full brightness in one minute) - but nothing seems to work?
What would be the correct way to do this?
Regards,
 Mark

**Comment by robertsLando** [comment]
It depends on your gateway settings. If the payload type is set to `Just Value` you shoud only send `99`  or `128`, If JSON time-value `{value: 99}`

**Comment by beanz** [comment]
I have no problem sending the value. As the subject of the questions says, how do I send the duration so that the duration in the openzwave SwitchMultilevel::Set call ends up being anything other than Default?

I currently set lights to come on to full brightness over ten minutes in order to help me wake up in the mornings but I don't seem to be able to do that via the MQTT interface.

**Comment by robertsLando** [comment]
There is no such feature in z2m, I that should be supported by your device and there should be a value in configuration that handles the duration. The other way would be to create a scene where you send multiple times to the same valueid a set command with some delay un seconds

Daniel

**Comment by beanz** [comment]
It is supported by the zwave API (see https://github.com/OpenZWave/open-zwave/blob/52db0e91de8361d68467195dcfd2a01544f7f361/cpp/src/command_classes/SwitchMultilevel.cpp#L430) and many common devices support this. My understanding was that the z2m project was aiming to provide "full access" to all API features "by simply using MQTT".

It would make sense to me to be able to send `{"value": 99, "duration": 137}` for example (as I do with my current zwave implementation) to leverage the full power of common zwave devices rather than have to script it with scenes (which I could obviously do but it seems overly complicated for something already supported by the "hardware" directly).

I understand now that the z2m project doesn't currently support this but in simply closing my question and your response it also seems like you are saying it never will? That's a shame as I'd might have been tempted to work on a pull request.

Thanks for your time in answering my questions. It is much appreciated.

**Comment by robertsLando** [comment]
Sorry for that initially I thought that you was asking for something else. I need to ask Fishwaldo about this because I never know about this feature, could you tag him here? I’m not on my laptop right now, tomorrow I will reopen this and if possible I will integrete the feature. 

Daniel

**Comment by beanz** [comment]
@Fishwaldo tagging you on this question as requested by @robertsLando.

Thanks!

**Comment by beanz** [comment]
I think I see how it can be done currently. (I'd test it now but my family are going to sleep in all the rooms with dimmers and might not appreciate it. I'll test it tomorrow.) I'd have to send three messages:

1) Send the duration to topic `zwave2mqtt/<node-id>/38/1/5/set`,
2) Send the level value to topic `zwave2mqtt/<node-id>/38/1/0/set`, and
3) Send the default duration value (255) to topic `zwave2mqtt/<node-id>/38/1/5/set`.

My currently implementation performs this as a single zwave message and so it is a shame there isn't a way to do this via a single message on the mqtt API but at least I can do what I want.

**Comment by robertsLando** [comment]
@beanz That is what I meant when I said:

> should be supported by your device and there should be a value in configuration that handles the duration

Let me know

**Comment by beanz** [comment]
Okay. The non-atomic process I described does work. When you say "Z2M provides a generic gateway that maps values from zwave<-->mqtt", I think it maps from mqtt specifically to the openzwave API since as you can see from the code I referenced the wire protocol to the controller permits sending the duration atomically with the value. The way the duration is handled is specific to openzwave not the zwave specification AFAIK.

When you say "takes the duration from an external configuration value" I don't quite understand. Looking at the debug, the duration value is stored internally between steps 1 and 2 and does not seem to be sent to the device except during the set call. So I don't understand why you say it is "an external configuration value" when it appears entirely virtual within the openzwave API not external at all.

Regardless, I have a way to do what I want. While I'm curious why the openzwave API does things this way, I completely understand the z2m matching what the openzwave API does in the simplest manner possible as a design choice.

**Comment by Fishwaldo** [comment]
Everything in OZW is essentially exposed as a value. In this case, as long as a device supports specifying dim duration, a duration value is exposed. 

You have to be aware of the order of setting values. If Z2m is setting the duration value “after” the level, then of course it will not take effect (but will for the next level set and so on”). 

Sending them in a atomic fashion may mean your left to the whims of JavaScript or JSON parsing or Z2m when determining the order that values are set.

**Comment by robertsLando** [comment]
@beanz If you look at the code you previuosly pointed me to: 

```c++
bool SwitchMultilevel::SetLevel(uint8 const _instance, uint8 const _level)
			{
				Log::Write(LogLevel_Info, GetNodeId(), "SwitchMultilevel::Set - Setting to level %d", _level);
				Msg* msg = new Msg("SwitchMultilevelCmd_Set", GetNodeId(), REQUEST, FUNC_ID_ZW_SEND_DATA, true);
				msg->SetInstance(this, _instance);
				msg->Append(GetNodeId());

				if (GetVersion() >= 2)
				{
					Internal::VC::ValueByte* durationValue = static_cast<Internal::VC::ValueByte*>(GetValue(_instance, ValueID_Index_SwitchMultiLevel::Duration));
					uint8 duration = durationValue->GetValue();
					durationValue->Release();
...
```

You can see that the args of the method `SetLevel` are `instance` and `level`. There is no `duration` parameter because it is fetched by another valueid here 

```c++
Internal::VC::ValueByte* durationValue = static_cast<Internal::VC::ValueByte*>(GetValue(_instance, ValueID_Index_SwitchMultiLevel::Duration));
					uint8 duration = durationValue->GetValue();
```

This is what I mean when I say 'It is take from another configuration value" Because duration is a configuration value of the device.
