### ISSUE TITLE
[bug] aeotec ZW122 Water Sensor 6 manufacturer name is unknown

### ISSUE THREAD

**Issue by twochannel** [OpenZWave/Zwave2Mqtt#198]
**Version 2.1.0**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.0
Openzwave Version: 1.4.1 (whatever is default w/ container)

**Describe the bug**
The aeotec ZW122 Water Sensor 6 manufacturer  shows up as

`    "manufacturer": "Unknown: id=0086",`
`    "model": "0x007a",`
`    "name": "Unknown: type=0102, id=007a",`

in the product column of the gui and the hass device json output.

**To Reproduce**
1. Securely pair the water sensor (non-secure shows correct information)
2. View product column in web ui.

**Expected behavior**
Manufacture/model show correctly.

**Additional context**
none

**Comment by Fishwaldo** [comment]
https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices

**Comment by Fishwaldo** [comment]
But clarification- OZW 1.4 is not accepting new config updates.

**Comment by robertsLando** [comment]
Try to call `Refresh node info` from control panel against this node

**Comment by twochannel** [comment]
Thanks for the replies.  I assumed since the manufacturer showed up in a non-secure pairing, it would be fine when paired securely.  I did the refresh node info then woke the device up and it did not populate the correct info.  FWIW on native home assistant integration it showed correctly when paired securely.

**Comment by jerepeer** [comment]
Had the same problem with the Aeotec Siren6  (ZW164). Switching to OZW 1.6 was my only option. It works now.

**Comment by robertsLando** [comment]
@twochannel Please consider update to OZW 1.6

**Comment by twochannel** [comment]
1.6 shows manuf info correctly when securely paired.  Thank you
