### ISSUE TITLE
Unidentified device, but has a definition config/fibaro/fgwd111.xml

### ISSUE THREAD

**Issue by craigrallen** [OpenZWave/Zwave2Mqtt#201]
A device is included as an unknown device, but has an Open-Zwave definition file as per issue [#1873](https://github.com/OpenZWave/open-zwave/pull/1873)

I've included a device, but it is not identified. Also tried rediscovering the device with (Refresh Node Info). The unit is a Fibaro Walli Dimmer, but when including it doesn't identify and shows some of the Home Assistant devices, one comes up as a water sensor, but the device is a light switch without a water sensor.

I am using Home Assistant on a Raspberry Pi and not sure where to look for the definition files for zwave2mqtt. The version of HassOS is v3.8, Home Assistant is v0.103.6 and zwave2mqtt is v2.0.6.

How can I force identification and access the correct additional configuration parameters?

OpenZWave Error, Node017, ERROR: Dropping command, expected response not received after 1 attempt(s)
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: Notification - TimeOut
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Query) message (Callback ID=0x1b, Expected Reply=0x04) - PowerlevelCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x73, 0x02, 0x25, 0x1b, 0xb9
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x1b, 0x00, 0x00, 0x07, 0xf7
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x1b received (expected 0x1b)
OpenZWave Info, Node017, Request RTT 70 Average Request RTT 90
OpenZWave Detail, Expected callbackId was received
2020-01-15T18:25:03.816Z z2m:Zwave zwave node 17: changed: 115-1-0:Powerlevel:Normal -> Normal
OpenZWave Detail, Node017, Received: 0x01, 0x0a, 0x00, 0x04, 0x00, 0x11, 0x04, 0x73, 0x03, 0x00, 0x00, 0x94
OpenZWave Detail,
2020-01-15T18:25:03.820Z z2m:Zwave zwave node 17: changed: 115-1-1:Timeout:0 -> 0
OpenZWave Info, Node017, Response RTT 142 Average Response RTT 181
OpenZWave Info, Node017, Received a PowerLevel report: PowerLevel=Normal, Timeout=0
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=list
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Query) message (Callback ID=0x1c, Expected Reply=0x04) - ProtectionCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x75, 0x02, 0x25, 0x1c, 0xb8
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x1c, 0x00, 0x00, 0x10, 0xe7
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x1c received (expected 0x1c)
OpenZWave Info, Node017, Request RTT 161 Average Request RTT 125
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x0a, 0x00, 0x04, 0x00, 0x11, 0x04, 0x75, 0x03, 0x00, 0x00, 0x92
OpenZWave Detail,
2020-01-15T18:25:04.059Z z2m:Zwave zwave node 17: changed: 117-1-0:Protection:Unprotected -> Unprotected
OpenZWave Info, Node017, Response RTT 236 Average Response RTT 208
OpenZWave Info, Node017, Received a Protection report: Unprotected
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=list
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Query Stage Complete (Session)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Dynamic live=1
OpenZWave Detail, Node017, QueryStage_Dynamic
OpenZWave Detail, Node017, Queuing (Send) SwitchMultilevelCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x26, 0x02, 0x25, 0x1d, 0xea
OpenZWave Detail, Node017, Queuing (Send) MeterCmd_Get (Node=17): 0x01, 0x0a, 0x00, 0x13, 0x11, 0x03, 0x32, 0x01, 0x00, 0x25, 0x1e, 0xfc
OpenZWave Detail, Node017, Queuing (Send) MeterCmd_Get (Node=17): 0x01, 0x0a, 0x00, 0x13, 0x11, 0x03, 0x32, 0x01, 0x10, 0x25, 0x1f, 0xed
OpenZWave Info, Node017, CentralScene RequestState: 4
OpenZWave Info, Node017, CentralScene: Not a StaticRequest
OpenZWave Detail, Node017, Queuing (Send) AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x20, 0x8d
OpenZWave Detail, Node017, Queuing (Send) AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x09, 0x01, 0x25, 0x21, 0x8d
OpenZWave Detail, Node017, Queuing (Query) Query Stage Complete (Dynamic)
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x1d, Expected Reply=0x04) - SwitchMultilevelCmd_Get (Node=17): 0x01, 0x09, 0x00, 0x13, 0x11, 0x02, 0x26, 0x02, 0x25, 0x1d, 0xea
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x1d, 0x00, 0x00, 0x14, 0xe2
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x1d received (expected 0x1d)
OpenZWave Info, Node017, Request RTT 210 Average Request RTT 167
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x0b, 0x00, 0x04, 0x00, 0x11, 0x05, 0x26, 0x03, 0x00, 0x00, 0x00, 0xc1
OpenZWave Detail,
2020-01-15T18:25:04.348Z z2m:Zwave zwave node 17: changed: 38-1-0:Level:0 -> 0
OpenZWave Info, Node017, Response RTT 286 Average Response RTT 247
OpenZWave Info, Node017, Received SwitchMultiLevel report: level=0
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x1e, Expected Reply=0x04) - MeterCmd_Get (Node=17): 0x01, 0x0a, 0x00, 0x13, 0x11, 0x03, 0x32, 0x01, 0x00, 0x25, 0x1e, 0xfc
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x1e, 0x00, 0x00, 0x0c, 0xf9
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x1e received (expected 0x1e)
OpenZWave Info, Node017, Request RTT 132 Average Request RTT 149
OpenZWave Detail, Expected callbackId was received
OpenZWave Detail, Node017, Received: 0x01, 0x14, 0x00, 0x04, 0x00, 0x11, 0x0e, 0x32, 0x02, 0x21, 0x44, 0x00, 0x00, 0x00, 0x74, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xd1
2020-01-15T18:25:04.563Z z2m:Zwave zwave node 17: changed: 50-1-32:Exporting:false -> false
2020-01-15T18:25:04.565Z z2m:Zwave zwave node 17: changed: 50-1-0:Energy:1.16 -> 1.16
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 213 Average Response RTT 230
OpenZWave Detail, Node017, Refreshed Value: old value=false, new value=false, type=bool
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Info, Node017, Received Meter report from node 17: Energy=1.16kWh
OpenZWave Detail, Node017, Refreshed Value: old value=1.16, new value=1.16, type=decimal
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x1f, Expected Reply=0x04) - MeterCmd_Get (Node=17): 0x01, 0x0a, 0x00, 0x13, 0x11, 0x03, 0x32, 0x01, 0x10, 0x25, 0x1f, 0xed
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x1f, 0x00, 0x00, 0x14, 0xe0
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x1f received (expected 0x1f)
OpenZWave Info, Node017, Request RTT 196 Average Request RTT 172
OpenZWave Detail, Expected callbackId was received
2020-01-15T18:25:04.838Z z2m:Zwave zwave node 17: changed: 50-1-32:Exporting:false -> false
2020-01-15T18:25:04.840Z z2m:Zwave zwave node 17: changed: 50-1-8:Power:0.6 -> 0.6
OpenZWave Detail, Node017, Received: 0x01, 0x10, 0x00, 0x04, 0x00, 0x11, 0x0a, 0x32, 0x02, 0x21, 0x32, 0x00, 0x06, 0x00, 0x00, 0x00, 0x00, 0xd5
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 273 Average Response RTT 251
OpenZWave Detail, Node017, Refreshed Value: old value=false, new value=false, type=bool
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Info, Node017, Received Meter report from node 17: Power=0.6W
OpenZWave Detail, Node017, Refreshed Value: old value=0.6, new value=0.6, type=decimal
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x20, Expected Reply=0x04) - AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x08, 0x01, 0x25, 0x20, 0x8d
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x20, 0x00, 0x00, 0x0d, 0xc6
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x20 received (expected 0x20)
OpenZWave Info, Node017, Request RTT 132 Average Request RTT 152
OpenZWave Detail, Expected callbackId was received
2020-01-15T18:25:05.049Z z2m:Zwave zwave node 17: changed: 113-1-0:Alarm Type:0 -> 0
2020-01-15T18:25:05.050Z z2m:Zwave zwave node 17: changed: 113-1-1:Alarm Level:0 -> 0
2020-01-15T18:25:05.054Z z2m:Zwave zwave node 17: changed: 113-1-2:SourceNodeId:0 -> 0
2020-01-15T18:25:05.055Z z2m:Zwave zwave node 17: changed: 113-1-11:Power Management:254 -> 254
OpenZWave Detail, Node017, Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x11, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x08, 0xfe, 0x00, 0x91
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 208 Average Response RTT 229
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:Power Management event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail,
OpenZWave Info, Node017, Sending (Send) message (Callback ID=0x21, Expected Reply=0x04) - AlarmCmd_Get (Node=17): 0x01, 0x0c, 0x00, 0x13, 0x11, 0x05, 0x71, 0x04, 0x00, 0x09, 0x01, 0x25, 0x21, 0x8d
OpenZWave Detail, Node017, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node017, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node017, Received: 0x01, 0x07, 0x00, 0x13, 0x21, 0x00, 0x00, 0x0d, 0xc7
OpenZWave Detail, Node017, ZW_SEND_DATA Request with callback ID 0x21 received (expected 0x21)
OpenZWave Info, Node017, Request RTT 133 Average Request RTT 142
OpenZWave Detail, Expected callbackId was received
2020-01-15T18:25:05.261Z z2m:Zwave zwave node 17: changed: 113-1-0:Alarm Type:0 -> 0
2020-01-15T18:25:05.279Z z2m:Zwave zwave node 17: changed: 113-1-1:Alarm Level:0 -> 0
2020-01-15T18:25:05.280Z z2m:Zwave zwave node 17: changed: 113-1-2:SourceNodeId:0 -> 0
2020-01-15T18:25:05.281Z z2m:Zwave zwave node 17: changed: 113-1-12:System:254 -> 254
2020-01-15T18:25:05.286Z z2m:Zwave node 17 ready: FIBARO System - Unknown: type=1c01, id=1000 (Unknown)
OpenZWave Detail, Node017, Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x11, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x09, 0xfe, 0x00, 0x90
OpenZWave Detail,
OpenZWave Info, Node017, Response RTT 208 Average Response RTT 218
OpenZWave Info, Node017, Received Alarm report: type=0, level=0, sensorSrcID=0, type:System event:254, status=255
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=0, new value=0, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Refreshed Value: old value=254, new value=254, type=byte
OpenZWave Detail, Node017, Changes to this value are not verified
OpenZWave Detail, Node017, Expected reply and command class was received
OpenZWave Detail, Node017, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node017, Removing current message
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Notification: ValueChanged
OpenZWave Detail, Node017, Query Stage Complete (Dynamic)
OpenZWave Detail, Node017, AdvanceQueries queryPending=0 queryRetries=0 queryStage=Configuration live=1
OpenZWave Detail, Node017, QueryStage_Configuration
OpenZWave Detail, Node017, QueryStage_Complete
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=0 sleepingOnly=1
OpenZWave Detail, Node017, Notification: NodeQueriesComplete

**Comment by robertsLando** [comment]
@craigrallen This could happen sometimes when there are errors while scanning, try to call the api 'refresh node info` against the unknown node

**Comment by craigrallen** [comment]
Hi,

I tried to refresh node a couple of times. I also added a second identical device and it came up as unknown as well.

It seems to be some other issue that the device isn't recognized, because it is now two identical units that are showing unknown.

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by Fishwaldo** [comment]
OZW 1.4 is no longer updated. The config you reference are in 1.6. 
@robertsLando could you please drop 1.4 support, or at least make 1.6 the default. This is causing issues all over the place.

**Comment by robertsLando** [comment]
I wish but If I do this all people using z2m with Ozw 1.4 will have to remove and add back all nodes of their network and maybe someone will stop updating instead of doung this

Daniel

**Comment by Fishwaldo** [comment]
Then please stop tagging me on 1.4 issues. 1.6 has been out almost 12 months. I'm starting on 1.8 soon. I can't continue to support 1.4 (and it has bugs/issues that have been fixed in 1.6)

>Ozw 1.4 will have to remove and add back all nodes of their network 

eh? That does not make sense. The network is stored on the stick. If you start ozw 1.6, it will just work with existing nodes. No need to exclude/include devices.

Other things like the discussion around #197 are not forward compatible with 1.6.

**Comment by robertsLando** [comment]
@Fishwaldo users that have upgraded from 1.4 to 1.6 usually had to recreate the entire network because after the upgrade all devices are shown as sleep

**Comment by craigrallen** [comment]
How do I enable ozw 1.6 in the Home Assistant z2m version? I just thought it ran 1.6 as default?

**Comment by robertsLando** [comment]
@craigrallen If you are using docker switch to latest-dev tag

**Comment by craigrallen** [comment]
I'm using the standard Home Assistant build of HassOS and community download of z2m through the Home Assistant Lovelace interface, on a raspberry pi. Is this install of z2m in that instance docker based?

**Comment by Fishwaldo** [comment]
Sleeping devices just need to be woken up. You would have exactly the same experience as restarting OZW 1.4. 

As you can see - people are migrating to Z2m expecting OZW 1.6 and they are not getting it. It is frustrating a lot of users over there.

**Comment by craigrallen** [comment]
I just moved form the home assistant native to z2m to get it to work with devices I saw definition files for. To be honest if can't have it on 1.6, I'll move back to the native version on home assistant because it doesn't require all the extra effort to manage MQTT without any benefits.

**Comment by robertsLando** [comment]
> 'm using the standard Home Assistant build of HassOS and community download of z2m through the Home Assistant Lovelace interface, on a raspberry pi. Is this install of z2m in that instance docker based?

@craigrallen I don't know what the Hass Lovelace interface makes you download, I think it downloads [this](https://github.com/hassio-addons/addon-zwave2mqtt/blob/master/zwave2mqtt/Dockerfile) ? That is not maintaned by me, try to update to the latest version 2.1.0 please and let me know

**Comment by robertsLando** [comment]
> As you can see - people are migrating to Z2m expecting OZW 1.6 and they are not getting it. It is frustrating a lot of users over there.

I also got many issues from users updating to 1.6 and saw lot devices not working anymore that is why I hadn't still removed the 1.4 support. Also hass afaik is still using ozw 1.4 am I wrong?

**Comment by robertsLando** [comment]
@Fishwaldo For me removing ozw 1.4 support would be fine and would make it easier for me but I must be sure everything works as expected... If you confirm that this will not break anything I will remove supoort from next versions

**Comment by craigrallen** [comment]
Yep, Hass is using 1.4 natively and it's buggy and a lot of devices aren't fully recognized. There is work going on to build a 1.6 version as far as I can see from researching it, but it's not ready yet.

**Comment by craigrallen** [comment]
This is the community version I'm using

https://github.com/hassio-addons/addon-zwave2mqtt

**Comment by robertsLando** [comment]
@craigrallen Main reason why hass users are using zwave2mqtt is because it allows to prevent full network scans (that could take very long in large networks) when you restart hass. Now as I said the OZW 1.6 is already available [here](https://hub.docker.com/layers/robertslando/zwave2mqtt/latest-dev/images/sha256-1e719efe779801994a167d1dc73323edea8560bc4a51e8d99d5ce8e0b0d954df) you could choose to install it by your own or check if the one you installed has it or update it. From next release you will be able to see from control panel the OZW version too

**Comment by robertsLando** [comment]
@craigrallen So just update it as you are using 2.0.6 version and the latest is 2.1.0

**Comment by Dinth** [comment]
@craigrallen is your node detected as Dead by any chance? Had this few times with OZW1.6 and Fibaro switches, but readding the node helps?

**Comment by robertsLando** [comment]
@Fishwaldo Just to inform you, OZW 1.4 support removed from Z2M 2.1.1. Now latest tag hìhas 1.6 version

**Comment by Fishwaldo** [comment]
👍👍👍

**Comment by syphernl** [comment]
> @Fishwaldo Just to inform you, OZW 1.4 support removed from Z2M 2.1.1. Now latest tag hìhas 1.6 version

@robertsLando I installed Z2M 2.1.1 (via the zipfile) but it still includes OZW 1.4.1?

**Comment by robertsLando** [comment]
What do you mean with `via zip file`?  If you have downloaded the pkg version from github releases the OZW is not shipped with it, OZW is installed in your system

**Comment by syphernl** [comment]
> What do you mean with `via zip file`? If you have downloaded the pkg version from github releases the OZW is not shipped with it, OZW is installed in your system

This one: https://github.com/OpenZWave/Zwave2Mqtt/releases/download/v2.1.1/zwave2mqtt-v2.1.1.zip AFAIK this bundles everything without needing to install libs yourself?

**Comment by robertsLando** [comment]
@syphernl Nope. Only if you use docker it works in that way. OZW is a separated software from Z2M

**Comment by syphernl** [comment]
> @syphernl Nope. Only if you use docker it works in that way. OZW is a separated software from Z2M

Ah I see. Didn't recall installing it myself, but it was indeed in my bash history :)
