### ISSUE TITLE
Can not add Secure devices.

### ISSUE THREAD

**Issue by Mdleal** [OpenZWave/Zwave2Mqtt#202]
Version: 2.1.0 on docker
Devices: First Alert smoke detector, kwikset lock

I've added 3 secure device and non have added securely. I have the key in place and added the device within inches of the aeon stick. What kind of logging do I need to turn on to help figure out what's going on?

**Comment by robertsLando** [comment]
@Mdleal the secure flag that you see in control panel is not always correct because it depends on a valueid that not all secure devices have. So it could be possible that you added it securely and you see a false flag on the control panel

**Comment by Mdleal** [comment]
I can not control the locks via mqtt or HA. Here is the device in zwcfg.
[](https://pastebin.com/MSnYMN8J)

**Comment by Fishwaldo** [comment]
You need to ensure a network key is set and it’s added securely.

**Comment by Mdleal** [comment]
Network key is set but I do not get the secure pop up when adding a device. I have tried removing the key and re-adding it. I'll create a new one and try again.

**Comment by Fishwaldo** [comment]
You need to use the right function when adding it as secure. I have no idea how that’s exposed in Z2m

**Comment by robertsLando** [comment]
When you send a controller action to start the inclusion from control panel you will see a popup that asks if you want ti add that node in secure mode or not, just press in ok and the node will be added with security enabled

Daniel

**Comment by Mdleal** [comment]
@robertsLando I am not getting the pop up. I might blow everything away and start over. I have 2 pi's with their own stick running zwave2mqtt and both do not get the pop up.

**Comment by robertsLando** [comment]
Please send me the screenshot of the action you are sending... once you select the action press the airplaine botton on the right of the dropdown 

Daniel

**Comment by Mdleal** [comment]
![image](https://user-images.githubusercontent.com/691042/72667898-520bfc80-39e6-11ea-99bf-f1b135c696fe.png)

**Comment by Mdleal** [comment]
Reset Z-wave stick and reinstalled zwave2mqtt resolved the issue. I know get the pop up.

**Comment by robertsLando** [comment]
@Mdleal I think that was something related to browser that was blocking the pop ups or something else not strictly related to z2m. Gla you fixed it

**Comment by cts1085** [comment]
I am running into the same problem and have used multiple browsers with no pop-up. How did you reset the Z-wave stick?

**Comment by robertsLando** [comment]
To reset the zwave-stick you could both do it via the UI or by following the z-stick manual (I suggest you to follow the manual)

**Comment by cts1085** [comment]
Perfect - I will give it a go - so I should expect a pop-up dialog when adding the first device that I know supports secure add - Thanks for all of your help!

**Comment by robertsLando** [comment]
@cts1085 YOu should send `Add Node (inclusion)` controlle action and than a pop-up will be show to ask you if you want to add it securely or not

**Comment by cts1085** [comment]
ok - tried that before resetting my zwave stick - ensured browser (chrome) allows pop-ups and it did not prompt me. My next step is to reset everything

**Comment by robertsLando** [comment]
@cts1085 https://stackoverflow.com/questions/34063030/javascript-confirm-not-working-in-chrome

Try to disable Ad BLock

**Comment by cts1085** [comment]
So - before resetting - I tried the following: Disabled Ad block, allowed pop-ups, even tried incognito same issue, also tried a clean install of firefox - same thing.  The log simply said adding unsecure:

` 
 
2020-03-03T19:03:50.942Z z2m:App Zwave api call: addNode [ false ]
2020-03-03T19:03:50.944Z z2m:Zwave Success zwave api call addNode true
2020-03-03T19:03:50.950Z z2m:Zwave controller command { nodeid: 0, state: 1, errcode: 0, help: 'AddDevice Starting' }
OpenZWave Detail, Queuing (Controller) Add Device
OpenZWave Info, Add Device
OpenZWave Detail, contrlr, Queuing (Command) ControllerCommand_AddDevice: 0x01, 0x05, 0x00, 0x4a, 0xc1, 0xb9, 0xc8
2020-03-03T19:03:50.958Z z2m:Zwave controller command { nodeid: 0, state: 4, errcode: 0, help: 'AddDevice Waiting' }
OpenZWave Detail, Notification: AddDevice ControllerCommand - Starting
OpenZWave Detail,
OpenZWave Info, contrlr, Sending (Command) message (Callback ID=0xb9, Expected Reply=0x4a) - ControllerCommand_AddDevice: 0x01, 0x05, 0x00, 0x4a, 0xc1, 0xb9, 0xc8
OpenZWave Info, contrlr, Encrypted Flag is 0
OpenZWave Detail, contrlr, Received: 0x01, 0x07, 0x00, 0x4a, 0xb9, 0x01, 0x00, 0x00, 0x0a
OpenZWave Detail,
OpenZWave Info, contrlr, FUNC_ID_ZW_ADD_NODE_TO_NETWORK:
OpenZWave Info, contrlr, ADD_NODE_STATUS_LEARN_READY
OpenZWave Detail, contrlr, Expected callbackId was received
OpenZWave Detail, contrlr, Expected reply was received
OpenZWave Detail, contrlr, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, contrlr, Removing current message
OpenZWave Detail, Notification: AddDevice ControllerCommand - Waiting
OpenZWave Info, WriteNextMsg Controller nothing to do
2020-03-03T19:03:53.480Z z2m:Zwave controller command { nodeid: 0, state: 6, errcode: 0, help: 'AddDevice InProgress' }
OpenZWave Detail, Received: 0x01, 0x07, 0x00, 0x4a, 0xb9, 0x02, 0x00, 0x00, 0x09
OpenZWave Detail,
OpenZWave Info, FUNC_ID_ZW_ADD_NODE_TO_NETWORK:
OpenZWave Info, ADD_NODE_STATUS_NODE_FOUND
OpenZWave Detail, Notification: AddDevice ControllerCommand - InProgress
2020-03-03T19:03:53.793Z z2m:Zwave controller command { nodeid: 42, state: 6, errcode: 0, help: 'AddDevice InProgress' }
OpenZWave Detail, Received: 0x01, 0x1c, 0x00, 0x4a, 0xb9, 0x03, 0x2a, 0x15, 0x04, 0x18, 0x01, 0x5e, 0x85, 0x59, 0x55, 0x86, 0x72, 0x5a, 0x73, 0x80, 0x98, 0x9f, 0x84, 0x5b, 0x70, 0x6c, 0x7a, 0xef, 0x26, 0xcc
OpenZWave Detail,
OpenZWave Info, FUNC_ID_ZW_ADD_NODE_TO_NETWORK:
OpenZWave Info, ADD_NODE_STATUS_ADDING_SLAVE
OpenZWave Info, Adding node ID 42 - Non-Secure
OpenZWave Detail, Node042, Notification: AddDevice ControllerCommand - InProgress
OpenZWave Detail, Received: 0x01, 0x07, 0x00, 0x4a, 0xb9, 0x05, 0x2a, 0x00, 0x24
2020-03-03T19:03:55.966Z z2m:Zwave controller command { nodeid: 42, state: 6, errcode: 0, help: 'AddDevice InProgress' }
OpenZWave Detail,
OpenZWave Info, FUNC_ID_ZW_ADD_NODE_TO_NETWORK:
OpenZWave Info, ADD_NODE_STATUS_PROTOCOL_DONE
O`

**Comment by robertsLando** [comment]
@cts1085 I will replace that confirm dialog with a normal dialog in future, sincerly I don't know why it doesn't work in your instance I'm sorry :( 

![Schermata da 2020-03-04 08-09-12](https://user-images.githubusercontent.com/11502495/75854019-83525780-5def-11ea-9a37-1626816f510d.png)

**Comment by robertsLando** [comment]
@cts1085 Just submitted a fix for this. WIll be available in next 3.0.1 release

**Comment by cts1085** [comment]
Thank you very much! I will still try a reset of the controller as indicated above to see if that resolves it - I will let you know.

**Comment by robertsLando** [comment]
@cts1085 Don't need it now, don't waste your time :)
