### ISSUE TITLE
[question] how to get a list of all available nodes?

### ISSUE THREAD

**Issue by magtimmermans** [OpenZWave/Zwave2Mqtt#207]
Hi,

First of all thanks for this great project! 

I have aquestion which command i need to send to zwave2mqtt topic to get a list of all available nodes?

**Comment by robertsLando** [comment]
@magtimmermans Nope there is not such functionality, what would you need it for ?

**Comment by magtimmermans** [comment]
Pitty, i have a homey and i am not happy with the range of the zwave module. I am not sure if it is broken but any way i bought a zwave usb stick and installed everything on a rasp pi. Now i am writing a program that create those devices on homey and the communicate with the homey devices using zwave2mqtt. To add the devices to homey i need a list with all available devices (nodes) and can create the devices (nodes) on homey. I have tested this with one node where i know the number from and this works great. I have done this also for zigbee2mqtt wich has such a function. Something like zigbee2mqtt/bridge/config/devices/get which give me a list of all nodes and some basic info like brand, type etc.

**Comment by robertsLando** [comment]
I could add this as a feature but I was thinking about something like _EVENTS topic where you receive all zwave events like: scanComplete, nodeAdded, nodeReady, nodeAvailable etc.. with all the args of this events like nodeInfo etc. Would it be ok for you ?
