### ISSUE TITLE
Protocol support in host url

### ISSUE THREAD

**Issue by papertigers** [OpenZWave/Zwave2Mqtt#21]
Maybe I am missing something but passing in the host and port to the mqtt `options.servers` array inside lib/MqttClient.js doesn't seem to allow me to connect to a tls secured mosquitto broker.

If I manually change the code to be `var client = mqtt.connect('tls://mqtt.example.com', options)` then everything works as expected and a connection to the mqtt broker is established.

I have tried messing around with putting the url in the "Host url" section of the web UI and that results in connection failures that look like:

```
1556827963: New connection from 10.8.8.98 on port 8883.
1556827963: OpenSSL Error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
1556827963: Socket error on client <unknown>, disconnecting.
```

**Comment by robertsLando** [comment]
Will submit a commit with the fix today

**Comment by robertsLando** [comment]
@papertigers Please pull last version and tell me if it's working. 

Just add the protocol in the host url like: `tls://mqtt.example.com`

**Comment by papertigers** [comment]
Working perfectly.
Thanks!

Side note, I am using lets encrypt and I had to add the lets encrypt root cert to my local certs.
It's possible that others may be issuing a self signed cert instead and they might want a check mark in the UI for `"rejectUnauthorized": false`.  I can open another issue for that if you would like.

**Comment by robertsLando** [comment]
I think that I could add that option by default to be false. Would it be ok for you?

**Comment by papertigers** [comment]
I think a default of false would be bad because it exposes the user to a potential mitm attack.  I think the default of true that's implied now is the right way to go.  I think a user should explicitly have to click a "I am using a self signed cert" box.

**Comment by robertsLando** [comment]
Yep sure you right, now I will submit the fix with the ui improovments than let me know if it works

**Comment by robertsLando** [comment]
@papertigers Please check now and let me know, I have added an option `Allow self signed certs` on MQTT settings UI. Enable that flag and that will set the `"rejectUnauthorized": false` on connection options.

Remember to rebuild the project with `npm run build` to see the ui changes. 

If your problem is fixed close this issue
