### ISSUE TITLE
[bug] Voltage metering is detected as gas density

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#213]
**Version**
2.1.0
Build/Run method
- [x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.0
Openzwave Version: 1.6

**Describe the bug**
Voltage value of power sensors is detected as "gas density". 

**To Reproduce**
Can be reproduced both with Fibaro and TKB power switches with power metering. 

**Additional context**

I believe its this bit of code:
```
        } else if (type === 'meter') { // https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml#L680
          let index = valueId.index
          if (index <= 9 || index === 48 || index === 64) cfg = 'sensor_power'
          else {
            switch (index) {
              case 32:
              case 33:
              case 34:
                cfg = 'sensor_water'
                break
              case 16:
              case 17:
                cfg = 'sensor_gas_density'
                break
              case 19:
              case 35:
                cfg = 'sensor_pulse'
            }
          }
        }
```

**Comment by robertsLando** [comment]
@Dinth I think your device goes against the standards devices command classes specs: https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml#L679. 

In your case command class is 50 and the index I think is 16 or 17 that based on that file means should be a gas meter, you should edit this by your own in hassDevices from control panel or in hass/devices.js file

**Comment by Dinth** [comment]
@robertsLando 

>@Dinth I think your device goes against the standards devices command classes specs: https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml#L679.

Its really weird, as Home Assistant was always detecting this correctly and it's not just one odd model but two different from different manufacturers. Anyhow, i will try to fix this using devices.js as soon as i will figure out how to do that.

**Comment by robertsLando** [comment]
That’s interesting, I would like to know how hass identify devices to create. Is it inside hass zwave repo?

Daniel

**Comment by Dinth** [comment]
I really dont know how HA is built. But to be honest I had over 50 zwave devices and besides devices which were not supported by OZW i dont remember having an issue with entities being created wrong type over past two years when i was using HA built in OZW1.4.
With OZW1.6/Z2M almost every single device has an odd water or gas sensor somewhere which should not belong there.
Potentially this may be a OZW1.6 thing, but that would be a huge regression with many popular devices and defo wouldnt go unnoticed.

**Comment by robertsLando** [comment]
I will investigate on this

**Comment by robertsLando** [comment]
@Fishwaldo Do you know something about this? I mean do you know how hass zwave integration works? I can't find the source code. I don't know if they have created a database zwave-config --> hass devices like I'm doing with hass/devices.js or what else...

**Comment by Dinth** [comment]
@robertsLando OK i think that with the sensors, HA is using the unit to determine what kind of data it stores.
But with other devices, like distinguishing lights, binary switches and fans, **i think** it uses this code: https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/zwave/discovery_schemas.py

**Comment by robertsLando** [comment]
Wow your link is what I was looking for and I think I could apply it to Z2M too. I saw they also have https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/zwave/workaround.py that is something like my hass/devices.js. 

Actually I have not the time to dig into this and add to the code but it is a point to start with. WOuld you mind to send a PR to improve discovery? Just fork the project and take a look at `lib/Gateway.js`. 

[Here](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L200) Is where I start the discovery. There are two methods: [discoverDevice](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L622) and [discoverValue](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L700) The first one checks for existing configurations inside /hass/devices.js (so the workarounds) and the seconds does the real auto-discovery that we are talking about by trying to guess the right component to create based on zwave valueid props.

**Comment by Dinth** [comment]
@robertsLando my level of coding is very entry-level. My badge may say "Contributor" but the only thing i contributed was a screenshot :)

Ive picked up one thing which *may* be causing problems though. In this place the code is going through all the "values", checks command class assigned to that value and proceeds accordingly - https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L719 This being said, looking at OZW config files devices often have CommandClasses which are there theoretically, but dont work - for example: https://github.com/OpenZWave/open-zwave/blob/4f1da72fceb2ead7cc0814edcf58a784cb2b942e/config/aeotec/dsa03202.xml#L79 and https://github.com/OpenZWave/open-zwave/blob/4f1da72fceb2ead7cc0814edcf58a784cb2b942e/config/aeotec/dsa03202.xml#L88. As far as i can see, most of those CommandClasses have a GetSupported tag set to false. Is Z2M still running discoverValue for those values? 

I think that OZW config files for all my binary switches which have dimmer detected instead contain: 
```
 <!-- COMMAND_CLASS_SWITCH_MULTILEVEL. This class is in the list reported by the device, but it does not respond to requests -->
  <CommandClass id="38">
    <Compatibility>
      <GetSupported>false</GetSupported>
    </Compatibility>
  </CommandClass>

```
Also one more thing. 
Here https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L762 i can see a nice if loop trying to guess the type of value based on the label. 

What if you could take similar approach to guess - or at least verify - the type of other values?
This is something i could potentially help with, copy/paste and slightly changing regex is about my level of coding :) And i was just about trying to do that with gas_density sensor, but i noticed that since i upgraded Z2M to 2.1.1 (and im assuming OZW to the latest build as im using ) yesterday evening, the gas_density sensors (which were actually detecting voltage on Fibaro and TKB switches) are gone 
<img width="326" alt="Screenshot 2020-01-23 at 15 48 19" src="https://user-images.githubusercontent.com/313674/73000478-ce447c80-3df8-11ea-8a5a-8fa10df37907.png">

**Comment by robertsLando** [comment]
> most of those CommandClasses have a GetSupported tag set to false. Is Z2M still running discoverValue for those values?

Yes it runs discoverValue for each value you see in controlpanel (it means every value that OZW detects), but I don't know what `GetSupported` means sincerly. Maybe @Fishwaldo knows

> What if you could take similar approach to guess - or at least verify - the type of other values?

Check the label isn't really good as with OZW 1.6 labels now support differents languages. I have make long thoughts about hass auto discovery and how to cleverly map values from zwave to hass but I never found something 'strong'. The best option would be to create a database for all devices that my algorithm cannot auto-discover but this depends on the active users that contribute to the project as there are lot zwave devices out there :(

Maybe we could extend some regex on units to make it better

**Comment by Dinth** [comment]
> but I don't know what GetSupported means sincerly. 
I really hope he wont mind, but i will tag @petergebruers

>Check the label isn't really good as with OZW 1.6 labels now support differents languages.
Would it be possible to check the unit of measurement instead of the label? "V" stands for volt anywhere in the world. 
> The best option would be to create a database for all devices that my algorithm cannot auto-discover but this depends on the active users that contribute to the project as there are lot zwave devices out there :(
This may work, but only once the userbase reaches a certain critical point

**Comment by robertsLando** [comment]
Just for a quick reference:

° °C C F ---> temperature
pa bar atm ---> pressure
V volt ---> Voltage
A ---> Current
kwh kw w watt ---> Power
m3 ---> Water
kg/m3 ---> Gas density
lux lx ---> Illuminance

Are this all? I can create regex based on this and If I don't find any occurence use the switch case based on valueid index

**Comment by Dinth** [comment]
Ive got a slightly different idea. The value type still gives us more information than the unit - provided it is correct. For example the code must be able to distinguish air pressure from water pressure. 
What if its done other way around:
```
case 15: // voltage
 #verify if thats correct
  if (/\b(v|volt)\b/gi.test(valueId.units)) { 
  #ok, now are almost certain that the value type is correct
    cfg = 'sensor_power'
  } else {
  # something went wrong, lets figure out wth is the correct value type
    if (/\b(c|°|f)\b/gi.test(valueId.units)) {
          cfg = 'sensor_temperature'
        } else if (/\b(w|v|watt|volt|kw|kwh)\b/gi.test(valueId.units)) {
          cfg = 'sensor_power'
        } else if (/\b(bar|pa)\b/gi.test(valueId.units)) {
          cfg = 'sensor_humidity'
        }
```
Its more code but once you could make one switch, i can do the boring work and copy and paste it few times. Doesnt make a lot of difference now, but in the future - if you would like for example to create more specific entity names (voltage vs more generic power) it will make things easy and still accurate.

**Comment by robertsLando** [comment]
@Dinth by doing what you are doing you always make units check a priority so the result will always be the same as what I told you :) You firstly check for the valueId index than you make sure units are ok, if not you check the correct type based on units. 

More efficent would be firstly check units (when the command class is a multilevel or a meter) and then check for valueid index in case the units tests doesn't return a valid configuration.

I think that we could create a function `typeByUnits()` that returns the cfg type based on units instead of copy and paste the code you suggested there. 

for example: 

```js
function typeByUnits(units) {

var cfg = null
if (/\b(c|°|f)\b/gi.test(valueId.units)) {
          cfg = 'sensor_temperature'
        } else if (/\b(w|v|watt|volt|kw|kwh)\b/gi.test(valueId.units)) {
          cfg = 'sensor_power'
        } else if (/\b(bar|pa)\b/gi.test(valueId.units)) {
          cfg = 'sensor_humidity'
        }
...

return cfg
}
```

**Comment by Dinth** [comment]
I think the code you're looking for is here: https://github.com/OpenZWave/open-zwave/blob/5fdefd84b60c6c4989e39d8948dc199890d16da3/cpp/src/command_classes/SensorMultilevel.cpp
Unfortunately its objective so i literally dont understand nothing from it. 

Going back to this:
```
 <!-- COMMAND_CLASS_SWITCH_MULTILEVEL. This class is in the list reported by the device, but it does not respond to requests -->
  <CommandClass id="38">
    <Compatibility>
      <GetSupported>false</GetSupported>
    </Compatibility>
  </CommandClass>
```
Is that GetSupported variable exposed to Z2M somehow?

**Comment by Dinth** [comment]
So as far as i understand, GetSupported doesnt really imply that the value should be hidden (although comments in some of the config files may indicate otherwise), just that the value should not be updated.

Also i had a look in HA code and found this
```
DEVICE_CONFIG_SCHEMA_ENTRY = vol.Schema(
    {
        vol.Optional(CONF_POLLING_INTENSITY): cv.positive_int,
        vol.Optional(CONF_IGNORED, default=DEFAULT_CONF_IGNORED): cv.boolean,
        vol.Optional(
            CONF_INVERT_OPENCLOSE_BUTTONS, default=DEFAULT_CONF_INVERT_OPENCLOSE_BUTTONS
        ): cv.boolean,
        vol.Optional(
            CONF_INVERT_PERCENT, default=DEFAULT_CONF_INVERT_PERCENT
        ): cv.boolean,
        vol.Optional(
            CONF_REFRESH_VALUE, default=DEFAULT_CONF_REFRESH_VALUE
        ): cv.boolean,
        vol.Optional(
            CONF_REFRESH_DELAY, default=DEFAULT_CONF_REFRESH_DELAY
        ): cv.positive_int,
    }
)
```

and i believe that CONF_IGNORED makes entity discovery skip the entity. But i couldnt find where that value is coming from.

**Comment by billiaz** [comment]
I do experience the same issue with Fibaro Wall plugs.
Where Watt (w) is confused to be water:

`{
  "type": "sensor",
  "object_id": "water",
  "discovery_payload": {
    "value_template": "{{ value_json.value }}",
    "icon": "mdi:water",
    "state_topic": "mqttzwave/Master_Bedroom/m_bedroom_wall_plug/50/1/32",
    "json_attributes_topic": "mqttzwave/Master_Bedroom/m_bedroom_wall_plug/50/1/32",
    "device": {
      "identifiers": [
        "zwave2mqtt_Master_Bedroom-m_bedroom_wall_plug"
      ],
      "manufacturer": "FIBARO System",
      "model": "0x1000",
      "name": "FGWPE/F Wall Plug",
      "sw_version": "22.22"
    },
    "name": "Master_Bedroom-m_bedroom_wall_plug_water",
    "unique_id": "zwave2mqtt_Master_Bedroom-m_bedroom_wall_plug_35-50-1-32"
  },
  "discoveryTopic": "sensor/Master_Bedroom-m_bedroom_wall_plug/water/config",
  "values": [
    "50-1-32"
  ],
  "persistent": true,
  "id": "sensor_water"
}`

**Comment by Dinth** [comment]
Thank you @billiaz. Which version of Z2M are you running

**Comment by billiaz** [comment]
It is packed with the addon of hass (0.4.2) and I found from package.json of the node the version 2.0.6

**Comment by robertsLando** [comment]
I'm waiting for @Fishwaldo for `GetSupported`

**Comment by robertsLando** [comment]
@Dinth Did you try with latest changes?

**Comment by Fishwaldo** [comment]
GetSupported isn't relevent here. (as far as the Meter Class goes from what I read). Get Supported means that OZW will not try to retrieve the current value from that CommandClass (but the device might still send Report or Set messages to OZW so its "still valid").

As far as the mappings on the Meter Class - https://github.com/OpenZWave/open-zwave/blob/master/config/SensorMultiLevelCCTypes.xml is a config file for what Meter Types OZW can support. The Index exposed by the SensorMultiLevel class does not map to anhything in the standard, so you can not use the Specifications there. The mapping is controlled by this config file. Index Values 1 - 255 equal the SensorType ID value in that file, and index values 256-512 are the different scales that the device can report (or user select, eg, C versus F). 

Hence, using "Units" on Index 1-255 is probably not the way to go, but map the ValueID index to the type you are interested in (bearing in mind that a user can change the "scale" that is reported though).

**Comment by robertsLando** [comment]
> The mapping is controlled by this config file

You mean [this](https://github.com/OpenZWave/open-zwave/blob/master/config/SensorMultiLevelCCTypes.xml) ?

So for example temperature is usually is 
- 49: sensor multilevel class
- 1: the instance 
- 1: Index (In this case matching the Sensor type)

But is there something like this for command class 50 ? (meters)
Does it also rely on that file?
Because I have some meters valueID and no one respect that specs...

**Comment by Fishwaldo** [comment]
Instance is dependent upon the device endpoint. You can also have multiple “sensors” per endpoint (meaning more than 1 ValueID per instance). 

Meter is hard coded per this table: https://github.com/OpenZWave/open-zwave/blob/0d94c9427bbd19e47457578bccc60b16c6679b49/cpp/src/command_classes/Meter.cpp#L74

(You can use those ValueID_Index_Meter enums if they are exposed to nodeJS. )

**Comment by robertsLando** [comment]
> Meter is hard coded per this table: https://github.com/OpenZWave/open-zwave/blob/0d94c9427bbd19e47457578bccc60b16c6679b49/cpp/src/command_classes/Meter.cpp#L74

Is there a way to get the meter type for a specific valueID?

```
enum MeterType
			{
				MeterType_Electric = 0,
				MeterType_Gas,
				MeterType_Water,
				MeterType_Heating,
				MeterType_Cooling
			};
```

**Comment by Fishwaldo** [comment]
Apart from units, no. But all meter types have a static Index Value.

**Comment by robertsLando** [comment]
I still don't understand how to correctly identify meters so...

**Comment by petergebruers** [comment]
If you have an id then this gets the index

index = vID.GetIndex();

And then you can compare it with ValueID_Index_Meter::Gas_Cubic_Meters for example

It points to that enum @Fishwaldo posted and "index" is "stable" because the Z-Wave Spec assigned these numbers.

**Comment by robertsLando** [comment]
```c++
std::map<uint32_t, s_MeterTypes> MeterTypes = {
					{ValueID_Index_Meter::Electric_kWh, {"Electric - kWh", "kWh"}},
					{ValueID_Index_Meter::Electric_kVah, {"Electric - kVah", "kVah"}},
					{ValueID_Index_Meter::Electric_W, {"Electric - W", "W"}},
					{ValueID_Index_Meter::Electric_Pulse, {"Electric - Pulses", "Pulses"}},
					{ValueID_Index_Meter::Electric_V, {"Electric - V", "V"}},
					{ValueID_Index_Meter::Electric_A, {"Electric - A", "A"}},
```

Does it means that if I have index 0 it is `Electric_kWh`, index 2 `Electric_W`, index 4 `Electric_V` and so on?

**Comment by petergebruers** [comment]
Yes

**Comment by petergebruers** [comment]
Here is an interesting snippet from Domoticz

```cpp
		else if (vOrgIndex == ValueID_Index_Meter::Gas_Cubic_Meters)
		{
			_device.devType = ZDTYPE_SENSOR_GAS;
		}
		else if (vOrgIndex == ValueID_Index_Meter::Gas_Cubic_Feet)
		{
			_device.devType = ZDTYPE_SENSOR_GAS;
			_device.scaleMultiply = 0.0283168f; //(divide the volume value by 35,315)
		}
```

So Domoticz only has one type of meter object and so they have to convert from Cubic Feet to m3

**Comment by robertsLando** [comment]
Because I have this: 

![Schermata da 2020-01-29 11-51-51](https://user-images.githubusercontent.com/11502495/73350680-cae44180-428d-11ea-98fc-e27265f8693f.png)

And Index 8 in the enum isn't Watt

**Comment by petergebruers** [comment]
> And Index 8 in the enum isn't Watt

Sorry, I have had a very bad week adn I am catching up. I'll start reading from the start of this topic. There has to be a misunderstanding about which number refers to what...

**Comment by petergebruers** [comment]
Tested Neo Wall Plug and Fibaro Wall Plug, I don't see "8" and cannot find a discrepancy anywhere. Here is what I get...

2020-01-29 12:32:17.435 Always, OpenZwave Version 1.6-1016-g2bbbd2dd Starting Up

```
Fibaro Wall Plug

2020-01-29 12:35:59.912 Info, Notification: Value Added Home 0xd96a77cd Node 2 Genre user Class METER Instance 1 Index 0 Type decimal IsSet False ValueAsString 0.0
2020-01-29 12:35:59.912 Detail, Node002, Notification: ValueAdded
2020-01-29 12:35:59.912 Info, Notification: Value Added Home 0xd96a77cd Node 2 Genre user Class METER Instance 1 Index 2 Type decimal IsSet False ValueAsString 0.0
2020-01-29 12:35:59.912 Detail, Node002, Notification: ValueAdded
2020-01-29 12:35:59.912 Info, Notification: Value Added Home 0xd96a77cd Node 2 Genre user Class METER Instance 1 Index 256 Type bool IsSet False ValueAsString False
2020-01-29 12:35:59.912 Detail, Node002, Notification: ValueAdded
2020-01-29 12:35:59.912 Info, Notification: Value Added Home 0xd96a77cd Node 2 Genre system Class METER Instance 1 Index 257 Type button IsSet True ValueAsString False
2020-01-29 12:35:59.912 Detail, 

ValueIDIndexesDefines.h


0 ValueID_Index_Meter::Electric_kWh
2 ValueID_Index_Meter::Electric_W
256 ValueID_Index_Meter::Exporting -> true or false indicates power drawn from the grid vs delivered to the grid
257 ValueID_Index_Meter::Reset -> Erase values stored on the device


Neo Wall Plug

2020-01-29 13:01:48.733 Info, Node003, Creating MeterType Electric - kWh (1) with Unit kWh (0) at Index 0
2020-01-29 13:01:48.733 Info, Node003, Creating MeterType Electric - W (1) with Unit W (2) at Index 2
2020-01-29 13:01:48.733 Info, Node003, Creating MeterType Electric - V (1) with Unit V (4) at Index 4
2020-01-29 13:01:48.733 Info, Node003, Creating MeterType Electric - A (1) with Unit A (5) at Index 5
2020-01-29 13:01:48.734 Detail, Node003,   Expected reply and command class was received
2020-01-29 13:01:48.734 Detail, Node003,   Message transaction complete
2020-01-29 13:01:48.734 Detail, 
2020-01-29 13:01:48.734 Detail, Node003, Removing current message
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 0 Type decimal IsSet False ValueAsString 0.0
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 2 Type decimal IsSet False ValueAsString 0.0
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 4 Type decimal IsSet False ValueAsString 0.0
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 5 Type decimal IsSet False ValueAsString 0.0
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 256 Type bool IsSet False ValueAsString False
2020-01-29 13:01:48.734 Detail, Node003, Notification: ValueAdded
2020-01-29 13:01:48.734 Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre system Class METER Instance 1 Index 257 Type button IsSet True ValueAsString False

0 ValueID_Index_Meter::Electric_kWh
2 ValueID_Index_Meter::Electric_W
4 ValueID_Index_Meter::Electric_V
5 ValueID_Index_Meter::Electric_A
256 ValueID_Index_Meter::Exporting -> true or false indicates power drawn from the grid vs delivered to the grid
257 ValueID_Index_Meter::Reset -> Erase values stored on the device
```

Are you mixing OZW 1.4 with 1.6? I am not familiar with how it used to be on 1.4...

Please note this type of log line is specific to open-zwave-control-panel: `Info, Notification: Value Added Home 0xd96a77cd Node 3 Genre user Class METER Instance 1 Index 0 Type decimal IsSet False ValueAsString 0.0`. It tells you the index... But that's just a double check, it matches what OZW logs.

**Comment by robertsLando** [comment]
@petergebruers I have just submitted a commit that should identify meters and sensors multilevel correctly based on 

https://github.com/OpenZWave/open-zwave/blob/0d94c9427bbd19e47457578bccc60b16c6679b49/cpp/src/command_classes/Meter.cpp#L74

And

https://github.com/OpenZWave/open-zwave/blob/0d94c9427bbd19e47457578bccc60b16c6679b49/config/SensorMultiLevelCCTypes.xml

**Comment by robertsLando** [comment]
Anyone can test latest commit?

**Comment by Dinth** [comment]
Is it in docker? Ive tried pulling latest "latest" branch, but i dont think anything new was downloaded.

**Comment by robertsLando** [comment]
@Dinth not yet, just on master. I suggest you to use nodejs version to be able to always use the latest updates :)

**Comment by robertsLando** [comment]
@Dinth Closing this for now, will reopen if necessary
