### ISSUE TITLE
[question] 404 - Error: Not Found on Webpage

### ISSUE THREAD

**Issue by SKOJau** [OpenZWave/Zwave2Mqtt#217]
Since Yesterday i have a problem with my docker installation of Z2M v2.1.1.
It worked just fine for 2 days. As soon as I’m going on the webinterface I’m getting the Yellow reconnecting symbol in the upper right corner and the devices aren't apearing anymore. In the log there is an error with the bold parts always changing:

GET / 304 2.964 ms - -
POST /socket.io/?EIO=3&transport=polling&t=**M_I40vB** 404 - Error: Not Found
POST /socket.io/?EIO=3&transport=polling&t=**M_I40vB** 302 3.768 ms - 23
GET / 200 3.921 ms - 1432
GET /index.html 404 - Error: Not Found
GET /socket.io/?EIO=3&transport=polling&t=**M_I41D4** 302 4.839 ms - 23

The Zwave and MQTT communication is working fine, just the Webinterface is not working anymore. I already tried to rebuild the docker file but it did not solve the problem.

What could be the problem there?

**Comment by robertsLando** [comment]
I have other users running it without problems sincerly dunno what is break here. How are you starting you docker container?

**Comment by SKOJau** [comment]
If i go back to 2.1.0 the problem disappears.
Normally I'm managing my containers with the Portainer webinterface. I also tried to start it as a new container in the commandline you provided in the readme

**Comment by robertsLando** [comment]
Are you running it on arm32/64 or amd?

Daniel

**Comment by SKOJau** [comment]
Its running on an RPI3, so it should be arm. Reacently i did all updates on the system.

**Comment by robertsLando** [comment]
@SKOJau I'm investigating...

**Comment by robertsLando** [comment]
@SKOJau Another user using z2m 2.1.1 on rpi 3 told me it's working correctly. Could you please remove the docker image and try with a fresh install?

**Comment by SKOJau** [comment]
@robertsLando Did a new pull of the image and now its working. I dont know why, but thats absolutly fine :).
Thanks for your great work on that project 👍
