### ISSUE TITLE
[bug] command classes which were hidden in HA/OZW1.4 are visible in Z2M

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#219]
**Version**
2.1.1

Build/Run method
- [*] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6

**Describe the bug**
Some devices have CommandClasses which dont work or should be hidden. Such entities were not visible in HA/OZW1.4, but Z2M generates values for them.
Examples of such devices:
- Fibaro FGS-213
- Fibaro FGS-223
Which are both binary switches but theoretically support _COMMAND_CLASS_SWITCH_MULTILEVEL_ but as per OZW device config file it isn't functional though:
```
  <!-- COMMAND_CLASS_SWITCH_MULTILEVEL. This class is in the list reported by the device, but it does not respond to requests -->
  <CommandClass id="38">
    <Compatibility>
      <GetSupported>false</GetSupported>
    </Compatibility>
  </CommandClass>
```
and HA/OZW1.4 was not creating device entities for this class.
Looking at OZW config files, there's plenty of other devices which have Command Classes which dont work.

**Expected behavior**
Such command classes should be hidden, values coming from them should not be visible in Z2M web interface or passed to HA.

**Comment by Dinth** [comment]
Moving the discussion from https://github.com/OpenZWave/Zwave2Mqtt/issues/213

**Comment by robertsLando** [comment]
> Some devices have CommandClasses which dont work or should be hidden. Such entities were not visible in HA/OZW1.4, but Z2M generates values for them.

I don't generate values I just take values that OZW pass to me :( I don't know how to access that flag, @Fishwaldo could you help?

**Comment by Fishwaldo** [comment]
OZW has "never" hidden values/command classes. What you are seeing is probably something that HA did itself in the native integration. If you used the old z2m (based on 1.4) or ozwcp (with 1.4) then you will see the same values as 1.6

what you are hitting is more than likely a bug with Fibaro. Unfortunately their QA sucks and they force you to purchase their HomeCenter to update the firmware. Thats why I don't recommend them.  

I'll answer your specific question on the OZW issue tracker about these devices, but in essense, you have a buggy device. Blaming Z2M or OZW isn't going to get Fibaro to fix their issues :)
