### ISSUE TITLE
How to migrate from "Domoticz + Aeon zwave stick" to zwave2mqtt 

### ISSUE THREAD

**Issue by mchangsp** [OpenZWave/Zwave2Mqtt#220]
Hi all,
I have looked around on the internet for my question but cannot find any forum for zwave2mqtt.
Google also does not have anyone documenting this.

I have a running zwave network configured with Domoticz on a AEON Labs ZW090 Z-Stick Gen5 EU.
I want to use zwave2mqtt to manage this zwave network.
Home Assistant with MQTT autodiscovery will be my new home automation hub.

I already managed to start zwave2mqtt in a Docker container on a Raspberry Pi 3B+.
zwave2mqtt succesfullt connects to the stick and receives data from the stick.
However the Docker container just stops and I have to restart.
(I can supply al kinds of logs, please tell me which ones are interesting.
That's how far I get. The zwave devices do not appear on the control panel.

Stuff involved:
- Raspberry Pi 
- zwave2mqtt in a Docker container - https://github.com/OpenZWave/Zwave2Mqtt#docker-tada-way
- Domoticz 4.10717 using OpenZWave library
- I have a zwcfg_0xyyyyyyyy.xml file

Questions
1. How do I migrate the zwave network definitions into zwave2mqtt?
2. How do I import a zwcfg_0xyyyyyyyy.xm into zwave2mqtt?
3.  How long do I have to wait before devies show up?

**Comment by Dinth** [comment]
Devices as in node numbers should show up immediately, although with empty product and type fields - which will get populated after few minutes depending on the size of your network.

Can you please run "docker logs <your z2m instance name>" and paste the output for a start?

**Comment by robertsLando** [comment]
> How do I import a zwcfg_0xyyyyyyyy.xm into zwave2mqtt?

Just copy it inside the `store` folder. If running with docker ensure to map local store folder with app store folder in docker container.

> How long do I have to wait before devies show up?

Depends on how many devices your network has, it could one minute or 10 minutes or even more on very large networks

If your docker container stops please paste here the error thrown

**Comment by mchangsp** [comment]
OK thanks for the tips.
I will try on my own, and try to create an environment where I can recreate the error easily. I will close this question. When I can reproduce the error  consistently I will open a new question and post some logs.
At the moment sometimes zwave2mqtt just stops without giving an error....

**Comment by robertsLando** [comment]
@mchangsp Ok let me know about that stop

**Comment by Fishwaldo** [comment]
Zwcfg is only for 1.4. It’s not used in 1.6 and has been renamed to ozwcache (as it’s not a config file). The formats are different so you can’t copy it over. 

It doesn’t matter anyway, as it’s just a cache file and will be regenerated
