### ISSUE TITLE
[question] Removed/renamed nodes, doesn't dissapear from HomeAssistant

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#221]
I have removed or renamed some nodes. I can still see them on my Home Assistant.
Running 2.1.1 version
Is there something I am doing wrong?

Behaviour:
Removed node: still there

Renamed: Old and new still on my MQTT devices
**On options**
My MQTT options: Retain, Store
Gateway: Use nodes instead of ID, HASS Discovery, Retained Discovery

**Comment by Dinth** [comment]
Nope, you're doing everything fine, this is a behavior of Home Assistant. Apparently @robertsLando has this on his todo list so maybe he has a plan how to deal with it, but it wont be easy due to the way MQTT and HA autodiscovery work.

**Comment by billiaz** [comment]
thought so, but if there is a guide how to "manually" cleanup, I am up to that too

**Comment by Dinth** [comment]
Im struggling with that myself. Ive got several dozens of entities in HA which i want to get rid off. 
If the sensor is "Unavailable" in HA you can just go to Developer -> States, click on the "i" icon next to sensors name and click "Remove entity". 
If the sensor is "Unknown" then its a bigger problem, you can try restarting HA/Z2M/Mosquitto server and try again.

**Comment by Dinth** [comment]
Actually in recent version HA added possibility of mass removing entities which i just tested. 
You can do that from Control Panel -> Entities.

**Comment by robertsLando** [comment]
@billiaz If the discovery payload was retained you have to use mqtt explorer or some other tool to remove them from mqtt broker (or just restart the broker if it stores retained in memory and not on disk). 

I also used to complete remove mqtt integration from hass and than restart hass and z2m

**Comment by billiaz** [comment]
Saw that! Played around. now deletion seems to work.
I cleaned up the devices from .storage/*core files and then entities from webgui
