### ISSUE TITLE
[bug] Motion sensors not working

### ISSUE THREAD

**Issue by chr55** [OpenZWave/Zwave2Mqtt#227]
robertslando/zwave2mqtt   latest              45912840ae75

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6.0

**Describe the bug**
I am currently using HomeSeer Z-Wave and am determining if Home Assistant / Zwave2Mqtt would be a better fit for me. I have two Z-Wave motion sensors that work fine in HomeSeer but do not work in Zwave2Mqtt / Home Assistant. 

Sensor 1
WAPIRZ-1 Motion Sensor (Linear (Nortek Security Control LLC))
Battery and Temperature working great. Motion not working.

Sensor 2
ZP3111 Multisensor 4in1 (Vision Security)
Battery, Temperature, Illuminance, Humidity working great. Motion not working. 

**To Reproduce**
I am using MQTT Explorer to watch the traffic.

Sensor 1 reports this on the discovery topic 
{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.value }}","device_class":"door","state_topic":"zwave2mqtt/6/48/1/0","json_attributes_topic":"zwave2mqtt/6/48/1/0","device":{"identifiers":["zwave2mqtt_nodeID_6"],"manufacturer":"Linear (Nortek Security Control LLC)","model":"0x0203","name":"WAPIRZ-1 Motion Sensor","sw_version":"4.84"},"name":"nodeID_6_contact","unique_id":"zwave2mqtt_nodeID_6_6-48-1-0"}

Sensor 2 reports this on the discovery topic
{"payload_on":true,"payload_off":false,"value_template":"{{ value_json.value }}","device_class":"door","state_topic":"zwave2mqtt/10/48/1/0","json_attributes_topic":"zwave2mqtt/10/48/1/0","device":{"identifiers":["zwave2mqtt_nodeID_10"],"manufacturer":"Vision Security","model":"0x2101","name":"ZP3111 Multisensor 4in1","sw_version":"5.01"},"name":"nodeID_10_contact","unique_id":"zwave2mqtt_nodeID_10_10-48-1-0"}

Over time these topics do not change from the initial value and at best re-report the same value
{"value_id":"6-48-1-0","node_id":6,"class_id":48,"type":"bool","genre":"user","instance":1,"index":0,"label":"Sensor","units":"","help":"Binary Sensor State","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"value":true}

{"value_id":"10-48-1-0","node_id":10,"class_id":48,"type":"bool","genre":"user","instance":1,"index":0,"label":"Sensor","units":"","help":"Binary Sensor State","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"value":false}

This leads to Home Assistant not getting updated values either.

**Expected behavior**
Using MQTT Explorer I find the motion reported on topic 6/113/1/7 and 10/113/1/7

The first device goes to "Intrusion at Unknown Location" for 5 seconds then goes back to "Clear"

12:30:51
{"value_id":"6-113-1-7","node_id":6,"class_id":113,"type":"list","genre":"user","instance":1,"index":7,"label":"Home Security","units":"","help":"Home Security Alerts","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Clear","Intrusion at Location","Intrusion at Unknown Location","Tampering -  Cover Removed","Tampering - Invalid Code","Glass Breakage at Location","Glass Breakage at UnknownLocation","Motion Detected at Location","Motion Detected at Unknown Location","Tampering - Product Moved","Unknown Event"],"value":"Intrusion at Unknown Location"}

12:30:56
{"value_id":"6-113-1-7","node_id":6,"class_id":113,"type":"list","genre":"user","instance":1,"index":7,"label":"Home Security","units":"","help":"Home Security Alerts","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Clear","Intrusion at Location","Intrusion at Unknown Location","Tampering -  Cover Removed","Tampering - Invalid Code","Glass Breakage at Location","Glass Breakage at UnknownLocation","Motion Detected at Location","Motion Detected at Unknown Location","Tampering - Product Moved","Unknown Event"],"value":"Clear"}

**Additional context**
Has anyone experienced this before? I need to resolve this or come up with a workaround before I could consider moving to Home Assistant zwave2mqtt. 

Would I get better results using only Home Assistant native zwave and not using zwave2mqtt at all? One of the attractions of zwave2mqtt is having it decoupled from the home automation system but I obviously need my motion sensors working.

If the sensors blip over to motion for just a few seconds how can I automate from that? I'm used to my motion sensors being "tripped" for a few minutes. 

Thank you

**Comment by chr55** [comment]
This is the first device
https://products.z-wavealliance.org/products/1034

and the second

https://products.z-wavealliance.org/products/1744

**Comment by chr55** [comment]
I went ahead and brought another motion sensor over from my old Z-Wave network. It is a different brand. It is device
EcoLink PIRZWAVE2.5-ECO
https://products.z-wavealliance.org/products/1500

It works VERY WELL in both zwave2mqtt and also Home Assistant. The motion sensor is very responsive in Home Assistant and works perfectly. Motion detected / Clear all working as expected.

This tells me I have a problem with just individual devices / brands of motion sensor and not a wider problem in my configuration. 

1/31/2020 2:43:30 PM
{"value_id":"11-113-1-7","node_id":11,"class_id":113,"type":"list","genre":"user","instance":1,"index":7,"label":"Home Security","units":"","help":"Home Security Alerts","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Clear","Tampering -  Cover Removed","Motion Detected at Unknown Location"],"value":"Motion Detected at Unknown Location"}

1/31/2020 2:49:41 PM
{"value_id":"11-113-1-7","node_id":11,"class_id":113,"type":"list","genre":"user","instance":1,"index":7,"label":"Home Security","units":"","help":"Home Security Alerts","read_only":true,"write_only":false,"min":0,"max":0,"is_polled":false,"values":["Clear","Tampering -  Cover Removed","Motion Detected at Unknown Location"],"value":"Clear"}

**Comment by robertsLando** [comment]
Hi @chr55, thanks for your issue, unfortunally based on your logs it is difficult to debug the problem, it could be a device problem for sure if the new one is correctly working. Can I close this so?

**Comment by chr55** [comment]
With so many of my motion sensors not working in zwave2matt / Home Assistant I will stay on my current home automation platform ( HomeSeer ) where they are working perfectly. Thank you for the response. You can close this ticket.
