### ISSUE TITLE
[question] Battery Device values not held until battery device receives update

### ISSUE THREAD

**Issue by aretakisv** [OpenZWave/Zwave2Mqtt#228]
I will use an example on this.
I have a climate control (battery operated) TRV.

Once I send new value to 67-1-1 of the device (setpoint) the value a few seconds after this change will return to the previous state.... once device wakes, receives the command and the value updates to the new value.

Flow on a device with 5m wake interval:
``` 
Device setpoint: 19
Moving slider to : 20.5
2-3 seconds after slider returns to: 19
about 5 minutes after: 20.5
```

Is there way to fix this?  using _events or other way?

**Comment by aretakisv** [comment]
I noticed the following.
On my danfoss device I have Hour/minutes and day as user values, but also Heating set point

The heating setpoint 67-1-1 when I change the value from z2m web int or HASS, MQTT doesn't receive an update until the device wakes where the: 129-1-0, 129-1-1 129-1-2 do change on MQTT topic before device wakes.

Is this expected?

**Comment by Fishwaldo** [comment]
Yes. That’s the way battery devices work. They can only receive updates once they wake up. 

I can’t comment why the GUI reverts to the old value though. That’s something specific to Z2M or the Node Wrapper.

**Comment by petergebruers** [comment]
For sake of completeness. Newer battery operated TRVs like Eurotronic Spirit and Fibaro FGT-001 respond within about 1 second, they are "frequently listening routing slaves"... They behave more like mains devices.

**Comment by robertsLando** [comment]
I don't take the newer value until I don't receive a feedback from the device
