### ISSUE TITLE
[bug] Philio PSM02-1 philio 4 in 1

### ISSUE THREAD

**Issue by nicoxygen** [OpenZWave/Zwave2Mqtt#229]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Brand: Philio **PSM02-1 Slim Multi-Sensor**
**Model:** 0x0002
par Philio Technology Corp
Firmware: 1.00

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6.0

**Describe the bug**
- It is a problem between zwave2mqtt and the module, I used this module with openzwave under jeedom and there was no problem.
- Inclusion is not a problem.
- **Bug:** After inclusion the temperature is in celsius but once the first change of state (door opening) the temperature goes into fahrenheit.
the temperature unit is well set in celsius.
- **Bug** with the motion detector which remains on true it does not change state
by default i have value on **true** but on psm02.xml openz-wavze, by default value is on false:
<Value genre="user" index="0" instance="1" label="Motion Sensor" max="0" min="0" read_only="true" type="bool" value="false" write_only="false"/>

- Door opening **ok**
- Battery **ok**
- illuminosity **ok**
- tamper **?**

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by nicoxygen** [comment]
for first bug is a problem of parameter just change bit:5 to 12 and not 8 who is for farenheit
for motion dectector it's good
but i have a problem with door sensor

**Comment by robertsLando** [comment]
So the only problem is the door sensor now?

**Comment by nicoxygen** [comment]
in fact these are only configuration problems I must find the right balance, I had made a mistake it is the door sensor that does not currently work, hence my question of recommended configuration.
