### ISSUE TITLE
[question] Error while discovering value 42-49-1-1 of node 42: Cannot set property 'unit_of_measurement' of undefined

### ISSUE THREAD

**Issue by mshiznitzh** [OpenZWave/Zwave2Mqtt#231]
I have 2 MultiSensor 6 with the newest firmware that keep getting this error. 

z2m:Gateway Error while discovering value 42-49-1-1 of node 42: Cannot set property 'unit_of_measurement' of undefined +277ms
  z2m:Gateway Error while discovering value 42-49-1-3 of node 42: Cannot set property 'unit_of_measurement' of undefined +2ms
  z2m:Gateway Error while discovering value 42-49-1-5 of node 42: Cannot set property 'unit_of_measurement' of undefined +1ms
  z2m:Gateway Error while discovering value 42-49-1-27 of node 42: Cannot set property 'unit_of_measurement' of undefined +1ms

Because of these error I am not getting the sensors in Home Assistant. 
 I looked in the /hass.configurations.js and it looks like the units are there for each type of sensor.

I have added a picture to show what data is coming back into zwave2mqtt for the node.  As you can see the units are correct here. 

![image](https://user-images.githubusercontent.com/6580826/73616227-694a0d00-45d6-11ea-93bc-e6e1f8a194a2.png)

I didn't want to list this as a bug in case I am missing something.  Anyone have an idea on where I should be looking?

**Comment by chilicheech** [comment]
This might be related to what's happening to me as well. I created #232 but I haven't seen any errors in the logs.

**Comment by robertsLando** [comment]
@mshiznitzh Fixed now
