### ISSUE TITLE
[bug] minor Bug Fibaro eyes FGMS001 motion sensor

### ISSUE THREAD

**Issue by nicoxygen** [OpenZWave/Zwave2Mqtt#233]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6.0

for home assistant binary_sensor_alarm is 
 "payload_on": **255**,
    "payload_off": **0**,

and not

 "payload_on": true,
    "payload_off": false,

**Comment by robertsLando** [comment]
@nicoxygen Is this for every ` binary_sensor_alarm` device?

**Comment by nicoxygen** [comment]
no just for fgms001 other products are true and false

**Comment by ovenystas** [comment]
I have found the same issue on `binary_sensor_alarm` devices on these other Fibaro devices as well. They also need values of 255 and 0 instead of true and false.
FGMS001-ZW5 Motion Sensor
FGSS101 Smoke Sensor
FGFS101 Flood Sensor

**Comment by robertsLando** [comment]
Could you create a PR for those devices ? Just add them to `hass/devices.js`
