### ISSUE TITLE
[bug] product configuration not saved

### ISSUE THREAD

**Issue by nicoxygen** [OpenZWave/Zwave2Mqtt#235]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6.0

[bug] I think it has already been mentioned, the configurations are reset by default when the container is restarted, they do not remain saved, it is annoying.

**Comment by robertsLando** [comment]
@nicoxygen Configurations are not resetted, you should send 'requestConfigParams` agains the node to refresh them

**Comment by nicoxygen** [comment]
it's possible to translate zwave2mqtt ? if yes i translate to french

**Comment by robertsLando** [comment]
@nicoxygen actually there is no multilanguage support. I'm the only mantainer of the project

**Comment by nicoxygen** [comment]
I suspect and frankly congratulations

**Comment by robertsLando** [comment]
@nicoxygen About your issue I have just submit a fix
