### ISSUE TITLE
After node excluded from controller, it still remains in the hidden list in zwave2mqtt webui?

### ISSUE THREAD

**Issue by Support-Vezca** [OpenZWave/Zwave2Mqtt#238]
Manually built (git clone - npm install - npm run build ) 
Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

This may just be the way this app is designed to function and not a bug.
Say I have 5 nodes in the zwave controller, node 1,2,3,4,5... then I include node 6, then I exclude node 6, I check on the controller using pc controller software and it is indeed completely gone... however in the zwave2mqtt webui that particular node '6' remains in the webui list as hidden and from thereon any further inclusions carry on from number 7... rather than doing 6 again... would be nice to just completely wipe it off the list especially considering it is the 'last' node in the controller anyway?

ps. love this app, great to finally see some initiative in taking another important protocol into the world of MQTT pluggables, very smart gent who chose to do this! Well done!

**Comment by Fishwaldo** [comment]
Node ID’s are assigned by the controller and not the application. When adding a node we have no influence over the node number assigned and is usually the next highest number.

**Comment by robertsLando** [comment]
@Support-Vezca that is how zwave works so isn't a bug. What you can do is replace a node after you have removed it so it will take that id

**Comment by Support-Vezca** [comment]
How does one replace a node?

**Comment by robertsLando** [comment]
@Support-Vezca You have to firstly remove the node, than select the node in the table go to node actions dropdown select `Replace failed node` that will make your controller in inclusion mode and you will be able to add a new device that will take that id

**Comment by Support-Vezca** [comment]
Excellent!!!!!
