### ISSUE TITLE
[question] How to improve performance

### ISSUE THREAD

**Issue by s-frei** [OpenZWave/Zwave2Mqtt#239]
Hi there,

first of all thanks for your continous development of this software. We are using it to develop a custom _home automation_ software against it and are planning to run multiple zwave networks with your software and control them over mqtt. We planned to use ten networks and in that case also ten times your piece of software.

**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.1.1
Openzwave Version: 1.6.1004

**Description**
Performing actions on multiple devices over mqtt in a short period of time leads to a large delay on executing the called actions. "Notification - TimeOut" seems to slow things down as the calls aren't processed asynchronous.

**To Reproduce**
1. Switch multiple devices at once over mqtt.

**Curent behavior**
The switches are performing actions one after another with remarkable delay. 

**Expected behavior**
The switches are perfoming utmost simultaneously.

**Additional context**
On following image you are able to see when actions have been triggered and when they finally are realised.
![grafik](https://user-images.githubusercontent.com/25681388/73826821-b6102c80-47fe-11ea-95be-3e5bf887781f.png)

We are aware that Z-Wave isn't performing in real-time, but it shouldn't be that slow anyways.

Maybe we can fix this issue together. Just let me/us know!!!

**Comment by robertsLando** [comment]
@s-frei Unfortunally I think this is a protocol limit and not something can be improved. Anyway I tag @Fishwaldo that maybe could say more about this

**Comment by robertsLando** [comment]
@s-frei Is this software open-source? just for information, I like to see how people are using z2m :)

**Comment by s-frei** [comment]
> 
> 
> @s-frei Is this software open-source? just for information, I like to see how people are using z2m :)

Unfortunately not at this time.

**Comment by robertsLando** [comment]
@s-frei Ok let me know if you need some support :) About your question, how many devices are in your network?

**Comment by Fishwaldo** [comment]
The Z-Wave Protocol is basically serial transactions. Meaning you have to wait for the previous command to finish before starting a new one. 

its also low bandwidth. At most 100K assuming all ZW+ devices, and when you have non plus devices, it can go as low as 40K. Its not wifi speeds by any stretch of the imagination.

Regarding the timeouts, the logs posted are not OZW logs, so I can't say. It could be RF issues, it would be devices that are not 100% compliant to the specs, it could be collisions etc. 

When you start hitting RF issues, internally the protocol will do retry (LWR, Node Neighbors, Explorer Frames, then repeat at 40K and again at 9.6K). According to the specs those retries add upto around 40 seconds, in OZW we found in real life if something doesn't respond after 10 seconds, its very very rare for it to respond from 11-40 seconds, so we just move on.

**Comment by s-frei** [comment]
> 
> About your question, how many devices are in your network?

We recently went productive with six networks, each around 50 nodes, managed over MQTT by your software.

>
> @s-frei Ok let me know if you need some support :) 

Thank you, I will 😉
