### ISSUE TITLE
Question: Get current state from a node_id

### ISSUE THREAD

**Issue by kjetilsen** [OpenZWave/Zwave2Mqtt#24]
Hi there. 
I'm struggling with the api. I have set everything up and I can get all subscriptions on a topic. But when I start my own application I want to get the current value/state for a node.

I have tried to publish to this topic:
`<prefix>/<?Location>/<node_name>/status` or `<prefix>/<?Location>/<node_name>/status/set`
Where my prefix are set in my settings, and location is set to Kontor. 

What am I missing here? 

I'm kinda lost, so hope somebody could help me out :) 

If this is the wrong place to publish questions I'm sorry.

Best Regards
Kjetil

**Comment by robertsLando** [comment]
From Readme.md

> By default Node status (true if node is ready false if node is dead) will be published in:
<mqtt_prefix>/<?node_location>/<node_name>/status


Daniel

**Comment by kjetilsen** [comment]
Thank you for the reply!

I have tried that, but the payload is empty. There must be something I am doing wrong. What should be in the message? And will the response only report if the node is alive or not? Not the actual value? Like a dimmer level. 

Regards,
Kjetil

**Comment by robertsLando** [comment]
@kjetilsen please, read docs you can find everything there... 

You have asked me for node status not node values, node values have different topics based on the gateway type you have chosed in settings. 

Follow the docs step by step and you will be able to make it work, you don't have to publish nowthing to get updates, mqtt is event oriented so it will publish the update everytime the value changes
