### ISSUE TITLE
[question] ZW164 Indoor Siren 6 (Aeotec Limited) Trigger Sound?

### ISSUE THREAD

**Issue by hostrup** [OpenZWave/Zwave2Mqtt#242]
Hi! 
I own a new ZW164 Indoor Siren 6 (Aeotec Limited) - and i am running the Zwave2MQTT - in docker. 
I have successfully paired the deivce - using a network key. 

Now - as another user stated - i am not able to change the tamber setting - but there seems to be a connection to the Siren. 

When i do "tamber" the device - i get this in the log files: 

zwave2mqtt          | 2020-02-05 22:06:42.119 Detail, Node003, Decrypted Packet: 0x00, 0x60, 0x0d, 0x02, 0x01, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x0e, 0x00, 0x00
zwave2mqtt          | 2020-02-05 22:06:42.120 Detail,
zwave2mqtt          | 2020-02-05 22:06:42.120 Info, Node003, Received a MultiChannelEncap from node 3, endpoint 2 for Command Class COMMAND_CLASS_NOTIFICATION
zwave2mqtt          | 2020-02-05 22:06:42.120 Info, Node003, Received Notification report (>v1): Type: Siren (14) Event: Clear (0) Status: true, Param Length: 0
zwave2mqtt          | 2020-02-05 22:06:42.120 Detail, Node003, Refreshed Value: old value=1, new value=0, type=list
zwave2mqtt          | 2020-02-05 22:06:42.120 Detail, Node003, Changes to this value are not verified
zwave2mqtt          | 2020-02-05 22:06:42.120 Detail, Node003, Notification: ValueChanged
zwave2mqtt          |   z2m:Zwave zwave node 3: changed: 113-3-14:Doorbell 1 Siren:Active -> Clear +97ms

I use home-assistant - and have setup integration to my mosquitto broker: 
mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

But i dont get any "devices" in home-assistant. 
I can "listen" in the mqtt settings - under the developer tools - where i get this - when i subscribe to # 

{
    "value_id": "3-113-9-14",
    "node_id": 3,
    "class_id": 113,
    "type": "list",
    "genre": "user",
    "instance": 9,
    "index": 14,
    "label": "Instance 9: Siren",
    "units": "",
    "help": "Siren Alerts",
    "read_only": true,
    "write_only": false,
    "min": 0,
    "max": 0,
    "is_polled": false,
    "values": [
        "Clear",
        "Active"
    ],
    "value": "Clear"
}

So i guess - the MQTT server is working. 

Now - it would have been nice to see the device in home-assist - so that i could use it in my automatisations - but i guess the device is not fully implemented. 

Now - this might bee a noob question - but how do i test the device from the zwave2mqtt webpanel? can i somehow "trigger" the device - to make i sound one of its alarm? 

br Ronni

**Comment by hostrup** [comment]
Hi again! 
OK - it looks like the download - of device should just finish. 
Now i can actually make it play a tone - by using the "user" section on the node - in the control panel. 

Next step - to be able to trigger this by using mqtt :)

**Comment by robertsLando** [comment]
@hostrup Just check the readme for more info :)

**Comment by ThePierce** [comment]
@hostrup did you get the siren working? if so, could you please explain how?

**Comment by hostrup** [comment]
Hi ThePierce. 
Yes - with mqtt commands. 
You can see my questions / answers here: https://github.com/cgarwood/homeassistant-zwave_mqtt/issues/45

br Ronni
