### ISSUE TITLE
[question] update configuration parameter using MQTT publish

### ISSUE THREAD

**Issue by aretakisv** [OpenZWave/Zwave2Mqtt#246]
I was reading the main page but for some reason I cannot pinpoint how it is done.

I have a device (doorbell) and i want to update 121-3-2 value from 25 to 0.
The device in my mqtt is:
zwave2mqtt/nodeID_9/121/3/2/
Is there way to set a value on this?

Is there maybe alternative to create a custom device supporting a volume setting 0-100? I could write something about it for the Doorbell 6, now is almost fixed.

the reason is, now our baby boy is coming home, i want to mute the doorbell at night

**Comment by robertsLando** [comment]
Publish on topic

zwave2mqtt/nodeID_9/121/3/2/set

Payload: (depends on the gateway payload settings) 

Just value: 0
Json/zeave object:  {value:0}

Daniel

**Comment by aretakisv** [comment]
cool! i was putting a / in the end and didn't help

**Comment by aretakisv** [comment]
Two reasons:
1. Slash
2. I have two zwave2mqtt, migrating from Razberry to z-stick. running on the same MQTT, I was using the same MQTT Name, which was connecting/disconnecting each other. once i changed this, I saw 4 clients (Homeassistant, my explorer and two Z2M, instead of 3 in total.
I suspect the reason 2 made assume I was doing something wrong

**Comment by aretakisv** [comment]
after restarting my zwave2MQTT i lost soundswitch on this node. I can no longer use the sound switch options nor can see the CC 121 (0x79).
Tried heal, NIF, Request node info... nothing brings these back.

**Comment by robertsLando** [comment]
@aretakisv That's really realy strange, any error in logs? @Fishwaldo Could this happen??
