### ISSUE TITLE
[question] gateway only producing discovery for battery

### ISSUE THREAD

**Issue by mitharen** [OpenZWave/Zwave2Mqtt#247]
I have some First Alert Z-Combo alarms that I'm trying to add to a zwave2mqtt/mosquitto/hassos group. I can see the alarms pairing and zwave2mqtt publishing information to mosquitto, but when creating events for hassos discovery only the batteries are getting recognized. It seems like the classid for the alarm is correct and should be converted into a discovery event. Any ideas? Attaching a picture from mqttexplorer showing the queues.

![image](https://user-images.githubusercontent.com/460233/74090867-9ab35480-4a7e-11ea-9d1c-2d86d91271d9.png)

**Comment by robertsLando** [comment]
@mitharen Are you using latest version from master ?

**Comment by mitharen** [comment]
No, I'm using the 2.1.1 release from last month packaged through the hassio addon. That might explain it. Thanks.
