### ISSUE TITLE
[question] State becomes null/unknown on HASS when i restart zwave2mqtt

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#255]
I have an issue where state becomes unknown in HASS when i restart zwave2mqtt
An example:
I have a Eurotronics Spirit TRV. once i restart zwave2mqtt the state of temperature and mode becomes unknown/null.

For the purpose of debugging:
Screenshots in order of events
1. State before restart
<img width="1234" alt="Screenshot 2020-02-12 at 11 24 01" src="https://user-images.githubusercontent.com/4048920/74326164-3a782780-4d8a-11ea-81bb-a0a8c0e17f60.png">

2. After restarting zwave2mqtt (and after discovery happened on zwave2mqtt side)
<img width="956" alt="Screenshot 2020-02-12 at 11 26 27" src="https://user-images.githubusercontent.com/4048920/74326378-8f1ba280-4d8a-11ea-8ff4-4894fb9808f5.png">

3. States are shown on Z2M but not in HASS
<img width="1567" alt="Screenshot 2020-02-12 at 11 27 37" src="https://user-images.githubusercontent.com/4048920/74326489-c427f500-4d8a-11ea-849d-e4a7d1308531.png">

4. Updating Heating to Heat again (just click the 'execute') will update the state in HASS
Temperature still null
<img width="1537" alt="Screenshot 2020-02-12 at 11 28 09" src="https://user-images.githubusercontent.com/4048920/74326596-f89bb100-4d8a-11ea-93b8-d6bf7ab748a0.png">
<img width="399" alt="Screenshot 2020-02-12 at 11 28 58" src="https://user-images.githubusercontent.com/4048920/74326612-005b5580-4d8b-11ea-90e4-c914dee6d760.png">
<img width="1254" alt="Screenshot 2020-02-12 at 11 29 09" src="https://user-images.githubusercontent.com/4048920/74326631-06513680-4d8b-11ea-968c-120b71fc9203.png">

Setting I have set to on:
Zwave:
 - Logging
 - Auto update Database
 - Save configuration
MQTT:
 - Retain
 - Store
Gateway:
 - Use node names instead of  numeric nodeIDs
 - HASS Discovery

Is there a way to fix this during restarts?

**Comment by robertsLando** [comment]
@billiaz Is retain on mqtt enabled? COuld you check the value of those vars with mqtt explorer? Does this happen for all values?

**Comment by billiaz** [comment]
1. Retain is enabled
2. should QOS also be higher than 0? i have it 0?

The values are retained at MQTT as I can see.

If i restart home assistant without touching values in Z2M values return... 
I am confused.

**Comment by billiaz** [comment]
More details. When starting Z2M the page of nodes looks like:
<img width="1567" alt="Screenshot 2020-02-12 at 16 44 28" src="https://user-images.githubusercontent.com/4048920/74351150-05ce9500-4db7-11ea-8b46-72d1638c6075.png">

still discovering (i call it discovery)... once discovery finishes and looks like:

<img width="1558" alt="Screenshot 2020-02-12 at 16 45 41" src="https://user-images.githubusercontent.com/4048920/74351249-2ac30800-4db7-11ea-8306-a6b395ae5d7e.png">

then values goes to null in HASS... i believe then it is when it sends all MQTT discovery workload to HASS.

**Comment by robertsLando** [comment]
@billiaz I think that too, maybe when the value is rediscovered this happen?

**Comment by billiaz** [comment]
even on stored values this happens tested that.
HASS retain discovery could help?

**Comment by robertsLando** [comment]
@billiaz Not sure, you should try to open an issue on hass and tell why if a component already discovered receives another discover its values become null

**Comment by billiaz** [comment]
@robertsLando doesn't consider them discovered

log:
```
homeassistant-dc7dccd84-bz694 raspberrypi3-homeassistant 2020-02-12 19:16:31 INFO (MainThread) [homeassistant.components.mqtt] Got update for entity with hash: ('climate', 'BabyRoom-Radiator thermostat') '{'min_temp': 8, 'max_temp': 28, 'modes': ['off', 'heat', 'cool'], 'mode_state_topic': 'zwave2mqtt/BabyRoom/Radiator/64/1/0', 'mode_command_topic': 'zwave2mqtt/BabyRoom/Radiator/64/1/0/set', 'current_temperature_topic': 'zwave2mqtt/BabyRoom/Radiator/49/1/1', 'temp_step': 0.5, 'current_temperature_template': '{{ value_json.value }}', 'temperature_state_template': '{{ value_json.value }}', 'temperature_command_topic': 'zwave2mqtt/BabyRoom/Radiator/67/1/1/set', 'mode_state_template': '{% set values = {"Off":"off","Heat":"heat","Heat Eco":"cool"} %} {{ values[value_json.value] if value_json.value in values.keys() else \'off\' }}', 'temperature_state_topic': 'zwave2mqtt/BabyRoom/Radiator/67/1/1', 'device': {'identifiers': ['zwave2mqtt_BabyRoom-Radiator'], 'manufacturer': 'EUROtronic', 'model': '0x0001', 'name': 'EUR_SPIRITZ Wall Radiator Thermostat', 'sw_version': '0.16'}, 'name': 'BabyRoom-Radiator_thermostat', 'unique_id': 'zwave2mqtt_BabyRoom-Radiator_thermostat', 'platform': 'mqtt', 'discovery_hash': ('climate', 'BabyRoom-Radiator thermostat')}'
homeassistant-dc7dccd84-bz694 raspberrypi3-homeassistant 2020-02-12 19:16:31 INFO (MainThread) [homeassistant.components.mqtt] Updating component: climate.babyroom_radiator_thermostat
```

it is updating the component, which probably causes this.

**Comment by robertsLando** [comment]
Ok should this be considered a bug in hass? Would you like to open an issue there? 


Daniel

**Comment by billiaz** [comment]
Reference ticket in HASS: https://github.com/home-assistant/home-assistant/issues/31759

**Comment by billiaz** [comment]
@robertsLando Is here a way to extract the payload HASS stores and compare it to the one z2m publishes? I am still scratching my head over these details!

**Comment by robertsLando** [comment]
@billiaz IDK, I really have low knowledge about hass :disappointed:

**Comment by RezzZ** [comment]
@billiaz can you share your custom thermostat json defined in zwave2mqtt for hass auto discovery?
I'm strugling with the correct format and
https://github.com/OpenZWave/Zwave2Mqtt#thermostats
seems missing a few parameters compared with other auto defined devices
