### ISSUE TITLE
[bug] zwave2mqtt crash during initialization when value polling enabled on sleeping device

### ISSUE THREAD

**Issue by kvaster** [OpenZWave/Zwave2Mqtt#256]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: latest git (Feb 13, 2020)
Openzwave Version: latest git (Feb 13, 2020)

**Describe the bug**
Zwave2Mqtt crash when polling intensity enabled on 'time' value.

**To Reproduce**
1. Setup polling interval to 10000ms
2. Setup Danfos Living Connect thermostat
3. Setup New Value for 'Day', 'Hour', 'Minute'
4. Setup polling intensity to 1 on 'Minute'
5. Restart zwave2mqtt

After restart zwave2mqtt crashes.

I've tried to set up polling of this values via zwave api call (mqtt api) - and it works, but polling will not persist after zwave2mqtt restart.

**Expected behavior**
Polling should apply without problems right after device initialization.

**Additional context**

It seems that valueID is not available yet (device initializes) during this call:

```
02-13T20:41:06.295Z z2m:Zwave Notification from node 9: Notification - NoOperation (2)
/home/zwave/Zwave2Mqtt/lib/Gateway.js:258
        if (!this.zwave.client.isPolled(v)) {
                               ^

TypeError: OpenZWave valueId not found: 9-129-1-2
    at Gateway.onNodeStatus (/home/zwave/Zwave2Mqtt/lib/Gateway.js:258:32)
    at ZwaveClient.emit (events.js:321:20)
    at ZwaveClient.notification (/home/zwave/Zwave2Mqtt/lib/ZwaveClient.js:504:14)
    at OZW.emit (events.js:333:22)
```

**Comment by kvaster** [comment]
Seems that problem is cause my device was somehow in state 'DEAD' and there was no any properties/values for it. Anyway it should not lead to zwave2mqtt crash I think...

**Comment by robertsLando** [comment]
@kvaster Thanks for your issue, that error is strange as at that point node is marked as ready so it should have all values, maybe it gets ready and immediatly dead before calling that api. Anyway I have added a try catch to handle this now :) thanks!
