### ISSUE TITLE
ZW090 Z-Stick Gen5 EU (AEON Labs) led does not turn off

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#259]
**Version**
Build/Run method
- [robertslando/zwave2mqtt:latest ] Docker

Zwave2Mqtt version: 2.1.1
Openzwave Version: ? the one in the docker I guess

**Describe the bug**
I have a "ZW090 Z-Stick Gen5 EU (AEON Labs)" as zwave controller.
It has a LED that is blinking constantly like crazy in red, orange, blue.
What I understant, this is correct behavour for this device, unless explicitly turned off.

In the configuration for the controller, there is a "LED indicator configuration" [enable/Disable]

If I change it to [Disable] and press the blue arrow next to the value, I get a response saying "Successfully call api setValue"

Problem is LED is still blinking and if I refresh the page, value has changed to [Enable]

**To Reproduce**
Try and set the [Disable] value, then refresh the page and visually look at the LED.

**Expected behavior**
LED should stop blinking

**Comment by robertsLando** [comment]
I suggest you to use this command to turn off led blink:

`echo -e '\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51'|cu -l /dev/ttyACM0 -s 115200`

Remember to replace `/dev/ttyACM0` with your device path
