### ISSUE TITLE
Question: Launching at Boot

### ISSUE THREAD

**Issue by michael-benoit** [OpenZWave/Zwave2Mqtt#26]
Sorry for a possible Linux noob question. How would I automatically launch Zwave2Mqtt at boot? I'm trying to create a systemd service, but issues with references to file dependencies, etc.

**Comment by robertsLando** [comment]
The easiest way is to use docker compose 

```
wget https://raw.githubusercontent.com/robertsLando/Zwave2Mqtt-docker/master/compose/docker-compose.yml
docker-compose up
```

The second option is to use [pm2](http://pm2.keymetrics.io/docs/usage/startup/). If you have nodejs already installed use` npm install -g pm2` otherwise you can install pm2 as `.deb`

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv D1EA2D4C

# 2. Add the PM2 repository
echo "deb http://apt.pm2.io/ubuntu stable main" | sudo tee /etc/apt/sources.list.d/pm2.list

# 3. Update list of available packages
sudo apt-get update

# 4. Install PM2
sudo apt-get install pm2
```

Than follow the link for instructions for running it on startup
