### ISSUE TITLE
[feat] Health check endpoints

### ISSUE THREAD

**Issue by DanielWinks** [OpenZWave/Zwave2Mqtt#264]
**Is your feature request related to a problem? Please describe.**
Currently, there aren't any health check endpoints. 

**Describe the solution you'd like**
It'd be valuable to be able to set up health and liveness probes in Kubernetes to a (semi-standard) /healthz endpoint. 

A HTTP endpoint for /healthz that gives 200 OK if the Zwave network is connected/USB stick is responding would be great. An additional one, perhaps on a different port or different url that responds with 200 OK if both Zwave is healthy **and** MQTT broker is connected would also be useful.

**Describe alternatives you've considered**
Currently I have a script I call which subscribes to a topic, publishes to `zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-z2m/api/getLibraryVersion/set` and checks for a response seems to work relatively well. However this requires adding a script to my pod, as well as building a custom container image with Mosquitto.

**Additional context**
Z2M running on a Pi3 in a Kubernetes cluster.

**Comment by robertsLando** [comment]
Hi Daniel, thanks for your feature request. What status code should I use for a fail? 404?
What if I create 3 health Checks:

`/health` : General health status, respond with a 200 if both mqtt and zwave are connected
`/health/mqtt`: Mqtt status
`/health/zwave`: Zwave status

**Comment by DanielWinks** [comment]
I think a 5xx code would be more appropriate. 500/502/504 all seem like they'd work. Per the Kubernetes docs: 

> Any code greater than or equal to 200 and less than 400 indicates success. Any other code indicates failure.

The end points seem good too, like the idea of having 3. 

JSON isn't needed, and I think the 3 end points alone provide enough info. Either zwave and MQTT are up or not. If not, 5xx and the pod gets killed and replaced by kubelet. Kubernetes doesn't look at response body, just the response code.

**Comment by robertsLando** [comment]
@DanielWinks Check readme https://github.com/OpenZWave/Zwave2Mqtt#healt-check-endpoints

**Comment by DanielWinks** [comment]
Looks great, minor edits submitted in https://github.com/OpenZWave/Zwave2Mqtt/pull/265
