### ISSUE TITLE
[bug] Changing poll_interval and poll_intensity sometimes doesn't apply

### ISSUE THREAD

**Issue by kvaster** [OpenZWave/Zwave2Mqtt#268]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: latest git (today)
Openzwave Version: latest git (today)

**Describe the bug**
I've made setup with poll_intervall = 10000 (10 seconds) and added value polling at each interval.
After I've changed poll_intervall to 60000, but nothing changed - values updated each 10 seconds.
Restart also doesn't help. After small investigation I found that changing poll_interval does not affect ozwcache_*.xml in store folder. And it seems that same goes for poll_intensity in value settings.

**To Reproduce**
Setup poll_intervall to 1000, add value with poll_intensity 1.
Observe proper values in ozwcache_*.xml
Delete value, change poll_interval to 60000.
Observe old/wrong values in ozwcache_*.xml

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by robertsLando** [comment]
@kvaster Poll interval and poll intensity are set after each restart. I don't know if this could be a problem of ozw that is not updating them as If you set them the first time it works

**Comment by kvaster** [comment]
Poll settings are set after each restart, but values are not updated in ozw settings.
I will take a look into code.
