### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by CaCu15** [OpenZWave/Zwave2Mqtt#271]
I've been using zwave2mqtt for 6 month without major problems. But since the upgrade to OpenZwave 1.6 I'm experiencing problems with device discovery. I'm using release 2.2.0 (tried 2.1.1, 2.1.0 as well) in a docker container and tried starting with a complete fresh install to ensure there are no effects of the old configuration.  My zwave network consists of 
- 1 ZME_UZB1 USB Stick (Z-Wave.Me)
- 6 Fibaro FGD212 Dimmer 2
- 1 Fibaro FGWPE/F Wall Plug Gen5
- 1 Steinel 140-2
- 1 Fibaro FGS213 Switch
- 1 Everspring - AN180 Plug-in ON/OFF Module

All devices are discovered, but a lot of endpoint/(command classes are missing, e.g.:
- My Fibaro Dimmers (FGD212 ) do only show 1 dimmer endpoint (38/1/0), all the endpoints for power and power consumption are missing (command class 50?) and all the zwave alarm endpoints are missing
- My Steinel 140-2 does only show entities from command classes 112 (configuration) and 114 (system). All endpoints previously shown when using ozw 1.4 (illumination sensor, motion sensor, binary switch) are missing
- The Fibaro Wall Plug does only show 1 switch endpoint (37/1/0), all the endpoints for power and power consumption are missing (command class 50?)
 
I also tried changing the config path as described in [issue #250](https://github.com/OpenZWave/Zwave2Mqtt/issues/250), but that doesn't help as well

I tried refreshing the node info, but that doesn't help. Log output for noe 11 shows some errors;
```
  z2m:App Zwave api call: refreshNodeInfo [ 11 ] +36s

  z2m:Zwave Success zwave api call refreshNodeInfo  +17s

  z2m:Zwave Node removed 11 +8ms

  z2m:Zwave Node added 11 +2ms

  z2m:Zwave Notification from node 11: Notification - NoOperation (2) +52ms

2020-02-24 06:18:51.900 Error, Node011, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "Request Node Info (Node=11): 0x01, 0x04, 0x00, 0x60, 0x0b, 0x90"
  z2m:Zwave Notification from node 11: Notification - TimeOut (1) +10s
2020-02-24 06:19:05.389 Error, Node011, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "ManufacturerSpecificCmd_Get (Node=11): 0x01, 0x09, 0x00, 0x13, 0x0b, 0x02, 0x72, 0x04, 0x25, 0x49, 0xf6"
  z2m:Zwave Notification from node 11: Notification - TimeOut (1) +13s
  z2m:Zwave node 11 AVAILABLE:  -  (Multilevel Power Switch) +3ms
  z2m:Zwave ValueAdded: 11-38-1-6 Step Size +3ms
  z2m:Zwave ValueAdded: 11-38-1-7 Inc +7ms
  z2m:Zwave ValueAdded: 11-38-1-8 Dec +7ms
  z2m:Zwave ValueAdded: 11-38-1-5 Dimming Duration +6ms
  z2m:Zwave ValueAdded: 11-38-1-0 Level +8ms
  z2m:Zwave ValueAdded: 11-38-1-1 Bright +7ms
  z2m:Zwave ValueAdded: 11-38-1-2 Dim +10ms
  z2m:Zwave ValueAdded: 11-38-1-3 Ignore Start Level +6ms
  z2m:Zwave ValueAdded: 11-38-1-4 Start Level +6ms
  z2m:Zwave ValueAdded: 11-39-1-0 Switch All +6ms
  z2m:Zwave ValueAdded: 11-114-1-0 Loaded Config Revision +7ms
  z2m:Zwave ValueAdded: 11-114-1-1 Config File Revision +6ms
  z2m:Zwave ValueAdded: 11-114-1-2 Latest Available Config File Revision +6ms
  z2m:Zwave ValueAdded: 11-114-1-3 Device ID +5ms
  z2m:Zwave ValueAdded: 11-114-1-4 Serial Number +4ms
  2020-02-24 06:19:28.901 Error, Node011, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchMultilevelCmd_Get (Node=11): 0x01, 0x09, 0x00, 0x13, 0x0b, 0x02, 0x26, 0x02, 0x25, 0x4d, 0xa0"
2020-02-24 06:19:28.902 Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
2020-02-24 06:19:28.902 Warning, CheckCompletedNodeQueries all=0, deadFound=0 sleepingOnly=1
  z2m:Zwave Notification from node 11: Notification - TimeOut (1) +6s

  z2m:Zwave node 11 ready:  -  (Multilevel Power Switch) +154ms
```

Any ideas?

**Comment by robertsLando** [comment]
@CaCu15 Do you see those values in values list?

**Comment by robertsLando** [comment]
@CaCu15 Could you check home assistant logs to see if there are errors on discovery and paste them here please? On my instance everything is working

**Comment by CaCu15** [comment]
I can see the following values in the zwave2mqtt's web interface:
"User" section:
11-38-1-0
11-38-1-1 (as button "Bright")
11-38-1-2 (as button "Dim")

Not entries in "configuration" section

"System" section
11-38-1-3 (as switch "ignore start level")
11-38-1-4
11-39-1-0

Will look for my home assistant logs..

**Comment by robertsLando** [comment]
@CaCu15 Ok so this is not an hass discovery problem but seems an Openxwave probelm, could you try to exclude and include back a node? To be sure it takes the same id use in order `Remove Node` and than `Replace Failed node` functions.

**Comment by CaCu15** [comment]
In the Home Assistant logs there are a lot of entries like the one below. I already know this kind of errors. They come from a type mismatch in the value of the MQTT message. The state_template and brightness template treat the value as an int, but obviously they are transmitted as string. Hence in the past I changed the auto generated templates:

`"brightness_template": "{{ (value / 99 * 255) | round(0) }}",`
to: 
`"brightness_template": "{{ (value|int / 99 * 255) | round(0) }}",`

This way HASS discovery works fine. 

But all this errors are related to HASS discovery, not to the discovery of the zwave devices itself by the gateway. Hence i thought, that this errors are not relevant for my problem...


`2020-02-24 07:19:05 ERROR (MainThread) [homeassistant.util.logging] Exception in state_received when handling msg on 'zwave2mqtt/Eingang/Eingang_Decke/38/1/0': '0'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_template.py", line 240, in state_received
    ].async_render_with_possible_json_value(msg.payload)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 275, in async_render_with_possible_json_value
    return self._compiled.render(variables).strip()
  File "/usr/local/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: unsupported operand type(s) for /: 'str' and 'int'`

**Comment by robertsLando** [comment]
@CaCu15 could you set payload to JSON time value or entire zwave object, this would fix those errors

**Comment by CaCu15** [comment]
I will try that today in the evening. Currently I don't have access to my installation.

**Comment by robertsLando** [comment]
Remeber to remove the hass stored configurations, If you have.

**Comment by CaCu15** [comment]
That seems to help. I'm getting the same zwave endpoints as in previous versions. Thx for your support!
