### ISSUE TITLE
[feat] Make Devices in HASS easier to identify

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#274]
Currently, HASS registers smilar devices under the same Name/Device

an example of Eurotronic sensors:
<img width="1415" alt="Screenshot 2020-02-27 at 19 51 59" src="https://user-images.githubusercontent.com/4048920/75476315-abc6f580-599a-11ea-8eff-d23df5869595.png">

Philips Hue uses the fields in different way:
Device: the name of the bulb
Manufacturer: the Manufacturer
Model: the name of the model.

What if we change the payload in order to register the devices as named in the system (using NodeID AND/OR the name of it, instead of the DEVICE model 

wouldn't the above list easier to identify?

**Comment by robertsLando** [comment]
@billiaz In poor words you suggest to change [this](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L429) With the node name/id?

**Comment by billiaz** [comment]
yeap, this way the device will clearly show in HASS.
and move this to the Model (instead of the HEX id)
I've seen this on normal Z-wave (1.4) and all the plugins i used
1. Philips hue
2. Gardena

**Comment by robertsLando** [comment]
Would you mind to send a PR for this? I will review it :)
