### ISSUE TITLE
[bug] HASS Devices dissapear or partially appear in Z2M after "refresh node info"

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#277]
Build/Run method
- X Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.2.0
Openzwave Version: 1.6.0

Creating a separate bug for this.

When performing refresh node info on a Node. The "HASS Devices" dissapearing or partially appearing after the discovery.

Example:
I have a Home plug of Fibaro 
When Z2M starts the devices for Home assistant are:
<img width="793" alt="Screenshot 2020-02-28 at 13 48 27" src="https://user-images.githubusercontent.com/4048920/75549945-19256580-5a31-11ea-834c-30e7213ec2da.png">

Once I perform a "Refresh node info" on this node

devices completely disappear:
<img width="1095" alt="Screenshot 2020-02-28 at 13 51 34" src="https://user-images.githubusercontent.com/4048920/75551939-8935ea80-5a35-11ea-9262-f556dffae147.png">

On Thermostats it uses custom devices discovery setup. 
this is a strange behaviour.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by robertsLando** [comment]
@billiaz `refresh node info` causes node to be removed and added back with the configuration fetched from the ozw config database, I cannot view your second image

**Comment by billiaz** [comment]
I waited in some devices for 1-2 days. they do not reappear. 
they do only if I restart the whole z2m
This was not the case before. (v 2.1)

Reattaching image:
<img width="1095" alt="Screenshot 2020-02-28 at 13 51 34" src="https://user-images.githubusercontent.com/4048920/75551939-8935ea80-5a35-11ea-9262-f556dffae147.png">

**Comment by hvxl** [comment]
I see the same issue when sending "online" to the "hass/status" topic via MQTT. Initially all of my ZWave devices are reported. But after refreshing a node, that node is no longer reported when triggering Hass discovery reports.

**Comment by robertsLando** [comment]
@hvxl @billiaz PLease check latest commit should fix this issue

**Comment by hvxl** [comment]
Confirmed. The hass output now correctly reports all devices after performing a refreshNodeInfo. Thanks for the quick fix.
