### ISSUE TITLE
[Question] Properties polling

### ISSUE THREAD

**Issue by kvaster** [OpenZWave/Zwave2Mqtt#28]
Telling the truth I do not completele understand how properties polling is implemented in openzwave right now, but it will be very good to have different settings per property for polling.

Two types of devices at my setup are: danfoss thermostat and MCO CO2 sensor.
First devices is almost always in sleep mode, second one is always on. Danfoss thermostat wakes up from time to time and pushes current temp settings. CO2 sensor automatically pushes sensor value change is more then 50ppm....

But it's not good. For CO2 device is would be much better to have possibility to poll it's value periodically (i.e. get value each 10 seconds) and for danfoss thermostat it would be very good to have possibility to adjust it's clock - this is more complicated. You should listen on 'wake up' event, imediatelly poll for clock values and send new time in case there is a big difference - this steps should be done before device will go to sleep again.

**Comment by robertsLando** [comment]
Actually the only way to set the polling interval is by using the entry in zwave settings `Poll Interval` and set the intensity of pooling for the value you need to poll. If it is a battery power device there is no way AFAIK to ask for updates, the update is triggered from the device when he decide to send it

**Comment by kvaster** [comment]
In openhab it is implemented in other way: they trigger query for values they want to poll on wakeup event. I.e. danfoss termostat pushes only battery level settings on wakeup, they do not push their current time. You can define 'check' period for such values - if passed more then 30 minutes (for example) from last check then openhab will request time value on next device wakeup and will correct it.

**Comment by robertsLando** [comment]
Could you explain this better?  Actually you can set the properties polling intensity of each value by adding a value on the gateway settings table. I never used OpenHab Zwave plugin so I don’t know how it works.

**Comment by kvaster** [comment]
I'm sorry, I've missed message.

Generally we want receive data in two ways: 1) immediate data in case of some change / alarm (it device decision to send such data) 2) we want to update some metrics from our 'application' depending on our ow logic. 1 now is OK - we receive data imediatelly when it is sent from devices. But with 2 we have some problems.

We have: devices which may be sleeping, problems with lot's of requests at the same time.

What I'am expecting to be able to do (as a developer): I'd like to be able to schedule poll for a value at any time I want. For alive devices this poll should happen when there is 'slot' available (according to poll position in poll queue). For sleeping devices I'm expecting poll to be executed right in the moment device wakes up to send some data (maybe other data) to us. Such poll should have highest priority. After each poll we should give application some small time to send additional commands (if it's required) to device.

Example: CO2 sensor + Danfoss thermostat. CO2 sensor is always alive and auomatically send it's value when it changes more then 50ppm. Danfoss thermostat wake's up according to it's wake up period (300s for example) and sends it's current settings and battery status. For CO2 sensor we want more detailed value history - we want to track value chanhes each 10 seconds even if change is less then 50ppm. For thermostat we want to automatically adjust it's time (it is not sent automatically on each wakeup). We make schedule for polling CO2 value each 10 seconds and thermostat time each 1800 seconds (for example).

I think that it's all clear with CO2 value - we schedule poll request and after receiving value we will schedule one more poll request in 10 seconds. For thermostat we schedule poll request and system will make this poll exactly that time device will wakeup. After receiving time we will compare it with current and if it have big difference we will send set time command. Sleeping devices do not go sleep right after sending data, they wait for different commands from controller / application for small amount of time. Also in case CO2 schedule is at the same time when thermostat wakes up, CO2 polling will be delayed until thermostat time polling will be finished.

**Comment by robertsLando** [comment]
@kvaster I think you should be able to do what you want by using [MQTT APIs](https://github.com/OpenZWave/Zwave2Mqtt#gift-mqtt-apis). With them you have full control of Zwave network and you can programatically ask to a node to update a value for example by using `refreshValue` api check [here](https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-values.cc#L116)

**Comment by kvaster** [comment]
Ok. Thanks. I will check if it works this way!

**Comment by robertsLando** [comment]
Any updates @kvaster ?

**Comment by kvaster** [comment]
It needs some code to be written from my side and I had no time yet, but I understand the concept and it should work. I think this issue can be closed. I will add comments after I will implement this in my system. Thanks!
