### ISSUE TITLE
[bug] Network Graph not showing spiderweb

### ISSUE THREAD

**Issue by raymonvdm** [OpenZWave/Zwave2Mqtt#280]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.2.0
Openzwave Version: 1.6.1044

**Describe the bug**

The network graph is not working correctly because al data is shown on a couple of pixels see https://imgur.com/a/D2HtDT3

**To Reproduce**
1. Go to 'http://192.168.100.52:8091/'
2. Click on mesh.'
3. See error

**Expected behavior**

A nice spider web of all the nodes and their neighbours to see if we have network issues

**Comment by robertsLando** [comment]
What browser are you using? Could you open developer console in chrome/firefox and check if there are errors?

**Comment by raymonvdm** [comment]
I tried Firefox and Chrome but bot seem to have the same issue. Today i rebuild my Z-Wave network by resetting the stick and including all nodes one by one to clean out died nodes en adding some extra nodes. And the view is now different

https://imgur.com/a/DI5yNs7

The bug might hower be changed into a wish  to increase the canvas

**Comment by robertsLando** [comment]
Seems working now, doesn’t it? How many nodes do you have in your network?

Daniel

**Comment by raymonvdm** [comment]
At the moment there are 25 nodes, but i need to add a couple in the upcomming week.

**Comment by robertsLando** [comment]
Let me know how it goes

**Comment by razvanws** [comment]
I'm using zwave2mqtt v3.2.2 and I'm having the same issue. Actually, I was never able to see that map regardless of the zwave2mqtt version used.
I'm using Chrome browser.

You can see how it appears below. I have 16 nodes.
https://imgur.com/a/2R1lzvu

**Comment by razvanws** [comment]
After a "heal" command, I can see it like this:
https://imgur.com/a/59MWqL0

**Comment by robertsLando** [comment]
Do you see any error in console log? Is the scan completed?

---

Daniel

**Comment by razvanws** [comment]
The scan is completed. Now I see again the first image.
As soon as I switch to network graph tab, I get this error in console:
https://imgur.com/a/3f7jyT0

**Comment by razvanws** [comment]
Actually, I was able to download the SVG as well, if it helps you:
https://svgur.com/i/Lbv.svg

**Comment by robertsLando** [comment]
Was it working in previous version?

---

Daniel

**Comment by razvanws** [comment]
Unfortunately it didn't work for me with any version, no matter how old.

**Comment by robertsLando** [comment]
Do debug this I need to know if you see any error in console log, how many node there are in your network and the build method you are using (docker/nodejs/pkg) 

---

Daniel

**Comment by razvanws** [comment]
I have 16 nodes (excluding the gateway usb stick). I'm getting the following console error:
https://imgur.com/a/3f7jyT0

Regarding the build method, I'm using a the hassio addon below which creates a docker container:
https://github.com/hassio-addons/addon-zwave2mqtt/

**Comment by robertsLando** [comment]
@razvanws Your error says `Error: missing 14` could you tell me something more by inspecting the error?

**Comment by razvanws** [comment]
If I inspect ue-d3-network.umd.js:5313 I can see the following function:
`function link_find(nodeById, nodeId) {
  var node = nodeById.get(nodeId);
  if (!node) throw new Error("missing: " + nodeId);
  return node;
}`

Below you can see line 5363 (which calls line 5313 above):
`if (typeof link.target !== "object") link.target = link_find(nodeById, link.target);`

Hope it helps you.

**Comment by robertsLando** [comment]
Try to check my last PR to see if it fixes you problem
