### ISSUE TITLE
How do I request data from ZWave2Mqtt

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#281]
Hi,

I have my own home automation app with an implementation of an old OZW library. I wish to decouple this from my app and Zwave2Mqtt seems like a great candidate!

I would still like to do most of the node management in my app as I am running multiple controllers for 2 locations and all the logic and UI is already in place.

Most is covered by the mapping to the API calls which is great, but I was wondering how to request the entire list of ZWave nodes, including their command classes, so I can populate it on my app's side. Publishing them all individually in sequence would also be fine.

Also, it would be very useful if the Mqtt topic prefix could be a few steps deep for integration in existing Mqtt environments. i.e. "MyEnvironment/Location/Zwave"

Kind regards,
Elco

**Comment by robertsLando** [comment]
Take a look to: https://github.com/OpenZWave/Zwave2Mqtt#zwave-events

**Comment by elcosmelco** [comment]
As I understand it those just echo the events from the OZW lib when they occur right? That won't do me any good if I start my app after these events - I would like to request these on demand rather than listening at the right moment.
I.e. I could never reboot my app separately from the Zwave2Mqtt app, I would always have to restart my app first and then restart Zwave2Mqtt to build the node list based on the OZW events.

Hope this makes sense!

**Comment by robertsLando** [comment]
@elcosmelco Done
