### ISSUE TITLE
[bug]"Send 'list' values as integer index" sends meaningless value.

### ISSUE THREAD

**Issue by hvxl** [OpenZWave/Zwave2Mqtt#282]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.2.0
Openzwave Version: 1.6.992

**Describe the bug**
The value sent when enabling the "Send 'list' values as integer index" feature is useless.

For example: My Everspring AN181 uses the following mapping for Power Management Alerts (class 113, index 8): 0=Clear, 1=Power Applied, 8=Over Load Detected. My Fibaro FGD212, on the other hand, uses 0=Clear, 4=Surge Detected, 5=Brownout Detected, 6=Over Current Detected, 8=Over Load Detected, 9=Load Error.

For some reason Zwave2MQTT reports the following list of values for the AN181:["Clear", "Clear", "Power Applied", "Over Load Detected"]. I don't know why Clear appers twice. For the FGD212 the list is: ["Clear", "Surge Detected", "Brownout Detected", "Over Current Detected", "Over Load Detected", "Load Error"]. Now, for the AN181, Zwave2MQTT indicates the current value is 2. But since the enumeration values can be localized, there is no way to tell what that means.

Openzwave uses a fixed mapping for the possible values, so 8 always means that an overload was detected, independent of the device or any localization. But in Zwave2MQTT this information is lost and an overload comes out as 3 on an AN181, and as 4 on an FGD212. 

To be useful, Zwave2MQTT should either report the openzwave numbers, or there should be some way to map the reported value back to the openzwave number. This could be done by changing the "values" entry in the json data from an array to an object, like {"0": "Clear", "1": "Power Applied", "8": "Over Load Detected"} for an AN181. As the order of json objects is not guaranteed, it would be more convenient to still use the openzwave number in the second case too, otherwise some agreement on how the entries are assumed to be ordered must be specified.

**Comment by robertsLando** [comment]
>  I don't know why Clear appers twice

@hvxl The list of values comes from OZW I don't have the control of that, maybe it could be a typo on device configuration of ozw library? you should try to check [here](https://github.com/OpenZWave/open-zwave/tree/master/config)

> This could be done by changing the "values" entry in the json data from an array to an object, like {"0": "Clear", "1": "Power Applied", "8": "Over Load Detected"} for an AN181.

This should be done in openzwave-shared library, not here. Would you mind to send a PR for that?
Check [here](https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/utils.cc#L129)

**Comment by robertsLando** [comment]
Check out this: 60272ab90bc829965160b5d0722ee8a126a5ce4f

**Comment by robertsLando** [comment]
@Fishwaldo How can I call `SetValue` with a list value and not a list item?

**Comment by hvxl** [comment]
> @Fishwaldo How can I call `SetValue` with a list value and not a list item?

Heh, I had the same question a while ago: https://github.com/OpenZWave/open-zwave/issues/1885

**Comment by robertsLando** [comment]
I think that would be lot more user friendly

**Comment by hvxl** [comment]
> Check out this: [OpenZWave/node-openzwave-shared@60272ab](https://github.com/OpenZWave/node-openzwave-shared/commit/60272ab90bc829965160b5d0722ee8a126a5ce4f)

That looked promising, but that version doesn't actually work for me. Either I'm doing something wrong, or the change breaks zwave2mqtt. I also see that the change has been reverted again.

For completeness, this is how I tried to use the fix:
```
npm install OpenZWave/node-openzwave-shared#60272ab90bc829965160b5d0722ee8a126a5ce4f
npm start
```
That ends with: TypeError: valueId.values.indexOf is not a function

**Comment by robertsLando** [comment]
@hvxl I have moved that change on a separeted branch of openzwave shared, it needs also some work on z2m side to make it work

**Comment by hvxl** [comment]
> it needs also some work on z2m side to make it work

Right. That was why z2m would no longer run.

I forked both node-openzwave-shared and Zwave2Mqtt and then made the necessary changes with 60272ab as the starting point. That seems to do what I wanted.

**Comment by chilicheech** [comment]
The `Send 'list' values as integer index` seems to have no effect for me. It still sends the value as a string. For example, my thermostat device still sends `"value": "Heat"` instead of `"value": 1` in the json payload.

**Comment by robertsLando** [comment]
@chilicheech This issue is different than what you mean. Actually the 'index' is the index of the value in the valueID values array, that usually is different from the  value index
