### ISSUE TITLE
[bug] Cant add new nodes

### ISSUE THREAD

**Issue by errolsancaktar** [OpenZWave/Zwave2Mqtt#286]
**Version**

Build/Run method
- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: latest
Openzwave Version: 1.6

**Describe the bug**

**To Reproduce**
1. Go to 'add node
2. try to add node via device guide
3. get:
2020-03-03T05:20:33.814Z z2m:Zwave Success zwave api call addNode true
OpenZWave Detail, Queuing (Controller) Add Device
OpenZWave Info, WriteNextMsg Controller nothing to do

**Expected behavior**
add new node

**Additional context**

**Comment by robertsLando** [comment]
@errolsancaktar What is the error?

**Comment by Fishwaldo** [comment]
I assume you clicking add node In Z2M before clicking anything on the device?

**Comment by errolsancaktar** [comment]
yup clicked add new node, get the message in the error log and it doesnt add anything.  

`2020-03-09 12:12:18.439 Detail, contrlr,   Expected reply was received
2020-03-09 12:12:18.439 Detail, contrlr,   Message transaction complete
2020-03-09 12:12:18.439 Detail,
2020-03-09 12:12:18.439 Detail, contrlr, Removing current message
2020-03-09 12:12:18.439 Detail, Notification: AddDevice ControllerCommand - Waiting
2020-03-09 12:12:18.440 Info, WriteNextMsg Controller nothing to do`

**Comment by Fishwaldo** [comment]
There is no error in the log. It’s waiting for you to do the inclusion on the device. You need to consult the device manual. 

If it still doesn’t happen, please verify the frequency of the stick and the device your adding.

**Comment by errolsancaktar** [comment]
So it’s weird. I have a couple of these in my network already and just went
to add a couple more. They are the Monoprice zwave door sensors. It’s like
it doesn’t see them at all when I try to include either securely or
insecurely. Is there a log level I can turn up to get more info?

**Comment by errolsancaktar** [comment]
something must have mucked up in the config files.  once i removed the data folder and started fresh with just the info on the zwave controller it let me add the device.  no clue why it wasnt working before
