### ISSUE TITLE
[bug] Only one device showing up in HASS with ALL entities in it

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#287]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master
Openzwave Version: master

**Describe the bug**
All entities are showing up under a single MQTT device in HASS:
<img width="1415" alt="Screen Shot 2020-03-02 at 11 04 56 PM" src="https://user-images.githubusercontent.com/732659/75751038-60824f00-5cda-11ea-8d68-ea10ca890144.png">
<img width="344" alt="Screen Shot 2020-03-02 at 11 05 15 PM" src="https://user-images.githubusercontent.com/732659/75751045-65470300-5cda-11ea-9649-624bf21f6bd1.png">
I suspect it's because they all have their device identifier set to the same value: `zwave2mqtt_0xc5b5c9e5`
<img width="724" alt="Screen Shot 2020-03-02 at 11 06 28 PM" src="https://user-images.githubusercontent.com/732659/75751143-a3442700-5cda-11ea-8c4c-cec63f26fe6a.png">
<img width="457" alt="Screen Shot 2020-03-02 at 11 06 57 PM" src="https://user-images.githubusercontent.com/732659/75751154-a5a68100-5cda-11ea-9754-fc7bd7654b62.png">

**To Reproduce**

**Expected behavior**
Entities should be grouped under their own devices.

**Additional context**
This was working properly in version 2.2.0.

**Comment by robertsLando** [comment]
@chilicheech Please use latest version from master, I have fixed this in latest commit :)
