### ISSUE TITLE
[bug] All light devices showing error in HASS: Invalid state value received

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#288]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master branch
Openzwave Version: 1.6 - master branch

**Describe the bug**
All light devices are throwing this error in HASS:
```
hass    | 2020-03-03 06:17:21 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_template] Invalid state value received
```
All of the lights are now `unknown` in HASS.
The discovery payload looks like this:
```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "state_topic": "z2m/30/38/1/0",
    "state_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
    "command_topic": "z2m/30/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xc5b5c9e5"
      ],
      "manufacturer": "Linear (Nortek Security Control LLC)",
      "model": "WD500Z-1 Wall Dimmer Switch (0x3034)",
      "name": "dining_lights",
      "sw_version": "5.41"
    },
    "name": "dining_lights_dimmer",
    "unique_id": "zwave2mqtt_0xc5b5c9e5_30-38-1-0"
  },
  "discoveryTopic": "light/dining_lights/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "id": "light_dimmer"
}
```
I believe this change broke it, form PR #270: https://github.com/OpenZWave/Zwave2Mqtt/commit/2314898f4cc57debd15e74cb60cbd0b98001d226#diff-42b2a4d55075f77590c8aa76053c2f82L180
Here's the reason I believe that caused the error:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema_template.py#L223-L228
https://github.com/home-assistant/core/blob/dev/homeassistant/const.py#L200-L201
The states need to be lowercase `on` and `off`. Not sure what the reasoning was to set those to uppercase in that change.

When I manually change the `HASS Device JSON` to use `on` `off` instead of `ON` `OFF` things work properly again.

**To Reproduce**

**Expected behavior**
The correct value should be extracted.

**Additional context**

**Comment by robertsLando** [comment]
@chilicheech Check readme and the closed PR

**Comment by chilicheech** [comment]
Hi @robertsLando, I am on the latest version of HASS. As you can see in the code I linked the values should be lowercase. I know the documentation says it should be uppercase, but the code looks for lowercase. Either the HASS documentations is wrong or the HASS code is wrong. In any case, please keep this issue open since this error is still happening, even if what I pointed above is not the cause. We have to find what's causing it.

I'm gonna open an issue in HASS too and link this one too it.

Cheers,

**Comment by robertsLando** [comment]
@chilicheech Open the issue on hass so and let me know :)

**Comment by chilicheech** [comment]
Thanks. Give me a few hours to do it since I'm taking the kids to school. Here's what I found so far. The documentation for payload_on and payload_off you linked in the PR is for the `default schema`. We are using the `template schema`. They even have an example with it using uppercase values for the default schema and lowercase values for the template schema: https://www.home-assistant.io/integrations/light.mqtt/#simple-string-payload

**Comment by robertsLando** [comment]
@chilicheech Are you sure maybe the problem is with the mqtt plugin version? Maybe the breaking change has come from there

**Comment by robertsLando** [comment]
@chilicheech https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema_basic.py#L91

**Comment by robertsLando** [comment]
@chilicheech Could you also try to add this to `configurations.js` light component:

```js
payload_off: 'OFF',
payload_on: 'ON',
```

To check if it works or not

**Comment by chilicheech** [comment]
> @chilicheech https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema_basic.py#L91

The problem is we use the Z2M uses the `schema_template`, not the `schema_basic`, and the `schema_template` uses lowercase on/off:
- https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema_template.py#L223-L228
- https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema.py#L9

Let me try your suggestion to see what happens.

**Comment by robertsLando** [comment]
@chilicheech Seems you are right https://github.com/home-assistant/core/blob/dev/homeassistant/const.py#L200

I think I should make a patch release for this :( Let me know if the fix I suggested works or not, but I don't think it will work as I don't see any reference to `payload_on|off` in the schema_template.py

**Comment by chilicheech** [comment]
OK, I tried your suggestion and got the following error in HASS:
```
hass    | 2020-03-03 17:54:49 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'schema': 'template', 'brightness_template': '{{ (value_json.value / 99 * 255) | round(0) }}', 'state_topic': 'z2m/17/38/1/0', 'state_template': '{{ "OFF" if value_json.value == 0 else "ON" }}', 'command_topic': 'z2m/17/38/1/0/set', 'command_on_template': '{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}', 'command_off_template': '0', 'payload_off': 'OFF', 'payload_on': 'ON', 'device': {'identifiers': ['zwave2mqtt_0xc5b5c9e5_node17'], 'manufacturer': 'Linear (Nortek Security Control LLC)', 'model': 'WD500Z-1 Wall Dimmer Switch (0x3034)', 'name': 'foyer_lights', 'sw_version': '3.0.0'}, 'name': 'foyer_lights_dimmer', 'unique_id': 'zwave2mqtt_0xc5b5c9e5_17-38-1-0', 'platform': 'mqtt'},)
hass    | Traceback (most recent call last):
hass    |   File "/venv/lib/python3.7/site-packages/homeassistant/components/mqtt/light/__init__.py", line 57, in async_discover
hass    |     config = PLATFORM_SCHEMA(discovery_payload)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
hass    |     return self._exec((Schema(val) for val in self.validators), v)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
hass    |     raise e if self.msg is None else AllInvalid(self.msg, path=path)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
hass    |     v = func(v)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
hass    |     return self._compiled([], data)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
hass    |     return schema(data)
hass    |   File "/venv/lib/python3.7/site-packages/homeassistant/components/mqtt/light/__init__.py", line 35, in validate_mqtt_light
hass    |     return schemas[value[CONF_SCHEMA]](value)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
hass    |     return self._compiled([], data)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
hass    |     return base_validate(path, iteritems(data), out)
hass    |   File "/venv/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
hass    |     raise er.MultipleInvalid(errors)
hass    | voluptuous.error.MultipleInvalid: extra keys not allowed @ data['payload_off']
```
The light devices never showed up. Here are some screenshots:
![Screen Shot 2020-03-03 at 10 09 00 AM](https://user-images.githubusercontent.com/732659/75805750-3e6aea00-5d37-11ea-97d2-c01789fefcf7.png)
![Screen Shot 2020-03-03 at 10 09 16 AM](https://user-images.githubusercontent.com/732659/75805752-4034ad80-5d37-11ea-9e73-379040e4f75e.png)

**Comment by balloob** [comment]
`on` and `off` has been the values for the last 3 years … https://github.com/home-assistant/core/blame/dev/homeassistant/components/mqtt/light/schema_template.py#L223-L226 

It should not have been changed to capitalized versions.

**Comment by chilicheech** [comment]
@balloob, I agree for `schema_template`. But it seems that for `schema_basic` it does use all caps, which seems inconsistent and may cause confusion: https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/light/schema_basic.py#L90-L91

In Zwave2Mqtt the `light_dimmer` devices use `schema_template` while the `light_rgb_switch` uses `schema_basic`.

**Comment by balloob** [comment]
Right. That is confusing. It's inconsistent but would be too much of a breaking change to break now on our side.

**Comment by robertsLando** [comment]
@balloob @chilicheech Sorry for this guys, will release a patch today 3.0.1

**Comment by chilicheech** [comment]
Thanks for the quick fix!
