### ISSUE TITLE
Question: No message when switch changed physically

### ISSUE THREAD

**Issue by michael-benoit** [OpenZWave/Zwave2Mqtt#29]
I'm not receiving messages when my Leviton Dimmer Switch is changed physically. If it's changed via the API I receive the appropriate messages. Is this by design?

**Comment by CurrentThread** [comment]
I'm receiving messages when switching my dimmers and switches physically (Qubino and Fibaro). Perhaps it is device specific?

**Comment by robertsLando** [comment]
Most of your questions are likely a device configuration issue and nothing about this library. Try to ask in [Openzwave](https://github.com/OpenZWave/open-zwave)
