### ISSUE TITLE
[bug] Lock device not using new human readable model in Hass discovery

### ISSUE THREAD

**Issue by raetha** [OpenZWave/Zwave2Mqtt#291]
**3.0.0**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.0
Openzwave Version: 1.6.2?

**Describe the bug**
Just upgraded to 3.0.0 and allowed all devices to recreate in Hass. Most look as expected with new human readable model for the device. One exception is my Schlage BE469 Touchscreen Deadbolt. It still shows a model as 0x5044. It is also the only device where the device name is also the model ("BE469 Touchscreen Deadbolt") rather than matching the other zwave devices where the device name matches the one specified in Zwave2Mqtt (e.g. "dining_room_lights").

**To Reproduce**
1. Enable Hass Discovery
2. Make sure zwave lock and switch exist
3. View resulting devices created in Hass

**Expected behavior**
Expected all discovered devices to look similar in their formatting, whatever that is. So names and models would feel consistent.

**Additional context**
![image](https://user-images.githubusercontent.com/901995/75790212-da492580-5d38-11ea-986f-c0a1731d40ee.png)

**Comment by robertsLando** [comment]
@raetha I think that is something from a previous instance? Because as you can see the code is different: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L440

**Comment by jaburges** [comment]
i updated to 3.0.0 and do not have this issue 
(confirmed I have also mapped /openzwave using the lastest device handlers from OZW repo)

Have you tried 'Refresh Node Info' since the update?
