### ISSUE TITLE
How can I determine if the auto update database is working? [question] 

### ISSUE THREAD

**Issue by cts1085** [OpenZWave/Zwave2Mqtt#293]
I am running HassOS 3.11 on a Raspberry Pi, Supervisor 207 with Add-on Zwave2MQTT 0.5.0

Is there a way via the UI to determine if the Auto Update Database switch is working? Where can I go to verify the updates are current?

Thank you!

**Comment by robertsLando** [comment]
Check logs on startup, OZW will check for new updates and download them

**Comment by cts1085** [comment]
Thank you!

**Comment by robertsLando** [comment]
I don't know how that container is installed, usually if you use docker-compose I use docker-compose log command

**Comment by cts1085** [comment]
This is all I was able to find, just in case others were wondering: 'ha addons log a0d7b954_zwave2mqtt'

But it shows the same as what is in the HA UI
