### ISSUE TITLE
[bug] Home Assistant Lock autodiscovery broken after update to 3.0.0

### ISSUE THREAD

**Issue by cliviu74** [OpenZWave/Zwave2Mqtt#294]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.0
Openzwave Version: 1.6
Home Assistant 0.106.4
Yale YD-01-CON + Yale Zwave module 2 a.k.a Keyless Connected (YD-01-CON) (0x0001) by Assa Abloy 

**Describe the bug**
Home Assistant autodiscovered lock stopped working after zwave2mqtt update from 2.2.0 to 3.0.0

**To Reproduce**
1. Install / Update zwave2mqtt 3.0.0
2. Go to Home Assistant and try to Unlock/Lock. Lock will remain in "unlocked" state. Lock does not respond to commands

**Expected behavior**
Locking and Unlocking should operate the lock. Status should be reflected in Home Assistant

**Additional context**
This seems to be related to the attempt to fix lock discovery changes in Home Assistant 0.104+ - https://github.com/OpenZWave/Zwave2Mqtt/issues/203

**Workaround**
Tweaking the discovery json payload in Z2M > [Lock Configuration] > Home Assistant - devices fixes the issue and restores the lock functionality.

1. Quote true/false value around lock state booleans
Replace
```
    "state_locked": true,
    "state_unlocked": false,
```
With
```
    "state_locked": "true",
    "state_unlocked": "false",
 ```
2. Add payload_(lock|unlock) booleans as Home Assistant sends "LOCK" "UNLOCK" json payloads by default which seems to be ignored by Z2M. 

```
    "payload_lock": "true",
    "payload_unlock": "false",
```

After changes, discovery payload should look like this:
```
discovery_payload": {
    "command_topic": "[prefix_topic]/2/98/1/0/set",
    "state_locked": "true",
    "state_unlocked": "false",
    "payload_lock": "true",
    "payload_unlock": "false",
    "value_template": "{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}",
...
```

**Comment by robertsLando** [comment]
@cliviu74 Are you sure this is actually working?

**Comment by robertsLando** [comment]
@cliviu74 Are you using gateway with payload `Just value` or other? If `Just value` please use `JSON` or `Zwave Object`

**Comment by cliviu74** [comment]
> @cliviu74 Are you sure this is actually working? Shouldn't also value_template be
> 
> ```
>     "value_template": "{% if value_json.value == false %} 'false' {% elif value_json.value == true %} 'true' {% else %} unknown {% endif %}",
> ```

Seems to be working fine, not sure why the booleans would be interpreted differently, mqtt shouldn't care much about it. 
This is the full discovery payload that works currently, if it helps
```
{
  "type": "lock",
  "object_id": "lock",
  "discovery_payload": {
    "command_topic": "[topic]/2/98/1/0/set",
    "state_locked": "true",
    "state_unlocked": "false",
    "payload_lock": "true",
    "payload_unlock": "false",
    "value_template": "{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}",
    "state_topic": "zwave2mqtt/2/98/1/0",
    "json_attributes_topic": "[topic]/2/98/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0x123456_node2"
      ],
      "manufacturer": "Assa Abloy",
      "model": "Keyless Connected (YD-01-CON) (0x0001)",
      "name": "nodeID_xx",
      "sw_version": "33.16"
    },
    "name": "nodeID_xx_lock",
    "unique_id": "zwave2mqtt_0x12345_2-98-1-0"
  },
  "discoveryTopic": "lock/nodeID_xx/lock/config",
  "values": [
    "98-1-0"
  ],
  "persistent": false,
  "id": "lock_lock
```

**Comment by cliviu74** [comment]
> @cliviu74 Are you using gateway with payload `Just value` or other? If `Just value` please use `JSON` or `Zwave Object`

Sorry, I'm not sure I know what you mean? Is this a gateway setting somewhere?

**Comment by robertsLando** [comment]
Go to settings, gateway section, payload type

**Comment by cliviu74** [comment]
> Go to settings, gateway section, payload type


So I fiddled with it and set it to "JSON Time-Value". Before if was the default, don't know what the default is.

settings.json config before:
```
"gateway":{"values":[],"type":0,"hassDiscovery":true,"discoveryPrefix":"homeassistant","retainedDiscovery":false}
```
settings.json config after the change
```
"gateway":{"values":[],"type":0,"hassDiscovery":true,"discoveryPrefix":"homeassistant","retainedDiscovery":false,"payloadType":0}
```

**Comment by cliviu74** [comment]
Worked like a charm, thanks for the help.
Discovery payload changed back to the original after resetting the gateway payload setting to JSON Time-Value. 
After rediscovery it works, lock/unlock works, also state is reflected by the lock status.

**Comment by ebfio** [comment]
I have the same issue with my Yale lock. I'm gathering the debug log to share here shortly, but in a nutshell, I can lock and unlock, but the state never gets updated on HA, manually or not.

I tried all the changes here in this thread, nothing worked. Sharing my logs soon...

**Comment by robertsLando** [comment]
send a screenshot or gateway settings json export please

**Comment by raetha** [comment]
@robertsLando Just a quick follow up here. I know you've made a bunch of changes for the lock issues with HA 104 and above, and most of them seemed to improve things. But I am still having the issue with lock status and have to update the lock JSON to put quotes around true and false for:
```
"state_locked": "true",
"state_unlocked": "false",
```
As long as the quotes are around true and false, all seems well with HA seeing the status correctly. I did check my payload and am doing entire z-wave value object, so that part appears correct from the thread. Happy to supply any other logs or anything I can to assist.

**Comment by robertsLando** [comment]
@raetha PLease set payload to json time value or entire zwave object when using with hass

**Comment by raetha** [comment]
In the UI it is set to entire zwave object as I mentioned. Is that not working as expected and I need to change something directly in the config?

**Comment by robertsLando** [comment]
Nope it should work

**Comment by raetha** [comment]
That’s what I thought. So the only fix I’veGotten to work was adding the quotes around those values in the json for the lock, then storing that. Do you happen to have a lock that is working correctly without the quotes? If so, would you mind sharing your config so I can compare. And maybe the discovery payload as well?

**Comment by robertsLando** [comment]
@raetha  are you using latest z2m version? Anyway I don't have a lock device, but @cliviu74 made it working

**Comment by cliviu74** [comment]
@robertsLando just a quick update, the autodiscovered lock has stopped working after a while, although the payload settings have been maintained the same (tried both JSON or Zwave Object with the same result)
Wrapping the booleans in quotes seems to fix this issue but, as I'm running z2m in docker, I lose the settings after a restart and I don't have the time to rebuild the patched file into my own image. 
At the moment I have configured the lock manually in Home Assistant (configuration below).
```
- platform: mqtt
  command_topic: "zwave2mqtt/2/98/1/0/set"
  name: Main Door
  payload_lock: 'true'
  payload_unlock: 'false'
  state_topic: "zwave2mqtt/2/98/1/0"
  state_locked: True
  state_unlocked: False
  value_template: '{{value_json.value}}'
  retain: true
```
I may have time on my hand in the coming days so I may be able to debug things on my lock if you need me. I will try to verify this further and propose a fix, time permitting.

**Comment by cliviu74** [comment]
Verified and confirmed a couple of times, adding quotes to boolean fixes the issue with autodiscovered locks in home assistant, removing the quotes breaks it again.
Tested on Z2M 3.0.1 with Gateway -> Payload Type: Entire Z-WAVE value Object

proposed change in the discovery payload:

```
    "state_locked": "true",
    "state_unlocked": "false",
```

**Comment by cliviu74** [comment]
Home Assistant is expecting the quoted string rather than a boolean. The JSON payload sent via MQTT wouldn't make a distinction between a string and a boolean. Probably Home Assistant is discarding the value if it's not string.
I think adding quotes to the discovery payload booleans is the proper fix for this.

Here's the MQTT JSON  discovery payload for the 

Broken:
```
[hassdiscoverytopic]/lock/nodeID_2/lock/config {"command_topic":"zwave2mqtt/2/98/1/0/set","state_locked":true,"state_unlocked":false,"value_template":"{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}","state_topic":"zwave2mqtt/2/98/1/0","json_attributes_topic":"zwave2mqtt/2/98/1/0","device":{"identifiers":["zwave2mqtt_0xxxxx_node2"],"manufacturer":"Assa Abloy","model":"Keyless Connected (YD-01-CON) (0x0001)","name":"nodeID_2","sw_version":"33.16"},"name":"nodeID_2_lock","unique_id":"zwave2mqtt_0xxxx_2-98-1-0"}
```

Working
```
[hassdiscoverytopic]/lock/nodeID_2/lock/config {"command_topic":"zwave2mqtt/2/98/1/0/set","state_locked":"true","state_unlocked":"false","value_template":"{% if value_json.value == false %} false {% elif value_json.value == true %} true {% else %} unknown {% endif %}","state_topic":"zwave2mqtt/2/98/1/0","json_attributes_topic":"zwave2mqtt/2/98/1/0","device":{"identifiers":["zwave2mqtt_0xxxxx_node2"],"manufacturer":"Assa Abloy","model":"Keyless Connected (YD-01-CON) (0x0001)","name":"nodeID_2","sw_version":"33.16"},"name":"nodeID_2_lock","unique_id":"zwave2mqtt_0xxxx_2-98-1-0"}
```

**Comment by robertsLando** [comment]
@cliviu74 Thank you, will submit a fix asap!

**Comment by robertsLando** [comment]
@cliviu74 Does this apply also to others? like lights?

**Comment by cliviu74** [comment]
@robertsLando thanks for looking into this, great stuff!
Unfortunately I only have a lock on zwave at the moment so I can only verify that.
From what I see, discovery payload looks a bit funny in Home Assistant, if the boolean is without quotes, I would imagine it would apply to others. 
From home assistant mqtt discovery documentation [https://www.home-assistant.io/docs/mqtt/discovery/] I can't see that booleans would be treated differently so I imagine passing them as strings is safe enough.

**Comment by robertsLando** [comment]
Because I have other configurations that have booleans, and I'm thinking that maybe also them could be broken

**Comment by cliviu74** [comment]
I suppose we can try to simulate discovery payloads of concern to verify them. If you have any thoughts on testing things, I can lend a hand to emulate.

**Comment by raetha** [comment]
I can confirm that my switches don't seem to have an issue with the payload_off and payload_on values not being in quotes, and show the correct light status in HA. Example working switch payload:
```
{
  "type": "switch",
  "object_id": "switch",
  "discovery_payload": {
    "payload_off": false,
    "payload_on": true,
    "value_template": "{{ value_json.value }}",
    "command_topic": "zwave2mqtt/15/37/1/0/set",
    "state_topic": "zwave2mqtt/15/37/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xce98cca6_node15"
      ],
      "manufacturer": "Inovelli",
      "model": "NZW30 Smart Switch (w/Scene) (0x1e00)",
      "name": "kitchen_island_lights",
      "sw_version": "1.03"
    },
    "name": "kitchen_island_lights_switch",
    "unique_id": "zwave2mqtt_0xce98cca6_15-37-1-0"
  },
  "discoveryTopic": "switch/kitchen_island_lights/switch/config",
  "values": [
    "37-1-0"
  ],
  "persistent": false,
  "id": "switch_switch"
}
```
So it isn't clear to me why HA has a different standard with the lock state values in the discovery json, only that it was consistent for my lock.

@robertsLando Sorry for not providing enough information originally. I was trying to be succinct, since I thought the issue had been mentioned and was effectively just affirming still there. But I should have provided more config like @cliviu74 did. Been a little distracted, I work in IT at a hospital and things are a little crazy right now, but figured I'd do some more smart home stuff in the down time I can find.

I'm happy to help test things. At this point on zwave I have a lock, a few switches (dimmable, static, and scene enabled), a FireFighter smoke alart, and contemplating some new toys as I can find time. Please let me know anything I do to assist as I'm more than happy to.

**Comment by robertsLando** [comment]
@cliviu74 In order to simulate discovery payload we should simulate nodes/valueids. I already did such things like you can see [here](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L303) but that is not the way. We could create a file with a fake node with different valueids, load that file on startup and emulate events

**Comment by robertsLando** [comment]
> I can confirm that my switches don't seem to have an issue with the payload_off and payload_on values not being in quotes

@raetha Thanks for the feedback!

> So it isn't clear to me why HA has a different standard with the lock state values in the discovery json, only that it was consistent for my lock.

Welcome to my world 😆 

> I work in IT at a hospital and things are a little crazy right now

I'm sorry for this, I live in Italy so I know that feel...

> I'm happy to help test things

Please join the slack channel so :) https://join.slack.com/t/zwave2mqtt/shared_invite/enQtNjc4NjgyNjc3NDI2LTc3OGQzYmJlZDIzZTJhMzUzZWQ3M2Q3NThmMjY5MGY1MTc4NjFiOWZhZWE5YjNmNGE0OWRjZjJiMjliZGQyYmU

**Comment by tvories** [comment]
3.0.3 fixed this for me!  Thanks for pushing it to the docker hub!
