### ISSUE TITLE
incorrect array JSON structure in API response

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#295]
Hi,

First of all - thanks for adding the getNodes API call!

In parsing the response I ran into an issue where the 'values' property of each node isn't structured like a proper JSON array, i.e. in square brackets, but rather as following:
`"productid": "0x005a",
    "type": "Static PC Controller",
    "values": {
      "112-1-81": {
        "value_id": "1-112-1-81",
        "node_id": 1,
        "class_id": 112, ... etc`

(sorry it insists on formatting it onto a single line)

Regards,
Elco

**Comment by robertsLando** [comment]
@elcosmelco No errors here, this is how I store them in the server to quick find them

**Comment by elcosmelco** [comment]
Ah my mistake - I thought it was an array but it is a dictionary - thanks!
