### ISSUE TITLE
Is there any way to get the HomeId ?

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#297]
Is there any way to request the HomeId via the api calls or otherwise?
I'm also after the OZW version if possible?
I could not find any references to this in the help.

Cheers,
Elco

**Comment by robertsLando** [comment]
@elcosmelco Actually there is no API for that, but I can add it!

**Comment by robertsLando** [comment]
@elcosmelco DONE

**Comment by elcosmelco** [comment]
Much appreciated - Thanks!
