### ISSUE TITLE
[bug] missing HASS sensors on thermostat device

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#298]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: docker 3.0.1
Openzwave Version: docker 3.0.1

**Describe the bug**
I added my thermostat to `customeDevices.js`:
```
module.exports = {
    '152-256-8194': [{ // CT32 Thermostat (2GIG Technologies)
        type: 'climate',
        object_id: 'thermostat',
        values: ['64-1-0', '49-1-1', '67-1-1', '67-1-2', '66-1-0', '69-1-0'],
        mode_map: { 'off': 'Off', 'heat': 'Heat', 'cool': 'Cool' },
        fan_mode_map: { 'auto': 'Auto Low', 'on': 'On Low'},
        setpoint_topic: { 'Heat': '67-1-1', 'Cool': '67-1-2' },
        default_setpoint: '67-1-1',
        discovery_payload: {
            min_temp: 50,
            max_temp: 85,
            modes: ['off', 'heat', 'cool'],
            fan_modes: ['auto', 'on'],
            action_topic: '66-1-0',
            action_template: '{{ value_json.value }}',
            current_temperature_topic: '49-1-1',
            current_temperature_template: '{{ value_json.value }}',
            fan_mode_state_topic: '69-1-0',
            fan_mode_command_topic: true,
            mode_state_topic: '64-1-0',
            mode_command_topic: true,
            temperature_state_template: '{{ value_json.value }}',
            temperature_command_topic: true,
        }
    }]
}
```
So now I only get the following hass devices:
- climate_thermostat
- sensor_battery_level
- sensor_humidity_air

The temperature sensor, along with other sensors, are now missing.
![Screen Shot 2020-03-04 at 5 11 39 PM](https://user-images.githubusercontent.com/732659/75938449-9ccdc080-5e3c-11ea-9a4a-9b0c690fbb25.png)

**To Reproduce**

**Expected behavior**
All sensors/devices should show up, in addition to the ones defined in the customDevices.js. Defining devices in the customDevices.js should either create new ones or replace existing ones, but not remove/delete existing ones.

**Additional context**

**Comment by robertsLando** [comment]
@chilicheech They are not missing, they are in the thermostat device :) Each valueid can only be discovered in 1 device

**Comment by chilicheech** [comment]
It would be nice to change this so that each value id gets discovered, and then in addition to that the custom devices get discovered. This would allow thermostats to be discovered in addition to the individual sensors.

**Comment by robertsLando** [comment]
that would need some thoughts, if you check the code you will see that this.discovered is a map topic->valueid, it should be changed to be an array, then I also don’t know why someone would need this

Daniel
