### ISSUE TITLE
Device DB not working 

### ISSUE THREAD

**Issue by christianwaite** [OpenZWave/Zwave2Mqtt#30]
I’d love to move over to this, but if I start afresh, it doesn’t pull any device information (docker). I’ve tried pulling over the folder structure of the device db and pointing at that, but everything is unrecognised.

If I feed it an existing zwcfg from hass, it works.

Am I doing something wrong?

**Comment by robertsLando** [comment]
Is there any error in logs? Could you try to ssh inside the docker container and check if the device db has the configuration files of your devices? 

Device db is `/usr/local/etc/openzwave/` here you will find all xml config files separated inside folders with the manufacturer name.

**Comment by christianwaite** [comment]
Thanks. I’ll strive to do this asap and get back to you. Free time is not readily available.

**Comment by robertsLando** [comment]
@christianwaite any updates on this?
