### ISSUE TITLE
Include node ID in response to API call requesting data from a node

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#301]
Currently when making API calls it will return the data without any information about the source node it was requested for.
For instance calling `getNodeNeighbors` will return a list but it might be difficult to figure out which node this is for. 

Perhaps an extra property in the result or something would be helpful here.

Cheers,
Elco

**Comment by robertsLando** [comment]
@elcosmelco You right, will add args to response

**Comment by robertsLando** [comment]
@elcosmelco Done
