### ISSUE TITLE
[question] Regression with Aeotect HEM (ZW095) ?

### ISSUE THREAD

**Issue by jyvern** [OpenZWave/Zwave2Mqtt#306]
I've an Aeotec HEM (1 phase). When I try to reset de total kWh counter, it fails with the last versions of zwave2mqtt (v3.0.1) when using this command : 
> -t "zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-broker/api/setValue/set" -m "{ \"args\": [6, 50, 1, 33, true] }"

and it works with the HA zwave2mqtt add-on (v2.0.6).
Is there a regression ? 
Best regards
JYV

**Comment by robertsLando** [comment]
@jyvern Why are you using mqtt apis for setvalue? Anyway do you get any error on console log?

**Comment by jyvern** [comment]
@robertsLando Because I mainly use Node-Red for the orchestration of my domotic. In this context, I use MQTT between every dongle (zwave, rfp1000, zigbee, rtl_433) and node-red. I give HA just a try for the moment. I've no logs but will truy to grab them.

**Comment by robertsLando** [comment]
@jyvern My question is because you should use `/set` instead of call the apis, it would be much clear :) 

Check docs: https://github.com/OpenZWave/Zwave2Mqtt#set-values

**Comment by jyvern** [comment]
I've tried but it fails too. It 's not surprising as this parameter is marked as read-only in the zwave2mqtt dashboard. 
`zwave2mqtt/hem/50/1/0 {"value_id":"6-50-1-0","node_id":6,"class_id":50,"type":"decimal","genre":"user","instance":1,"index":0,"label":"Electric - kWh","units":"kWh","help":"",**"read_only":true**,"write_only":false,"min":0,"max":0,"is_polled":false,"value":54.269,"lastUpdate":1583768492102}`

**Comment by robertsLando** [comment]
Aaaah, if it is read only, it cannot be write :)

**Comment by jyvern** [comment]
Yeahhh ! ;-) But could you explain why I've been able to reset it with HA and OZW 1.4 with zwave2mqtt 2.0.6 and now I can't ?

**Comment by robertsLando** [comment]
Find your config [here](https://github.com/OpenZWave/open-zwave/tree/master/config/aeotec), there could be an update that has made that value read only for some reason. @Fishwaldo

**Comment by robertsLando** [comment]
If your device is this one: https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/dsb09104.xml

YOu should use 6-112-1-100 to reset the counter

**Comment by Fishwaldo** [comment]
Reset is index 257. It’s a button.

**Comment by jyvern** [comment]
> Could your device be this one: https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/dsb09104.xml

No, it's actually a ZW095-C. I would like to help to diagnose this ... "regression ?" but I don't how to and where to start !

**Comment by robertsLando** [comment]
@jyvern Did you check @Fishwaldo comment, is it working now?

> Reset is index 257. It’s a button.

**Comment by jyvern** [comment]
I was thinking that's it's a joke. Isn't it ? Reset to factory default is not what I want to do.

**Comment by jyvern** [comment]
Succeed !!!
The API call "zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-broker /api/setValue/set" -m "{ "args": [6, 50, 1, 257, true] }" will reset the counter. 
@Fishwaldo Many thanks to you to pointed this button to me (I think first it was a joke, shame on me !)
