### ISSUE TITLE
additional option to set Value 

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#308]
Hi,

I would like to suggest an additional way to set a value other than posting a `/set` in the existing topic, or using the API `setValue` function, which requires the `ValueId` which I don't think we have at that point. It could be a custom setValue that takes `NodeId, CommandClassId, Index, Instance` and `Value` as arguments sidestepping the need for a ValueId object.

Hope this makes sense!

Cheers,
Elco

**Comment by robertsLando** [comment]
I can't find a reason why this should be implemented, anyway for your information `setValue` api can be called both using `(valueId, value)` and `(nodeid, comclass, index, instance, value)`

**Comment by elcosmelco** [comment]
ah it seems  I didn't look through the overloaded functions carefully enough! thanks!
