### ISSUE TITLE
Remove dead (and removed) nodes?

### ISSUE THREAD

**Issue by sarkyscouser** [OpenZWave/Zwave2Mqtt#309]
Is it possible to remove dead nodes?

I have a dead node that wouldn't remove itself via "remove node" so I factory reset the sensor and re-paired it leaving a dead node.

There are also several removed nodes visible when toggling "show hidden nodes" - is it possible to remove these as well?

According to the documentation there should be a "Remove Failed Node" option somewhere but it's not in the dropdown and I can't see it anywhere else.

**Comment by robertsLando** [comment]
@sarkyscouser You can only remove failed nodes. If a node is dead you should try to call removeFailed node against it. Once a node is marked failed you can replace it with a new one but you cannot "rearrange" nodeId of devices

**Comment by broyuken** [comment]
This doesn't really answer the question. I have a node that is marked as dead, but I cannot figure out how to remove failed node. Is it a command I have to run on the cli or is it an option in the gui somewhere? If it is, I'm not seeing it.

**Comment by sarkyscouser** [comment]
Thanks but can you provide more detail please. I’m not bothered about nodeIDs but how do we “call removeFailed node against it”?

**Comment by robertsLando** [comment]
@sarkyscouser There are details for everything in README.md. Lot users post questions that already have an answer in it but it seems many prefer to ask than read the docs. Anyway to explain better my question:

Once a device is included in the network it get an id that is incremental and is assigned from the controller. So the first device usually has nodeId 2, the second 3 and so on.  If you remove a device it will be marked as removed, you cannot do anything with it, you can just call an api to mark it as failed (has Node failed) and than call replace failed node to add a node in place of that. If a node is dead and you cannot manually remove it (exclude the device) you can do the same as described above, mark that as failed and replace it with another node. That's it
