### ISSUE TITLE
Container won't start for the second time

### ISSUE THREAD

**Issue by frankhommers** [OpenZWave/Zwave2Mqtt#31]
When I run `sudo docker run --rm -it -p 8091:8091 --device=/dev/ttyAMA0 -v /var/lib/zwave2mqtt:/usr/src/app/store robertslando/zwave2mqtt:latest`, configure everything and press CTRL-C.

It won't start the second time with this error message:

```
fs.js:1061
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'zwcfg_0xf5a134ce.xml'
    at Object.fs.unlinkSync (fs.js:1061:18)
    at fs.readdir.files.forEach.file (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at Array.forEach (<anonymous>)
    at fs.readdir (/snapshot/Zwave2Mqtt/lib/ZwaveClient.js:0:0)
    at FSReqWrap.oncomplete (fs.js:135:15)
pi@zigzag:~ $ sudo docker run --rm -it -p 8091:8091 --device=/dev/ttyAMA0 -v /var/lib/zwave2mqtt:/usr/src/app/store robertslando/zwave2mqtt:latest
```

Any idea?

**Comment by robertsLando** [comment]
The error is thrown here: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L192

I forgot to parse the entire file path, will fix this asap. Thanks!

**Comment by robertsLando** [comment]
@frankhommers If you want to prevent the crash just enable the flag `Save configuration` under Zwave settings

**Comment by frankhommers** [comment]
The Save config toggle works! Thanks ;-)
