### ISSUE TITLE
[feat]Add Docker support for linux/arm64/v8

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#311]
I try to get zwave2mqtt with docker on an Orange Pi 3. I use
robertslando/zwave2mqtt:latest

OPi3 responds

`Pulling zwave2mqtt (robertslando/zwave2mqtt:latest)...
latest: Pulling from robertslando/zwave2mqtt
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
`

**Comment by magpern** [comment]
I also tried 

`Pulling zwave2mqtt (robertslando/zwave2mqtt:arm64v8-latest)...
ERROR: manifest for robertslando/zwave2mqtt:arm64v8-latest not found: manifest unknown: manifest unknown
`

**Comment by magpern** [comment]
Duplicate of #
https://github.com/robertsLando/Zwave2Mqtt-docker/issues/15

**Comment by robertsLando** [comment]
Did you tried also `robertslando/zwave2mqtt:arm64v8-3.0.1`?

**Comment by magpern** [comment]
@robertsLando yes I tried that and it works fine!(saw it after I created this ticket). But I would rather, if possible, be able to just use latest to always get updates, if any

**Comment by robertsLando** [comment]
@magpern I think that is just a metter of a little fix in the build script, I sincerly don't know what I should add as variant to make it match your arch, could you dig into this?
