### ISSUE TITLE
[question] How to control nodes with one command?

### ISSUE THREAD

**Issue by prisikarm** [OpenZWave/Zwave2Mqtt#312]
Hello,
I have multiple z-wave radiator valves in one room. I would like to group them in order to set the temperature for the whole room by one command. Is it possible to do that in Zwave2mqtt?

Best regards,
Mike

**Comment by robertsLando** [comment]
@prisikarm If they have associatons group for this, yes you can. Or you could use broadcasts commands but they will affect all devices of that type

**Comment by prisikarm** [comment]
I am trying to create a Group, but the Current Associations field is empty, and I can only select one group called Group 1. I cannot save the group.

I am using Eurotonic Z-Wave Spirit radiator thermostats.

Is it possible that in future versions, Broadcast could be used for Locations?

**Comment by robertsLando** [comment]
> Is it possible that in future versions, Broadcast could be used for Locations?

Maybe, yes.

> I am trying to create a Group, but the Current Associations field is empty, and I can only select one group called Group 1. I cannot save the group.

It depends on the groups supported by your devices

**Comment by Dinth** [comment]
> @prisikarm If they have associatons group for this, yes you can. Or you could use broadcasts commands but they will affect all devices of that type

Another solution would be a simple shell script which would issue mosquitto_pub commands controlling all the devices through Z2M.
