### ISSUE TITLE
[bug] Removed Nodes show as Alive

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#315]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6.1061

**Describe the bug**
Removing a Node leaves a node present in the UI:
```
Unknown: type=0000, id=0000 (Unknown: id=0000)
```
However the node reports as `Alive` when clearly it isnt.

Can we have a look at how to handle Dead nodes as well while we are at it. 

**To Reproduce**
1. Exclude Node
2. Complete exclusion
3. Srefresh Web UI

**Expected behavior**
Removed node should no longer be present.

**Additional context**
This has happened a few times, but latest was with a lock.

**Comment by robertsLando** [comment]
Could you add a screenshot?

**Comment by jaburges** [comment]
![image](https://user-images.githubusercontent.com/14154875/77074987-e4ad2580-69ae-11ea-8d45-52bd23ce10ed.jpeg)

**Comment by robertsLando** [comment]
That's really strange. I will try to debug this

**Comment by jaburges** [comment]
![image](https://user-images.githubusercontent.com/14154875/77094146-4c706a00-69c9-11ea-8c51-e4738ef431d3.png)

**Comment by jaburges** [comment]
sorry a little small, but another example above

**Comment by robertsLando** [comment]
@jaburges I can't reproduce your issue. I have rmoved my node and added it back without any problem, I mean I dind't see such things appear in my devices table in control panel

**Comment by robertsLando** [comment]
@jaburges Just for info, I see you are having many issues with your devices, could you give me more info about the hardware you are using? I mean where did you install Z2M ? are you using an usb stick or what else?

**Comment by jaburges** [comment]
I have resolved most the issues except for the Kwikset locks reporting their manual lock/unlock state.

I’m using gen5 aeotec “z-stick” on an intel NUC. ESXi 6.5 on the bare metal, and then an Ubuntu server running HA, Z2M, mosquito dockers

**Comment by Fishwaldo** [comment]
Does that node appear in OZW_Log.txt? If so - then it wasn't removed properly from the stick for whatever reason.
