### ISSUE TITLE
[feat] Sleeping nodes - time last seen awake

### ISSUE THREAD

**Issue by Dinth** [OpenZWave/Zwave2Mqtt#319]
**Describe the solution you'd like**
Having a "Last seen awake" information for nodes which are sleeping in control panel would greatly help troubleshooting issues with failed nodes, dead batteries, etc. It could potentially be even shared through MQTT, but just having it in control panel would be great help. 

**Additional context**
It could look like that:
![Screenshot 2020-03-20 at 14 42 57](https://user-images.githubusercontent.com/313674/77174565-288c5180-6ab9-11ea-8ddf-55309f365d71.png)

**Comment by robertsLando** [comment]
Yes it could be done easily. Could I add a general 'lastActive' field that keeps track of both 'alive' and 'awake' events?

**Comment by robertsLando** [comment]
Actually I have made it like this:

```js
    case 3: // awake
    case 4: // sleep
    case 5: // dead
    case 6: // alive
      msg = 'node' + nodeid + ': node ' + NODE_STATUS[notif]

      let ready = notif !== 5
      let wasReady = ozwnode.ready

      if (ready || (!ready && wasReady)) {
        ozwnode.lastActive = Date.now()
      }
```

![Schermata da 2020-03-20 16-15-33](https://user-images.githubusercontent.com/11502495/77177599-1533b300-6ac6-11ea-8930-03ebf419f2ef.png)

**Comment by Dinth** [comment]
Looks perfect for me

**Comment by robertsLando** [comment]
Done

**Comment by Dinth** [comment]
@robertsLando thanks! Keep yourself safe in those hard times!

**Comment by Fishwaldo** [comment]
Just FYI - This information was already exposed by OZW (see the node statistics). There will be cases where OZW talks to a Node (Say a sleeping node that wakes up with no queued messages for it) that results in no state changes that a Application would see.
