### ISSUE TITLE
[feat]MQTT Payload addition - for Better telegraf/influxdb support

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#320]
Currently a payload is looking like:

```
{
  "value_id": "52-32-1-0",
  "node_id": 52,
  "class_id": 32,
  "type": "byte",
  "genre": "basic",
  "instance": 1,
  "index": 0,
  "label": "Basic",
  "units": "",
  "help": "Basic status of the node",
  "read_only": false,
  "write_only": false,
  "min": 0,
  "max": 255,
  "is_polled": false,
  "value": 0,
  "lastUpdate": 1584636017962
}
```

Telegraf supports parsing json payload to influxdb. this way I can directly make graphs and get info using mqtt's consumer.. 
Having the posibility to push measurements using the class_id  is the best approach. Because Class_id is int/float this is not possible for telegraf.
Another way would be to also translate class_id to class name! (Sensor_binary etc...)

I also saw there is a list of class_names already in the z2m.

I want to add this class_name in this payload. but I do not know how, if this was added, then telegraf can push this measurements, and been able to make metrics on top of this would make the experience. from AWESOME to SUPER DUPER!

**Comment by robertsLando** [comment]
So you would like something like this: 

```js
{
  "value_id": "52-32-1-0",
  "node_id": 52,
  "class_id": 32,
   "className": "ClassNameHere", // <----- this 
  "type": "byte",
  "genre": "basic",
  "instance": 1,
  "index": 0,
  "label": "Basic",
  "units": "",
  "help": "Basic status of the node",
  "read_only": false,
  "write_only": false,
  "min": 0,
  "max": 255,
  "is_polled": false,
  "value": 0,
  "lastUpdate": 1584636017962
}
```

**Comment by billiaz** [comment]
or class_name to keep it sane!

**Comment by billiaz** [comment]
@robertsLando can you point me, where I would be able to add this? :) 
I could also keep a fork for myself.

**Comment by robertsLando** [comment]
add [here](https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L227)

```js
data.class_name = Constants.commandClass(valueId.class_id)
```

**Comment by billiaz** [comment]
trying it. If this works, want me to pull request this on the mail project or not?

**Comment by robertsLando** [comment]
Nope, If I add this I need to add a dedicated option in the UI :)

**Comment by billiaz** [comment]
thanks! :)

**Comment by robertsLando** [comment]
@billiaz You welcome! let me know if it's working!
