### ISSUE TITLE
[question] blinds control / keep existint nodes

### ISSUE THREAD

**Issue by rflx18** [OpenZWave/Zwave2Mqtt#322]
hi, does the zwave2mqtt work with zwave mesh? i have fibaro and philios zwave blinds box, does zwave2mqtt fully work with them? also since they are already paired with the usb zwave stick does they still stay connected even if i change from homeassistant to zwave2mqtt?

**Comment by robertsLando** [comment]
> does the zwave2mqtt work with zwave mesh

What? I don't understand what you mean. It supports all zwave features

> also since they are already paired with the usb zwave stick does they still stay connected even if i change from homeassistant to zwave2mqtt

Yes, but you should refresh node info if you are moving from an older openwave version like 1.4

**Comment by rflx18** [comment]
i misspell, i was asking for zwave2mqtt blinds.
also im facing issues installing in raspberry pi 3 :S

**Comment by robertsLando** [comment]
What about blinds?

What errors?

**Comment by rflx18** [comment]
im stuck installing either openzwave and zwave2mqtt, both are confusing or it just me, 
im using rasperry pi 3 and already have nodejs installed for zigbee2mqtt.

[https://imgur.com/a/Kkch4GG](url)

**Comment by robertsLando** [comment]
Use docker way

**Comment by rflx18** [comment]
thats the all point, using the raspeberry pi so i can hide the qnap out of site

**Comment by rflx18** [comment]
installed docker in the raspberry, and started, but no nodes are showing, any guess?

**Comment by rflx18** [comment]
managed to go trought everything and homeassistant already detecting, the major issue is that the blinds/covers are detected as switch and i dont have the hability to close or open them. 2 bad :(
