### ISSUE TITLE
[bug] issue with 3.0.2 version

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#328]
upgrading to 3.0.2 I get some errors on OpenZwave side.
I do nto knwo if this is a library issues (which I suspect) or something else on the system

```
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:08:31.077 Info, Node065, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.18
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:08:31.077 Warning, Node065, Can't Find a ValueID Index for Electric - kWh (1) with Unit kWh (0) - Index 0
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:08:31.077 Warning, Node065, MultiChannel Encap CommandClass COMMAND_CLASS_METER HandleMsg returned false
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.076 Detail, Node065,   Received: 0x01, 0x14, 0x00, 0x04, 0x00, 0x41, 0x0e, 0x60, 0x0d, 0x02, 0x01, 0x32, 0x02, 0x21, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x9b
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.076 Detail,
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.076 Info, Node065, Received a MultiChannelEncap from node 65, endpoint 2 for Command Class COMMAND_CLASS_METER
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.076 Info, Node065, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.00
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.077 Warning, Node065, Can't Find a ValueID Index for Electric - kWh (1) with Unit kWh (0) - Index 0
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:02.077 Warning, Node065, MultiChannel Encap CommandClass COMMAND_CLASS_METER HandleMsg returned false
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.808 Detail, Node043,   Received: 0x01, 0x10, 0x00, 0x04, 0x00, 0x2b, 0x0a, 0x32, 0x02, 0x21, 0x44, 0x00, 0x00, 0x00, 0x1e, 0x00, 0x00, 0x81
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.808 Detail,
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.809 Info, Node043, Received Meter Report for Electric - kWh (1) with Units kWh (0) on Index 0: 0.30
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.809 Detail, Node043, Refreshed Value: old value=0.30, new value=0.30, type=decimal
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.809 Detail, Node043, Changes to this value are not verified
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.809 Detail, Node043, Refreshed Value: old value=false, new value=false, type=bool
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.809 Detail, Node043, Changes to this value are not verified
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.810 Detail, Node043, Notification: ValueChanged CC: COMMAND_CLASS_METER Instance: 1 Index: 0
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:09:46.810 Detail, Node043, Notification: ValueChanged CC: COMMAND_CLASS_METER Instance: 1 Index: 256
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25T14:09:46.811Z z2m:Zwave zwave node 43: changed: 50-1-0:Electric - kWh:0.3 -> 0.3
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25T14:09:46.812Z z2m:Zwave zwave node 43: changed: 50-1-256:Exporting:false -> false
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.278 Detail, Node063,   Received: 0x01, 0x12, 0x00, 0x04, 0x00, 0x3f, 0x0c, 0x60, 0x0d, 0x01, 0x01, 0x32, 0x02, 0x21, 0x32, 0x00, 0x00, 0x00, 0x00, 0x94
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.278 Detail,
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.278 Info, Node063, Received a MultiChannelEncap from node 63, endpoint 1 for Command Class COMMAND_CLASS_METER
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.279 Info, Node063, Received Meter Report for Electric - W (1) with Units W (2) on Index 2: 0.0
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.279 Warning, Node063, Can't Find a ValueID Index for Electric - W (1) with Unit W (2) - Index 2
zwave2mqtt-665dbd9c84-k8996 z2m 2020-03-25 14:10:53.279 Warning, Node063, MultiChannel Encap CommandClass COMMAND_CLASS_METER HandleMsg returned false
```

**Comment by robertsLando** [comment]
@billiaz Maybe @Fishwaldo has added some more verbose log in latest OZW? Let's see what he say about this

**Comment by Fishwaldo** [comment]
Has the interview for those devices completed (querystage_Complete?). If not that the reason. 

If it has, try RefreshNodeInfo

On 25 Mar 2020, at 10:16 PM, Daniel Lando <notifications@github.com> wrote:

﻿


@billiaz Maybe @Fishwaldo has added some more verbose log in latest OZW? Let's see what he say about this

**Comment by billiaz** [comment]
I performed twice the refreshnodeinfo on different nodes, and still getting this.
would querystage_Complete give a message in the end of the refresh?

**Comment by billiaz** [comment]
@Fishwaldo when the library is restarted, it never finishes the whole refresh node info.

With or without the ozwcache in the system

I have 18 devices in the network, with AEOTEC usb stick (gen 5).
I have TRVs from eurotronics, which work almost like mains devices.
And 4 only battery devices (except eurotronics).

If the driver restarts, I have to manually go through all devices and perform refresh node info (one at a time).

this was not happening in previous driver version. any ideas?

**Comment by billiaz** [comment]
I can confirm, this seems to be an issue after the latest release. 
When library starts with or without ozwcache file. random devices fail to interview. And at that point I need to interview one by one. to be sure everything works.

Tested Lib from commits: 14f2ba743ff5ce893f652cad3a86968e26f8ea10 and 55770df17be4f0196d2a64785369be91eeeb4479

**Comment by robertsLando** [comment]
@billiaz Could youb try to make a new custom docker version using a previous version of ozw to see if that is working?

**Comment by thecem** [comment]
[20200616 18:49:03.276 CEST] [ozw.library] [warning]: Warning - Node: 34 Can't Find a ValueID Index for Electric - kWh (1) with Unit kWh (0) - Index 0

Belongs to the same: [https://github.com/OpenZWave/open-zwave/issues/2054](url)
and [https://community.home-assistant.io/t/z-wave-command-class-meter-no-distinction-between-import-and-export/157916/21](url)

There is no diffrent ValueID for importing and exporting energy as required in the standard:

Following silabs Z-Wave Application Command Class Specification the values send from qubino device are correct:

0x32 ID 50 Command Class Meter
0x02 Command Meter_Report
_____Scale2(1)__Rate Type(2)__Meter Type (5)
0x41 0_________10___________00001
_______________Export_______Electric meter
**_or_**
0x21 0_________01___________00001
_______________Import________Electric meter

_____Precision(3)_Scale1(2)___Size
0x24 001_______00__________100
_______________kwh

I hope the new OZW implemtation will take care about this BUG.

**Comment by thecem** [comment]
@billiaz: is it a Qubino 3 Phase Smart meter or 1 Phase ?

**Comment by Fishwaldo** [comment]
>I hope the new OZW implementation will take care about this BUG.

There is no Bug - You have a "exporting" valueID that tells you if the current reading is a import or export value.

**Comment by thecem** [comment]
![grafik](https://user-images.githubusercontent.com/46648579/84809828-cb962e00-b00a-11ea-8844-556064a5fb75.png)
You see the qubino smart meter single phase exporting energy (to grid).

So the exporting should have a check?

**Comment by thecem** [comment]
If the "exporting" valueID that tells the current reading is a import or export value is exporting, then there is check in box?
Will it be send even via MQTT?
I couldn't see there is a difference in MQTT to HA eccept the electric (kwh) value is sometimes the export value and sometime the import value and no additional exporting value...
