### ISSUE TITLE
[Question] fgk-101 as doorbell not populating correctly

### ISSUE THREAD

**Issue by pbathuk** [OpenZWave/Zwave2Mqtt#33]
Hi,

I have recently moved over from HA zwave as I found that the constant reboots were messing up the network, one thing that I am missing however the ability to trip a fgk-101 device with a doorbell (found an article online) under HA it would change the status of the device from on to off and back again (about 10 times in a row), which I could then attach automation to trigger alerts etc..
Under zwave2mqtt I see that it nothing changes on the MQTT or zwave (webpage), however if I debug I see :
<code>
z2m:Zwave node event 15 0 +315ms
OpenZWave Detail, Node015, Received: 0x01, 0x09, 0x00, 0x04, 0x00, 0x0f, 0x03, 0x20, 0x01, 0x00, 0xdf

OpenZWave Detail, 
OpenZWave Info, Node015, Received Basic set from node 15: level=0. Sending event notification.
OpenZWave Detail, Node015, Notification: NodeEvent

z2m:Zwave node event 15 255 +179ms
OpenZWave Detail, Node015, Received: 0x01, 0x09, 0x00, 0x04, 0x00, 0x0f, 0x03, 0x20, 0x01, 0xff, 0x20
OpenZWave Detail,

OpenZWave Info, Node015, Received Basic set from node 15: level=255. Sending event notification.

OpenZWave Detail, Node015, Notification: NodeEvent
</code>

So the zwave info it being sent and the level set from off to on when the doorbell goes.
My question is: what is the easiest / best way (might be two different options) to map this change either into MQTT or as a websocket / command to node-red?

Cheers

**Comment by robertsLando** [comment]
Which version of openzwave are you using?

**Comment by pbathuk** [comment]
Just looked at the logs from the docker and it says 1.4.1

**Comment by pbathuk** [comment]
I see that openzwave outside the docker build is on 1.6, should I be upgrading the docker manually or does it get rebuilt with key versions automatically? 
Thanks

**Comment by robertsLando** [comment]
Openzwave 1.6 is not ready yet, well, node-openzwave-shared needs updates that is the wrapper I use for my project
