### ISSUE TITLE
[feat] health page - Modern infra (kubernetes)

### ISSUE THREAD

**Issue by billiaz** [OpenZWave/Zwave2Mqtt#330]
More and more people are working on kubernetes and other similar technologies. It has become common practice to have a "dummy" or real Endpoint which will return the health status of your application.

once this endpoint is available, the underlying orchestration considers the service ready to work. 

I would like to suggest implementing an empty or just Health page with endpoint "/healthz"
this way we can use this endpoint for our orchestration healthchecks.

Why '/healthz'?
- Stackoverflow - nice explanation: https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-f
- Kubernetes documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
- Some more bits from another project discussion https://github.com/jupyterhub/jupyterhub/issues/2532

**Comment by robertsLando** [comment]
https://github.com/OpenZWave/Zwave2Mqtt#healt-check-endpoints
