### ISSUE TITLE
[question] Are there any issues with the ZME_UZB1 USB Stick (Z-Wave.Me)

### ISSUE THREAD

**Issue by errolsancaktar** [OpenZWave/Zwave2Mqtt#332]
I've been having a terrible time trying to get my network reliable.  I originally had the linear controller and ran into some issues trying to repair some devices so i went with the UZB stick since it has zwave+.  i did a complete reset of the network and now devices come up dead randomly, door sensors like the HANK-DWS01  will not pair correctly or stay paired after a reboot.  Here are my settings if this helps anything:
![image](https://user-images.githubusercontent.com/60162646/77838764-fd96a300-7133-11ea-9548-d7c6739327c0.png)
![image](https://user-images.githubusercontent.com/60162646/77838766-07200b00-7134-11ea-99fe-0bc1fd236dde.png)
![image](https://user-images.githubusercontent.com/60162646/77838768-0f784600-7134-11ea-84c3-76e1b247bc6d.png)
![image](https://user-images.githubusercontent.com/60162646/77838771-156e2700-7134-11ea-85f8-91034b514560.png)
![image](https://user-images.githubusercontent.com/60162646/77838779-20c15280-7134-11ea-9737-c5ca1e1cd090.png)

as you can see node 19 finally paired but unless its right next to the zwave controller it does not report anything back.  i'm pulling my hair out at this point.  I removed all configurations and started with a fresh docker/data directory.

**Comment by robertsLando** [comment]
Nope AFAIK. @Fishwaldo Do you know?

**Comment by Botched1** [comment]
That's the same USB stick I use. No issues as far as I can tell - has been perfectly stable for me.

**Comment by Fishwaldo** [comment]
The only sticks that have issues are ones based on the new 700 Series Chips. They will work in the Dev branch (upcoming 1.7 release)
