### ISSUE TITLE
Best way to see if gateway is still responsive / alive 

### ISSUE THREAD

**Issue by elcosmelco** [OpenZWave/Zwave2Mqtt#333]
I would like to know if there is something like a heartbeat or query-able status topic I can listen to, to see the whether the service is still alive. I can of course query a random API call but I was wondering whether there is something more  appropriate, such as the status topic.

Cheers,
Elco

**Comment by robertsLando** [comment]
Did you checked: https://github.com/OpenZWave/Zwave2Mqtt#healt-check-endpoints

**Comment by elcosmelco** [comment]
I did notice that one - I was just hoping for something purely Mqtt - maybe even with some extra information, like uptime, time since last ZWave activity, driver status etc.

**Comment by robertsLando** [comment]
You could enable zwave events in settings (https://github.com/OpenZWave/Zwave2Mqtt#zwave-events) or use `getNodes` api via MQTT (https://github.com/OpenZWave/Zwave2Mqtt#custom-apis)

**Comment by elcosmelco** [comment]
I've already enabled the events but they are only triggered by the driver correct? Calling `getNodes` on large networks periodically will generate too much unnecessary traffic - what I'll do is call `getInfo` which is a minimal amount of data. Maybe adding some additional info to that would make sense?

**Comment by robertsLando** [comment]
Could you list the properties that you would like to be added to getInfo api (with also a description)? There is no problem for me to add them

**Comment by elcosmelco** [comment]
Ah great!

`uptime` - time since the start of the service
`lastUpdate` - time since the last OZW activity
`zwaveStatus` - intialization status of OZW

The latter 2 because your service and my app can restart independent of each other and if I restart my software say halfway during initialization of OZW I can still get a general idea of its state because any `EVENT` message might still take a while.

Thanks!
Elco

**Comment by robertsLando** [comment]
I have added this parameters to Zwave `getStatus` api:

```js
status.uptime = process.uptime()
status.lastUpdate = this.lastUpdate
status.description = this.status
```

Where description could be 

```
 'driverReady',
 'connected',
 'scanDone',
 'driverFailed',
 'closed'
```

**Comment by robertsLando** [comment]
@elcosmelco Check out latest commit
