### ISSUE TITLE
[bug] Multiple switches created for GE 26931 Smart Motion Switch

### ISSUE THREAD

**Issue by niemyjski** [OpenZWave/Zwave2Mqtt#338]
**Version**

latest master commit

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master
Openzwave Version: 1.6.0

**Describe the bug**
There are multiple switches generated for the 26931 GE zwave devices.
![image](https://user-images.githubusercontent.com/1020579/78153040-44202200-7400-11ea-8ca4-38da62b00eaa.png)

**To Reproduce**
1. Add any `26931 Smart Motion Switch (GE (Jasco Products))` switch

**Expected behavior**

There should be one switch generated.

**Comment by robertsLando** [comment]
> There should be one switch generated.

I don't think so, your device is multi-instance and as you can see the second is on instance 2 so there is no duplication. Please check your device manual

**Comment by niemyjski** [comment]
Why is this switch a multi-instance device? I don't see anywhere in the docs and none of my other ge z-wave devices are generating multiple switches. What is this second instance for? This really feels like a bug.

**Comment by niemyjski** [comment]
The device only has one physical switch, so I'm not sure how multiple switches would work here and that is why I filed this issue it just doesn't make sense to me or others on the forums.

**Comment by robertsLando** [comment]
@niemyjski It is for sure a device bug or a configuration bug, not something related to zwave2mqtt for sure. YOu should open an issue on Openzwave repo reporting this

**Comment by niemyjski** [comment]
Thanks will do!
