### ISSUE TITLE
[feat] Support replacing nodes securely

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#339]
**Is your feature request related to a problem? Please describe.**
If possible, support a secure version of the replaceNode feature just like when issuing an addNode (which prompts for secure/not secure).

**Describe the solution you'd like**
A prompt for replaceNode on secure/not secure.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robertsLando** [comment]
There is already an open PR for this #216 , it don't depends on my but I need to wait for OZW to make it available
