### ISSUE TITLE
Remove failed node

### ISSUE THREAD

**Issue by frankhommers** [OpenZWave/Zwave2Mqtt#34]
I have read https://github.com/OpenZWave/Zwave2Mqtt/issues/4 but I don't think it's enough to just have a replace function.

I think there really needs to be something to remove a failed node... Like this feature in Home Assistant which does it too: https://community.home-assistant.io/t/z-wave-help-dead-nodes/41673/21

What do you think?

**Comment by robertsLando** [comment]
I could try to implement a custom function that automatically tries to detect if a node is failed and than removes it just by adding a call before removeFailed node, what do you think about this?

**Comment by frankhommers** [comment]
That would be nice. I solved my current problem by hardresetting and re-adding everything.

Maybe you can look into this: https://community.home-assistant.io/t/where-is-the-remove-failed-node-option-for-z-wave-devices/89250/3

**Comment by robertsLando** [comment]
@frankhommers  Sorry for the late reply, now the feature requested has been added and will be available in next release. Thanks!
