### ISSUE TITLE
[question] Remove retained MQTT topics on exclusion

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#342]
Hi,

Messing around, I've noticed a lot of topics being left in my MQTT service, whenever I exclude, re-include, change from node-id to named topics etc. At least I've cleaned up a lot of topics.

Is there a feature, missing configuration, or something - that should clean up topics when devices disappear for good?

If not, I'll change this to a feature request :).

Edit: I imagine one of the workarounds is to let Z2M listen to the HASS alive/down messages by which it then republishes all discovery documents - but I feel like the retained message option is the "more correct" way of persisting configuration.

Mike.

**Comment by robertsLando** [comment]
@LordMike I really suggest to use MQTT Explorer for such things, it's lot easier :)

**Comment by LordMike** [comment]
Very well. I will comment though that it would be a user-friendly option to maintain / clean up when possible. I and others can very likely manage evaluating topics (or just remove all and let the system reboot) - but new users may find it hard.. :)

But hey. Now I know of MQTT Explorer. :)

**Comment by robertsLando** [comment]
> I will comment though that it would be a user-friendly option to maintain / clean up when possible

You right but I saw most users are using mqtt explorer
