### ISSUE TITLE
[question] Add validation on the node name?

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#344]
I was just burned by HASS not discovering some of my entities - as I was trying to find differences, I noticed all those not discovered has "." (dots) in their names. [And surely enough.](https://www.home-assistant.io/docs/mqtt/discovery/#configuration-variables)

> The ID of the node must only consist of characters from the character class [a-zA-Z0-9_-] (alphanumerics, underscore and hyphen).

How tightly integrated is Z2M with HASS (it seems like a lot), and if so - would it make sense to add a warning or such, on the name of nodes - so that when running with the "node name instead of node id" option, users are warned of this conflict?

**Comment by robertsLando** [comment]
@LordMike Thanks, fixed!
