### ISSUE TITLE
[bug] Ilumin RGB Bulb Discovery in HA missing features

### ISSUE THREAD

**Issue by SirDeadlystrike** [OpenZWave/Zwave2Mqtt#345]
**Version**

Build/Run method
- [x] Docker (Hass.io Addon)

Zwave2Mqtt version: 3.0.1
Openzwave Version: 1.6.974-r0

**Describe the bug**
Upon including the LZW42 Multi-Color Bulb (Inovelli) Z2M identifies the type as a "Light Dimmer Switch" and the product. 

The device it creates in home assistant is a light_rgb_dimmer.

In home assistant the device only has On/Off features and is missing Dimming, White color, and RGB

**To Reproduce**
1. Update your config files if the device is missing from OZW from the InovelliUSA Github repo
2. Include a  LZW42 Multi-Color Bulb with HASS Discovery on

**Expected behavior**
The bulb should be able to be fully controlled (Color, brightness, white temp, on/off)

**Additional context**
Another use was able to get the features of the bulb working by directly setting the MQTT topics in the configuration file for HA. I was unable to have success with this method. 
Ref: https://community.inovelli.com/t/ilumin-rgb-bulb-with-zwave2mqtt/2740/7

**Comment by robertsLando** [comment]
Try to use version 3.0.2

**Comment by zacs** [comment]
@SirDeadlystrike You can make this work by declaring manually as described here: https://community.inovelli.com/t/rgbw-bulb-in-home-assistant/1235/9 -- worked great for me.
