### ISSUE TITLE
[bug] Device XML issue

### ISSUE THREAD

**Issue by jtonk** [OpenZWave/Zwave2Mqtt#348]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6.1061

**Describe the bug**
parameter config does not show all options from list of the OZW device xml file. for parameter 100 (and 101) it only shows the option 1 to 6, but omitts 0 (disable) and 9 (sensor binary) from the list.

````xml
    <Value genre="config" index="100" instance="1" label="Enable / Disable Endpoints I2 or select Notification Type and Event" max="9" min="0" size="1" type="list" value="1">
      <Help>Enabling I2 means that Endpoint (I2) will be present on UI.
			Disabling it will result in hiding the endpoint according to the parameter set value.
			Additionally, a Notification Type and Event can be selected for the endpoint.
			Endpoint device type selection: notification sensor (1 - 6) sensor binary (9).
			NOTE: After parameter change, module has to be re included into the network in order setting to take effect!
			Default value 1.</Help>
      <Item label="Home Security; Motion Detection, unknown location." value="1"/>
      <Item label="Carbon Monoxide; Carbon Monoxide detected, unknown location." value="2"/>
      <Item label="Carbon Dioxide; Carbon Dioxide detected, unknown location." value="3"/>
      <Item label="Water Alarm; Water Leak detected, unknown location." value="4"/>
      <Item label="Heat Alarm; Overheat detected, unknown location" value="5"/>
      <Item label="Smoke Alarm; Smoke detected, unknown location" value="6"/>
      <Item label="Endpoint, I2 disabled" value="0"/>
      <Item label="Sensor binary" value="9"/>
    </Value>
````

**To Reproduce**
1. Go to 'node configuration' select the parameter 100 (or 101)
2. Click on 'pull down menu'
3. you don't have the options, "Endpoint, I2 disabled" and "Sensor binary"

**Expected behavior**
the options "Endpoint, I2 disabled" and "Sensor binary" should be presented as well.

**Additional context**

**Comment by robertsLando** [comment]
@jtonk Did you checked if those options are present in the ozwcache file? I have no control of the options, I show what I receive from OZW

**Comment by jtonk** [comment]
@robertsLando I assumed it was taken from the OZW 1.6 config folder, but I just double checked and the values 0 and 9 are present in the ozwcache file. Is there a way to send paramters manually? in other words override the pulldown menu

**Comment by robertsLando** [comment]
You can try to directly send the value using mqtt apis, but I think this needs some investigation 

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by jtonk** [comment]
This is so dumb of me. The pulldown shows the first 5 items, but if you scroll on it it show the latter two. Sorry for taking your time...
