### ISSUE TITLE
[question] Cannot add device overrides for some devices

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#349]
Hey,

I wanted to change the device class pushed to HASS for two of my three door / window sensors, but I couldn't do this with the device overrides (where I configure polling). What's the criteria for which devices can be overriden?

Note: I'll override the device class using the HASS document editor .. I (re-)discovered that feature after I found this potential bug. :)

![image](https://user-images.githubusercontent.com/1027111/78675360-3cbbb580-78e5-11ea-8d45-cb6004f7dd6b.png)

I have these three extra sensors, not present in the dropdown above.

![image](https://user-images.githubusercontent.com/1027111/78675380-42b19680-78e5-11ea-8af6-02d89025a946.png)

**Comment by robertsLando** [comment]
Hi Michael, that is not a bug, it’s how the gateway values work, in the readme you will find that in that dropdown are shown all devices types, this means one device for each type that is discovered in your network. This because in 99% of cases each device configuration will be the same for each type in the network and so you can configure one time and apply that to all the devices in your network :)

Daniel

Support me at:
    Github sponsors

**Comment by LordMike** [comment]
I figured it could be something like that (partly as no Node Id's were present).

But I'm still missing the door/window sensor in the list.

**Comment by LordMike** [comment]
The sensors all have the device id `134-112-2`, which as I read it, is the same manufacturer as the USB stick (`134-90-1`) - is the logic filtered to one device type per manufacturer?

**Comment by robertsLando** [comment]
> is the logic filtered to one device type per manufacturer

Nope, it checks the id and if not present it add the device to the devices list. Does this happen also if you restart the application?

**Comment by LordMike** [comment]
Oooh.. It may be that these devices probably haven't reported in since the last reboot of Z2M .. they're battery powered after all. 

They _have_ changed their state, but that might not entail a "ready"?

For these devices, I've also encountered that to apply new settings, I need to press their button - not just open/close the door/window .. possibly a byproduct of it not reporting "read" every time it wakes.

**Comment by robertsLando** [comment]
Yes so thayt is the problem so
