### ISSUE TITLE
Door locks?

### ISSUE THREAD

**Issue by brettyj** [OpenZWave/Zwave2Mqtt#35]
Hi,

Sorry not an issue, but don't see a forum to post questions on - has anyone used zwave2mqtt with doorlocks - specifically the Yale Conexis L1? Thinking about getting one, but don't know if it will work.

Also what USB sticks do you folks use? Will https://www.amazon.co.uk/gp/product/B00YETCNOE/ref=ox_sc_act_title_1?smid=A3P5ROKL5A1OLE&psc=1 work?

**Comment by robertsLando** [comment]
Try asking this kind of questions on [Openzwave](https://github.com/OpenZWave/open-zwave) repo

**Comment by brettyj** [comment]
Hi,

Sorry to be clear, are you saying that anything that works on Openzwave should work on zwave2mqtt? Because I believe people have gotten this to work with the zwave built into home assistant - so should be okay then?

**Comment by robertsLando** [comment]
Yep it should work, this is just a gateway that is using mqtt and opnzwave libs so everything that is related to devices is mostly a problem related to underlying libs
