### ISSUE TITLE
[bug] Aeotec Multisensor 6 and HASS autodiscovery reporting as door/contact sensor

### ISSUE THREAD

**Issue by fiLLLip** [OpenZWave/Zwave2Mqtt#354]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6.1061

**Describe the bug**
Aeotec Multisensor 6 reporting as binary_sensor_contact on Hass autodiscovery making it a door sensor, not motion.

**To Reproduce**
1. Add HASS Autodiscovery
2. Add Aeotec Multisensor 6
3. See device details in HASS
4. See "error"

**Expected behavior**
Should have been reporting as a motion sensor: binary_sensor_occupancy

**Additional information**
The sensor is reporting correctly when there is movement, so it is functionally OK. Updated the device_class to motion manually fixed the visual aspects.

Device is reporting "Sensor (xx-48-1-0)".
![image](https://user-images.githubusercontent.com/1264369/79221677-8b71ce00-7e56-11ea-8ee7-a85bf9c01508.png)
`2020-04-14T11:50:38.457Z z2m:Zwave zwave node 17: changed: 48-1-0:Sensor:false -> true
`

I see this is not matching the label requirements to include `motion`: 
https://github.com/OpenZWave/Zwave2Mqtt/blob/0d44d232ed85778b6eb547071b384b51cdd3a2fc/lib/Gateway.js#L906

Discovery document (after updating device_class):
```
{
  "type": "binary_sensor",
  "object_id": "contact",
  "discovery_payload": {
    "payload_on": true,
    "payload_off": false,
    "value_template": "{{ value_json.value }}",
    "device_class": "motion",
    "state_topic": "zwave/17/48/1/0",
    "json_attributes_topic": "zwave/17/48/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xfa862b6e_node17"
      ],
      "manufacturer": "AEON Labs",
      "model": "ZW100 MultiSensor 6 (0x0064)",
      "name": "Office-Multisensor",
      "sw_version": "Unknown"
    },
    "name": "Office-Multisensor_contact",
    "unique_id": "zwave2mqtt_0xfa862b6e_17-48-1-0"
  },
  "discoveryTopic": "binary_sensor/Office-Multisensor/contact/config",
  "values": [
    "48-1-0"
  ],
  "persistent": false,
  "id": "binary_sensor_contact"
}
```

Is this maybe something that must be changed/is better to fix in the OpenZwave lib?

**Comment by robertsLando** [comment]
@fiLLLip If you just need to chenge the device class you can change it using gateway values table. Simply add a new value to the table, select the device then this value and the device id to use for it and that device class will be used for all devices of that type. Unfortunally I have no way to detect that it is a door contact or something else, ignore the label check

**Comment by fiLLLip** [comment]
Perfect! Thanks :)
