### ISSUE TITLE
[Question] Nodes being removed after scan complete

### ISSUE THREAD

**Issue by PatrickSannes** [OpenZWave/Zwave2Mqtt#356]
If I'm not in the right place to ask these questions, please direct me to the proper location (i could not find it).

I just started to work with zwave2mqtt. My devices are configured on my EAON labs ZW090 gen5 stick (I had them configured in Home Assistant). I have 2 problems:
1: Devices are not recognized by vendor and the device id stays 0-0-0
2: After scan complete, my nodes are being removed and they are all dead again.

Is there a configuration setting that I'm missing?

GET / 304 0.534 ms - -
z2m:App User disconnected fi2jecHjWc6RO78pAAAZ +51s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 0.983 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 1.869 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 0.915 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 1.345 ms - -
z2m:App New connection d99sbLtrFil8oDpPAAAc +184ms
GET /static/logo.png 304 0.571 ms - -
z2m:Zwave Notification from node 7: Notification - TimeOut (1) +10s
OpenZWave Error, Node007, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchMultilevelCmd_Get (Node=7): 0x01, 0x09, 0x00, 0x13, 0x07, 0x02, 0x26, 0x02, 0x25, 0x9d, 0x7c"
GET /static/favicons/favicon-32x32.png 200 0.831 ms - 1831
z2m:Zwave Notification from node 8: Notification - TimeOut (1) +10s
OpenZWave Error, Node008, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchAllCmd_Get (Node=8): 0x01, 0x09, 0x00, 0x13, 0x08, 0x02, 0x27, 0x02, 0x25, 0x97, 0x78"
z2m:Zwave Notification from node 8: Notification - TimeOut (1) +10s
OpenZWave Error, Node008, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=8): 0x01, 0x09, 0x00, 0x13, 0x08, 0x02, 0x25, 0x02, 0x25, 0x9e, 0x73"
GET / 304 0.517 ms - -
z2m:App User disconnected d99sbLtrFil8oDpPAAAc +27s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 0.660 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 0.944 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 1.067 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 1.287 ms - -
z2m:App New connection YDPkJ2-SRl6sMNVLAAAd +186ms
GET /static/logo.png 304 0.531 ms - -
GET /static/favicons/favicon-32x32.png 200 0.791 ms - 1831
OpenZWave Error, Node009, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchAllCmd_Get (Node=9): 0x01, 0x09, 0x00, 0x13, 0x09, 0x02, 0x27, 0x02, 0x25, 0x98, 0x76"
z2m:Zwave Notification from node 9: Notification - TimeOut (1) +10s
GET / 304 0.551 ms - -
z2m:App User disconnected YDPkJ2-SRl6sMNVLAAAd +3s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 1.614 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 2.197 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 2.727 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 3.225 ms - -
z2m:App New connection 2EkD4g95uecMIpK-AAAe +167ms
GET /static/logo.png 304 0.492 ms - -
GET /static/favicons/favicon-32x32.png 200 0.888 ms - 1831
GET /api/settings 200 85.503 ms - 6168
z2m:App Zwave api call: refreshNeighborns [] +2s
z2m:Zwave Success zwave api call refreshNeighborns [
undefined,
[
3, 5, 6, 7, 8,
9, 11, 12, 16, 17
],
undefined,
[
1, 4, 5, 6, 7,
9, 11, 12, 17
],
[ 3, 5, 7, 8, 12 ],
[
1, 3, 4, 6, 7,
8, 9, 12, 17
],
[ 1, 3, 5, 7, 8, 12 ],
[
1, 3, 4, 5, 6,
8, 9, 11, 12, 16,
17
],
[
1, 4, 5, 6,
7, 9, 12, 16
],
[ 1, 3, 5, 7, 8, 12 ],
undefined,
[],
[
1, 3, 4, 5, 6,
7, 8, 9, 16, 17
],
undefined,
undefined,
undefined,
[],
[]
] +3s
z2m:Zwave Notification from node 9: Notification - TimeOut (1) +7s
OpenZWave Error, Node009, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=9): 0x01, 0x09, 0x00, 0x13, 0x09, 0x02, 0x25, 0x02, 0x25, 0x9f, 0x73"
z2m:Zwave Notification from node 12: Notification - TimeOut (1) +10s
OpenZWave Error, Node012, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchAllCmd_Get (Node=12): 0x01, 0x09, 0x00, 0x13, 0x0c, 0x02, 0x27, 0x02, 0x25, 0x99, 0x72"
GET / 304 1.030 ms - -
z2m:App User disconnected 2EkD4g95uecMIpK-AAAe +19s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 1.043 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 0.444 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 0.777 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 0.971 ms - -
z2m:App New connection 9HmCyQImSgT5XJD5AAAf +160ms
GET /static/logo.png 304 0.549 ms - -
GET /static/favicons/favicon-32x32.png 200 0.759 ms - 1831
GET / 304 0.549 ms - -
z2m:App User disconnected 9HmCyQImSgT5XJD5AAAf +2s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 0.538 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 1.329 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 1.425 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 1.473 ms - -
z2m:App New connection LSa12ZhVacMQ_lSfAAAg +159ms
GET /static/logo.png 304 0.485 ms - -
GET /static/favicons/favicon-32x32.png 200 0.836 ms - 1831
z2m:Zwave Notification from node 12: Notification - TimeOut (1) +10s
OpenZWave Error, Node012, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "SwitchBinaryCmd_Get (Node=12): 0x01, 0x09, 0x00, 0x13, 0x0c, 0x02, 0x25, 0x02, 0x25, 0xa0, 0x49"
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 3 ready: - (Multilevel Power Switch) +9ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 4 ready: - (Multilevel Power Switch) +19ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 5 ready: - (Multilevel Power Switch) +20ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 7 ready: - (Multilevel Power Switch) +8ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 8 ready: - (Binary Power Switch) +11ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=0
z2m:Zwave node 9 ready: - (Binary Power Switch) +10ms
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=0
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=1 sleepingOnly=1
z2m:Zwave node 12 ready: - (Binary Power Switch) +12ms
z2m:Zwave Network scan complete. Found: 12 nodes +156ms
z2m:Zwave ValueRemoved: 32-1-0 from node 1 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 1 +0ms
z2m:Zwave ValueRemoved: 114-1-1 from node 1 +1ms
z2m:Zwave ValueRemoved: 114-1-2 from node 1 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 1 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 1 +0ms
z2m:Zwave ValueRemoved: 112-1-81 from node 1 +0ms
z2m:Zwave ValueRemoved: 112-1-220 from node 1 +0ms
z2m:Zwave ValueRemoved: 112-1-242 from node 1 +1ms
z2m:Zwave ValueRemoved: 112-1-243 from node 1 +0ms
z2m:Zwave ValueRemoved: 112-1-252 from node 1 +0ms
z2m:Zwave ValueRemoved: 112-1-255 from node 1 +0ms
z2m:Zwave Node removed 1 +0ms
z2m:Zwave Node added 1 +0ms
z2m:Zwave ValueAdded: 1-112-1-81 LED indicator configuration +1ms
z2m:Zwave ValueAdded: 1-112-1-220 Configuration of the RF power level +0ms
z2m:Zwave ValueAdded: 1-112-1-242 Security network enabled +0ms
z2m:Zwave ValueAdded: 1-112-1-243 Security network key +1ms
z2m:Zwave ValueAdded: 1-112-1-252 Lock/Unlock Configuration +0ms
z2m:Zwave ValueAdded: 1-112-1-255 Reset default configuration +0ms
z2m:Zwave node 1 AVAILABLE: AEON Labs - ZW090 Z-Stick Gen5 EU (Static PC Controller) +0ms
z2m:Zwave ValueAdded: 1-32-1-0 Basic +1ms
z2m:Zwave ValueAdded: 1-114-1-0 Loaded Config Revision +0ms
z2m:Zwave ValueAdded: 1-114-1-1 Config File Revision +0ms
z2m:Zwave ValueAdded: 1-114-1-2 Latest Available Config File Revision +1ms
z2m:Zwave ValueAdded: 1-114-1-3 Device ID +0ms
z2m:Zwave ValueAdded: 1-114-1-4 Serial Number +1ms
z2m:Zwave ValueRemoved: 38-1-0 from node 3 +0ms
z2m:Zwave ValueRemoved: 39-1-0 from node 3 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 3 +0ms
z2m:Zwave ValueRemoved: 38-1-1 from node 3 +1ms
z2m:Zwave ValueRemoved: 114-1-1 from node 3 +0ms
z2m:Zwave ValueRemoved: 38-1-2 from node 3 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 3 +0ms
z2m:Zwave ValueRemoved: 38-1-3 from node 3 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 3 +0ms
z2m:Zwave ValueRemoved: 38-1-4 from node 3 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 3 +1ms
z2m:Zwave Node removed 3 +0ms
z2m:Zwave Node added 3 +0ms
z2m:Zwave ValueRemoved: 38-1-0 from node 4 +0ms
z2m:Zwave ValueRemoved: 39-1-0 from node 4 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 4 +0ms
z2m:Zwave ValueRemoved: 38-1-1 from node 4 +1ms
z2m:Zwave ValueRemoved: 114-1-1 from node 4 +0ms
z2m:Zwave ValueRemoved: 38-1-2 from node 4 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 4 +0ms
z2m:Zwave ValueRemoved: 38-1-3 from node 4 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 4 +0ms
z2m:Zwave ValueRemoved: 38-1-4 from node 4 +1ms
z2m:Zwave ValueRemoved: 114-1-4 from node 4 +0ms
z2m:Zwave Node removed 4 +0ms
z2m:Zwave Node added 4 +0ms
z2m:Zwave ValueRemoved: 38-1-0 from node 5 +0ms
z2m:Zwave ValueRemoved: 39-1-0 from node 5 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 5 +1ms
z2m:Zwave ValueRemoved: 38-1-1 from node 5 +0ms
z2m:Zwave ValueRemoved: 114-1-1 from node 5 +0ms
z2m:Zwave ValueRemoved: 38-1-2 from node 5 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 5 +0ms
z2m:Zwave ValueRemoved: 38-1-3 from node 5 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 5 +1ms
z2m:Zwave ValueRemoved: 38-1-4 from node 5 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 5 +0ms
z2m:Zwave Node removed 5 +0ms
z2m:Zwave Node added 5 +0ms
z2m:Zwave ValueRemoved: 37-1-0 from node 6 +1ms
z2m:Zwave ValueRemoved: 114-1-0 from node 6 +0ms
z2m:Zwave ValueRemoved: 114-1-1 from node 6 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 6 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 6 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 6 +1ms
z2m:Zwave Node removed 6 +0ms
z2m:Zwave Node added 6 +0ms
z2m:Zwave ValueRemoved: 38-1-0 from node 7 +1ms
z2m:Zwave ValueRemoved: 39-1-0 from node 7 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 7 +0ms
z2m:Zwave ValueRemoved: 38-1-1 from node 7 +0ms
z2m:Zwave ValueRemoved: 114-1-1 from node 7 +0ms
z2m:Zwave ValueRemoved: 38-1-2 from node 7 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 7 +1ms
z2m:Zwave ValueRemoved: 38-1-3 from node 7 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 7 +0ms
z2m:Zwave ValueRemoved: 38-1-4 from node 7 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 7 +0ms
z2m:Zwave Node removed 7 +0ms
z2m:Zwave Node added 7 +1ms
z2m:Zwave ValueRemoved: 37-1-0 from node 8 +0ms
z2m:Zwave ValueRemoved: 39-1-0 from node 8 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 8 +0ms
z2m:Zwave ValueRemoved: 114-1-1 from node 8 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 8 +1ms
z2m:Zwave ValueRemoved: 114-1-3 from node 8 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 8 +0ms
z2m:Zwave Node removed 8 +0ms
z2m:Zwave Node added 8 +0ms
z2m:Zwave ValueRemoved: 37-1-0 from node 9 +3ms
z2m:Zwave ValueRemoved: 39-1-0 from node 9 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 9 +1ms
z2m:Zwave ValueRemoved: 114-1-1 from node 9 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 9 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 9 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 9 +0ms
z2m:Zwave Node removed 9 +1ms
z2m:Zwave Node added 9 +0ms
z2m:Zwave Node removed 11 +0ms
z2m:Zwave Node added 11 +0ms
z2m:Zwave ValueRemoved: 37-1-0 from node 12 +0ms
z2m:Zwave ValueRemoved: 39-1-0 from node 12 +0ms
z2m:Zwave ValueRemoved: 114-1-0 from node 12 +1ms
z2m:Zwave ValueRemoved: 114-1-1 from node 12 +0ms
z2m:Zwave ValueRemoved: 114-1-2 from node 12 +0ms
z2m:Zwave ValueRemoved: 114-1-3 from node 12 +0ms
z2m:Zwave ValueRemoved: 114-1-4 from node 12 +0ms
z2m:Zwave Node removed 12 +0ms
z2m:Zwave Node added 12 +1ms
z2m:Zwave Node removed 16 +0ms
z2m:Zwave Node added 16 +0ms
z2m:Zwave Node removed 17 +0ms
z2m:Zwave Node added 17 +0ms
z2m:Zwave Notification from node 3: Notification - NoOperation (2) +22ms
z2m:Zwave node 1 ready: AEON Labs - ZW090 Z-Stick Gen5 EU (Static PC Controller) +2ms
OpenZWave Warning, Localization::ReadXMLVIDHelp: Error in /usr/local/etc/openzwave/aeotec/zw090.xml at line 36 - Duplicate Entry for CommandClass 112, ValueID: 81 (-1): Activer / désactiver l'indicateur LED lorsqu'il est branché (Lang: fr)
OpenZWave Warning, Localization::ReadXMLVIDLabel: Error in /usr/local/etc/openzwave/aeotec/zw090.xml at line 37 - Duplicate Entry for CommandClass 112, ValueID: 81 (-1): Configuration d'indicateur LED (Lang: fr)
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=0 sleepingOnly=0
z2m:Zwave Notification from node 4: Notification - NoOperation (2) +39ms
z2m:Zwave Notification from node 5: Notification - NoOperation (2) +34ms
z2m:Zwave Notification from node 6: Notification - NoOperation (2) +31ms
z2m:Zwave Notification from node 7: Notification - NoOperation (2) +31ms
z2m:Zwave Notification from node 8: Notification - NoOperation (2) +26ms
z2m:Zwave Notification from node 9: Notification - NoOperation (2) +26ms
GET / 304 0.487 ms - -
z2m:App User disconnected LSa12ZhVacMQ_lSfAAAg +13s
GET /static/css/app.6071a1385bbbf2e6bba673b992155bbf.css 304 0.466 ms - -
GET /static/js/manifest.2ae2e69a05c33dfc65f8.js 304 0.571 ms - -
GET /static/js/vendor.45216fe22e62d2b7f2a0.js 304 1.015 ms - -
GET /static/js/app.5c258ac23abe2879e2aa.js 304 1.361 ms - -
z2m:App New connection wBFOqqtKjp7YnRQdAAAh +194ms
GET /static/logo.png 304 0.515 ms - -
GET /static/favicons/favicon-32x32.png 200 0.825 ms - 1831
z2m:Zwave Notification from node 11: Notification - TimeOut (1) +10s
OpenZWave Error, Node011, ERROR: Dropping command, expected response not received after 1 attempt(s). Command: "NoOperation_Set (Node=11): 0x01, 0x09, 0x00, 0x13, 0x0b, 0x02, 0x00, 0x00, 0x25, 0xa8, 0x61"
z2m:Zwave Notification from node 12: Notification - NoOperation (2) +32ms
z2m:Zwave Notification from node 16: Notification - NoOperation (2) +276ms
OpenZWave Warning, Node016, WARNING: Device is not a sleeping node.
OpenZWave Warning, CheckCompletedNodeQueries m_allNodesQueried=0 m_awakeNodesQueried=1
OpenZWave Warning, CheckCompletedNodeQueries all=0, deadFound=0 sleepingOnly=0
z2m:Zwave Notification from node 17: Notification - NoOperation (2) +6s
z2m:Zwave Notification from node 17: Notification - Node Asleep (4) +0ms

**Comment by robertsLando** [comment]
@PatrickSannes Please disable `refreshNodeInfo` settings in zwave settings
