### ISSUE TITLE
[feat] arbitrary zwave config

### ISSUE THREAD

**Issue by chrisns** [OpenZWave/Zwave2Mqtt#358]
It would be great to be able to specify arbitrary zwave config, at the minute i'm having to patch the `lib/ZwaveClient.js` (ignore the other things in the patch I'll raise a seperate issue to discuss that

https://github.com/chrisns/iot-zwave/blob/master/monkey-patch.patch#L9-L14

Something in the `settings.json` would be great! thanks

if you agree with the principal I'm more than happy to write the code

**Comment by robertsLando** [comment]
About this, yes, maybe something under 'advaced' settings of zwave. I haven't expose all configurations as the ones that I expose usually fit for 90% of users and most don't really understand what they are used for. 


Like on the other issue, every feature is welcome. We should check how to expose this functions in the UI too. For now we could just take them from the json configuration, so if someone wants to access those feature can eventually manually edit the json to add them

**Comment by chrisns** [comment]
yeah, it's pretty niche, I mount the settings.json in read-only too and run the whole thing in k8s - I'm not the majority target market, but I'd like to maintain less so keen to ditch my code for something more widely adopted :) 

exposing via the ui is probably out of scope and not relevant, so i'd suggest something in the settings.json that is ignored by the UI?

thoughts? if that sounds about right as design, I'll put a PR in

**Comment by robertsLando** [comment]
Will wait for the PR so! Thanks @chrisns :+1:
