### ISSUE TITLE
[feat] expose the zwave client

### ISSUE THREAD

**Issue by chrisns** [OpenZWave/Zwave2Mqtt#359]
i've got my own stuff that talks to the zwave interface, (I'm migrating away from that and will just use your API eventually, but until then...)
https://github.com/chrisns/iot-zwave/blob/master/monkey-patch.patch#L22
At the minute I'm doing some gross patching, what would be nicer is to be able to specify something in the settings to include a plugin arch of some sort.

thoughts?
happy to write the code and pr if we can agree the style
similar for exposing the mqtt client would be good, though i've not looked at that side of the gateway just yet

**Comment by robertsLando** [comment]
Everything that introduce a feature here is more then welcome, just try to don't create breaking changes.

Explain me better what you want to do and we can choose the right way to implement it :) Or just open a PR and I will check what you are doing there

**Comment by chrisns** [comment]
i want to expose the raw zwave client to some arbitrary code so i can implement my own event listeners and publishers, also a raw telnet interface so i can faff about with the raw client when i'm trying to fix/diagnose gnarly network issues.
to spitball an idea as a super crude mechanism, could have a (non ui exposed setting) that would be:
```js
if (this.cfg.plugin) {
 require(this.cfg.plugin)(this.client)
}
```
around here: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L158

**Comment by robertsLando** [comment]
I think that could work! Why not pass entire `this` instead of the client only?

**Comment by chrisns** [comment]
yeah, fair point! ok cool! I'll knock that up 👍
