### ISSUE TITLE
Neither software not documentation contains any default values or explanations

### ISSUE THREAD

**Issue by KennethLavrsen** [OpenZWave/Zwave2Mqtt#36]
I am trying to - still not successful - setup this project.

I have the software compiled and running - but setting it up is almost impossible

Many of the settings are just blank fields.
What is the format of the network ID?
What poll interval should I use? I know little about z-wave - I have no idea if this should be 1 ms, or 10 ms, or 10000 ms. What is a good common sense default value? What is the minimum that will not make a zwave network collape?
What does the "Assume Awake" mean?

mqtt
What is a sensible reconnect interval?
What is the clean flag? What is recommended? Put a default and not a blank here

You can get this fixed easily in minutes by at least editing the documentation. And do not ask me to do it because I do not know the answers. I am totally confused

**Comment by robertsLando** [comment]
Most of you questions are documented in the readme.md in [zwave](https://github.com/OpenZWave/Zwave2Mqtt#zwave) and [mqtt](https://github.com/OpenZWave/Zwave2Mqtt#mqtt) sections. 

The format of the network key should be: `"0xCA,0xFE,0xBA,0xBE,.... " // <16 bytes total>` whithout blank spaces. The poll interval shouldn't be less than 1 second per device so it depends on how many devices you have in your network (if you have some polled device). The zwave network should not generete too much traffic and the correct way to receive updates should be handled by the devices theirself, when this doesn't happen so you use the poll of values.

**Comment by KennethLavrsen** [comment]
Thanks for updating the documentation also. This comment goes for all 3 reports
