### ISSUE TITLE
"remove a node" doc missing content [bug]

### ISSUE THREAD

**Issue by magnus919** [OpenZWave/Zwave2Mqtt#360]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
Doc bug. Trying to remove a node and the doc ends with:

> enable the exclusion mode in your device to.

But the sentence is not finished. I'm not really sure what to do next to remove a dead node.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by robertsLando** [comment]
It should be `enable the exclusion mode in your device TOO`. It's just a typo, there is a missing `o` there.
