### ISSUE TITLE
Turn on/off light by PIR motion

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#362]
I have used zigbee alot and figured out how to link different devices together on events.

How can I do this in zwave?

I have a PIR and I want it to turn on a switch on motion, and turn it of when no motion. Wo do I link devices in zwave?

**Comment by robertsLando** [comment]
You have to use zwave associations groups.
Go on Control Panel, under the table of nodes select the Groups tab and associate the two devices in the correct group 
---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by magpern** [comment]
@robertsLando  Okey???? That is not very self explanatory.... especially when it does not work...
I press Groups. I assume I select the PIR in the list of nodes
In Group I select something... don't know what it means.. tried lifeline and ...BASIC
![image](https://user-images.githubusercontent.com/6589760/79674006-61663600-81df-11ea-930c-0ee6e6c047e0.png)
And for target I assume it is the switch

Pressing ADD button. It says something like "api successfull"

Triggering the PIR.. nothing happens

**Comment by robertsLando** [comment]
If you check your device manual you should there should be the documentation about each of that group. I don’t own that device, you should just read about zwave associatons to understand what I’m speaking about

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by magpern** [comment]
Then I widen my question a little...

Has anyone gotten a PIR to turn on a switch? How did you do?

My PIR has this in its documentation

![image](https://user-images.githubusercontent.com/6589760/79674387-ffa7cb00-81e2-11ea-9815-d52acc600c6d.png)

My Switch has two assosiation grooups. One called Lifeline and the other called On/off

I assume the PIR is the one that decides what to happen. So I assume the PIR is the first devise chosen. The Group I assume, whell really I don't asume anything. There are four to choose between, but only two in the documentation. But I have tried Lifeline, and Basic_SET, neither turns on any switch.
I have selected the switch as Target.

I have pressed add after each attempt.

The group disapears in zwave2mqtt after each refresh, but I assume it is by design.

**Comment by robertsLando** [comment]
In my opinion you should add the switch to PIR group 4 “send sensor bunary report”. 

Alternatively you can do this using hass automations or node red.

If you don’t see the group added in current associations it means the group pair has not been done successfully

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by magpern** [comment]
Thanks! I'll check it out.
I suspect the implementation in open-zwave is wrong for this device.
When I compair [manual](https://fccid.io/Z52NAS-PD02Z/User-Manual/User-manual-2887191) with the file `nas-pd02z.xml` they don't match up, and the xml file states that protocol might have changed in version 3. And I think this is a version 3
![image](https://user-images.githubusercontent.com/6589760/79682675-626d8680-8224-11ea-9749-7a068b8842c5.png)

I'll experiment with the open-zwave files and see.
