### ISSUE TITLE
EUR_SPIRITZ Thermostat broken in zwave2mqtt 3.02 ozw 1.6

### ISSUE THREAD

**Issue by christoph-luebbe** [OpenZWave/Zwave2Mqtt#365]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.02
Openzwave Version: 1.6.974

**Describe the bug**
Device Type: Thermostat HVAC
Product: EUR_SPIRITZ Wall Radiator Thermostat (EUROtronic)
Values to Set Temperature for Heat (xx-67-1-1) and Heat Econ (xx-67-1-11) are not listed in the Value-list
However they are still readable via mqtt but they cannot be changed via xx-67-1-1/set and 67-1-11/set 

**To Reproduce**
1. Add a EUR_SPIRITZ Wall Radiator to the z-wave network using openzwave V 1.6.974 and zwave2mqtt 3.02 
2. Open Control Panel and select the device
3. Scroll down to User Values
4. See that the fields to Set the Heat Temp (xx-67-1-1) and Heat Econ Temp (xx-67-1-11) are missing

**Expected behavior**
The mentioned fields should be visible containing the two set points of the themostat and the values should be changeable in the Control Panel as well

**Additional context**
This worked with zwavw2mqtt 2.x and ozw 1.4
Interestingly the two missing parameters are transferred via mqtt if they are changed at the device

**Comment by christoph-luebbe** [comment]
I just checken the openzwave 1.6 config for the Eurotronic SPIRIT-Z

there the Command Class 64 lists the modes as Heat, and Heat Eco. No idea why I get Heat Econ instead. And also the Command Class 67 lists 1 and 11 as the two parameters to change the target values. So the definition in openzwaver seems to be ok.

<CommandClass id="64">
    <Instance index="1"/>
    <Value genre="user" index="0" instance="1" label="Mode" type="list">
      <Help>
                Off: No heating, only frost protection.
                Heat: Room temperature will be kept at the configured setpoint.
                Heat Eco: Energy save heating mode. Room temperature will be lowered to the configured eco setpoint in order to save energy.
                Full Power: Full power heating. This mode is left automatically after 5 minutes.
                Manufacturer Specific: Direct valve control mode. The valve opening percentage can be controlled using the switch multilevel command class.
            </Help>
      <Item label="Off" value="0"/>
      <Item label="Heat" value="1"/>
      <Item label="Heat Eco" value="11"/>
      <Item label="Full Power" value="15"/>
      <Item label="Manufacturer Specific" value="31"/>
    </Value>
    <SupportedModes>
      <Mode index="0" label="Off"/>
      <Mode index="1" label="Heat"/>
      <Mode index="11" label="Heat Eco"/>
      <Mode index="15" label="Full Power"/>
      <Mode index="31" label="Manufacturer Specific"/>
    </SupportedModes>
  </CommandClass>
  
  <CommandClass id="67">
    <Instance index="1"/>
    <Value genre="user" index="1" instance="1" label="Heat" max="28" min="8" read_only="false" type="decimal" units="°C" value="20" write_only="false"/>
    <Value genre="user" index="11" instance="1" label="Heat Eco" max="28" min="8" read_only="false" type="decimal" units="°C" value="16" write_only="false"/>
    <Compatibility>
      <Base>0</Base>
      <AltTypeInterpretation>false</AltTypeInterpretation>
    </Compatibility>
  </CommandClass>

**Comment by jamesarbrown** [comment]
For me I think it's working?

![Screenshot_20200422-072938](https://user-images.githubusercontent.com/891438/79948385-ac947900-846b-11ea-852f-65c685d7fdf7.png)

**Comment by robertsLando** [comment]
Please try with latest version 3.0.3

**Comment by christoph-luebbe** [comment]
Hi Daniel, thanks. I will try

**Comment by christoph-luebbe** [comment]
Hi James, Thanks for your comment. This is exactly what I would expect. I have no idea why I got this messed device config during the update. Daniel suggested to try 3.03. So I asked Frack from Home Assistant to provide us with an updated version of the zwave2mqtt add-on using 3.03. 
Hopefully this solves this problem.

**Comment by jamesarbrown** [comment]
I am on 3.02... i think. Certaintly thats what the http page says in top left and from docker latest image a couple of days ago. I need to investigate that later tonight and get onto 3.03 for other reason

**Comment by christoph-luebbe** [comment]
Ok I found the root cause. I had a zwfgxxxx.xml file which contained the outdated info. After deleting this and restarting zwave2mqtt everything seems ok. The odd thing is that these wrong settings weren't used and they came up just after the upgrade. 
I think it would be a good thing to mention this in the readme to check any zwfg files and consider delete it before the upgrade

**Comment by robertsLando** [comment]
@christoph-luebbe you didn't have to delete the file, you could simply call the api `refreshNodeInfo` from the UI or via MQTT that will refresh the cache and use latest version of config available :)
