### ISSUE TITLE
JSON Template for Value Setting

### ISSUE THREAD

**Issue by jamesarbrown** [OpenZWave/Zwave2Mqtt#366]
Hi,

I was trying to track down a typical JSON template for Zwave2MQTT for HA on an Aeotec Doorbell 6. My goal is to link it to another Aeotec trisensor, such I can force the doorbell to ring on motion detect.

This Scene I created and tested in zwave2mqtt. I would like to create this setting from HA which which the doorbell then activates that tone. I think its only for browsing the tone, but works for me.

![image](https://user-images.githubusercontent.com/891438/79908128-9e663e80-8412-11ea-8310-271eab4b7770.png)

Would appreciate any examples, guidance. Got in a bit over my head trying to convert a climate one!

**Comment by robertsLando** [comment]
The only way you can do this is to manually create a component in hass yaml configuration file that activate the scene using mqtt

**Comment by jamesarbrown** [comment]
Daniel probably did not explain well.

I was looking for a way to set 121-3-1 to value 27 or 0 via creating a JSON that ha can use.

Zwave2mqtt does not expose and auto create a JSON for a block of user settings on this device

The scene in zwave2mqtt was only to test that the principal worked

**Comment by robertsLando** [comment]
> I was looking for a way to set 121-3-1 to value 27 or 0 via creating a JSON that ha can use.

https://github.com/OpenZWave/Zwave2Mqtt#set-values ?
