### ISSUE TITLE
Zooz 4 in 1 no configuration

### ISSUE THREAD

**Issue by broyuken** [OpenZWave/Zwave2Mqtt#368]
I have a ZSE40 Zooz 4 in 1 sensor, and Z2M 3.02, the device was added fine, but I have no configuration options. I have the files there in my config, but they aren't showing up in the control panel. I have other devices that are populated fine.

**Comment by chilicheech** [comment]
My Zooz ZSE40 4 in 1 shows up just fine:
![Screen Shot 2020-04-22 at 1 22 31 PM](https://user-images.githubusercontent.com/732659/80029988-728f9b00-849c-11ea-92b1-8cccc79cdc6c.png)
Maybe you need to run a `Refresh Node Info`..

**Comment by broyuken** [comment]
I did that and then the node went to dead state

**Comment by robertsLando** [comment]
@broyuken Remove and add back your node so from the controller

**Comment by broyuken** [comment]
I have, I even added it back as a different node id. Same issue.

**Comment by robertsLando** [comment]
@broyuken Could you try using latest version published yesterday please? 3.0.3

**Comment by broyuken** [comment]
I’m using the hassio add on, how would I update? That is still using 3.0.2

**Comment by robertsLando** [comment]
@broyuken Ask them to make a new release or use my docker image instead of the addon

**Comment by robertsLando** [comment]
@broyuken Anyway I'm going to close this, it's not an issue with z2m but more likely something related to configuration versions of the device

**Comment by broyuken** [comment]
How would I fix a configuration version of the device? Is this an issue with ozw? Or something with my specific device? Where do I go from here if 3.0.3 doesn’t fix it?

**Comment by robertsLando** [comment]
@broyuken YOu could try to enable zwave setting that auto-updates the db

**Comment by broyuken** [comment]
It’s on

**Comment by robertsLando** [comment]
So just cross your finger and update to latest version :confused:

**Comment by broyuken** [comment]
I updated the config path to /etc/openzwave from /config/ozwave/config and repaired it and now the options show up.
