### ISSUE TITLE
[bug] double-click for GE 14291 In-Wall Smart Switch in home assistant

### ISSUE THREAD

**Issue by idyedov** [OpenZWave/Zwave2Mqtt#370]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.3? (image with latest docker tag)
Openzwave Version: 1.6.1080

**Describe the bug**
I have two light switches connected through zwave2mqtt:
1. 14291 In-Wall Smart Switch (GE (Jasco Products)) id 99-12342-18770
2. 46201 In-Wall Smart Switch (GE (Jasco Products)) id 99-12597-18770 (newer model)

second one generates a couple of "sensor_scene_state" sensors that are sent to home assistant and allow to identify events like double click. But the first one has no such sensors - just the switch.

**To Reproduce**
1. Add 14291 In-Wall Smart Switch (GE (Jasco Products)) to zwave2mqtt
2. Scroll down to 'Home Assistant - Devices' tab at the bottom
3. See just 'switch_switch' and no sensors

**Expected behavior**
Expected to see:
1. sensor_scene_state
2. sensor_scene_state_2

**Additional context**
openzwave device configs for these devices look pretty much identical:
1. https://github.com/OpenZWave/open-zwave/blob/167488850ae455d564951bedd1185a2d7cb8edfd/config/ge/14291-switch.xml
2. https://github.com/OpenZWave/open-zwave/blob/2114a5a14069ecb5140c252e26647f26fc39e933/config/ge/46201-switch.xml

**Comment by robertsLando** [comment]
@idyedov YOu should open this issue on openzwave repo, I have no control of such things on my side
