### ISSUE TITLE
[question] FGR-223, where is stop command ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [OpenZWave/Zwave2Mqtt#376]
Hi,

I try to add command to stop my roller (Fibaro  FGR-223) but i don't find any combo to do it :/

On jeedom, i can stop roller with :
Classe : 38
Instance : 1
Index : 2 
And command : type=buttonaction&action=release

Any idea ?

**Comment by robertsLando** [comment]
Please ask this kind of questions on Openzwave repo :) Every value that you see in UI comes from there

**Comment by m4dm4rtig4n** [comment]
hi @robertsLando , 

Features allready exist on openzwave because jeedom use openzwave 1.4 and have functionnality.

But i don't find how send to MQTT action type buttonaction & action release.

if i compare with jeedom, when i would send `zwave/PLACE/NAME/38/1/0/set`
Jeedom send command : type=setvalue&value=0

But when i see stop action, jeedom send command : type=buttonaction&action=release

i think jeedom simulate button action on roller, it's possible with zwave2mqtt ?

thx

**Comment by robertsLando** [comment]
Try to send `true` or `{"value": true}`  to `zwave/PLACE/NAME/38/1/0/set`

**Comment by m4dm4rtig4n** [comment]
@robertsLando thx !!!

With {"value": false}, the roller stop :)

thx guy and good job for you work !

**Comment by duncan-valleix** [comment]
> 
> 
> Try to send `true` or `{"value": true}` to `zwave/PLACE/NAME/38/1/0/set`

sorry, je repond en français mais 38/1/0/set {true} fait monté le volet et {false} le fait descendre, 38/1/2/set {true} force la descente du volet, 38/1/2/set {false} arrete la course du volet

**Comment by m4dm4rtig4n** [comment]
This parameter work fine :+1: 

![image](https://user-images.githubusercontent.com/7872518/80213752-f0d57400-8639-11ea-92e9-ecea578df630.png)
> zwave/PLACE/NAME/38/1/0/set with {"value": 99}

![image](https://user-images.githubusercontent.com/7872518/80213876-2712f380-863a-11ea-8564-963e91519867.png)
> zwave/PLACE/NAME/38/1/7/set with {"value": false}

![image](https://user-images.githubusercontent.com/7872518/80213923-3d20b400-863a-11ea-99ac-89591106187f.png)
> zwave/PLACE/NAME/38/1/7/set with {"value": true}

But have you idea for this parameters ?

![image](https://user-images.githubusercontent.com/7872518/80213989-617c9080-863a-11ea-81bf-c6fa0c3e5207.png)
> zwave/PLACE/NAME/112/1/15/set with {"value": ????????}

![image](https://user-images.githubusercontent.com/7872518/80214098-84a74000-863a-11ea-8ea6-ff92f9de661c.png)
> zwave/PLACE/NAME/38/1/0/set with {"value": ????????}

Thx :)

**Comment by robertsLando** [comment]
@m4dm4rtig4n Why don't you use the UI control panel?

**Comment by m4dm4rtig4n** [comment]
I use it, but I tell myself that one day I might need the information :D
I am trying to understand at the same time how mqtt works :)

**Comment by robertsLando** [comment]
In the value you have to use the value that you would send from the UI
