### ISSUE TITLE
Zombie nodes

### ISSUE THREAD

**Issue by xannor** [OpenZWave/Zwave2Mqtt#377]
0.6.0

Build/Run method
- [ x] Docker - hass io addon
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 0.6.0
Openzwave Version: 1.6.974

**Describe the bug**
I have 3 nodes on my network that do not exist, however they continually persist as dead nodes. The only way I can make them dissappear, temporarily, is to run a request info, then they get flagged as removed. However if I do a neighbor update of certain nodes, they rise again as dead nodes.

**Additional context**
The best I can determine is that they are marked as failed by the controller, but for some reason a few nodes still have them listed as neighbors so they rise again when a network update is done. The reason I believe they are marked as failed is because if I tell it to send a NIF, neighbor update, has failed, or remove failed node, nothing is logged for those nodes, if I send a request for info, it does attempt, reports the node as sleeping, and them flags it as removed. But, again, they rise when a neighbor update is requested.

**Comment by robertsLando** [comment]
Are you speaking about mesh graph?

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by xannor** [comment]
not specifically, but it can be used to visualize the links. I am mostly observing this through the debug log. As an example:

```
2020-04-24T11:11:11.133Z z2m:Zwave controller command {
nodeid: 11,
state: 7,
errcode: 0,
help: 'RequestNodeNeighborUpdate Completed'
}
OpenZWave Detail, Received: 0x01, 0x05, 0x00, 0x48, 0x58, 0x22, 0xc8
OpenZWave Detail,
OpenZWave Info, REQUEST_NEIGHBOR_UPDATE_DONE
OpenZWave Detail, Requesting routing info (neighbor list) for Node 11
OpenZWave Detail, Node011, Queuing (Command) Get Routing Info (Node=11): 0x01, 0x07, 0x00, 0x80, 0x0b, 0x00, 0x00, 0x03, 0x70
OpenZWave Detail, Node011, Notification: RequestNodeNeighborUpdate ControllerCommand - Completed
OpenZWave Detail,
OpenZWave Info, Node011, Sending (Command) message (Callback ID=0x00, Expected Reply=0x80) - Get Routing Info (Node=11): 0x01, 0x07, 0x00, 0x80, 0x0b, 0x00, 0x00, 0x03, 0x70
OpenZWave Info, Node011, Encrypted Flag is 0
OpenZWave Detail, Node011, Received: 0x01, 0x20, 0x01, 0x80, 0xf6, 0x1b, 0x78, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xcb
OpenZWave Detail,
OpenZWave Info, Node011, Received reply to FUNC_ID_ZW_GET_ROUTING_INFO
OpenZWave Info, Node011, Neighbors of this node are:
OpenZWave Info, Node011, Node 2
OpenZWave Info, Node011, Node 3
OpenZWave Info, Node011, Node 5
OpenZWave Info, Node011, Node 6
OpenZWave Info, Node011, Node 7
OpenZWave Info, Node011, Node 8
OpenZWave Info, Node011, Node 9
OpenZWave Info, Node011, Node 10
OpenZWave Info, Node011, Node 12
OpenZWave Info, Node011, Node 13
OpenZWave Info, Node011, Node 20
OpenZWave Info, Node011, Node 21
OpenZWave Info, Node011, Node 22
OpenZWave Info, Node011, Node 23
OpenZWave Detail, Node011, Expected reply was received
OpenZWave Detail, Node011, Message transaction complete
OpenZWave Detail,
OpenZWave Detail, Node011, Removing current message
```

This is a neighbor update request to node 11. It seem to report back node 12 and 20 as neighbors, though those nodes do not exist. Node 12 was a NanoMote quad that I had accidentally reset and is now another node (23 I believe), and node 20 was a GE hinge pin sensor that I had but could not remove, this one was also node 19, I had some issues when I first tried to set it up. I stopped using it because it is not compatible with my door frames.

**Comment by xannor** [comment]
Here is an example of sending a request info to node 20:
```
OpenZWave Detail, Node020, Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
OpenZWave Detail, Node020, ZW_SEND_DATA delivered to Z-Wave stack
OpenZWave Detail, Node020, Received: 0x01, 0x18, 0x00, 0x13, 0x6d, 0x01, 0x03, 0xb1, 0x00, 0x7f, 0x7f, 0x7f, 0x7f, 0x7f, 0x00, 0x01, 0x07, 0x00, 0x00, 0x00, 0x00, 0x02, 0x14, 0x15, 0x16, 0x46
OpenZWave Detail, Node020, ZW_SEND_DATA Request with callback ID 0x6d received (expected 0x6d)
2020-04-24T11:18:02.509Z z2m:Zwave Notification from node 20: Notification - NoOperation (2)
2020-04-24T11:18:02.509Z z2m:Zwave Notification from node 20: Notification - Node Asleep (4)
OpenZWave Detail, Node020, Extended TxStatus: Time: 9450, Hops: 0, Rssi: --- --- --- --- ---, AckChannel: 0, TxChannel: 1, RouteScheme: Explorer Route, Route: 0 0 0 0, RouteSpeed: 40K, RouteTries: 20, FailedLinkFrom: 21, FailedLinkTo: 22
OpenZWave Info, Node020, WARNING: ZW_SEND_DATA failed. No ACK received - device may be asleep.
OpenZWave Info, Node020, Node 20 has been marked as asleep
OpenZWave Info, Node020, Node not responding - moving QueryStageComplete command to Wake-Up queue
OpenZWave Detail, Node020, Notification: Notification - NoOperation
OpenZWave Detail, Node020, Notification: Notification - Node Asleep
```

This is also the only action I can send that shows anything in the log, if I do a NIF or has failed or remove failed, nothing is logged. When I do the request for info, the node get set as removed.

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by robertsLando** [comment]
Did you try to send updateNodeNeightbors api?

**Comment by xannor** [comment]
Against which node? I have done it against node 11, which reports node 12 and 20 as neighbors. Oddly enough this time it finally did not report node 20. I originally thought ti try to fire update neighbors on all nodes that had reported a link to a dead node, but the only flaw in that is that node 19 seems to have no links, but still comes back.

**Comment by robertsLando** [comment]
Against node 11

**Comment by xannor** [comment]
I have since moved to the other zwave package for home assistant, in there I removed the dead nodes.
