### ISSUE TITLE
[question] can't get celsius / fahrenheit to work on any temp sensor

### ISSUE THREAD

**Issue by idyedov** [OpenZWave/Zwave2Mqtt#378]
Hi,

I just installed zwave2mqtt 3.0.3 (openzwave 1.6.1080) and I have 2 different kinds of temperature sensors:

1. ZP3102 PIR Motion Sensor (Vision Security)
2. ZP3111 Multisensor 4in1 (Vision Security)

I'm trying to get the sensors to report in Fahrenheit instead of Celsius and am having issues with both of them - it always reports in Celsius.

I see two different settings for this (not sure why there's two) - one under configuration and one under system
![Screen Shot 2020-04-24 at 12 39 49 AM](https://user-images.githubusercontent.com/904832/80189124-09587680-85c7-11ea-87a8-8eb37e0f5aff.png)

If I set the System setting to Fahrenheit, I see a message in the logs that it sends out the command:
```
z2m:App Zwave api call: setValue [ 58, 49, 1, 256, 'Fahrenheit' ] +2m | stdout
```
it automatically resets to Celsius after a while (or if I hit "Rediscover Node" button).

From https://github.com/OpenZWave/Zwave2Mqtt/issues/102 I saw that changing units may require removing and adding the sensor - so I tried that, but still no luck - it always defaults to Celsius.

Is this an OpenZwave issue or zwave2mqtt? It worked fine in home assistant with openzwave 1.4.

Any help would be much appreciated.

Thank you.

**Comment by robertsLando** [comment]
You should open such questions on Openzwave repo, sorry I have no control of such things :(
