### ISSUE TITLE
UI randomly clearing down and showing nothing or nodes with missing types [bug]

### ISSUE THREAD

**Issue by djdd87** [OpenZWave/Zwave2Mqtt#396]
**Version** 

Build/Run method
- [x ] Docker (Haspian - Raspberry Pi 4)

Zwave2Mqtt version: 3.0.3
Openzwave Version: 1.6

**Describe the bug**
I've set up a third of my z-wave network and I've noticed that occasionally the whole UI seems to refresh and all my nodes (all all my nodes except the zstick ) just disappear for no reason. A few minutes later (or sometimes after refreshing the screen), the nodes reappear and all the nodes show as dead, or just some of them. When showing dead, there's usually no node information.

During this time, I can still use a tool such as MQTT Explorer to set the node states and turn my lights/switches on/off despite the fact zwave2mqtt shows nothing in the UI.

**To Reproduce**
1. Sorry, not sure. It seems to happen sporadically.

**Expected behavior**
I'd expect the node list to remain all the time and not randomly disappear. I would expect it if I had restart the docker image or the device, but the device is not being restarted.

**Additional context**
I'm using mosquitto as the broker in case that's relevant. 

I've attached images in the order that the issue has occurred 20 minutes ago.

![issue00](https://user-images.githubusercontent.com/22151993/80308107-ed222880-87c4-11ea-83e6-871044c8ef2b.png)
![issue01](https://user-images.githubusercontent.com/22151993/80308108-edbabf00-87c4-11ea-8167-73fec29773dd.png)
![issue02](https://user-images.githubusercontent.com/22151993/80308109-ee535580-87c4-11ea-81ae-d1c7507ae331.png)
![issue03](https://user-images.githubusercontent.com/22151993/80308110-ee535580-87c4-11ea-9b33-f622f1ce4a9d.png)

Settings are below:

![settings_mqtt](https://user-images.githubusercontent.com/22151993/80308545-8ce0b600-87c7-11ea-9324-fbed15e79a3d.png)
![settings_gateway](https://user-images.githubusercontent.com/22151993/80308547-8e11e300-87c7-11ea-9ef0-a34301f287bc.png)
![setting_zwave](https://user-images.githubusercontent.com/22151993/80308548-8e11e300-87c7-11ea-8910-1f32d375c7d2.png)

**Comment by robertsLando** [comment]
Please disable refreshNodeInfo from zwave settings

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by djdd87** [comment]
Doh... what triggers/is the scan that "after scan is complete" refers to?

**Comment by djdd87** [comment]
Issue hasn't occurred since making the specified change.
