### ISSUE TITLE
Add locations to the nodes on the Network Graph [feat]

### ISSUE THREAD

**Issue by djdd87** [OpenZWave/Zwave2Mqtt#397]
**Is your feature request related to a problem? Please describe.**
I've taken a more semantic approach to naming my z-wave nodes, e.g. /kitchen/light_switch, /playroom/light_switch (instead of /kitchen/kitchen_light_switch or /playroom/playroom_light_switch. So as I've got multiple entities with the same name (but different locations), it makes the network graph hard to read (without clicking on each node).

**Describe the solution you'd like**
I suspect not everyone will want to see the location, so I'd like to be able to see the location by a toggle above the graph. When enabled, the node names will appear in the format {location}/{node_name}.

**Describe alternatives you've considered**
The only alternative is to put the location name in the node name, or to click each node to see it's location.

**Additional context**
![network_graph](https://user-images.githubusercontent.com/22151993/80312229-01bdeb00-87dc-11ea-8800-be1400142caa.png)

**Comment by robertsLando** [comment]
@djdd87 It could be done yes, would you mind to send a PR for that?

**Comment by djdd87** [comment]
I'll happily take a look. Is there any way I can fake a set of nodes for the mesh? I only have one Z-Stick and it's running my Home Automation.

Does this UI change work for you?

![image](https://user-images.githubusercontent.com/22151993/80367572-3f298380-8883-11ea-8df9-e0ad8a40eb2b.png)

**Comment by robertsLando** [comment]
@djdd87 Yes that is how I would made that :) To fake nodes just add a script that adds them, check Mesh.vue the `convertNode` function is the one that creates the nodes to add to the mesh graph :)

**Comment by djdd87** [comment]
I'd like to do it! I saw that method, but I still can't work out how to get the nodes in. I'm a C# dev of nearly 20 years and I can't seem to get the Visual Studio Code debugger to attach/not error/do anything.

Where and how can I script the nodes in? I tried importing my nodes.json file, but that doesn't seem to do anything, and I can't work out how to replace the running store directory with a copy of my live store directory.

**Comment by robertsLando** [comment]
You could create a fake nodes array:
: 

```js
addFakeNodes(){
var nodes = [{//fakenode}, {//fakenode},{//fakenode}]
for (var i = 0; i < nodes.length; i++) {
        this.nodes.push(this.convertNode(nodes[i]))
}
}
```

And call this method in `mounted()`

**Comment by robertsLando** [comment]
@djdd87 Don't waste your time I have a PR ready for this
