### ISSUE TITLE
[Statement] MQTT auto discovery in HA

### ISSUE THREAD

**Issue by pbathuk** [OpenZWave/Zwave2Mqtt#40]
Hey, 
So I have set up my lights how I like them now, I luckily don't have many so easy to manually setup the HA discovery in MQTT.
I wanted to share my findings so far, incase this sparks something, or (with a bit more time & learning) I might complete a pull request to get this automated.

So I have only looked at lights & switches, and for lights only the brightness of them.
For switches its pretty easy to setup with a template such as :
Saved to : homeassistant/switch/dining_room/config
`{
  "name": "In_wall_dining_room_switch",
  "state_topic": "zwave/Dining_Room/19/37/1/0",
  "command_topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-Mos_mqtt/api/setValue/set",
  "availability_topic": "zwave/Dining_Room/19/status",
  "payload_on": "{ \"args\":[19,37,1,0,true]}",
  "payload_off": "{ \"args\":[19,37,1,0,false]}",
  "state_on": "true",
  "state_off": "false",
  "qos": 2,
  "retain": false,
  "payload_available": "true",
  "payload_not_available": "false",
  "unique_id": "dining_room_switch_111",
  "device": {
    "identifiers": "diningroomswitch111",
    "name": "in_wall_dining_room_switch",
    "sw_version": "1",
    "model": "Zwave",
    "manufacturer": ""
  }
}`

Lights get a little tricker, as annoyingly the payload on & payload off are supposed to match the state, which because I am using the API it does not...
`{
  "name": "In_wall_study_switch",
  "state_topic": "zwave/Study/21/37/1/0",
  "command_topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-Mos_mqtt/api/setValue/set",
  "availability_topic": "zwave/Study/21/status",
  "brightness_command_topic": "zwave/Study/21/38/1/0/set",
  "brightness_state_topic": "zwave/Study/21/38/1/0",
  "payload_on": "{ \"args\":[21,37,1,0,true]}",
  "payload_off": "{ \"args\":[21,37,1,0,false]}",
  "state_value_template": "{% if value_json.value == true %}{ \"args\":[21,37,1,0,true]}{% else %}{ \"args\":[21,37,1,0,false]} {% endif %}",
  "brightness_scale": 99,
  "qos": 2,
  "retain": false,
  "payload_available": "true",
  "payload_not_available": "false",
  "unique_id": "study_switch_111",
  "on_command_type": "first",
  "device": {
    "identifiers": "inwallstudyswitch111",
    "name": "in_wall_study_switch",
    "sw_version": "1",
    "model": "Zwave",
    "manufacturer": ""
  }
}`

A couple of things to note:
HA throws no error if you miss the device, but you can't set an area for an entity without a device block..  so I added it.
the brightness scale depends on the switch, my nano dimmers accept 1 to 99, where as HA can provide any value to 255 I believe, so that limits that
On_command_type is set to first, as I was finding that for my dimmer if I sent the on / off and then the brightness something was happening where it would not changed, first made the brightness go first.

Anyways this is how I have manually set them up so that HA can be left running and I don't have to play around with the config & keep rebooting..

**Comment by pbathuk** [comment]
Actually following a HA reboot the light one is not working... It does change the lights but always reverts to off not the state it actually is :(

**Comment by robertsLando** [comment]
Hi @pbathuk . Thanks for this, the HAss MQTT auto-discovery is the hottest feature on the todo list. I have made some checks and I think we should take inspiration from [zegbee2mqtt](https://github.com/Koenkk/zigbee2mqtt/blob/master/lib/extension/homeassistant.js) home assistant integration. Zegbee is really similar to zwave and I think it can be made work

**Comment by pbathuk** [comment]
Out of curiosity, is it best, or should I say more advisable to us value only or JSON (full or timestamp) for Mqtt? I see that for zigbee2mqtt they mention Json payload quite alot. Which I assume means the full JSON standard in z-wave? 
I only ask so that I can try to mirror and find what works / does not.
Currently I use value only

**Comment by robertsLando** [comment]
I don't understand what you mean with your question. When a value change is detected in zwave network there should be a function like the `discover` that compose the MQTT message with a JSON payload and the correct topic to send the update to HAss, the payload HAss expect must respect the HAss specification for MQTT auto-discovery, it changes based on the device type. Try to check the previous link and the [MQTT-Auto discovery](https://www.home-assistant.io/docs/mqtt/discovery/) specs.

**Comment by pbathuk** [comment]
Sorry, I mean from a config on the openzwave panel, there is the option for the gateway to store in Mqtt as:

Just value
JSON timevalue

**Comment by pbathuk** [comment]
Sorry accidentally clicked close on my phone

**Comment by robertsLando** [comment]
To make it working you can't use that, we must create a new one

**Comment by pbathuk** [comment]
Ah ok, so in theory you are thinking:
{Prefix}/{node_id}/status
Or something like that
And that would hold the HA required JSON values to use in the auto discovery? 
Only asking out of curiosity rather than how it will actually be done.

**Comment by robertsLando** [comment]
Yep something like that, need to study how to map devices and devices values into Hass devices configurations.

**Comment by pbathuk** [comment]
So 1 final update on this:

I have code that now works for reporting the state of the light, its a little hacky as I am using the Attributes only option & it appears HA reads the value true in as 'true' therefore causing no end of issues. After setting up a second dev instance of HA so I can reboot the docker etc I finally have :

`{
  "name": "In_wall_study_switch",
  "command_topic": "zwave/_CLIENTS/ZWAVE_GATEWAY-Mos_mqtt/api/setValue/set",
  "availability_topic": "zwave/Study/21/status",
  "brightness_command_topic": "zwave/Study/21/38/1/0/set",
  "brightness_state_topic": "zwave/Study/21/38/1/0",
  "payload_on": "{ \"args\":[21,37,1,0,true]}",
  "payload_off": "{ \"args\":[21,37,1,0,false]}",
  "state_topic": "zwave/Study/21/37/1/0",
  "state_value_template": "{% if value.replace(\"'\",'') == true %}{ \"args\":[21,37,1,0,true]}{% else %}{ \"args\":[21,37,1,0,false]}{% endif %}",
  "brightness_scale": 99,
  "qos": 2,
  "retain": false,
  "payload_available": "true",
  "payload_not_available": "false",
  "unique_id": "study_switch_111",
  "on_command_type": "first",
  "device": {
    "identifiers": "inwallstudyswitch111",
    "name": "in_wall_study_switch1",
    "sw_version": "1",
    "model": "Zwave",
    "manufacturer": ""
  }
}`

This is working robustly for me and I can see if the light is on as well as the brightness.
