### ISSUE TITLE
Run on an embedded GL-MT300N-V2

### ISSUE THREAD

**Issue by alekslyse** [OpenZWave/Zwave2Mqtt#41]
I have some GL-MT300N-V2 laying around, small embedded devices that originally run openWRT - this units are fully flashable and should be fully capable as running as a server for zwave2mqtt with a flash image.

Anyone had any luck flashing a openWRT / GL-MT300N-V2 device with a basic linux imsage and run zwave2mqtt on it? 

Would be an easy way to put a small factor zwave bridge in the house that is not a RPI

**Comment by robertsLando** [comment]
What I suggest to you is to pkg the application for that device. Is it an arm32v6/7 arm64 (aarch64) or what else?

Daniel
