### ISSUE TITLE
[question] Problems with Aeotec Multisensor 6, Firmware 1.13

### ISSUE THREAD

**Issue by maichai** [OpenZWave/Zwave2Mqtt#413]
Using Aeotec Multisensor 6 with Firmware 1.13 paired with Aeotec Zstick Gen 5

 System: HassOS 3.13  (amd64 / qemux86-64)
 Home Assistant Core: 0.108.9
 Home Assistant Supervisor: 219

 Add on 0.6.0
ZWave2MQTT v3.0.2
OpenZWave 1.6.974 binary addon for Node.JS.

There are a lot of quirks when you look at the sensor readings and settings detected by zwave2mqtt and what is promoted to Home Assistant for auto discovery.
In the end I had to look at what zwave2mqtt detected, and what was sent to MQTT.

But I am not at all sure that what is detected is right:

Comment: PIR is configured to “Basic Set” not “Binary Sensor Report”, if this makes a difference.

* binary_sensor_contact, 48/1/0, boolean, always reports "false", but only together with other sensor values. Seems to have no function at all, at least I don't see any immediate reports on this one, but maybe it is the tamper sensor that works differently? I thought it was about vibration sensing.

* sensor_alarm_home_security, 113/1/7, no unit: always reports "unknown", sends a report when motion is detected, so I assume it is the PIR motion detector. However, in zwave2mqtt log I find this:

```
2020-04-29 11:35:14.672 Detail, Node003,   Received: 0x01, 0x09, 0x00, 0x04, 0x00, 0x03, 0x03, 0x20, 0x01, 0x00, 0xd3
2020-04-29 11:35:14.672 Detail, 
2020-04-29 11:35:14.672 Info, Node003, ApplicationCommandHandler - Unhandled Command Class 0x20
2020-04-29 11:35:14.994 Detail, Node003,   Received: 0x01, 0x0f, 0x00, 0x04, 0x00, 0x03, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x07, 0x00, 0x00, 0x72
2020-04-29 11:35:14.995 Detail, 
2020-04-29 11:35:14.995 Warning, NotificationCCTypes::GetAlarmNotificationTypes - Unknown Alarm Type 7
2020-04-29 11:35:14.995 Warning, NotificationCCTypes::GetEventForAlarmType - Unknown AlarmType/Event 7/d
2020-04-29 11:35:14.996 Warning, NotificationCCTypes::GetAlarmType - Unknown AlarmType 7
2020-04-29 11:35:14.996 Info, Node003, Received Notification report (>v1): Type: Unknown (7) Event: Unknown (0) Status: true, Param Length: 0
2020-04-29 11:35:14.996 Detail, Node003, Refreshed Value: old value=0, new value=0, type=list
2020-04-29 11:35:14.997 Detail, Node003, Changes to this value are not verified
2020-04-29 11:35:14.997 Detail, Node003, Notification: ValueChanged
2020-04-29T09:35:14.998Z z2m:Zwave zwave node 3: changed: 113-1-7:Unknown:Unknown -> Unknown
```
Bottomline you get a state change from unknown to unknown, which is not helpful at all to detect the motion. Is is a bug in zwave2mqtt, is there a mapping missing somewhere? If I cannot do anything about it, what would you propose how to use such reports in home assistant to still get a state change for motion sensor entity?

Motion sensing is the most important part for me. If that does not work, all is lost with this sensor.

* sensor_battery_level, 128/1/0, %: always 100 when on USB power, no batteries were included.

* sensor_humidity_air, 49/1/5, RH: reports in deltas of 1, not sure how accurate the reported values are. This is somewhat interesting to display in the bathroom.

* sensor_illuminance, 49/1/3, Lux: reports 0 in a dark room. 3 with some light, 127 with a flashlight in front of it. Not sure how accurate that is, but it seems to do something. This * sensor is the second most important to me for automation to determine how bright the light bulbs should illuminate.

* sensor_sun_ultraviolet, 49/1/27, no unit: always 0 indoors AND outdoors. I don't care about that sensor anyway.

* sensor_temperature_air, 49/1/1, C: reports 5 degrees too high, calibration does not work (whatever I set as value for calibration, the setting will snap back to either 1 oder 255), insanely high threshold (3-112-1-41) of 1310976 and upper limit (3-112-1-49) of 18350336, and not possible to change them. Why these values, and why does it not update the values to what I am setting? Is my sensor broken or is there a problem with zwave2mqtt??

More quirks:

* Trying to enable the change-threshold-based reporting (3-112-1-48) for temperature, illuminance, humidity etc. does not work. I was not able enable this for any of the defined change-thresholds. Is this a problem in zwave2mqtt or with the sensor?

* The discovery JSON sent for Home Assistant auto discovery is missing the appropriate units.

Are there more sensor reeadings that I could use?
(For now I held back using auto discovery because I wanted to have full control over what Home Assistant is using here)

**Comment by chrisns** [comment]
i have one, so can comment
see the notes in the ozw spec
https://github.com/OpenZWave/open-zwave/blob/master/config/aeotec/zw100.xml
enable the `Binary Sensor Report`
you may also want to tweak the `Group [1+] Reports`

**Comment by maichai** [comment]
Chris, you were very fast with responding with the right solution, I wish I had seen it right away. After some time I found this solution too. But maybe one should also let zwave2mqtt work with "Basic Set"? Would that be possible?

Also the discovery JSON template for this sensor seems not to work. But maybe I am doing something wrong:

`
binary_sensor:
  - platform: mqtt
    name: "Motion Example"
    device_class: motion
    state_topic: "z2m/multisensor/48/1/0"
    json_attributes_topic: "z2m/multisensor/48/1/0"
    value_template: "{{ value_json.value }}"
    payload_on: 'true'
    payload_off: 'false'
`

When using full objects with JSON and the JSON template, it will not be able to match ‘true’. I suspect it is not latching on the “value: true” pair but on “value_id:…”, but I am not sure.
Setting the gateway to send only the value and not the full objects, and commenting out the template works fine.
This is of course not a solution that works for those people who want to use the auto discovery. Am I making a mistake here or needs something to be fixed in the discovery feature?

**Comment by chrisns** [comment]
its an underlying openzwave implementation, you'll likely find it common in most/all things that use openzwave, quick googling finds the same thing mentioned for domoticz for example in forums.

I don't know anything about home assistant discovery stuff, so can't help you on that bit I'm affraid @robertsLando might be able to comment?

**Comment by robertsLando** [comment]
@maichai It depends on you hass version, I had made some changes to make everything compatible with latest version. Try to change 

```
payload_on: true
payload_off: false
```

**Comment by jamesarbrown** [comment]
My Aeotec tri sensor under ozw2mqtt 3.03
```
binary_sensor:
  - platform: mqtt
    state_topic: "homeassistant/Garage/PIR/48/1/0"
    payload_on: true
    payload_off: false
    device_class: motion
    name: "Motion Detect - Garage PIR"
    value_template: "{{ value_json.value }}"
```

**Comment by maichai** [comment]
To be honest I do not see where your all proposals do anything different from what I have posted as configuration. Sorry, no offense intended.
The crucial part was configuring the PIR from "Basic Set" to "Binary sensor report".
So the question is still open, why OZW does not support "Basic Set".

Also still open is the problem around the temperature sensor settings. Could someone please got to your configuration section for the Multisensor 6 and look what you have for the following items? To me those settings seem to be crazy values and I can change not many of those!

Temperature Reporting Threshold (3-112-1-41): 1310976
Temperature Sensor Upper Limit (3-112-1-49): 18350336
Temperature Sensor Lower Limit (3-112-1-50): 256
Temperature Sensor Recover Limit (3-112-1-57): 5121
Temperature Sensor Calibration (3-112-1-201): 1 (accepts only 1,2,-254,-255)

comment: The temperature sensor reading actually is a normal value even within range of what a cheap-o-old meter is displaying!

Is it normal that I have those configuration values? Is it normal that I cannot change them?
If this is normal, maybe the help text can be amended to better explain how to understand the values and what can be set (the help text provides some explanation and value ranges, but it does not work for me!)

Is it a bug in  OZW or zwave2mqtt?

Or is my sensor broken and I should change it?

Thank you for caring and taking your time!

**Comment by Fishwaldo** [comment]
I’m not troubleshooting anything. Just noting that Basic CC should be avoided where possible: https://github.com/OpenZWave/open-zwave/wiki/Basic-Command-Class

**Comment by maichai** [comment]
That text actually says that it should also work with Basic Set, although it  is not the best solution. Actually it does NOT work with Basic set.

The issue of the "crazy" temperature values is still unclear to me. See my last comment above. Maybe  someone knows what is going on there.

**Comment by jamesarbrown** [comment]
@maichai my gut feeling re temp readouts, is that openzwave is getting the values the sensor reports, so quite simply the strange reading must be what the sensor is reporting. Others do seem to have it working. 

Its clear the mutlisensor6, if you do a bit of googling, is not the easiest of devices.

https://www.tabsoverspaces.com/233657-calibrating-aeotec-multisensor-6s-temperature-using-openzwave-in-domoticz

https://community.getvera.com/t/aeotec-multisensor-6-temperature-accuracy/191087

For now, forget the HA stuff, just see if you can get what you want via the ozw2mqtt control panel as first stage?

**Comment by maichai** [comment]
Thanks James, I am acually not talking about HA at all when I talk about the crazy temperature configuration values. Those are the values I get in zwave2mqtt when I click on the sensor and open the configuration section. So this problem is either in the sensor, in OWZ, or in zwave2mqtt.

What I try to understand is, whether I have a faulty hardware, so that I can return it and get a working hardware. But if the problem is with OZW or zwave2mqtt then it makes no sense to replace the hardware.

Therefore I was asking if someone can confirm my observations with their own hardware (then it is not a particular problem with MY sensor, it can still be a problem with ALL sensors, but what can I do then. nothing.)

If some gets "sane" values for the following settings and is able to change them in zwave2mqtt (within reasonable bounds), please let me know! This it what zwave2mqtt displays to me for the temperature settings:

Temperature Reporting Threshold (3-112-1-41): 1310976
Temperature Sensor Upper Limit (3-112-1-49): 18350336
Temperature Sensor Lower Limit (3-112-1-50): 256
Temperature Sensor Recover Limit (3-112-1-57): 5121
Temperature Sensor Calibration (3-112-1-201): 1 (accepts only 1,2,-254,-255)
