### ISSUE TITLE
zwave2mqtt - scroll bars [feat]

### ISSUE THREAD

**Issue by jaredgudnason** [OpenZWave/Zwave2Mqtt#419]
Is there any possibility to get scroll bars in the GUI.  i've been caught a few times where pop-down menus look like they only have a few options until i scroll wheel them, as there are no scroll bars.  additionally the main interface does't have scroll bars, or even resize to fit screen in a lot of cases.

**Comment by robertsLando** [comment]
I’m making a big refactoring of the code, will try to address this next week. 

If you are familiar with vue/vuetify fell free to open a PR :) 

---

Daniel - Software Engineer

Support me at:
    Github sponsors
