### ISSUE TITLE
State change not being published

### ISSUE THREAD

**Issue by brettyj** [OpenZWave/Zwave2Mqtt#42]
Hey,

I've got a door lock that reports it's battery state. I'm finding that while the zwave2mqtt Web interface is showing an updated battery state (93%), the mqtt topic it reports on is still showing the retained message of 100%, so it appears this change isn't being pushed to mqtt.

Any recommendations on what I could try to fix this?

Thanks, love this programme!

**Comment by robertsLando** [comment]
Hi @brettyj . That's strange because every value change that goes to the ui is also forwarded to mqtt. Do you see any error on console log? Are you able to do a debug? Are you running the application using docker, pkg or full nodejs app?

**Comment by brettyj** [comment]
Hey,

I've since restarted the pi so the log has been wiped, but I'll keep an eye out for when I notice the battery has changed. When you say do a debug, how do you want me to debug this? I'm happy to help how I can. I'm using this in docker.

Here's a screenshot showing the disparity:
![image](https://user-images.githubusercontent.com/1395855/60040356-b402be80-96b0-11e9-961f-43bf8a6b5183.png)

Thanks

**Comment by robertsLando** [comment]
Hi brettyj, for the debug you should run the version here in github, than use `npm run dev` to start the frontend page and `node --inpect bin/www` to start the debug on the backend, than set some breakpoints for example in value change and in the websocket to check if the messages are forwarded correctly. 

The screenshot you have sent here is so strange, what is the correct value? 100 or 92?

**Comment by brettyj** [comment]
I've noticed at some point since my comment it's pushed the new battery level to MQTT. I'll keep an eye on it.

I don't know if it's an issue with the device or this component, but there's a string output by the device called "Log Record" which doesn't seem to update very often - every now and then it will, but I don't know what triggers it.

**Comment by robertsLando** [comment]
It is almost impossible that the value changes and the change is not triggered, I think it is mostly a problem with the device or maybe with the device configuration. Try to enable poll of that value and see if the change is triggered correctly.

Daniel

**Comment by brettyj** [comment]
Hey thanks for the reply - how would I go about enabling poll of the value?

**Comment by robertsLando** [comment]
You have two options: 
- Enable pool using Mqtt apis (check docs)
- Add a value in gateway settings values table end check the enable poll flag (suggested) 

Daniel

**Comment by Fishwaldo** [comment]
Polling battery devices wouldn’t work as expected. 

In OZW 1.6 we do refresh the battery level when a device wakes up tho (via a config variable - see https://github.com/OpenZWave/open-zwave/wiki/CommandClass-Compatibility-Flags (refreshonwakeup)

**Comment by robertsLando** [comment]
@Fishwaldo  thanks for the answer. Do you know if openzwave shared is ready for OZW 1.6? I would like to switch to OZW 1.6 in docker container image of zwave2mqtt but I don't want to break everything :(

**Comment by Fishwaldo** [comment]
Sorry. Not sure. I know some work has been done on shared but don’t know how complete it is. Have you tested yet?

**Comment by robertsLando** [comment]
Actually I haven’t any device to test so nope :(

**Comment by robertsLando** [comment]
@Fishwaldo Today I have made some tests (Not with OZW 1.6 but with openzwave shared latest version) and I have found some strange behaviour with valueid type list, seems now something is broken as the value is an integer and not the value string from values array. https://github.com/OpenZWave/node-openzwave-shared/issues/316

**Comment by Fishwaldo** [comment]
You have to take that up with @ekarak. Nothing changed on the OZW side with regards to ValueLists.

**Comment by robertsLando** [comment]
Just sent a PR to fix it

Daniel

**Comment by brettyj** [comment]
Hey,

Sorry to be a pain, but the issue has come back - can I turn on debug logging or something to give you info without debugging it (it wouldn't be easy to debug it as I'm guessing the door lock returns the battery level as and when).

Thanks

**Comment by robertsLando** [comment]
I think it is more likely a bug with the xml file configuration

**Comment by brettyj** [comment]
How do I check that? What do I check for?

**Comment by robertsLando** [comment]
You find all config files here https://github.com/OpenZWave/open-zwave/tree/master/config

Daniel

**Comment by brettyj** [comment]
I'm a bit confused, the battery is showing fine in zwave2mqtt, and people using the hass zwave integration have the battery working fine and it's also using openwave. The issue seems to be that zwave2mqtt isn't broadcasting the change to mqtt

**Comment by robertsLando** [comment]
@brettyj I have added the support for the event "value refreshed" that should be triggered for battery updates. Check if it works now (you need t o use the version from master

**Comment by brettyj** [comment]
@robertsLando hey, I've built a new docker container from master, on boot the batteries are synced, I'll keep an eye on it, currently the battery hasn't changed since setting up the new docker container

**Comment by robertsLando** [comment]
Ok thanks let me know! 

Daniel

**Comment by brettyj** [comment]
I've switched on polling on that value and it seems to be working fine now - all changes are being reflected instantly in HASS - only issue is I can't understand the Polling Intensity - no matter what I set it to, it seems to poll the lock every second or so - how can I make it poll say once an hour or day? (don't want to destroy my battery life)

**Comment by robertsLando** [comment]
The poll intensity is bugged right now I don't know if it has been fixed with openzwave 1.6 should ask to @Fishwaldo . It should be 1* 2* 3* `poll interval` based on the intensity.

Anyway glad it has been fixed so I close this

**Comment by brettyj** [comment]
I've think I've come across a rather urgent bug. I turned off polling, but unknown to me, it was still polling every second and has knocked 10% off my battery life in an hour, so I deleted the entry in the override list, and saved, and it will still polling every second. So I restarted the docker container, and it's STILL polling every second. I've had to stop the docker container because otherwise it will destroy my battery by the end of the day.

How do I solve this? This is pretty urgent as I've had to turn off zwave

**Comment by brettyj** [comment]
Just an update, I deleted the xml files, and reset it up and now it's working, checking once an hour. Phew

**Comment by robertsLando** [comment]
Wil reopen this until news

**Comment by jshridha** [comment]
@brettyj Which xml files did you delete? Did you have to re-add any devices to your network afterwards?

I'm having a similar issue where updates aren't being sent to mqtt.

**Comment by brettyj** [comment]
zwcfg_xxx.xml and zwscene.xml - didn't have to re-add anything

**Comment by robertsLando** [comment]
@brettyj Can I close this now?
