### ISSUE TITLE
[bug] Unable to save configuration in Z2M 3.0.3

### ISSUE THREAD

**Issue by cliviu74** [OpenZWave/Zwave2Mqtt#420]
Zwave2Mqtt 3.0.3

Build/Run method
- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.3
Openzwave Version: 1.6

Unable to save configuration. Making changes to configuration result in an error pop-up "Your configuration contains errors, fix it" on the bottom of the screen when hitting the save button.

**To Reproduce**
1. Go to 'Settings'
2. Change any configuration settings
3. Scroll down to the bottom of the page and click "Save"
4. Black error pop-up appears

**Expected behavior**
Configuration will be saved

**Additional context**
settings.json
```
{"mqtt":{"name":"mqtt","host":"xxx.xxx.xxx","_ca":"","ca":"","_cert":"","cert":"","_key":"","key":"","retain":true,"clean":true,"store":true,"port":1883,"reconnectPeriod":1000,"prefix":"zwave2mqtt","qos":1,"disabled":false},"gateway":{"values":[],"type":0,"hassDiscovery":true,"discoveryPrefix":"homeassistant","retainedDiscovery":false,"payloadType":1},"zwave":{"port":"/dev/ttyACM0","networkKey":"0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX","logging":true,"saveConfig":true,"assumeAwake":true,"pollInterval":1000}}
```
![image](https://user-images.githubusercontent.com/8311970/80799146-fd0f8300-8b9d-11ea-8655-e7d7b8f0266d.png)

I was able to reproduce the same issue on a fresh install. After filling in mandatory fields, error pop-up appears on save.

**Comment by adamcstephens** [comment]
I'm receiving this error on 3.0.3 when attempting to enable `hassDiscovery`.

Downgrading to 3.0.2 allowed me to save the configuration.

**Comment by robertsLando** [comment]
@adamcstephens @cliviu74 Could you show me your configuration? (remove the secret key if any)

**Comment by cliviu74** [comment]
@robertsLando I've attached my config as a snippet in the original bug report. It is settings.json contents you're looking for?
Here it is again anyways.
```
{"mqtt":{"name":"mqtt","host":"xxx.xxx.xxx","_ca":"","ca":"","_cert":"","cert":"","_key":"","key":"","retain":true,"clean":true,"store":true,"port":1883,"reconnectPeriod":1000,"prefix":"zwave2mqtt","qos":1,"disabled":false},"gateway":{"values":[],"type":0,"hassDiscovery":true,"discoveryPrefix":"homeassistant","retainedDiscovery":false,"payloadType":1},"zwave":{"port":"/dev/ttyACM0","networkKey":"0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX, 0xXX","logging":true,"saveConfig":true,"assumeAwake":true,"pollInterval":1000}}
```

Same issue happens on a fresh new install of 3.0.3 in docker. 
Issue is gone on 3.0.2 with the same config, as @adamcstephens mentioned.
Please let me know if there's anything else you need for this.

**Comment by robertsLando** [comment]
Go to zwave settings and add commands timeout and your problem is fixed @cliviu74

**Comment by cliviu74** [comment]
Thanks @robertsLando, it's working now, both on my set-up as well as a new deployment. 
Probably the UX can be improved by making the alert more verbose as to what's missing. This may trip others, especially on a new set-up.
Expanding all configuration options by default would also do, as it would make it obvious what mandatory fields are missing.

**Comment by robertsLando** [comment]
@cliviu74 Yes thanks for the tip :) Big changes are coming in next release

**Comment by cliviu74** [comment]
@robertsLando thanks for the great work, well done.
Looking forward to the new releases.
Cheers!

**Comment by adamcstephens** [comment]
Thanks! I tried changing other settings to figure out what was missing, but the UI didn’t give any direction.
