### ISSUE TITLE
Adding Custom Component [question] 

### ISSUE THREAD

**Issue by jaredgudnason** [OpenZWave/Zwave2Mqtt#426]
trying to follow the documentation for adding a custom component (Honeywell T6 thermostat).
there is a large section on getting the device id (57-8-17),
then there is a section on what goes in the customDevices.json file.  (file doesn't exist, i created in store directory)

but no where does it tell you where/what to do with the device-id?  does it go in the json block, does it go in the json with "device-id": "57-8-17" ?  not sure.

Thanks

**Comment by robertsLando** [comment]
@jaredgudnason If you check `hass/devices.js` you will see some examples and you will understand how it works.

The export should be an object where keys are the deviceIds and values are the device discovery object configuration

**Comment by jaredgudnason** [comment]
where do i find hass/devices.js ?  is that in the zwave2mqtt container or the HA container ?
I dont see it in either of the mapped volumes from HA or z2m.
perhaps i should have asked the question under your docker zwave2mqtt project instead  ;)

**Comment by jaredgudnason** [comment]
Alright, i'm getting there.
I've got my customDevice climate device showing up in HA devices (is there any way to refresh that short of restarting the z2m container) ?
other question, there are a couple other sensors i want to expose to HA, which autodiscover doesn't pick up, Operating State on 66-1-0 and Fan State on 69-1-0.
do i have to define additional type:sensor entries in customDevices for those, or is there another way to do that?

**Comment by jaredgudnason** [comment]
figured it out.. added in the z2m interface.  added additional sensor definitions in the using the json add functionality.

**Comment by robwolff3** [comment]
Hey @jaredgudnason I also have the Honeywell T6 thermostat. Could you share your custom component written for it? It would be  HUGE help. Thanks! :)

**Comment by sdwilsh** [comment]
@robwolff3, I hope you made progress, but for anyone else, I figured I'd share what I ended up with.  Of note, I don't have A/C, so mine is configured as heat-only, so a config might look a little different (also why I'm not submitting a PR).  This is my `customDevices.json`:

```
{
    "57-8-17": [
        {
            "type": "climate",
            "object_id": "thermostat",
            "values": [
                "67-1-1",
                "64-1-0",
                "49-1-1"
            ],
            "mode_map": {
                "off": "Off",
                "heat": "Heat"
            },
            "setpoint_topic": {
                "Heat": "67-1-1"
            },
            "default_setpoint": "67-1-1",
            "discovery_payload": {
                "min_temp": 40,
                "max_temp": 90,
                "modes": [
                    "off",
                    "heat"
                ],
                "mode_state_topic": "64-1-0",
                "mode_command_topic": true,
                "current_temperature_topic": "49-1-1",
                "current_temperature_template": "{{ value_json.value }}",
                "temperature_state_template": "{{ value_json.value }}",
                "temperature_command_topic": true,
                "temperature_unit": "F",
                "temp_step": 1,
                "precision": 0.5
            }
        }
    ]
}
```

**Comment by robertsLando** [comment]
Hi guys, I suggest you to swtich to the new project: https://github.com/zwave-js/zwavejs2mqtt
