### ISSUE TITLE
FGDW002 Door Opening Sensor 2 (FIBARO System) not show open/close

### ISSUE THREAD

**Issue by poudenes** [OpenZWave/Zwave2Mqtt#428]
**Version**

Build/Run method
- [ ] Docker

Zwave2Mqtt version: 3.0.2
Openzwave Version: 1.6.974

**Describe the bug**
Fibaro Door Sensor is add correct. But its not showing open or close of the door

**To Reproduce**

**Expected behavior**
Door/window state give correct state of node. Open or closed

**Additional context**
![Schermafbeelding 2020-05-03 om 14 36 20](https://user-images.githubusercontent.com/4399532/80914402-9334dc00-8d4b-11ea-9055-ded4fe16229c.png)

**Comment by robertsLando** [comment]
@poudenes This is not an issue whit z2m please open this issue on OZW repo
