### ISSUE TITLE
Set row number per page

### ISSUE THREAD

**Issue by pbathuk** [OpenZWave/Zwave2Mqtt#43]
Is it possible to change the default rows per page to something else?
The default appears to be 10, however i prefer 50 or All (50 does not exist), so wondered if there was a config setting to change the default or some JS that can force it to change?

**Comment by robertsLando** [comment]
Actually there is not an option/setting for this, it is hardcoded in ControlPanel.vue here https://github.com/OpenZWave/Zwave2Mqtt/blob/master/src/components/ControlPanel.vue#L64

Just change this: `[10,25,{"text":"All","value":-1}]` with `[50,{"text":"All","value":-1}]`

**Comment by pbathuk** [comment]
Thanks for the assist :)

**Comment by SkyHyperV** [comment]
I changed this in Settings.vue and ControlPanel.vue to 50, ... but even after a service restart, it still only shows the 10, 20 and All.
