### ISSUE TITLE
[feat] support certificate based auth

### ISSUE THREAD

**Issue by chrisns** [OpenZWave/Zwave2Mqtt#430]
at the minute only auth is username password
would be great to support certificates too!
https://github.com/mqttjs/MQTT.js/blob/master/types/lib/client-options.d.ts#L118-L130

should straight forward since these are just strings to file locations, which the mqtt client handles loading the actual files

**Comment by robertsLando** [comment]
@chrisns already workiung, try to set the host url using a secure protocol: eg: tls://localhost

**Comment by chrisns** [comment]
oh! yup, so you are! cool!
