### ISSUE TITLE
[bug] darkmode network graph connections hard to read

### ISSUE THREAD

**Issue by roflmao** [OpenZWave/Zwave2Mqtt#444]
**Version**

Build/Run method
- [ x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.1.0
Openzwave Version: 1.6.xxxx

**Describe the bug**
Network graph in dark mode is hard to read with black on gray: https://www.jottacloud.com/s/0066291ca7ba3ac4d54a5ed40886ffc57c7

**Expected behavior**
Use another color which is human readable.

**Comment by robertsLando** [comment]
PR ready :+1:
