### ISSUE TITLE
[bug] Dark Mode - Highlighted Row in Nodes view not visible

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#452]
**Version**
3.0.4

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.0.4
Openzwave Version: 1.6.1080?? (3.0.4 not listed on docker hub readme)

**Describe the bug**
In dark mode the highlighted row isnt visible as white text on light grey background (image in slack)

**To Reproduce**
1. Dark mode enabled
2. Click on Nodes list row

**Expected behavior**
Darken the text for the highlighted row?

**Comment by robertsLando** [comment]
@jaburges PR is ready :)
