### ISSUE TITLE
[bug] CT101 Thermostat Missing Auto Mode

### ISSUE THREAD

**Issue by Hassiopeia** [OpenZWave/Zwave2Mqtt#453]
**Version**

Build/Run method
- [ X] Docker

Zwave2Mqtt version: 3.1.0
Openzwave Version: 1.6+

**Describe the bug**
The new addition of the CT101 thermostat lacks the Auto mode for setting a heat/cool range in Home Assistant

**To Reproduce**
1. Connect CT101 thermostat
2. setup hass discovery
3. check the modes in hass
4. Validate that its missing from the hass device json

**Expected behavior**
It would include all modes, eg. off, heat, cool, auto, aux heat

**Additional context**
Thanks for adding the CT101. I was holding off on zwave2mqtt until it was easier for me to integrate.

**Comment by Hassiopeia** [comment]
I just managed to update hass/devices.js and the Auto mode shows up, but it does not show the temperature range associated with Auto(heat=68, cool-72). The thermostat was previously handled as a dual thermostat in HA with 2 entities merged until recently someone corrected that for zwave dual thermostats.

**Comment by robertsLando** [comment]
@Hassiopeia Would you mind to fix the configuration? I don't own this device so it's difficult for me to fix this

**Comment by Hassiopeia** [comment]
I will attempt to fix it, however @idyedov might be better suited to help out as he originally added the CT101 and it sounds like he could test it as well. However after some research last night I think the issue primarily lies with the MQTT HVAC component and how it handles thermostats with two setpoints. I don't believe it can merge them together. I managed to configure it to accept the mode of Auto by updating hass/devices.js but I couldn't find a way for it to display both the heat and cool setpoints. This was an issue with this thermostat on HA Zwave as well until it was fixed with HA 103.

**Comment by robertsLando** [comment]
Ok so let's see if @idyedov can help with this. I'm here for everything else

**Comment by idyedov** [comment]
Sorry, don't have much insight on what it takes to handle both heat and cool setpoints separately here. I only use mine in heat mode

**Comment by Hassiopeia** [comment]
I found that there are MQTT HVAC configuration variables for high and low temperatures command, topics, and states. I don't know how to configure them, but I'll try. So I suppose this is just a custom configuration issue for me to figure out in hass/devices.js as @robertsLando mentioned to begin with.

**Comment by robertsLando** [comment]
@Hassiopeia any updates?

**Comment by Hassiopeia** [comment]
I was not able to figure out how to configure the CT101 as a dual set point thermostat using MQTT. I switched to the Home Assistant pre-release of zwave over MQTT and it displayed the thermostat correctly in HA. I think the issue really lies with either the MQTT HVAC integration in HA or my ability to configure it.
