### ISSUE TITLE
Weird behavior with double switch

### ISSUE THREAD

**Issue by Phontana** [OpenZWave/Zwave2Mqtt#461]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.1.0
Openzwave Version: 1.6.0

**Describe the bug**
I have a Fibaro Double Switch in my Z-wave network. I have configured MQTT in Home Assistant without discovery, and all of my devices are working well, except for the double switch. I am seeing this behavior:

- When I turn on the switch in Home Assistant, the switch is turned on in Zwave2Mqtt and the state is updated properly in Home Assistant;
- When I turn off the switch in Home Assistant, the switch is **not** turned off in Zwave2Mqtt and the state is **not** updated properly in Home Assistant.
- When I turn on the switch in Zwave2Mqtt, the switch is turned on and the state is updated properly in Home Assistant;
- When I turn off the switch in Zwave2Mqtt, the switch is turned off and the state is updated properly in Home Assistant;

And now the really strange part: when I enable Home Assistant Discovery on a random topic (something other than configured in Home Assistant as discovery topic) and I do the same as above, this is the result:

- When I turn on the switch in Home Assistant, the switch is turned on in Zwave2Mqtt and the state is updated properly in Home Assistant;
- When I turn off the switch in Home Assistant, the switch is **correctly** turned off in Zwave2Mqtt and the state is ** correctly** updated properly in Home Assistant.
- When I turn on the switch in Zwave2Mqtt, the switch is turned on and the state is updated properly in Home Assistant;
- When I turn off the switch in Zwave2Mqtt, the switch is turned off and the state is updated properly in Home Assistant;

Is it possible that the parsing of the commands from Home Assistant is working different when discovery is turned on? Even though I never use the discovered entities?

This is the configuration of the switch in Home Assistant:

```
- platform: mqtt
  name: bathroom_fan
  state_topic: "zwave/bathroom/double_switch/37/2/0"
  command_topic: "zwave/bathroom/double_switch/37/2/0/set"
  value_template: "{{ value_json.value }}"
  payload_on: true
  payload_off: false
```

Maybe something is wrong with my configuration, but that doesn't explain the behavior described above.

**To Reproduce**
See description above.

**Expected behavior**
I don't need to enable discovery to update the switch properly, it should work exactly the same with or without discovery enabled.

**Additional context**
-

**Comment by robertsLando** [comment]
@Phontana try to use `payload_on: 'true'` and `payload_off: 'false'`

**Comment by Phontana** [comment]
@robertsLando I disabled Hass Discovery and tested with those. When using `payload_on: 'true'` and `payload_off: 'false'`, the switch does update on the Zwave2Mqtt part, but the state in Home Assistant isn't updated. So this makes it even worse compared to using `payload_on: true` and `payload_off: false`. 

I also tried `payload_on: 'True'` and `payload_off: 'False'` and in that case, I get the same behavior as described in the first post. 

So turning on the switch from Home Assistant does work, a message containing `True` is posted om the command_topic, the state is updated correctly, but when turning it off from Home Assistant, `False` is posted to the command_topic but Zwave2Mqtt doesn't seem to be able to parse it. The only thing I see on the state topic is an update of the `"lastUpdate"` field in the JSON message.

**Comment by robertsLando** [comment]
@Phontana check what z2m sends to that topic and then work on hass configuration, I don't see any issue with z2m here but just hass that isn't transltaing the value that comes from mqtt correctly. Try also to use a command template, what message is hass sending when you press the switch?

**Comment by Phontana** [comment]
@robertsLando I disabled Hass Discovery and tested some things. I see the following:

- On the command topic (`zwave/bathroom/double_switch/37/2/0/set`) the message `True` is sent (no JSON, just plain text). The z2m logs shows this as a result:
```
z2m:Mqtt Message received on zwave/bathroom/double_switch/37/2/0/set +22s
z2m:Zwave zwave node 35: changed: 37-2-0:Instance 2: Switch:false -> true +3s
```
On the state topic (`zwave/bathroom/double_switch/37/2/0`), the `value` property is updated properly and this is reflected in Home Assistant.

- On the command topic (`zwave/bathroom/double_switch/37/2/0/set`) the message `False` is sent when the switch is turned off (again, no JSON, just plain text). The z2m logs shows this as a result:
```
z2m:Mqtt Message received on zwave/bathroom/double_switch/37/2/0/set +2s
z2m:Zwave zwave node 35: changed: 37-2-0:Instance 2: Switch:true -> true +2s
```
On the state topic (`zwave/bathroom/double_switch/37/2/0`), the `value` property is **not** updated at all and therefore the switch remains turned on.

**Comment by Phontana** [comment]
By mentioning the `command_template`, you put me on the right track. Although the MQTT switch doesn't have the `command_template` option, it does have `payload_on`, `payload_off`, `state_on` en `state_off`.

I updated my configuration to the code below and now it is working as expected.

```
- platform: mqtt
  name: bathroom_fan
  state_topic: "zwave/bathroom/double_switch/37/2/0"
  command_topic: "zwave/bathroom/double_switch/37/2/0/set"
  value_template: "{{ value_json.value }}"
  payload_on: '{ "value" : true }'
  payload_off: '{ "value" : false }'
  state_on: true
  state_off: false
```

Thank you for your help, it is much appreciated.
