### ISSUE TITLE
Re-sending zwave commands after reboot

### ISSUE THREAD

**Issue by matthew-larner** [OpenZWave/Zwave2Mqtt#462]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
The issue I'm facing is that after a reboot, it seems to resend the last state from mqtt to all z-wave devices. The reason this is an issue is because my garage door only supports toggle - when zwave2mqtt sends the same state to it after a reboot, it toggles the garage door to open.

**Comment by robertsLando** [comment]
@matthew-larner That's not an issue, that's mqtt behaviour, if you have retain flag set to true you have to disable it
