### ISSUE TITLE
[feat] Ability to set a blank name

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#463]
**Is your feature request related to a problem? Please describe.**
I was about to ensure I wasn't pushing my z-wave devices to HASS with names (as I want to create my devices there, myself, and want to reuse the names). But I couldn't set a blank name again, in Z2M.

**Describe the solution you'd like**
Ability to clear a name for a node/device in Z2M

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by robertsLando** [comment]
PR ready @LordMike :)
