### ISSUE TITLE
[bug] ZW095 Home Energy Meter Gen5 (AEON Labs) not updating / wrong initialization

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#464]
**Version**
Z2M docker dev

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.1.0
OpenZwave 1.6.1115

**Describe the bug**
I have just bought a ZW095 Home Energy Meter Gen5 (AEON Labs)
It registeres fine in Z2M, but it never updates. It only updates if I manually select to refresh node info. Nothing in the log, nothing in MQTT. Total silence.

**To Reproduce**
Just include the node and wait. Nothing happens

**Expected behavior**
The device to update as expected according to settings.

**Additional context**
I have found how to make the device update. After hours and hours of googling.
I found it [here](https://community.openhab.org/t/solved-home-energy-meter-hem-g3-aeon-labs-gen5-zw095-do-not-report-automatically/44579/22) Austris_V post from Dec '18 (now called @billiaz )

It is something with the association groups that is not set up correctly.
I downloaded Z-Wave PC Controller and manually set the association groups (I think that is what I did)

![image](https://user-images.githubusercontent.com/6589760/81509386-89424880-930a-11ea-9cbd-de775297fe70.png)

After sending the command "85 01 0X 01" (where X is the Grouping identifyer) the device started updating according to the set number of seconds in setting 111 to 113

Please include a way to do this in Z2M. 

I don't know if this is a bug for Z2M or OpenZwave. One could say the device is not properly initializing.

**Comment by magpern** [comment]
Logfile from the include procedure is [here](https://paste.ubuntu.com/p/vJDSnBXwTr/)

**Comment by robertsLando** [comment]
> I don't know if this is a bug for Z2M or OpenZwave. One could say the device is not properly initializing.

I think it's firstly a device compatibility issue and from another side a OZW issue but definetly not an issue with z2m @magpern. Please open this issue on OZW library or let's see if @Fishwaldo can reply here

**Comment by magpern** [comment]
Closing and reopening in openzwave https://github.com/OpenZWave/open-zwave/issues/2214
