### ISSUE TITLE
[feat] bulk subscribe to wildcard vs subscribing to individual topics

### ISSUE THREAD

**Issue by chrisns** [OpenZWave/Zwave2Mqtt#472]
**Is your feature request related to a problem? Please describe.**
Some brokers measure/bill/limit on the number of individual subscriptions you create, conceptually they can be compute intensive at scale especially with big ozw networks with over a hundred devices equating to in excess of a thousand subscriptions for all the individual values of each node.

**Describe the solution you'd like**
Therefore it would be great to by configuration subscribe to a wildcard based on the prefix.

**Describe alternatives you've considered**
some brokers e.g. aws limit you to 50 subscriptions per connection, so in theory you could shard between multiple mqtt connections but that feels even more ugly!

**Comment by robertsLando** [comment]
I'm ok for this. I think we could use `<prefix>/+/+.../set` we just need to count the 'levels' on subscribe and check if we have a wildecard subscription for that :)
