### ISSUE TITLE
3-Speed fan lists "Dim" and "Bright" rather than something more applicable

### ISSUE THREAD

**Issue by zlalanne** [OpenZWave/Zwave2Mqtt#48]
When controlling a 3-speed fan (I'm using the GE one for instance) the buttons that show up are for "Bright" and "Dim". It probably makes sense to change these to "Faster" and "Slower" for fans.

![zwave2mqtt_fan](https://user-images.githubusercontent.com/571411/60763607-6a658c80-a03d-11e9-855b-9d46be26312d.png)

**Comment by robertsLando** [comment]
The label you see there are from Openzwave device xml configuration file. You should edit that and send a PR to openzwave I have no control of that. Find the configuration there: 
https://github.com/OpenZWave/open-zwave/tree/master/config

Daniel
