### ISSUE TITLE
[bug] State of the NOTIFICATION_REPORT(0x0E=siren) is not reflected in the control panel

### ISSUE THREAD

**Issue by petrovcicklemen** [OpenZWave/Zwave2Mqtt#480]
**Version**

Build/Run method
- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.1.0
Openzwave Version: 1.6.1115

**Describe the bug**
I am testing a device, which sends out a NOTIFICATION_REPORT(0x0E=siren, 0x01=active siren), when it receives an arbitrary NOTIFICATION_REPORT. The device does send out the mentioned notification report, OpenZwave also detects it (one can see the transition from Clear -> Active -> Clear), but the state is not reflected in the control panel.

**To Reproduce**
This device is not yet on the market, but I can help with reproduction and other tests, if it would help.

**Expected behavior**
After receiving the mentioned notification report, the state should be suitably updated to "Active".

**Additional context**
I'm attaching a gif, that shows the field and the  Zwave2MQTT/OpenZWave console output, where the transitions are detected.

![NotificationTypeSirenNotUpdated](https://user-images.githubusercontent.com/19154318/81820778-50d08380-9531-11ea-977d-f77f18423bcc.gif)

**Comment by robertsLando** [comment]
@petrovcicklemen If you refresh the page, is the status of the siren correct then?

**Comment by petrovcicklemen** [comment]
@robertsLando: Yes, it is the only field, that is not automatically refreshed. I'm attaching a gif.
![NotificationTypeSirenNotUpdated2](https://user-images.githubusercontent.com/19154318/81822252-24b60200-9533-11ea-825f-7628d5d9313e.gif)

**Comment by robertsLando** [comment]
I'm thinking that maybe it's a vuetify bug that prevents to disabled inputs field to be refreshed correctly

I will try to set it as readonly to see if this make it work

**Comment by petrovcicklemen** [comment]
@robertsLando: Thanks.

**Comment by robertsLando** [comment]
@petrovcicklemen PR is ready

**Comment by petrovcicklemen** [comment]
@robertsLando: I just retested this using the latest version of the Zwave2Mqtt_v3.2.1. It appears, that the issue is still present.

![luxylight_notificationtypesirennotupdated](https://user-images.githubusercontent.com/19154318/82647931-32e0de00-9c17-11ea-88a3-6205ae4bb09e.gif)

**Comment by robertsLando** [comment]
You confirm that a refresh of the page makes the data display correct and that this only happens with read-only fields?

**Comment by petrovcicklemen** [comment]
@robertsLando I only tested like last time. As can be seen from the gif,  the field is only updated, if you refresh the website. All the other fields, used for sending actuation commands and for displaying the current selection, are automatically updated.

**Comment by robertsLando** [comment]
Humm sincerly I don't know why this happens, all fields are created from the same template the only thing that changes is the read-only attribute to them, I dont't know if that is a vuetify issue :( Are you able to debug using chrome devtools? You should add a break in socket value change event and check if the event is received correctly and the node value is updated: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/src/components/ControlPanel.vue#L1209

**Comment by robertsLando** [comment]
@petrovcicklemen I have gound the bug, fixed once #538 will be merged

**Comment by petrovcicklemen** [comment]
Thanks @robertsLando. I already retested the device on v3.2.2 and everything works correctly now.
