### ISSUE TITLE
[question] Groups? How to use?

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#483]
I assume Groups is associations. How is it to be used?

If I select a node and a target and press add
![image](https://user-images.githubusercontent.com/6589760/81855528-c2272b00-955f-11ea-8636-e2c736c8d026.png)
I see some movement in the logs.

If I refresh the page. Everything is gone!

![image](https://user-images.githubusercontent.com/6589760/81855641-e551da80-955f-11ea-8450-cebda23d433b.png)

One would think "Current associations" would be populated.

**Comment by robertsLando** [comment]
@magpern Do you see z2m log output? Does it receive the group association request? 

Once you press ADD the association should be displayed on current associations

**Comment by magpern** [comment]
When I press ADD after selecting the node, group and target. I see this in the log file
[logfile after add button pressed](https://paste.ubuntu.com/p/JfDYhfNnQk/)

This is what I see in z2m
![image](https://user-images.githubusercontent.com/6589760/81943297-7d50d200-95fb-11ea-9096-852e4adf79db.png)

This is what I see after pressing F5 (refresh) and selecting the same node
![image](https://user-images.githubusercontent.com/6589760/81943398-9e192780-95fb-11ea-9466-0eb5291a7227.png)

Nothing in the log file when pressing the "GROUPS" tab. Current associations is empty, I have never seen anything here

**Comment by robertsLando** [comment]
@magpern I don't see errors in your log file. Is that node 11?

```
2020-05-14 13:50:07.622 Info, Node006, Association::Set - Adding node 11 to group 2 of node 6
,2020-05-14 13:50:07.623 Detail, 
,2020-05-14 13:50:07.623 Detail, Node006, Queuing (WakeUp) AssociationCmd_Set (Node=6): 0x01, 0x0b, 0x00, 0x13, 0x06, 0x04, 0x85, 0x01, 0x02, 0x0b, 0x25, 0xa7, 0xea
,2020-05-14 13:50:07.623 Info, Node006, Get Associations for group 2 of node 6
,2020-05-14 13:50:07.623 Detail, 
,2020-05-14 13:50:07.624 Detail, Node006, Queuing (WakeUp) AssociationCmd_Get (Node=6): 0x01, 0x0a, 0x00, 0x13, 0x06, 0x03, 0x85, 0x02, 0x02, 0x25, 0xa8, 0xeb
,  z2m:Zwave Success zwave api call addAssociation  +3s
,  z2m:App Zwave api call: getAssociations [ 6, 2 ] +497ms
,  z2m:Zwave Success zwave api call getAssociations [] +495ms
,2020-05-14 13:50:09.501 Detail, Node016,   Received: 0x01, 0x18, 0x00, 0x04, 0x00, 0x10, 0x12, 0x56, 0x01, 0x32, 0x02, 0x21, 0x74, 0x00, 0x04, 0x43, 0x99, 0x00, 0x05, 0x00, 0x04, 0x43, 0xae, 0xc2, 0xda, 0xf9
,2020-05-14 13:50:09.501 Detail, 
```

The call is successfully made but maybe your devices cannot be grouped in that group?

**Comment by Fishwaldo** [comment]
> Queuing (WakeUp)

Device is sleeping. It needs to be woken up so the commands can be sent.

**Comment by magpern** [comment]
It is Node006.
I'm not saying there is an error. The device node006 successfully bound to the other device (wall switch).

What I think is wrong, is the GUI.

It gives you the impression it will list all active bindings, since that is what it says.
But it do not. It is always empty.

Which in turn makes it hard to unbind anything, since it is not listed.

**Comment by robertsLando** [comment]
> It gives you the impression it will list all active bindings, since that is what it says.
But it do not. It is always empty

If it doesn't show them, it means I'm not receiving them from the `getAssociations` call as you can see from your log

**Comment by magpern** [comment]
> If it doesn't show them, it means I'm not receiving them from the `getAssociations` call as you can see from your log

How do you get it to do a `getAssociations`?
I have devices from four different vendors, and none show any associations. The Node006 above is associated to a wall switch and it works, the light turns on on movement.

Is there any other program I can run to trigger commands and see the result?

**Comment by robertsLando** [comment]
You can trigger those commands using mqtt apis. Anyway every device should at least show the association of lifeline group with the controller. If you select lifeline group do you see the controller in associations? 


---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by robertsLando** [comment]
Some devices are multi instances, for example if a thermostat has 3 temperature sensors it will have 3 instances for the temperature 

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by magpern** [comment]
Thank you! My questions have been answered
