### ISSUE TITLE
[bug] Clicking a device the second time, removes the discovery doc

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#489]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: `3.1.0`
Openzwave Version: `1.6.1115`

**Describe the bug**
Clicking a device twice, will remove the discovery doc from the UI. It seems every second click will show/hide the doc.. Hiding the doc also presents a validation error.

**To Reproduce**
1. Select a node
2. Select a device in the devices list
3. Select the same device again
4. Observe the discovery doc disappearing, and a validation error is shown

**Expected behavior**
Clicking a device multiple times will not remove its details.

**Additional context**
N/A

**Comment by LordMike** [comment]
I just noticed the default of the page is no doc and an error. Maybe the second click is deselecting the device?

**Comment by robertsLando** [comment]
Yes that’s an expexted behaviour, the second click is deselecting it, like it is for nodes in nodes table

---

Daniel - Software Engineer

Support me at:
    Github sponsors
