### ISSUE TITLE
[bug] Empty node type and product after adding new device

### ISSUE THREAD

**Issue by RualdOrdelman** [OpenZWave/Zwave2Mqtt#49]
**Version**
Got this bug in version in the latest stable and the current head.

Steps:~
-add a new node 
-Choosing in the UI the controller option "Add node", cancel the secure option
-Including the node by pressing the including option on the node
-The node is added successful

The new node is displayed in the list but with an empty type and product. It looks like there's no refresh or something. 

When I look at the log I see all the information. In the UI all the entities and config option are available in the UI. Renaming the node in the UI are not displayed in the interface. 

When I restart the application of docker container the type, product and new node name  is displayed correctly.

<img width="1108" alt="Schermafbeelding 2019-07-13 om 12 37 37" src="https://user-images.githubusercontent.com/1227427/61172509-a5a81400-a585-11e9-8a88-d06c6bc366cc.png">
<img width="957" alt="Schermafbeelding 2019-07-13 om 12 37 58" src="https://user-images.githubusercontent.com/1227427/61172516-b5275d00-a585-11e9-8392-0aa6b65030b7.png">

**Comment by robertsLando** [comment]
@RualdOrdelman could you try with latest commit?

**Comment by robertsLando** [comment]
@RualdOrdelman I have changed the way UI updates on node add events, try now

**Comment by robertsLando** [comment]
@RualdOrdelman Now it is fixed with https://github.com/OpenZWave/Zwave2Mqtt/commit/1b9fd36037c263d140d6ec624302d713a6bb089c
