### ISSUE TITLE
[feat] Update 'Last active' when messages arrive from nodes

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#490]
**Is your feature request related to a problem? Please describe.**
I understand [the `Last Active` column](https://user-images.githubusercontent.com/1027111/82088864-d18aad80-96f2-11ea-9830-dab3c531e5e1.png)) as the last time this specific node was active on my network. If a node was last active, days ago, it hasn't sent any message since then.

In reality, the column shows the last time a full refresh was done (?). This seems misleading.

**Describe the solution you'd like**
That any time a message is received from a node (any kind of heartbeat, update, value, config, ..), the `Last Active` is amended to show this.

**Describe alternatives you've considered**
N/A

**Additional context**
I've identified [this code](https://github.com/OpenZWave/Zwave2Mqtt/blob/ac44aed7bf6cbdbf26609b583f4d4552bd0e089d/lib/ZwaveClient.js#L440) that seems to be the only place setting the `Last Active` value. 

Other functions in this file would need to have the same update. Perhaps a more generic place is available?

**Comment by robertsLando** [comment]
@LordMike In poor words you would like that `Last Active` is updated everytime I receive something from the node, included value changes?

**Comment by LordMike** [comment]
Yes. My thinking is that the timestamp showing the last time the device communicated - which would be helpful to identify when a battery-powered device last did something, or that mains powered devices actually are communicating..

.. is more helpful than a timestamp showing the last time the device was scanned/refreshed..

**Comment by Fishwaldo** [comment]
Already tracked in OZW: see http://www.openzwave.com/dev/classOpenZWave_1_1Manager.html#a5f331b5ae9e90a44d08552c4b26ff9f4

**Comment by LordMike** [comment]
Oh - maybe the value just needs to be surfaced? .. and the current value be renamed to `Last refresh` ?

**Comment by robertsLando** [comment]
@LordMike Actually I'm not calling that api to get that value but I'm updating the value when I get a notification, I think that from my side it would be better to 'manually' update it when something is received from the node instead of calling that function in loop to update the value

**Comment by LordMike** [comment]
Right. Z2M doesn't call the statistics api, as it is now?

**Comment by Fishwaldo** [comment]
There may be cases where a device communicates over the network, but OZW never “exposes” a change on the device. Eg when it “wakes-up” and OZW has nothing in the queue for it, OZW will just send a message saying “wakeup-no more information” to the device which triggering anything on the app side of things. 

A scenario where this happens more often than not is a battery powered sensor (Eg window) that is never opened. Users want to know if it’s still “alive” without having to open/close the window to test it. (Or water sensor where flooding is a exception)

**Comment by LordMike** [comment]
@Fishwaldo is there a neat way to get events for these kinds of updates, from OZW, that Z2M might use?

**Comment by ahochsteger** [comment]
I want to support the use case of @LordMike, since I just fell into the same trap thinking that half of my devices don't have a connection to the Z-Wave network anymore because of showing days-old "Last Active" values.
Is there a work-around possible?
I'm also willing to get my hands dirty and try to adjust the code myself, if someone could point me to the right direction ...

**Comment by robertsLando** [comment]
@ahochsteger 

`lastActive` is updated on `lib/ZwaveClient`:

Node status: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L469
Notification: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L575

You could simply add it there too: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L506

But you need to call `this.emit('nodeStatus', ozwnode)` in order to send the update to the ui directly. Or you could update it silently but a refresh is needed in order to see it update

**Comment by ahochsteger** [comment]
@robertsLando, thanks for the hint, seems to be straight forward - I'll give it a try :-).
Do you think that adding the event emit might cause performance problems in the UI if you have a large number of nodes?
For example I have currently more than 60 active devices.

**Comment by ahochsteger** [comment]
@robertsLando, I've got a few more questions:

**(1) HOWTO Question**
What's the desired way of running z2m in development mode while accessing the serial device and setting all zwave configuration?
I tried to do it using `npm run dev` and put all settings into the Zwave section while disabling the gateway (as I do not want to send messages to the MQTT broker during development) but it doesn't seem to save the change. After reloading everything is gone.
Without that it's hard to tell, if my changes in the code are really working and I don't want to send an untested PR ...

**(2) Current implementation approach**
My current try was to add the lastActive update to this line, just after updating the cache:
https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L524
Or is it better placed within the `if (ozwnode.ready)` block?
I read that nodeReady() is triggered after all values have been added, but I'm not sure what that means in the context of this issue.

**Comment by robertsLando** [comment]
`npm run dev` starts the frontend in development mode at the port `8082` with hot reloading feature. You also need to start the backend in another terminal with `npm start` or `node bin/www` or `nodemon bin/www` if you want also the hot reloading of the server in development mode
