### ISSUE TITLE
[question] Honeywell 39351 (ZW3005) In-Wall Smart Dimmer Strange Operation

### ISSUE THREAD

**Issue by jasonsinclair5** [OpenZWave/Zwave2Mqtt#491]
I have a couple in-wall Honeywell dimmer switches, and the operation is inconsistent in home assistant/ mqtt. The entity in HA improperly reports state because if you send a payload of 0 to shut off, it changes the value from 99 to either 97 or 98 and the light shuts off. Even if I manually send the command within MQTT Explorer. Sending 255 when the value is 0 will put it at 2 or 3, and 99 will put it at 99, etc. The brightness scale within HA works properly, but I cannot turn on/off the light and have it report the light is off. If I manually hit the up rocker on the switch, it changes the value to its last state. Pressing down on the rocker will change it to 0. These are consistent, but any MQTT command is not. Below is the HA discovery template generated.

```
{
  "schema": "template",
  "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
  "state_topic": "homeassistant/OfficeLight/38/1/0",
  "state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
  "command_topic": "homeassistant/OfficeLight/38/1/0/set",
  "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
  "command_off_template": "0",
  "device": {
    "identifiers": [
      "zwave2mqtt_0xe0a10345_node6"
    ],
    "manufacturer": "Honeywell",
    "model": "39351 / ZW3005 In-Wall Smart Dimmer (0x3038)",
    "name": "Office Light",
    "sw_version": "Unknown"
  },
  "name": "Office Light",
  "unique_id": "zwave2mqtt_0xe0a10345_6-38-1-0"
}
```

**Comment by jasonsinclair5** [comment]
I think it might be related to this issue: https://github.com/OpenZWave/Zwave2Mqtt/issues/116

I added that value to the gateway values table: polling 1 sec, checked verify and it appeared to be working. However, within a couple minutes the gateway crashed and I had to restart the docker container. It kept crashing unless I removed that value from the table. I tried to comb through the logs, and here's the best thing I could find:

```
2020-05-17 02:24:27.712 Info, Node002, Initializing Node. New Node: false (false)
2020-05-17 02:24:27.722 Detail, Node006, Polling: COMMAND_CLASS_SWITCH_MULTILEVEL index = 0 instance = 1 (poll queue has 0 messages)
2020-05-17 02:24:27.722 Error, MutexImpl::UnLock failed with error: 11 (1)
```

Any thoughts?

**Comment by LordMike** [comment]
I have had some bouts with the Z2M dimmer thingy, primarily with the scaling of the values. What's the maximum value of the Honeywell 39351?

I'm not sure about the crashes, but getting back a different value than you sent definitely sounds like [my scaling experiences](#488).

**Comment by jasonsinclair5** [comment]
>What's the maximum value of the Honeywell 39351?

The value is 0-99 and 255 being last state I believe. I have another dimmer (Nutone WD500Z-1) that operates the same way with the same values.
 
> I'm not sure about the crashes, but getting back a different value than you sent definitely sounds like [my scaling experiences](#488).

So I think I might have made some headway. I disabled polling on the manual gateway value and just checked "Verify Changes" and the dimmers have been operating correctly using the default HASS discovery template. So far no crashes, but I'll keep monitoring.

**Comment by robertsLando** [comment]
@Fishwaldo Could you check [this](https://github.com/OpenZWave/Zwave2Mqtt/issues/491#issuecomment-629734933) log?

What could cause that kind of error?

**Comment by jasonsinclair5** [comment]
Adding "Verify Changes" for the device under gateway settings fixed this issue.
