### ISSUE TITLE
[bug] Docker Image Missing

### ISSUE THREAD

**Issue by chriskacerguis** [OpenZWave/Zwave2Mqtt#492]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
Per the docs, the docker image `openzwave/zwave2mqtt` does not exist in hub.docker.com or the https://hub.docker.com/u/openzwave org/user.  Trying to run the docker run per the docs results in:
```
Unable to find image 'openzwave/zwave2mqtt:latest' locally
docker: Error response from daemon: pull access denied for openzwave/zwave2mqtt, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**To Reproduce**
1. SSH to Raspberry Pi
2. Install docker via get.docker.com
3. Run `docker run --rm -it -p 8091:8091 --device=/dev/ttyACM0 -v $(pwd)/store:/usr/src/app/store openzwave/zwave2mqtt:latest`

**Expected behavior**
I expect the image to run.

**Additional context**
I did find the repo at `robertslando/zwave2mqtt:latest`

**Comment by chrisns** [comment]
Hi, that’s my fault. Sorry. I’ve not fixed the build. You can get it from here in the meantime https://hub.docker.com/r/robertslando/zwave2mqtt/dockerfile

**Comment by chrisns** [comment]
#473

**Comment by robertsLando** [comment]
@chriskacerguis We are working on this

**Comment by robertsLando** [comment]
@chriskacerguis Please use: `robertslando:zwave2mqtt:latest`
