### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by lsilva171** [OpenZWave/Zwave2Mqtt#500]
**Version**
3.2.0
Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

**Describe the bug**
Zwave2MQTT was working properly before upgrading Zwave2MQTT container to 3.2.0
After the upgrade, thefollowing error shows up in the log:

  z2m:Store scenes.json not found +0ms
,  z2m:Gateway No customDevices file found +0ms
,Error: Cannot find module './package-lock.json'
,Require stack:
,- /usr/src/app/app.js
,- /usr/src/app/node_modules/app-root-path/lib/app-root-path.js
,- /usr/src/app/node_modules/app-root-path/index.js
,- /usr/src/app/bin/www
,    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
,    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
,    at Module.require (internal/modules/cjs/loader.js:1019:19)
,    at require (internal/modules/cjs/helpers.js:77:18)
,    at Object.<anonymous> (/usr/src/app/app.js:21:32)
,    at Module._compile (internal/modules/cjs/loader.js:1133:30)
,    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
,    at Module.load (internal/modules/cjs/loader.js:977:32)
,    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
,    at Module.require (internal/modules/cjs/loader.js:1019:19)
,    at require (internal/modules/cjs/helpers.js:77:18)
,    at require (/usr/src/app/node_modules/app-root-path/lib/app-root-path.js:14:11)
,    at /usr/src/app/bin/www:33:15
,    at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
,    at Promise._settlePromiseFromHandler (/usr/src/app/node_modules/bluebird/js/release/promise.js:547:31)
,    at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:604:18) {
,  code: 'MODULE_NOT_FOUND',
,  requireStack: [
,    '/usr/src/app/app.js',
,    '/usr/src/app/node_modules/app-root-path/lib/app-root-path.js',
,    '/usr/src/app/node_modules/app-root-path/index.js',
,    '/usr/src/app/bin/www'
,  ]
,}
,

And the the web page is not accessible anymore 

**To Reproduce**

**Expected behavior**

**Additional context**
The container is running on Raspberry PI 3B with Ubuntu.
Returning the container to 3.1.0 fixes the issue and Zwave2MQTT is back to work

**Comment by talzac** [comment]
Same problem, and I thought it was my fault, I have tried to fix this now in an hour.... how can I doanload the old ?

**Comment by lsilva171** [comment]
> Same problem, and I thought it was my fault, I have tried to fix this now in an hour.... how can I doanload the old ?

You will need to delete the current container and docker run it again, this time using robertslando/zwave2mqtt:3.1.0 instead of robertslando/zwave2mqtt:latest

**Comment by towerhand** [comment]
Yup can confirm. I had to roll back to 3.1.0 since 3.2.0 is broken and won't start.

**Comment by iblis82** [comment]
Same

**Comment by chrisns** [comment]
3.2.1 is currently building with a fix for this https://github.com/OpenZWave/Zwave2Mqtt/runs/686633361

**Comment by dgooglr** [comment]
> 3.2.1 is currently building with a fix for this https://github.com/OpenZWave/Zwave2Mqtt/runs/686633361

Awesome! This solved it for me
