### ISSUE TITLE
[bug]Device in Home Assistant looses its set-values

### ISSUE THREAD

**Issue by magpern** [OpenZWave/Zwave2Mqtt#504]
Latest dev version docker

My server automatically updates to the latest docker and I have noticed that I loose some settings in Home Assistant when it updates.

I have a TF 056 Thermostat that I have altered a little in `customDevices.js`

I have this, so I can set the "Energy Heat"-mode from the GUI in HA. (auto maps to Energy Heat)

```module.exports = {
  '411-514-3': [
    { // Heatit Thermostat TF 056 (ThermoFloor AS)
      type: 'climate',
      object_id: 'thermostat',
      values: ['64-1-0', '49-2-1', '67-1-1', '67-1-2', '67-1-11'],
      mode_map: { 'off': 'Off', 'heat': 'Heat', 'cool': 'Cool', 'auto': 'Energy Heat' },
      setpoint_topic: { "Heat": '67-1-1', "Cool": '67-1-2', "Energy Heat": '67-1-11' },
      default_setpoint: '67-1-1',
      discovery_payload: {
        min_temp: 15,
        max_temp: 30,
        temp_step: 0.5,
        modes: ['off', 'heat', 'cool', 'auto' ],
        mode_state_topic: '64-1-0',
        mode_command_topic: true,
        current_temperature_topic: '49-2-1',
        current_temperature_template: '{{ value_json.value }}',
        temperature_state_template: '{{ value_json.value }}',
        temperature_command_topic: true
      }
    }
```

When the updated docker starts, these settings are lost. It defaults to the standard implementation of the zwave2mqtt implementation of the device. The "auto" mode is not shown in HA anymore.

![image](https://user-images.githubusercontent.com/6589760/82320064-f2911e00-99d2-11ea-9168-8d459798b75c.png)

The component in HA also has lost its settings. It shows the pemp, but the set temperature is "unknown" and the mode is also "unknown"

If I manually go to zwave2mqtt and push new values to the device. The values appear in HA
![image](https://user-images.githubusercontent.com/6589760/82320434-911d7f00-99d3-11ea-8aee-0fc9a657baae.png)

![image](https://user-images.githubusercontent.com/6589760/82320470-a1cdf500-99d3-11ea-9537-94197574e473.png)

But to get back the "auto" mode I have to re-discover device
![image](https://user-images.githubusercontent.com/6589760/82320639-e6f22700-99d3-11ea-91a3-7c8490ec896c.png)

But when I re-discover the device, the set values disappear, and I have to set the set values again.

![image](https://user-images.githubusercontent.com/6589760/82320782-1f920080-99d4-11ea-8646-20d951fe7261.png)

It would be nice if the devices preserve the set values after a reboot / docker update / Home Assistant reboot etc

**Comment by robertsLando** [comment]
@magpern I need to know you docker-compose content or your docker command. In order to have persistent files you have to map store folder in a local folder as described [here](https://github.com/OpenZWave/Zwave2Mqtt/tree/master/docker#run-using-local-folder)

This is not really a bug but more like a question :)

**Comment by magpern** [comment]
Well, the bug is that the settings are restored to default and not uses the customDevice.js

The second bug is that the values are not retained (fetched) when zwave2mqtt restarts and/or Home Assistant restarts

**Comment by robertsLando** [comment]
> Well, the bug is that the settings are restored to default and not uses the customDevice.js

Nothing has changed on that side, if the file is here z2m will load it at boot (check logs to have a confirm)

> The second bug is that the values are not retained (fetched) when zwave2mqtt restarts and/or Home Assistant restarts

Did you follow this: https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta

> In your Home Assistant configuration.yaml

```yml
mqtt:
  discovery: true
  discovery_prefix: <your_discovery_prefix>
  broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```

**Comment by magpern** [comment]
> > Well, the bug is that the settings are restored to default and not uses the customDevice.js
> 
> Nothing has changed on that side, if the file is here z2m will load it at boot (check logs to have a confirm)
> 

I'm not saying it has changed. I'm saying it does not work. I woke up this morning, server had updated to version 3.2.1... Settings was changed. The customeDevice.js was replaced with the standard implementation and set values was gone.

> > The second bug is that the values are not retained (fetched) when zwave2mqtt restarts and/or Home Assistant restarts
> 
> Did you follow this: https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta
> 
> > In your Home Assistant configuration.yaml
> 
> ```yaml
> mqtt:
>   discovery: true
>   discovery_prefix: <your_discovery_prefix>
>   broker: [YOUR MQTT BROKER]  # Remove if you want to use builtin-in MQTT broker
>   birth_message:
>     topic: 'hass/status'
>     payload: 'online'
>   will_message:
>     topic: 'hass/status'
>     payload: 'offline'
> ```
> 

No I use the MQTT integration available in Home Assistant.
I also use zigbee2mqtt and tasmota. zigbee2mqtt pushes values to home assistant when it starts up. Tasmota you have to request an update on Home Assistant startup
On zwave2mqtt.. I don't know how the values get to Home Assistant, but the does not all the time

**Comment by magpern** [comment]
I am not ablie to reproduce it at the moment.
I retarted the mqtt server, then the "auto" setting from customeDevices.js had disapeared. I had to re-discover device.

But them I restarted the mqtt server again, and it did not disapear.

As comparison. If I stopp zigbee2mqtt all devices in home assistant turn to state "Unavailable". When I start zigbee2mqtt again, the values return.

With zwave2mqtt, I see no change to the values when it is online or offline.

**Comment by magpern** [comment]
Now I restarted home assistant and the "auto" disapeared

![image](https://user-images.githubusercontent.com/6589760/82325576-c037ee80-99db-11ea-913d-32d93f6091ee.png)

**Comment by magpern** [comment]
I think I have fond one reason for the bug!

The discovery message is not marked as `RETAINED`
It is missing the retained flag. All devices from zwave2mqtt lack this flag
![image](https://user-images.githubusercontent.com/6589760/82328025-9aace400-99df-11ea-899f-9bfb349e1eb9.png)

In the GUI of zwave2mqtt there is a column that say "Persistant". It turns to "Yes" if you press the button STORE.
But when you press "Re-discover node" it turns back to "No" and message is not retained

**Comment by robertsLando** [comment]
> No I use the MQTT integration available in Home Assistant.

Even zigbee2mqtt uses the same method to detect hass restarts, you have to go to hass `configuration.yml` and add those lines that are for the hass mqtt client

**Comment by magpern** [comment]
> > No I use the MQTT integration available in Home Assistant.
> 
> Even zigbee2mqtt uses the same method to detect hass restarts, you have to go to hass `configuration.yml` and add those lines that are for the hass mqtt client

I don't exactly know. I used the HA GUI to add the MQTT integration, and it works for zigbee2mqtt.

> 
> > The discovery message is not marked as RETAINED
> 
> If you go to gateway settings there is an option called `retained discovery` for this

Yes, I have 'retained discovery' on. It was a bug in MQTT Explorer. It only shows this flag on first message. If a new message arrives, the flag is not shown, but it is still there.

Now there is a lot of "noise" in this issue report.

The fact remains.

The discovery topic changes from time to time, and the original node values are not updated in the Home Assistant GUI under some, yet to be found, circumstances.

**Comment by travisghansen** [comment]
I think this may be a bug in ha or the mqtt integration. I’ve seen some weird stuff with my thermostat as well and still not sure what causes it. Haven’t had a chance to dig in yet but I will at some point.
