### ISSUE TITLE
[bug] Lack of icons when internet is gone

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#508]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.1
Openzwave Version: 1.6.1123

**Describe the bug**
I had an internet outage, and then all my icons were gone in Z2M :)

![image](https://user-images.githubusercontent.com/1027111/82421533-71449480-9a81-11ea-92c2-512b44d168e1.png)

**To Reproduce**
1. Cut internet
2. Clear any caches
3. Visit Z2M

**Expected behavior**
Icons were loaded from Z2M, and therefore wouldn't require internet.

**Additional context**
N/A

**Comment by robertsLando** [comment]
Strange they should be handled by webpack. I have to investigate

**Comment by robertsLando** [comment]
@LordMike Fixed in 3.2.2
