### ISSUE TITLE
problem docker restarting always

### ISSUE THREAD

**Issue by nicoxygen** [OpenZWave/Zwave2Mqtt#509]
hello with end version docker restarting allways and in journal i have:
Error: Cannot find module './package-lock.json'

**Comment by chrisns** [comment]
Hi, that was an issue with `3.2.0`, please try pulling 3.2.1 (or re-pull `:latest`)
@robertsLando can we remove the the `:3.2.0` from dockerhub?

**Comment by nicoxygen** [comment]
thank you
