### ISSUE TITLE
[bug] Unknown product/type

### ISSUE THREAD

**Issue by larstobi** [OpenZWave/Zwave2Mqtt#513]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.1
Openzwave Version: 1.6.1123

**Describe the bug**
All the product descriptions show unknown or "()".

|ID|Type|Product|Name|Location|Secure|Status|Last Active|
|--|----|-------|----|--------|------|------|-----------|
| 1 |	Static PC Controller | 	ZW090 Z-Stick Gen5 EU (AEON Labs) 		|||	No |	Alive |	5/22/2020, 5:27:07 PM
| 2 |	Binary Power Switch |	Unknown: type=0000, id=0000 (Unknown: id=0000) 		|||	No |	Alive |	5/22/2020, 5:32:09 PM
| 3 |	Multilevel Power Switch |	Unknown: type=0000, id=0000 (Unknown: id=0000) 		|||	No |	Alive |	5/22/2020, 5:32:09 PM
| 4 |	Multilevel Power Switch |	Unknown: type=0000, id=0000 (Unknown: id=0000) 		|||	No |	Alive |	5/22/2020, 5:32:09 PM
| 5 |	Multilevel Power Switch |	() 	|||		No |	Alive |	5/22/2020, 5:34:29 PM
| 6 |	Multilevel Power Switch |	() 	|||		No| 	Alive |	5/22/2020, 5:34:29 PM
| 7 |	Multilevel Power Switch |	Unknown: type=0000, id=0000 (Unknown: id=0000) 	|||		No |	Alive |	5/22/2020, 5:32:09 PM
| 9 |	General Thermostat V2 |	Unknown: type=0000, id=0000 (Unknown: id=0000) 	|||		No |	Alive |	5/22/2020, 5:30:24 PM
| 15 |	Binary Power Switch |	Unknown: type=0000, id=0000 (Unknown: id=0000) 	|||		No |	Alive |	5/22/2020, 5:32:09 PM
| 18 |	Valve Open Close |	Unknown: type=0000, id=0000 (Unknown: id=0000) 	|||		No |	Alive |	5/22/2020, 5:30:44 PM

**To Reproduce**
1. Start the container
2. Leave it for a while
3. Observe the Product column

**Expected behavior**
The product is recognized with name and model number.

**Additional context**
I have enabled auto update database, run first time with refresh node info, and then turned it off. I have also run the docker cp openzwave folder step and mounted it in the running container.

**Comment by larstobi** [comment]
@Fishwaldo robertsLando said on Slack that you might be able to help?

**Comment by robertsLando** [comment]
Try to also add here OZW_LOG so we can debug this better

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by larstobi** [comment]
I tried ozwdaemon, but it also has the same issue.
https://gist.github.com/larstobi/7e35d71619411892d2efb33b9f36b566

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by besynnerlig** [comment]
Any progress on this?

**Comment by robertsLando** [comment]
It's not a butg with z2m but something with underling lib (or a user error/ device error), I cannot do anything to fix this on my side

**Comment by besynnerlig** [comment]
> 
> 
> It's not a butg with z2m but something with underling lib (or a user error/ device error), I cannot do anything to fix this on my side

OK thanks. I just bought new devices and will replace them to get rid of the problem.

**Comment by darkbasic** [comment]
I had the same issue, this is due to some communication error occurred when openzwave queried for the node.
The solution is to stop zwave2mqtt, remove the node from ozwcache_xxx.xml and restart it to let it requery the node.
