### ISSUE TITLE
Hass device creation

### ISSUE THREAD

**Issue by mlankamp** [OpenZWave/Zwave2Mqtt#52]
How does the system decide which Hass devices the create for auto discovery? I have multiple Fibaro powerplugs and default two devices are created (switch and sensor). The sensor uses the kWh unit of measurement.
The Fibaro also has a value for the Power, which uses Watt:
![image](https://user-images.githubusercontent.com/8513556/61415993-9f51c900-a8f2-11e9-906e-06333c98fca7.png)

When I update the nodes.json, I can add the additional sensor. I just curious how the system decides which device to create.

**Comment by robertsLando** [comment]
I have created a function that try to guess the correct component to create based on value properties like command class, index, instance, units of measurements and label. It is a work in progress as zwave devices are a lot so there will be for sure some device that is not discovered as expected... This is why I have added the possibility to edit the discovery configuration of each device manually and store it in a file that can be easily exported/imported for backup. 

I have also created a file named `/hass/devices.js` where I plan to create a "database" that will contain all devices configuration with customizations, for example the command class 38 (switch_multilevel) on zwave should be used for light dimmers, some manufacturer uses it also for fans and else so in those cases I can't decide which is the correct component to create so before to guess the componet I will check in that file if there is an existing configuration to use.

**Comment by mlankamp** [comment]
Is it a solution to remap this file using a volume in the docker container? Or add an additional file? This would make it easy for people to add/test their own mappings?

**Comment by robertsLando** [comment]
check it here https://github.com/OpenZWave/Zwave2Mqtt#Add-new-component

**Comment by mlankamp** [comment]
Thanks, but I never see an `Add` button

**Comment by robertsLando** [comment]
If you are using the “nodejs” version and not the docker you have to run “npm run build” to update the ui after pull from master

Daniel
