### ISSUE TITLE
[question] Switches not sending status when manually pressed

### ISSUE THREAD

**Issue by jasonsinclair5** [OpenZWave/Zwave2Mqtt#539]
I have a couple in-wall switches that I moved over to z2m, but when they are manually pressed, no status is sent showing they are on/off. The first switch is a Leviton switch (DS15S-1BZ) with add-ons for 3 and 4 way configurations and what's bizarre is it will send an instant status when the main switch is turned on/off, but any add-on switches don't. The other is a NuTone NWS15Z which doesn't send any status updates when turned on/off manually. I have tried to enable polling on both device types, but the system immediately crashes once discovery is complete. I also have "verify value" enabled, but that doesn't help. If I run a "refresh node info" it updates the status.

**Comment by robertsLando** [comment]
`refresh node info` removes and adds back the node so that is why you see the value update (all values are updated)

**Comment by robertsLando** [comment]
Try to enable value poll, consider that this will kill the battery life of the device

**Comment by jasonsinclair5** [comment]
> Try to enable value poll, consider that this will kill the battery life of the device

I tried enabling polling, and it eventually crashes and I have to restart the container. The logs don't show anything specific, but the web page shows a "yellow icon" in the right corner and it loses connection. I have tried values 1-30.

**Comment by robertsLando** [comment]
strange you don't see anything in logs, the yellow icons means the socket is disconnected and it means the server crashes

**Comment by jasonsinclair5** [comment]
Are the only logs contained in OZW_log.txt ? I can clear them, set the value and try again.

**Comment by robertsLando** [comment]
Don't you have a console that is showing logs? OZW_log.txt it's only for ozw related things

**Comment by jasonsinclair5** [comment]
I'm running it in Docker, and the only logs I see are the OZW logs. Is there somewhere else I should be looking?

**Comment by robertsLando** [comment]
Depends on how you are starting the container so. docker logs or docker-compose logs ?

**Comment by jasonsinclair5** [comment]
Thanks. I set the value and it crashed...digging through the docker logs on the container right now....more to follow..

**Comment by jasonsinclair5** [comment]
I found this error below:

```
z2m:Zwave Network scan complete. Found: 17 nodes +2s
2020-06-03 09:51:25.170 Detail, Node018, Notification: NodeAdded
2020-06-03 09:51:25.172 Warning, Node016, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xe0a10345, ValueID: (Id 0x0000000010494010, NodeID 16, Genre user, CC 0x25, Instance 1, Index 0, Type bool)
2020-06-03 09:51:25.173 Warning, Exception: Manager.cpp:1570 - 101 - Invalid ValueID passed to GetValueLabel
terminate called after throwing an instance of 'OpenZWave::OZWException'
  what():  Manager.cpp:1570 - InvalidValueIDError (101) Msg: Invalid ValueID passed to GetValueLabel
```

**Comment by jasonsinclair5** [comment]
Actually, it looks like after that error above, it came back to life and rescanned everything again only to come up with a similar error:

```
  z2m:Zwave Node added 2 +2ms
2020-06-03 09:56:24.735 Warning, Node008, Node::GetValue - Couldn't find ValueID in Store: HomeID: 0xe0a10345, ValueID: (Id 0x0000000008494010, NodeID 8, Genre user, CC 0x25, Instance 1, Index 0, Type bool)
2020-06-03 09:56:24.735 Warning, Exception: Manager.cpp:1570 - 101 - Invalid ValueID passed to GetValueLabel
terminate called after throwing an instance of 'OpenZWave::OZWException'
  what():  Manager.cpp:1570 - InvalidValueIDError (101) Msg: Invalid ValueID passed to GetValueLabel
```

Both node 8 and node 16 are these devices in question that I enabled polling. There are 3 total.

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by Fishwaldo** [comment]
I think it’s pretty self explanatory:
> 2020-06-03 09:56:24.735 Warning, Exception: Manager.cpp:1570 - 101 - Invalid ValueID passed to GetValueLabel

The ValueID doesn’t exist. Additionally the wrapper isn’t handling exceptions. Not a OZW error.

**Comment by robertsLando** [comment]
It never happened since before, need to check if something has change

**Comment by jasonsinclair5** [comment]
Quick update: I figured out the issue with the Leviton switches not sending updates when manually pressed. Two out of three had 1.15 firmware and the other had 1.20. The one with updated firmware functioned properly. I was able to get the other 2 flashed using Z-Flash and they now function properly.

As for the Nortek switches that don't send updates, I have polling working at 30 sec, but it took a couple restarts to get the zwave network up without it crashing. However, if I make another change or reboot, it may drop out again.

**Comment by robertsLando** [comment]
I think it's a device issue so?

**Comment by robertsLando** [comment]
@jasonsinclair5 I have just released a patch for openzwave-shared that is ready to bump in a PR here

**Comment by jasonsinclair5** [comment]
Yes, the manual press for the Leviton switch was firmware, but the polling crash was not. I’ll test out the new build when it’s ready and let you know. Thanks for your help with this!

**Comment by robertsLando** [comment]
Let me know
