### ISSUE TITLE
[bug] Handle rediscovery after broker connection

### ISSUE THREAD

**Issue by pbathuk** [OpenZWave/Zwave2Mqtt#54]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.1
Openzwave Version: 1.4.1

**Describe the bug**
When zwave2mqtt and the MQTT broker restart at the same time zwave2mqtt Hass discovery options don't appear to rebuild again. Therefore meaning a second reboot of zwave2mqtt is required.

**To Reproduce**
1. Have mosquito and zwave2mqtt as dockers
2. Set zwave2mqtt to depend on mosquito
3. Have HASS discovery enabled
4. Reboot the system

**Expected behavior**
Hass Mqtt topics to rebuild in the broker

**Additional context**
Discussed on slack

**Comment by robertsLando** [comment]
@pbathuk Try this and let me know :)

**Comment by pbathuk** [comment]
I have just completed a the build of the latest version (2 commits after this as I liked the sound of the new feature as well).
I restarted Zwave to ensure it was working - it was.
I then rebooted the server.. all setup and working fine on a reboot. 
Therefore happy to say this appears to be fixed :)
thanks
