### ISSUE TITLE
[bug] Missing controller actions

### ISSUE THREAD

**Issue by VaticanUK** [OpenZWave/Zwave2Mqtt#554]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.2
Openzwave Version: 1.6.1133

**Describe the bug**
`Remove Failed Node` command missing

Readme.md says

> Remove a failed node
If a node is missing or marked as dead. There is a way to cleanup the controller by executing Remove Failed Node. This will forcebly delete the node from the controller. It can only succeed if:

> Node has ben first marked as failed using Has node failed
Marked as Dead by the controller
Alive and Sleeping nodes cannot be deleted.

However `Remove Failed Node` does not appear in controller or node command dropdown:
![image](https://user-images.githubusercontent.com/1851814/83773128-0ea3e900-a67c-11ea-9ca0-7185c835c447.png)
![image](https://user-images.githubusercontent.com/1851814/83773158-16638d80-a67c-11ea-9e0b-8246d89e4e1b.png)

**To Reproduce**
1. Go to 'Control Panel'
2. Click on 'Controller actions'
3. Command doesn't exist
4. Click on 'Node actions'
5. Command doesn't exist

**Expected behavior**
Command is expected to exist, or readme.md needs to be updated.

**Comment by jasonsinclair5** [comment]
I thought it was missing too awhile back, but noticed I had to "scroll down" with my mouse wheel, or hit the down arrow on my keyboard to see it:

![image](https://user-images.githubusercontent.com/61260365/83776249-91fa1600-a64d-11ea-9ae9-db36fb6a2376.png)
