### ISSUE TITLE
[feat] Alarms in home assistant

### ISSUE THREAD

**Issue by jshridha** [OpenZWave/Zwave2Mqtt#56]
Command class 113 contains alarm information that is not being included in home assistant as sensors. Below is an example of this command class from a smoke/fire detector.

The only value that I need to tell if smoke or CO2 is detected is the alarm_type field, but I believe that two sensors should be created. One for the alarm_type and one for the alarm_level just for completeness.

A contact sensor I have for the garage door also transmits a "burglar" message. I'm not sure what it does, but it may be good to include that also (see second image below).

![image](https://user-images.githubusercontent.com/11232787/61585276-aca2c980-ab25-11e9-9527-a2f13b12aee8.png)

![image](https://user-images.githubusercontent.com/11232787/61585318-55e9bf80-ab26-11e9-94d9-c6a09d856773.png)

**Comment by robertsLando** [comment]
@jshridha What component do you think I should create on hass when detecting alarm command class? A sensor?

**Comment by robertsLando** [comment]
I have this: https://github.com/OpenZWave/open-zwave/blob/master/config/Localization.xml#L8 Does your sensor send binary states or multilevel states (from x to y levels) ?

**Comment by jshridha** [comment]
Yes - I'm thinking it should be a sensor. I'm thinking one sensor for each value just to stick with the convention that hass already has.

**Comment by jshridha** [comment]
It sends multiple levels. The alarm_type will be either 1, 2, 12, or 13.

**Comment by robertsLando** [comment]
Ok I could create by default a sensor with generic class and a custom icon like the `mdi:alarm-light`

**Comment by robertsLando** [comment]
@jshridha Please try this and let me know if it works :)

**Comment by jshridha** [comment]
@robertsLando This works partially. I'm getting the alarm_type in hass, but the alarm_level is sending its discovery to the same topic as alarm_type. It looks like alarm_level is being overwritten by the alarm_type discovery. Also, the burglar value is not being sent at all.

Both of these messages are sent to the same topic (homeassistant/sensor/laundry_first_alert/alarm/config)

Sent at 07/22/2019 2:57:29 PM:
```
{
  "icon": "mdi:alarm-light",
  "value_template": "{{ value_json.value }}",
  "state_topic": "zwave/laundry_first_alert/113/1/0",
  "json_attributes_topic": "zwave/laundry_first_alert/113/1/0",
  "device": {
    "identifiers": [
      "zwave2mqtt_laundry_first_alert"
    ],
    "manufacturer": "First Alert",
    "model": "0x0002",
    "name": "ZCombo Smoke and Carbon Monoxide Detector",
    "sw_version": "0.05"
  },
  "name": "laundry_first_alert_alarm",
  "unique_id": "zwave2mqtt_laundry_first_alert_26-113-1-0"
}
```

Sent at 07/22/2019 2:57:30 PM:
```
{
  "icon": "mdi:alarm-light",
  "value_template": "{{ value_json.value }}",
  "state_topic": "zwave/laundry_first_alert/113/1/1",
  "json_attributes_topic": "zwave/laundry_first_alert/113/1/1",
  "device": {
    "identifiers": [
      "zwave2mqtt_laundry_first_alert"
    ],
    "manufacturer": "First Alert",
    "model": "0x0002",
    "name": "ZCombo Smoke and Carbon Monoxide Detector",
    "sw_version": "0.05"
  },
  "name": "laundry_first_alert_alarm",
  "unique_id": "zwave2mqtt_laundry_first_alert_26-113-1-1"
}
```

**Comment by robertsLando** [comment]
Thanks @jshridha I forgot to check the value index, now I publish only the alarm level. Please try this again and let me know :)

**Comment by jshridha** [comment]
That gets us close. #62 gets us the rest of the way there.
