### ISSUE TITLE
[bug] spawn udevadm errors are back on SmartOS

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#57]
**Version**
2.0.1-master

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.1
Openzwave Version: 1.6.848

**Describe the bug**
The errors about unable to start the udevadm process are back, I think they are releated to opening the settings page.

**To Reproduce**
1. start zwave2mqtt on non linux (e.g. smartos)
2. go to the settings page

**Expected behavior**
Don't try and start udevadm on non linux systems.

**Additional context**
udev and by extension udevadm is a linux specific thing, it for certain does not exist on SmartOS/illumos and AFAIK the BSD's also use something else.

**Comment by robertsLando** [comment]
Do you have any console log to append here @sjorge ?

**Comment by sjorge** [comment]
```
2019-07-21T14:30:28.337Z z2m:App New connection b-3F-qjpWPq57M8xAAAB
2019-07-21T14:30:48.328Z z2m:App User disconnected b-3F-qjpWPq57M8xAAAB
2019-07-21T14:30:48.518Z z2m:App Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
GET /api/settings 200 82.698 ms - 67581
2019-07-21T14:30:58.344Z z2m:Gateway Closing Gateway...
```

It's also visible in the list from #59 as that also does an update of the setting page, so it triggers the udevadm command also.

**Comment by robertsLando** [comment]
I sincerly have no Idea about this bug :(

**Comment by sjorge** [comment]
Maybe this is coming from one of the libraries?

**Comment by robertsLando** [comment]
@sjorge could be, yes

**Comment by robertsLando** [comment]
@Fishwaldo

**Comment by Fishwaldo** [comment]
Not OZW. (Else you would see if with MinOZW)

**Comment by sjorge** [comment]
Will test with MinOZW once I get home.

~ sjorge

**Comment by robertsLando** [comment]
@sjorge I have added you to the [thanks](https://github.com/OpenZWave/Zwave2Mqtt/#-thanks) section of the project :)

**Comment by sjorge** [comment]
Cool!

I also tracked the udevadm call to the serialport dependency: https://github.com/serialport/node-serialport/blob/3d34d0f7c06009bf256a4af0f306d3a2e30b3bf6/packages/bindings/lib/linux-list.js#L43

Not sure how it is being called on SmartOS as that seems to be Linux specific code?

**Comment by sjorge** [comment]
@robertsLando what is the list callback for here https://github.com/OpenZWave/Zwave2Mqtt/blob/a7f28f849657a4a63a8978dffb9b305d3f85fc49/app.js#L118 ?

Is it to check if the port exists? If so maybe we can replace that for an `fs.exists` for SmartOS/illumos.

**Comment by robertsLando** [comment]
This is used to get the list of available serial ports

**Comment by sjorge** [comment]
We can probably skip that for SmartOS then, the code uses udevadm, which will not work. And I think the debug in the callback is printing the message. If you want to do minimal sanity checking on the entered value a fs.exists should be OK.

**Comment by robertsLando** [comment]
Ok so I need a way to detect smartos on nodejs. What does [process.platform](https://nodejs.org/api/process.html#process_process_platform) returns to you?

**Comment by sjorge** [comment]
I would expect sunos, as OpenSolaris -> illumos, which SmartOS is a distro off.

```
[isotope :: sjorge][~]
[.]$ node x
sunos
[isotope :: sjorge][~]
[.]$ cat x
console.log(process.platform);
```

Seems to confirm that.

**Comment by robertsLando** [comment]
Ok I will try to add a check so, try the next commit

**Comment by robertsLando** [comment]
@sjorge  Try now :)

**Comment by sjorge** [comment]
Yep, that fixed it!
