### ISSUE TITLE
[bug] Physically removed devices show as Alive

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#573]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.2
Openzwave Version: >OZW 1.6.1115 ?

**Describe the bug**
I have 3 devices that were removed from the network. One needed factory resetting, one broke and one was removed as the battery died (Strips door sensor has a fixed battery).

These devices were not unpaired. However the Strips device is reporting as `Alive` and it is somewhere on the way to a recycling facility.
The other devices show as `Alive` also.

The Last Active information shows the last time I rebooted or updated the docker image. 
If I `Test Node` or `RefreshNodeInfo` they persist.
They also persist beyond `Remove Failed Node`

This is likely to be causing issues in my mesh.

**To Reproduce**
1. Factory reset device and do not unpair
2. Restart Z2M
3. Device still exists

**Expected behavior**
Node should definitely appear `Dead` and then allow the steps to remove it

**Comment by jaburges** [comment]
Keeping this current. Latest docker of Z2M. Same issue applies.

Node is showing as Alive, but last updated Never

**Comment by robertsLando** [comment]
@jaburges That's very strange, do you have any nodejs knowladge to debug this? The only way to mark a node as alive is to receive a node alive notification

**Comment by jaburges** [comment]
nope, but i'm always learning - what should i look at specifically?

**Comment by robertsLando** [comment]
@jaburges You shoud install node on your machine, clone this repo and debug the project with node inspector. It's not that easy but if you wish to start: https://nodejs.org/en/docs/guides/debugging-getting-started/

**Comment by jaburges** [comment]
moved to zwavejs - closing as dont have time to debug
