### ISSUE TITLE
[question] Will/Testament messages with retain flag

### ISSUE THREAD

**Issue by Ciredm** [OpenZWave/Zwave2Mqtt#583]
Hello,

On previous release (3.0.3, if I remember well), Will and Testament messages had retain flag enabled.
But since my migration to relase 3.2.2, they don't have any more this flag.
How it is possible to retrieve this feature? I don't want to have retain flag on all messages, only on <mqtt_prefix>/_CLIENTS/ZWAVE_GATEWAY-<mqtt_name>/status messages.

ZWave2Mqtt: 3.2.2
OpenZWave: 1.6
Hosted on Raspberry Pi raspian

Regards,

**Comment by robertsLando** [comment]
The retain flag option has been extended to all messages and there is no way to use it only on specific topics (will/testament). I suggest you to enable it globally, retain flag is useful

**Comment by Ciredm** [comment]
Hi,

Thanks for your answer.

Regards
