### ISSUE TITLE
[bug] Two nodes with same name confuses MQTT set-value

### ISSUE THREAD

**Issue by LordMike** [OpenZWave/Zwave2Mqtt#592]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.2.2
Openzwave Version: 1.6.1133

**Describe the bug**
I added a new node (29) which I named `wallswitch_3`, not realizing that an existing node (9) also had the name `wallswitch_3`. I then removed my new node (29), and properly replaced the existing node (9) with the new physical device. 

Send MQTT messages to `../wallswitch_3/..` logs output like:

```
z2m:Mqtt Message received on zwave2mqtt/wallswitch_3/38/6/0/set +3s
z2m:Zwave Error while writing 255 on 29-38-6-0: OpenZWave valueId not found: 29-38-6-0 +3s
```

In this log, it attempted to send to node no. 29, instead of 9. I think there are multiple errors:

* A failed node (not shown by default in the nodes table) is used when directing messages
* Two nodes can have the same name

**To Reproduce**
1. Name two nodes the same
2. Send a value / message to node A and B using MQTT
3. Observe that both messages are sent to either A or B

**Expected behavior**
Some constraint preventing this issue from occurring.

**Additional context**
I renamed the removed node no. 29, but the error persists. When I click the (new) device physically, the `wallswitch_3` MQTT topics are updated.

**Comment by robertsLando** [comment]
@LordMike This seems more like a user error, I could add a warning in control panel but it's not really a bug, also two nodes can have same name but different locations

**Comment by robertsLando** [comment]
nope, the name is just a node property, the real id is the node id that is unique

**Comment by LordMike** [comment]
But isn't the name used in the MQTT topics, when the `Use nodes name instead of numeric nodeIDs` option is enabled?.. In that case, the name will refer to 2+ nodes, where I've experienced that only one of them then receives the value.

**Comment by LordMike** [comment]
I've restarted Z2M, and can confirm that I can now send a message to my `wallswitch_3`, with it ending at node 9 instead of 29. I dunno why the name stuck with the node 29, even though it was renamed to blank / empty string.

**Comment by robertsLando** [comment]
> But isn't the name used in the MQTT topics, when the Use nodes name instead of numeric nodeIDs option is enabled?.. In that case, the name will refer to 2+ nodes, where I've experienced that only one of them then receives the value.

Sure but you know that there are lot different gateway setups, a user should take care of the names he choose for his devices, also as I said before a name could be equal but the location could be different and in that case it should work

**Comment by LordMike** [comment]
Right.
