### ISSUE TITLE
[feature] Provide an action for refreshing node info for all nodes in the zwave network

### ISSUE THREAD

**Issue by j9brown** [OpenZWave/Zwave2Mqtt#596]
**Is your feature request related to a problem? Please describe.**

When the openzwave devices classes or manufacturer specific configurations are updated, I need to refresh the cached configuration information by updating node information.

**Describe the solution you'd like**

zwave2mqtt has a "refresh node info" setting to automatically refresh all node info upon startup.  I would like a way to manually invoke this action as needed.

**Describe alternatives you've considered**

I could temporarily enable the automatic refresh setting, restart zwave2mqtt, then disable the setting again but it's inconvenient.

**Additional context**

I encountered this problem because my device database path was incorrect when I first set up the system so it was unable to find device_classes.xml.  While I have resolved that issue, I do expect to need to refresh node information occasionally as I perform zwave network maintenance or contribute new manufacturer specific configurations for my devices.

**Comment by robertsLando** [comment]
> I could temporarily enable the automatic refresh setting, restart zwave2mqtt, then disable the setting again but it's inconvenient.

This is the main reason about that, it ensures that the refresh is done only when the node is ready and the scan is completed. That flag should never be always enabled

**Comment by j9brown** [comment]
Yeah, it would be a bad idea to keep the refresh on all the time.  A more powerful alternative might be to provide support for bulk actions on multiple nodes.

For example, the user clicks checkboxes to select several nodes (or perhaps all, or perhaps all matching some criterion) then invokes the Refresh Node Info, Get Neighbors, Ping, or similar maintenance actions.

**Comment by robertsLando** [comment]
Ok I add this to TODOs so

**Comment by j9brown** [comment]
Cool!  Yay!  :)

**Comment by robertsLando** [comment]
@j9brown A PR is ready for this and will be available in next release!
