### ISSUE TITLE
[bug] Gateway values table - bug with polling reset

### ISSUE THREAD

**Issue by DarS007** [OpenZWave/Zwave2Mqtt#599]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.3.0

**Describe the bug**
_Gateway values table_ allows to customize MQTT specific values topic for each device (or rather device type). Great feature, thank you for it! 
When you define the _translation_ for the _device type_, you can also select _poll_ option. I was tempted to check it. It worked as intended - frequent, continuous MQTT status messages flooded my MQTT broker. So far so good ... 
The trouble started when I tried to disable the _poll_. The web GUI accepted it and saved, but ... the gateway continued to generate frequent MQTT status messages:
```
  z2m:Zwave zwave node 19: changed: 37-1-0:Switch:false -> false +394ms
  z2m:Zwave zwave node 12: changed: 37-1-0:Switch:false -> false +393ms
  z2m:Zwave zwave node 18: changed: 37-1-0:Switch:false -> false +395ms
  z2m:Zwave zwave node 19: changed: 37-1-0:Switch:false -> false +394ms
  z2m:Zwave zwave node 12: changed: 37-1-0:Switch:false -> false +401ms
  z2m:Zwave zwave node 18: changed: 37-1-0:Switch:false -> false +397ms
  z2m:Zwave zwave node 19: changed: 37-1-0:Switch:false -> false +394ms
  z2m:Zwave zwave node 12: changed: 37-1-0:Switch:false -> false +401ms
  z2m:Zwave zwave node 18: changed: 37-1-0:Switch:false -> false +391ms
```
Zwave2Mqtt restart did not help. MQTT polling messages were still coming.

Then I checked _ozwcache_xxx.xml_ file where I saw `poll_intensity` **not zeroed** for some devices (exactly the same devices that were spamming with MQTT polling messages):
```
<CommandClass id="37" name="COMMAND_CLASS_SWITCH_BINARY">
	<Compatibility />
	<State>
		<CCVersion>1</CCVersion>
		<InNif>true</InNif>
	</State>
	<Instance index="1" />
		<Value type="bool" genre="user" instance="1" index="0" label="Switch" units="" 
		read_only="false" write_only="false" verify_changes="true" poll_intensity="2" 
		min="0" max="0" value="False">
		<Help>Turn On/Off Device</Help>
		</Value>
</CommandClass>
```
It looks that the GUI code properly _sets_ the polling in the config file. But the _polling reset_ (when the user tries to disable it via GUI) is not properly propagated.
I did additional troubleshooting and I manually set (in _ozwcache_xxx.xml_ file) `poll_intensity="0"` for all devices that had previously `poll_intensity="2"`. Once the changes were made, the gateway started to work properly. No more continuous MQTT poll messages.

**To Reproduce**
1. Go to 'Settings => Gateway'
2. On the bottom left of 'Gateway' section click on 'NEW VALUE' and create any arbitrary value translation entry. Make sure you enable 'Poll' option.
3. Save the changes and check your MQTT monitor. You should see frequent (0.5sec in my case) MQTT messages like `z2m:Zwave zwave node 12: changed: 37-1-0:Switch:false -> false +393ms`
4. Go back to 'Settings => Gateway' and edit your value translation line. Disable 'Poll' option. Save the changes.
5. Check your MQTT monitor. You should **not see** frequent MQTT poling messages (this should be the expected behavior). If you still see them, this confirms the bug in the code.

**Comment by DarS007** [comment]
Yeah, some additional comment. 
I was also testing possible workarounds. The most obvious was to set the _poll intensity_ to **ZERO** before turning poling off (so the value 0 would be hopefully written to the cache file). 
I thought this is a good idea, but ... the web GUI **prohibits** entering 0 there, displaying 'Min value is 1' error. Grrrrr

**Comment by robertsLando** [comment]
In poor words would you like me to allow insert 0 as poll intensity?

**Comment by robertsLando** [comment]
From a code side, everything seems good as the poll is disabled in case the value is polled:

https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L307-L313

But sincerly I don't know if a value expects also to set the intensity to 0. @Fishwaldo is disablePoll enought to disable the poll of a value? Is there any known bug about disablePoll not working?
