### ISSUE TITLE
[feat] removeFailedNode

### ISSUE THREAD

**Issue by soumya92** [OpenZWave/Zwave2Mqtt#60]
It would be great to be able to call "removeFailedNode" on a dead node. Currently that does not seem possible, only "replaceFailedNode" is available.

**Comment by robertsLando** [comment]
Are you sure it is not possible? Did you try to enable the flag “show failed nodes” on the table? It allows you see all nodes amd select them. Also it should be possible to call removefailed node from controller commands and than once triggered a popuo wil ask you to enter the node id

Daniel

**Comment by soumya92** [comment]
Reasonably certain. I tried with both hidden nodes checked and unchecked.
The hidden nodes toggle only appears to affect nodes that are "Removed". The nodes I want to delete are "Dead", and are shown regardless of the toggle.

The options I see on the controller are:

- Add Node (inclusion)
- Remove Node (exclusion)
- Transfer primary role
- Create new primary
- Receive configuration
- Cancel Command
- Heal Network
- Driver statistic
- Hard reset
- Soft reset
- Test network
- Update neighbors
- Get Node neighbors
- Update return route
- Delete return routes
- Send NIF
- Request network update
- Node statistic
- Has node failed
- Replace failed node
- Heal node
- Replication send
- Test node

And the options I see when selecting a "Dead" node are:

- Update neighbors
- Get Node neighbors
- Update return route
- Delete return routes
- Send NIF
- Request network update
- Node statistic
- Has node failed
- Replace failed node
- Heal node
- Replication send
- Test node

They both offer a "replace" but not "remove" for failed nodes.

However, I can call all API methods over MQTT, so this is very low priority. It would be a nice to have in the UI, but is hardly blocking anything, since I can just fire up mosquitto_pub.

**Comment by robertsLando** [comment]
Now I got it, it is impossible in zwave protocol to remove a failed node, you can just replace it. To detect a node has failed you should send the command “update return routes” and then “has node faled” against the dead node. That’s a protocol limitation

Daniel

**Comment by soumya92** [comment]
Oh, interesting. That might explain why calling removeFailedNode over mqtt did not help :)
I will try out your suggestion. Thanks!
