### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ghada-Ch** [OpenZWave/Zwave2Mqtt#606]
**Version**

Build/Run method
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.6

ZWave2MQTT error: /home/pi/ZWave2MQTT/node_modules/openzwave-shared/build/Release/openzwave_shared.node: undefined symbol: _ZN9OpenZWave7Options6CreateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_S8_

**Comment by robertsLando** [comment]
@Ghada-Ch You are running a very old version of z2m, could you try to use latest please?

**Comment by Ghada-Ch** [comment]
Sorry,there is a command line to upgrade or I shoud remove it and install again !!???

**Comment by Ghada-Ch** [comment]
mkdir Zwave2Mqtt
cd Zwave2Mqtt
# download latest version
curl -s https://api.github.com/repos/OpenZWave/Zwave2Mqtt/releases/latest  \
| grep "browser_download_url.*zip" \
| cut -d : -f 2,3 \
| tr -d \" \
| wget -i -
unzip zwave2mqtt-v*.zip
./zwave2mqtt
------------------------------------------
I run this code but when I exec ./zwave2mqtt
I got this error 
./zwave2mqtt: 1: ./zwave2mqtt: ELF: not found
./zwave2mqtt: 2: ./zwave2mqtt: Syntax error: "(" unexpected

**Comment by robertsLando** [comment]
Run the command `uname -a` and tell me the output. The pkg version only works on amd64

**Comment by Ghada-Ch** [comment]
Linux raspberrypi 4.19.118+ #1311 Mon Apr 27 14:16:15 BST 2020 armv6l GNU/Linux

**Comment by robertsLando** [comment]
Ok that's the problem, go for docker
