### ISSUE TITLE
[bug] setValue no longer works

### ISSUE THREAD

**Issue by jshridha** [OpenZWave/Zwave2Mqtt#61]
**Version**

Build/Run method
Docker built with latest commit: 3eafd996381ff0b27a20c0182a31305a9c68d690

Openzwave Version: 1.4.1

**Describe the bug**
Commands are no longer being sent. For some reason setValue recently doesn't actually communicate with the network. See the logs below for example:
```
zwave_1        | 2019-07-22T22:20:26.974Z z2m:App Zwave api call: setValue [ 25, 38, 1, 0, '99' ]
zwave_1        | 2019-07-22T22:20:26.980Z z2m:Zwave Success zwave api call setValue
zwave_1        | 2019-07-22T22:20:39.409Z z2m:App Zwave api call: setValue [ 25, 38, 1, 0, '50' ]
zwave_1        | 2019-07-22T22:20:39.414Z z2m:Zwave Success zwave api call setValue
zwave_1        | 2019-07-22T22:20:40.768Z z2m:App Zwave api call: setValue [ 25, 38, 1, 1, true ]
zwave_1        | 2019-07-22T22:20:40.769Z z2m:Zwave Success zwave api call setValue
zwave_1        | 2019-07-22T22:21:01.261Z z2m:App Zwave api call: setValue [ 25, 38, 1, 0, '99' ]
zwave_1        | 2019-07-22T22:21:01.262Z z2m:Zwave Success zwave api call setValue
```

**To Reproduce**
The bug happens both when I use the GUI to set the value and when I send a command over MQTT.

I am working to track down which commit caused the issue. I will report back shortly with that information.

**Comment by jshridha** [comment]
I'm not quite sure what happened, but this issue seems to have disappeared. Hopefully it does not come back. I'll reopen if it does.

**Comment by robertsLando** [comment]
@sjorge I have added you to the [thanks](https://github.com/OpenZWave/Zwave2Mqtt/#-thanks) section of the project :)
