### ISSUE TITLE
Warning, Failed - Network Key Not Set

### ISSUE THREAD

**Issue by Ghada-Ch** [OpenZWave/Zwave2Mqtt#617]
I added Network key to option.xml but still
Warning, Failed - Network Key Not Set

**Comment by robertsLando** [comment]
> I added Network key to option.xml but still

What? :confused: 

You have to add network key using the UI

**Comment by Ghada-Ch** [comment]
I am sorry this my first project,please can you explain this point.😢

**Comment by robertsLando** [comment]
@Ghada-Ch Once installed and running, go to localhost:8091 --> settings tab --> zwave settings --> network key

**Comment by Ghada-Ch** [comment]
That's why I am asking bcz  localhost:8091 doesn't work !
