### ISSUE TITLE
[question] Installing on Unraid

### ISSUE THREAD

**Issue by magaman** [OpenZWave/Zwave2Mqtt#620]
Hello, been trying to get this up and running properly on my Unraid box, it does work with minimal tweaking of the container variables in Unraid changing port and passing the USB. But my issue is I can't seem to figure out how to map the directory to my /appdata directory so that I can alter the zwave device xmls. I've tried a few different variable in an attempt to map the Config folder location but no luck yet. Any insight would be great. This has been the first container that is actually grabbing my devices properly and working very well.

**Comment by robertsLando** [comment]
Hi @magaman, unfortunally I never used uraid so I can't help with your probelm if it is unraid related. Try to ask in some unraid forum?

**Comment by magaman** [comment]
yeah reached out on reddit, was given this information "unfortunately, that particular dockerfile does not use the VOLUME command." seems that is the roadblock

**Comment by robertsLando** [comment]
@magaman There was another user asking for this. It can be done but would need some help from someone that uses Unraid (I never used it so can't help), I can give support from Z2m side if needed. 

Here you find all the informations: https://github.com/robertsLando/Zwave2Mqtt-docker/issues/17

**Comment by robertsLando** [comment]
Thanks so much @jaburges for this. It anyone is interested here @jaburges have created a quick guide: https://community.home-assistant.io/t/zwave2mqtt-unraid-community-app-docker-available/227054
