### ISSUE TITLE
[bug] FGMS001 motion detection does not update MQTT sensor state (48-1-0)

### ISSUE THREAD

**Issue by jghaanstra** [OpenZWave/Zwave2Mqtt#621]
**Version**
Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.4.0
Openzwave Version: 1.6

**Describe the bug**
Zwave2Mqtt is not updating the mqtt motion alarm value for the Fibaro FGMS001 motion sensor. A motion event is detected from the sensor but the state of the 48-1-0 topic remains on the state which it intially has when pairing the device. See the animated gif below where you can see the motion events coming in and being cancelled while the state of the sensor remains true without changing. 

![2020-07-09_17-26-43](https://user-images.githubusercontent.com/4710062/87065756-c1cea780-c211-11ea-8cb8-ceaad3147893.gif)

**To Reproduce**
1. Pair a Fibaro FGMS001 motion sensor
2. Trigger a motion event
3. Check your Mqtt broker if the value of the 48-1-0 topic is updated.

**Expected behavior**
Having the topic 48-1-1 for this sensor updated in correspondence of the motion events.

**Additional context**
This issue seems to be specific for this type of sensor. My NEO Coolcam sensors work fine.

**Comment by robertsLando** [comment]
@jghaanstra This seems to me more like a device issue then a Zwave issue, if that value is not updated is not something that z2m can control, mayba a configuration? If you see that value 113-1-7 detects a motion why don't use that value instead?

**Comment by jghaanstra** [comment]
Thanx for the quick response. I tried the sensor with another zwave controller (Homey) and it reports motion events just fine so I dont think its device related. That is backed up up that 113-1-7 also detects the motion events from the sensor. So the events are actually coming in.  That's why it seemed to me this is not handled correctly within zwave2mqtt.

Enabling polling is not going to work as well as this is a battery operated device which is sleeping most of the time and I dont want to drain the battery.

I did look into using 113-1-7 for my purpose but I need a boolean value for my purpose I do not really have the option to parse the values from 113-1-7.

But if you think this is unrelated to zwave2mqtt then close the issue.

**Comment by robertsLando** [comment]
I tell you this because Zwave2mqtt treats all values in the same way so there is no reason why that value is not sent in mqtt, if it is not sent it means that I don’t receive the value change event from Openzwave library. 
So the issue could be there (in ozw lib), or maybe it’s a configuration issue or A compatibility issue with ozw lib, do you have zwave logging enabled? Could you paste here the log output when that change happens ? So we can see what the library is catching (and what is not). @Fishwaldo

**Comment by jghaanstra** [comment]
Ok, makes sense it not being in zwave2mqtt. Here is the logging of a motion detection and cancellation. Hopefully it helps to pinpoint this. I have added the configuration of the sensor as well.

```
2020-07-09T21:07:26.048Z z2m:Zwave zwave node 7: changed: 113-1-7:Home Security:Clear -> Motion Detected at Unknown Location
OpenZWave Detail, Node007,   Received: 0x01, 0x11, 0x00, 0x04, 0x00, 0x07, 0x09, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x07, 0x08, 0x00, 0xb3, 0x00, 0xd3
OpenZWave Detail, 
OpenZWave Info, Node007, Got a AlarmCmd_Report Message.... 
OpenZWave Info, Node007, Received Notification report (&gt;v1): Type: Home Security (7) Event: Motion Detected at Unknown Location (8) Status: true, Param Length: 0
OpenZWave Detail, Node007, Refreshed Value: old value=3, new value=0, type=byte
OpenZWave Detail, Node007, Changes to this value are not verified
OpenZWave Detail, Node007, Refreshed Value: old value=0, new value=3, type=list
OpenZWave Detail, Node007, Changes to this value are not verified
OpenZWave Detail, Node007, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
OpenZWave Detail, Node007, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7

2020-07-09T21:07:56.541Z z2m:Zwave zwave node 7: changed: 113-1-256:Previous Event Cleared:0 -> 8
2020-07-09T21:07:56.542Z z2m:Zwave zwave node 7: changed: 113-1-7:Home Security:Motion Detected at Unknown Location -> Clear
OpenZWave Detail, Node007,   Received: 0x01, 0x12, 0x00, 0x04, 0x00, 0x07, 0x0a, 0x71, 0x05, 0x00, 0x00, 0x00, 0xff, 0x07, 0x00, 0x01, 0x08, 0xa7, 0x00, 0xc6
OpenZWave Detail, 
OpenZWave Info, Node007, Got a AlarmCmd_Report Message.... 
OpenZWave Info, Node007, Received Notification report (&gt;v1): Type: Home Security (7) Event: Clear (0) Status: true, Param Length: 1
OpenZWave Detail, Node007, Refreshed Value: old value=0, new value=8, type=byte
OpenZWave Detail, Node007, Changes to this value are not verified
OpenZWave Detail, Node007, Refreshed Value: old value=3, new value=0, type=list
OpenZWave Detail, Node007, Changes to this value are not verified
OpenZWave Detail, Node007, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
OpenZWave Detail, Node007, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
```

![image](https://user-images.githubusercontent.com/4710062/87091612-433a3000-c23a-11ea-8f79-bd87cffacb7b.png)

**Comment by robertsLando** [comment]
> OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
2020-07-09T21:27:13.565Z z2m:Zwave zwave node 4: changed: 48-1-0:Sensor:false -> true

> OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
2020-07-09T21:27:44.688Z z2m:Zwave zwave node 4: changed: 48-1-0:Sensor:true -> false

Seems working based on logs :confused:

**Comment by jghaanstra** [comment]
> > OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
> > OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
> > 2020-07-09T21:27:13.565Z z2m:Zwave zwave node 4: changed: 48-1-0:Sensor:false -> true
> 
> > OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 256
> > OpenZWave Detail, Node004, Notification: ValueChanged CC: COMMAND_CLASS_NOTIFICATION Instance: 1 Index: 7
> > 2020-07-09T21:27:44.688Z z2m:Zwave zwave node 4: changed: 48-1-0:Sensor:true -> false
> 
> Seems working based on logs

Node 4 is a working NEO Coolcam PIR. I put that in there for reference. Node 7 is the Fibaro which is missing the binary report.

**Comment by robertsLando** [comment]
@jghaanstra All the log is about node 4, nothing mentioning node 7 anywhere

**Comment by jghaanstra** [comment]
> @jghaanstra All the logs are about node 4, nothing mentioning node 7 anywhere

The first log (there are two log parts I'm my post) contains the motion detection and cancel for node 7. Just read the post from top to bottom .. ;-)

**Comment by robertsLando** [comment]
Ops sorry I completely missed the first part, I need to get a cup of coffie this morning :)

**Comment by robertsLando** [comment]
Ok just checked your logs, I'm quite sure now it's something related to some compatibility issue of the device with Openzwave. Hopefully @Fishwaldo could help, or you could try to open this issue (and link this one) to ozw library. Sorry but I can't help more then this

**Comment by jghaanstra** [comment]
Ok, thanx for your effort on this. Will open up an issue in the OZW library.

Send you a couple of beers for the good work on zwave2mqtt, keep it up.

**Comment by robertsLando** [comment]
Got it, Thanks so much @jghaanstra :pray:
