### ISSUE TITLE
[question] Docker tags confusing

### ISSUE THREAD

**Issue by mingan666** [OpenZWave/Zwave2Mqtt#633]
The [readme file ](https://github.com/OpenZWave/Zwave2Mqtt/tree/master/docker)linked from [docker hub](https://hub.docker.com/r/robertslando/zwave2mqtt) does not contain the latest releases.

Just wondering which releases are considered stable? The last one mentioned in the readme is 3.1.0, but the last version available on docker hub is 3.4.1.

**Comment by robertsLando** [comment]
@mingan666 It isn't updated now as releases are automatic, we will remove tags from that file
