### ISSUE TITLE
[bug] List of current associations empty, but only in one group

### ISSUE THREAD

**Issue by zargony** [OpenZWave/Zwave2Mqtt#637]
**Version**

Build/Run method
- [X] Docker (k3s kubernetes)
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 3.4.1
Openzwave Version: 1.6.-1

**Describe the bug**
Associations empty in one channel of keyfob (Devolo MT2653) while other channels seem ok.

**To Reproduce**
1. Go to 'groups'
2. For node, select keyfob (node 2)
3. For group, select 'Group C' -> list of current associations is empty
4. For any other group -> list of current associations shows associated nodes

**Expected behavior**
I would expect to see a list of current associations.

**Additional context**
The list of associations seems to to be retrieved correctly though. From the log, a while after starting up zwave2mqtt and refreshing node 2 (my keyfob):
```
2020-07-22 10:40:29.547 Info, Node002, Sending (Send) message (Callback ID=0xa7, Expected Reply=0x04) - MultiChannelAssociationCmd_Get (Node=2): 0x01, 0x0a, 0x00, 0x13, 0x02, 0x03, 0x8e, 0x02, 0x04, 0x25, 0xa7, 0xed
2020-07-22 10:40:29.547 Info, Node002, Encrypted Flag is 0
2020-07-22 10:40:29.557 Detail, Node002,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
2020-07-22 10:40:29.557 Detail, Node002,   ZW_SEND_DATA delivered to Z-Wave stack
2020-07-22 10:40:29.721 Detail, Node002,   Received: 0x01, 0x07, 0x00, 0x13, 0xa7, 0x00, 0x00, 0x11, 0x5d
2020-07-22 10:40:29.722 Detail, Node002,   ZW_SEND_DATA Request with callback ID 0xa7 received (expected 0xa7)
2020-07-22 10:40:29.722 Info, Node002, Request RTT 173 Average Request RTT 532
2020-07-22 10:40:29.723 Detail, Node002,   Expected callbackId was received
2020-07-22 10:40:30.495 Detail, Node002,   Received: 0x01, 0x14, 0x00, 0x04, 0x00, 0x02, 0x0e, 0x8e, 0x03, 0x04, 0x0a, 0x00, 0x00, 0x0e, 0x01, 0x11, 0x01, 0x1b, 0x01, 0x0e, 0x02, 0x69
2020-07-22 10:40:30.495 Detail,
2020-07-22 10:40:30.495 Info, Node002, Response RTT 947 Average Response RTT 1056
2020-07-22 10:40:30.496 Info, Node002, Received MULTI_CHANNEL_ASSOCIATION_REPORT from node 2, group 4
2020-07-22 10:40:30.497 Info, Node002,   The group contains:
2020-07-22 10:40:30.497 Info, Node002,     Node 14 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 17 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 27 End Point 1
2020-07-22 10:40:30.498 Info, Node002,     Node 14 End Point 2
2020-07-22 10:40:30.498 Info, Node002, Querying associations for node 2 is complete.
2020-07-22 10:40:30.499 Detail, Node002,   Expected reply and command class was received
2020-07-22 10:40:30.499 Detail, Node002,   Message transaction complete
2020-07-22 10:40:30.501 Detail,
2020-07-22 10:40:30.501 Detail, Node002, Removing current message
2020-07-22 10:40:30.501 Detail,
```

But querying the associations returns an empty list:

```
2020-07-22T10:48:16.923Z z2m:App Zwave api call: getAssociations [ 2, 4 ]
2020-07-22T10:48:16.924Z z2m:Zwave Success zwave api call getAssociations []
```

While it does work fine for other channels:

```
2020-07-22T10:48:15.012Z z2m:App Zwave api call: getAssociations [ 2, 2 ]
2020-07-22T10:48:15.013Z z2m:Zwave Success zwave api call getAssociations [ 3 ]
```

Group 4 is the only group that does not show associations, even though it definitely has (the keyfob turns on lights and ozw logs show the associations are reported). Though group 4 is the only one with multiple associations. I ended up with 4 associations since I added a few while looking for why the list of current associations is empty. So it seems possible to add more associations, but I'm also unable to remove any of the associations (which might be related or a completely different problem)

**Comment by robertsLando** [comment]
Just for reference: 

this is the method used on ozw shared https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-groups.cc#L46

That calls: http://www.openzwave.net/dev/classOpenZWave_1_1Manager.html#a20176eafcbf7cb117d8a137ef17b48e0

I cannot find any errors in how them are called, it may be some compatibility problem of that specific device? Anyway you could manually call those method using mqtt apis to manually remove nodes that are not present in the list. 

I don't know how to help you there as on my side everything seems correct

**Comment by zargony** [comment]
> it may be some compatibility problem of that specific device?

I can't tell for sure since I don't have a second Z-Wave network to test with, but I'd be surprised if it's a problem with the device. It's some time ago that I last updated associations, but I didn't have problems with it yet. Also the correct associations seem to be received. This looks more like the list of associations are lost in z2m or in ozw for some reason.

> Anyway you could manually call those method using mqtt apis to manually remove nodes that are not present in the list.

Unfortunately I'm not so familiar with using the API manually. Could you point me into the right direction for which method to call and how to do that?

**Comment by robertsLando** [comment]
https://github.com/OpenZWave/Zwave2Mqtt#zwave-apis

`<mqtt_prefix>/_CLIENTS/ZWAVE_GATEWAY-<mqtt_name>/api/removeAssociation/set`

Payload: 
```
{
  "args": [nodeid, group, targetnode]
}
```

The same for `addAssociation`

The result of this call will be published in 

`<mqtt_prefix>/_CLIENTS/ZWAVE_GATEWAY-<mqtt_name>/api/removeAssociation`

**Comment by zargony** [comment]
Thanks! I was able to remove/add associations using `addAssociation`/`removeAssociation` this way.

From what I see, the list of current association doesn't list associations with instance ids. E.g. the same group (group 4 on node 2) works fine when I add an association to node 15 (using args `[2, 4, 15]`). The association shows fine in the UI. If I however add an association with an instance id, e.g. endpoint 2 on node 27 (args `[2, 4, 27, 2]`), it doesn't show this association in the UI and `getAssociations` doesn't return it (but it does work on the device). If I add multiple associations, only the ones without an instance id are shown. Ozw debug log correctly lists all associations, so this might be a bug in z2m?

**Comment by robertsLando** [comment]
@zargony In fact you are right. Just noticed that there is an override of `getAssociations` method (http://www.openzwave.net/dev/classOpenZWave_1_1Manager.html#a9b94e5df2e6ea1fbefb786f9f078a01d) that should make the work. I need to understand how to implement this on openzwave shared. 

Are you familiar with cpp?

**Comment by robertsLando** [comment]
I have found it: https://github.com/OpenZWave/node-openzwave-shared/blob/master/src/openzwave-groups.cc

**Comment by zargony** [comment]
Cool, thanks for the quick response!

(I'm having troubles cross-building an arm64 image on my Mac to test it, but I'll try asap when I can build on a real Linux)

**Comment by robertsLando** [comment]
Isn’t it already available on dockerhub? I mean the arm64 image

---

Daniel

**Comment by zargony** [comment]
> Isn’t it already available on dockerhub? I mean the arm64 image

From what I see, images of PRs are built but not pushed to Docker Hub.

**Comment by robertsLando** [comment]
Nope, dev tag is used for this :) it is builded on every commit to master branch

**Comment by robertsLando** [comment]
Ops sorry I misunderstood, you right I thought the pr was merged. Wait a moment

**Comment by robertsLando** [comment]
@zargony dev branch will be the feature in an hour or less, let me know :) This will be available in next release 4.0.0

**Comment by zargony** [comment]
List of current associations shows fine now. Cool, thanks a lot!

But I still can't seem to remove an association with an instance id. It works for associations without an instance id, but not for associations with an instance id. It looks like the instance id isn't passed to the API call, because ozw log states
```
2020-07-24 10:37:47.174 Info, Node002, MultiChannelAssociation::Remove - Removing End Point 0 on node 28 from group 4 of node 2
```
(end point 0 even though I set instance id to 5 on the web page)


Some UX thoughts:
- it would certainly be easier to remove an association if you could just select it in the list of current associations and press "remove"
- it shows "instance id: 0" for associations without an instance id now, which might be confusing. I think it's common practice to not show the instance id at all if it's 0, e.g. just `Node 5`, but `Node 5, instance 2` or `Node 5.2` for instance id 2.

**Comment by robertsLando** [comment]
You have to enable multi instance switch end specify the instance there when instance is > 0

**Comment by zargony** [comment]
I did enable the multi instance switch and specified an instance id > 0. It works for adding a new association, but doesn't seem to work for removing an existing association.

**Comment by robertsLando** [comment]
I think I forgot to add instance in removeAssociation call, will fix that tomorrow thanks for the report :)

---

Daniel

**Comment by robertsLando** [comment]
@zargony fixed this too, available on dev branch if you are interested to test it :)

**Comment by zargony** [comment]
> fixed this too, available on dev branch if you are interested to test it :)

@robertsLando Works fine, thanks a lot! (though the UI could be improved at some time ;) )

**Comment by robertsLando** [comment]
@zargony I have many UI improvments in my TodoS, What I miss is time :( I try to focus on make things work for now
