### ISSUE TITLE
Home Assistant 0.113 change to birth and will message topic defaults

### ISSUE THREAD

**Issue by raetha** [OpenZWave/Zwave2Mqtt#638]
**Describe the solution you'd like**
Per the Home Assistant 0.113 release notes, they have changed the MQTT integration to have a default topic for birth and will messages of "homeassistant/status". Details can be found in release notes at: https://www.home-assistant.io/blog/2020/07/22/release-113/

It would be ideal if Zwave2Mqtt either made the topic configurable, or if it would be updated to use the default value from HA. With HA going more and more towards UI based configuration, having to manually update the configuration YAML should ideally be an option, but not a requirement.

**Comment by robertsLando** [comment]
@raetha PR ready. It will come with a major release 4.0.0

**Comment by raetha** [comment]
@robertsLando Thanks so much for the quick update. I look forward to 4.0.0 coming out! :)
