### ISSUE TITLE
[bug] Updating config results in disconnecting from MQTT

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#64]
**Version**
2.0.2

Build/Run method
- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2
Openzwave Version: 1.4.1

**Describe the bug**
As soon as I change a setting, the gateway will disconnect from MQTT and keeps on reporting it cannot reconnect:
```
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.861Z z2m:Zwave zwave node 28: changed: 113-1-0:Alarm Type:0 -> 0
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.861Z z2m:Mqtt Error while publishing a value client disconnecting
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.862Z z2m:Zwave zwave node 28: changed: 113-1-1:Alarm Level:0 -> 0
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.862Z z2m:Mqtt Error while publishing a value client disconnecting
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.862Z z2m:Zwave zwave node 28: changed: 113-1-2:SourceNodeId:0 -> 0
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.862Z z2m:Mqtt Error while publishing a value client disconnecting
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.862Z z2m:Zwave zwave node 28: changed: 113-1-10:Burglar:0 -> 8
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.863Z z2m:Mqtt Error while publishing a value client disconnecting
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.879Z z2m:Zwave zwave node 28: changed: 48-1-0:Sensor:false -> true
Jul 24 20:15:42 zwave2mqtt zwave2mqtt[623]: 2019-07-24T18:15:42.879Z z2m:Mqtt Error while publishing a value client disconnecting
```
I have to actually restart Z2M in order to get it going again.

**To Reproduce**
See above

**Expected behavior**
The MQTT connection to be restored

**Additional context**
-

**Comment by robertsLando** [comment]
What you mean with "change a settings" ? Do you mean you set a new setting and than you click on save?

**Comment by syphernl** [comment]
If I make any change in the settings, this results in disconnecting from MQTT and constantly reporting the above error. It doesn't seem to reconnect. Only a restart solves it (the settings are ok)

**Comment by syphernl** [comment]
It looks like this issue is happening if the `zwcfg_HOMEHEX.xml` is not writable by the Z2M user. After fixing this, I can store the configuration just fine.

Perhaps it would be wise to add a check for this.

**Comment by julien-w** [comment]
I've this problem. After un-checking the "Hass discovery" in settings and saving them...
And permissions seems to be OK.

**Comment by robertsLando** [comment]
I’m not able to reproduce this problem. Could you provide more info about the version running? 

Daniel

**Comment by julien-w** [comment]
Just edited my first message above, I'm on docker with latest-dev since a few days (used my own build before to have OZW 1.6).

I'm using this docker-compose:
version: "3.7"
services:
  zwave2mqtt:
#    build: Zwave2Mqtt-source/.
    image: robertslando/zwave2mqtt:latest-dev
    user: "0:0"
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - zwave
    devices:
      - "/dev/zstick:/dev/ttyACM0"
    volumes:
      - ./data:/usr/src/app/store
    environment:
      - TZ=Europe/Paris
    ports:
      - "8091:8091"
networks:
  zwave:

**Comment by julien-w** [comment]
I can reproduce this problem by modifying Hass discovery or Retain discovery in the settings.

**Comment by robertsLando** [comment]
@julien-w Sorry but in all my instances I never expected such problem... The problem should be related for sure to some kind of permission issue, the only directory where z2m writes is the `store` directory so you should just ensure that everything is writable there

**Comment by julien-w** [comment]
Juste tryed on docker :latest, i've the same problem (using the same directory).
I'll check again permissions, thank you.
