### ISSUE TITLE
[question] Node values 'Lost' after 'Refresh Node Info' (Fibaro Wall Plug)

### ISSUE THREAD

**Issue by kvaster** [OpenZWave/Zwave2Mqtt#641]
Recently I have added several Fibaro wall plugs in my system - FGWPE/F Wall Plug Gen5 (FIBARO System).

After initialization it was all OK - I was able to see following items under 'User':
- Switch
- Power
- Electric kWh
- Electric W
- Exporting

But after 'Refresh Node Info' I can see only following items:
- Switch
- Power

How can I bring back all other parameters ?

**Comment by robertsLando** [comment]
@kvaster Did you try to send it again? Or did you try to restart the application?

**Comment by kvaster** [comment]
Both. Send again, restart, all of this.

**Comment by kvaster** [comment]
Probably this is 'fibaro' bug or openzwave lib bug :/

**Comment by robertsLando** [comment]
@kvaster Could you send the ozw log here?

**Comment by kvaster** [comment]
OZW logs were not enabled by default. I will enable them, but there will be only log lines after 'refresh node info'.
I've attached log. Please take a look on node 14.
[OZW_Log.txt](https://github.com/OpenZWave/Zwave2Mqtt/files/4967318/OZW_Log.txt)

**Comment by kvaster** [comment]
Also in ozwcache before refreshing node info:

```
                        <CommandClass id="50" name="COMMAND_CLASS_METER">
                                <Compatibility />
                                <State>
                                        <CCVersion>2</CCVersion>
                                        <InNif>true</InNif>
                                        <StaticRequests>2</StaticRequests>
                                </State>
                                <Instance index="1" />
                                <Value type="decimal" genre="user" instance="1" index="0" label="Electric - kWh" units="kWh" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="4.88">
                                        <Help></Help>
                                </Value>
                                <Value type="decimal" genre="user" instance="1" index="2" label="Electric - W" units="W" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="0.0">
                                        <Help></Help>
                                </Value>
                                <Value type="bool" genre="user" instance="1" index="256" label="Exporting" units="" read_only="true" write_only="false" verify_changes="false" poll_intensity="0" min="0" max="0" value="False">
                                        <Help></Help>
                                </Value>
                                <Value type="button" genre="system" instance="1" index="257" label="Reset" units="" read_only="false" write_only="true" verify_changes="false" poll_intensity="0" min="0" max="0">
                                        <Help></Help>
                                </Value>
                        </CommandClass>
```

And after:

```
                        <CommandClass id="50" name="COMMAND_CLASS_METER">
                                <Compatibility />
                                <State>
                                        <InNif>true</InNif>
                                        <StaticRequests>2</StaticRequests>
                                </State>
                                <Instance index="1" />
                        </CommandClass>
```

**Comment by robertsLando** [comment]
Soooo strange 😐 did you also tried to remove and add back again the node?

**Comment by kvaster** [comment]
Yes. And I can see all values right after adding plug. And they are gone again after 'Refresh Node Info'

**Comment by robertsLando** [comment]
@Fishwaldo Why does this happen? It's not someting related to Z2M... @kvaster could you attach the OZW_LOG when you do this please? I suggest you to remove the device, add it back and call refresh node info so we can see what's going on on the logs

**Comment by kvaster** [comment]
I'm sorry, I'm away from home right now. I will give full logs on Monday. But it looks like it is related to open-zwave itself.

**Comment by robertsLando** [comment]
@kvaster sure, I have no control of them. Can I close this and could you open a issue on ozw repo?
