### ISSUE TITLE
[bug] - Fibaro FGBS-222 Smart Implant - System Parameter 117-1-0 not sent properly to module after value change fom "Unprotected" to "No Operation Possible"

### ISSUE THREAD

**Issue by sbik38** [OpenZWave/Zwave2Mqtt#647]
Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: latest (but I don't know where to check this in Docker)
Openzwave Version: 1.6.0

**Describe the bug**
My Fibaro FGBS-222 Smart Implant was properly included (after Exclusion) and status is alive with all parameters visible and changeable except the parameter (from System) 117-1.0 by default at "Unprotected" that I want to change to "No Operation Possible" to dissociate the Inputs IO of the modules from the Outputs IO
When I select "No Operation Possible" from the dropdown menu and then press the Arrow validation icon, either it switch back immediately by its own to "Unprotected", or it accept it, but then when I exit that Module and come back again in its settings, that parameter 117-1-0 is still at "Unprotected" value (means my selection was not sent to the module)
Note : same behaviour with 117-2-0
If you could have a look on this that would be really great
Note : That module is working properly as under Jeedom ZWave Plugin I was able to set it to "No Operation Possible"

**To Reproduce**
explained above

**Expected behavior**
Expect to have parameter 117-1-0 and 117-2-0 staying that the value that I select + validate (means the value " No Operation Possible' instead of "Unprotected"

**Comment by sbik38** [comment]
If this can help, I have now Add-on info. I unplug my Aeotec Gen5 Stick controler from my NAS (where Zwae2MQTT Broker is running) and connected it to my PC. I run then the Silicon Labs "ZWave PC Controler 5" SW and set inside that tool Manually the Local Protection setting of my Smart Implant Node to the value 2 (which correspond to the value "No Operation Possible")
I then unplug the USB Key from my PC and plug it again to my NAS
I checked then in Zwave2MQTT the value of that 117-1-0 and here..... : Magic, the default value is now "No Operation Possible".
This solve my issue, but I think that would be great to fix that bug for other users as using the Silicon Lab SW is here really a tricky way
Hope this helps

**Comment by robertsLando** [comment]
@sbik38 I think it something strictly related to your device (so maybe a compatibility problem or else) and I suggest to answer this kind of questions (with OZW log attached) in OZW log library
