### ISSUE TITLE
[feat] Ignoring/not discovering specific keys to HASS

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#65]
**Is your feature request related to a problem? Please describe.**
With the HASS functionality I now have a lot of "useless" entities such as `alarm_type`, `alarm_level` and `alarm_burgular`. It would be nice if these could be prevented to be sent to HASS, and therefor not being discovered.

**Describe the solution you'd like**
An entity blacklist of sorts would be nice. It could be a list of keys that should not be sent to MQTT.

**Comment by robertsLando** [comment]
Like other issue. I suggest to put the gateway in manual mode and manually select which value you want to send for each device type in your network. In this way you can also set a custom device class and icon too
