### ISSUE TITLE
[feat] Send device_class motion for motion sensors for HASS discovery

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#66]
**Is your feature request related to a problem? Please describe.**
Right now motion sensors create the `_contact` sensor with open/closed. HASS sees this - by default - as a door. If the discovery could send `device_class`: `motion` it should change to a motion icon + On/Off (Detected/Not detected).

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
In the HASS customize_glob configuration I have put the following:
 ```
binary_sensor.*_pir_contact:
  icon: mdi:walk
  device_class: motion
```
This solves the problem, but it would be nicest if Z2M could send the corrected data to HASS.

**Comment by robertsLando** [comment]
Hi @syphernl . To discover devices I try to guess the correct hass configuration based on zwave device and other properties of the values of device. Sometimes it is impossible for me to know the exactly type of device, for example for binary sensors, I suggest you to add this value to gateway vlaues table and set your custom device class from the dropdown list. Check readme for more information
