### ISSUE TITLE
feat: change theme-color header meta based on dark theme

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#669]
**Is your feature request related to a problem? Please describe.**
This is related to when I select dark theme for the site on an Android phone and the navigation bar at the bottom remains white.

**Describe the solution you'd like**
I would like the navigation bar to also go black or white according to whether dark theme is on or off. I believe this would mean setting the `<meta name="theme-color" content="#ffffff">` header to #000000 instead of #ffffff, but I'm not sure this is the fix. 

I also noticed that that meta tag is set twice here;
https://github.com/OpenZWave/Zwave2Mqtt/blob/master/views/index.ejs#L9
and here:
https://github.com/OpenZWave/Zwave2Mqtt/blob/master/views/index.ejs#L21
Might need to remove one of them.

**Describe alternatives you've considered**
Unfortunately, there are no alternatives that I can think of.

**Additional context**
Here's light mode with a light navigation bar at the bottom.
![Screenshot_20200814-213605_Chrome](https://user-images.githubusercontent.com/732659/90305333-57df9880-de76-11ea-889e-e3c6d412a14a.jpg)

Here's dark mode with a light navigation bar at the bottom. This is the one I'd like the navigation bar to match the dark mode by being black.
![Screenshot_20200814-213144_Chrome](https://user-images.githubusercontent.com/732659/90305336-59a95c00-de76-11ea-86a6-74d8606a1989.jpg)

Cheers,

P.S. apologies I don't know how to resize the images

**Comment by robertsLando** [comment]
Ok I think I can use this function 

```js
function changeThemeColor() {
    var metaThemeColor = document.querySelector("meta[name=theme-color]");
    metaThemeColor.setAttribute("content", getRandomColor());
    setTimeout(function() {
        changeThemeColor();
    }, 3000);
}
```

TO programmatically change the theme color once the theme changes, also I have to remove the duplicate meta tag, let me sort this

**Comment by robertsLando** [comment]
@chilicheech done
