### ISSUE TITLE
[feat] LWT handling

### ISSUE THREAD

**Issue by Wildcarde** [OpenZWave/Zwave2Mqtt#674]
**Is your feature request related to a problem? Please describe.**
Allow for the configuration of LWT messages for zwave devices so it's possible to detect and alert on device failure.

**Describe the solution you'd like**
I've got a zwave GE digital pool timer that I use for managing and monitoring my pools filtering schedule.  However I don't seem to have anyway of detecting failure states with the published information available via zwave2mqtt.  This is important in scenarios where the GFCI breaker may trip and disable the pool filter entirely, it doesn't happen often (twice now in 2 years) but I'd like to be able to setup alerting so I can keep track of the event and send myself push notifications when it happens.

**Describe alternatives you've considered**
I've considered adding some node-red code that compares desired states and reported wattage but that will generate a number of false positives vs. being able to montior device status directly.

**Comment by robertsLando** [comment]
> detecting failure states

What you mean?

**Comment by Wildcarde** [comment]
Specifically in this case: if the GFCI breaker trips power is cut, the device goes offline entirely.  The zwave stick is aware of this, but it doesn't seem that information is propagated forward so that it can be detected by mqtt clients.

**Comment by robertsLando** [comment]
Did you checked `status` topic? each device has it

**Comment by Wildcarde** [comment]
Is that a stock export for all devices? I don't see anything related to status in the 'new value' pane under the gateway.

**Comment by Wildcarde** [comment]
it would seem yes:
Message 2 received on zwave0/Garage/PoolPower/status at 6:36 PM:
```
{
    "time": 1598206882076,
    "value": true,
    "status": "Alive"
}
```

Ok, I'll add some monitoring around this and see if that's sufficient for what I need, thanks for the tip!

**Comment by robertsLando** [comment]
@Wildcarde Let me know, closing this for now :)
