### ISSUE TITLE
[question] Light discovered in Hassio without rgb

### ISSUE THREAD

**Issue by joselito11** [OpenZWave/Zwave2Mqtt#68]
I am migrating from existing Zwave integration in Hassio. Zipato Bulb 2 was in Hassio(installed ZWAVE2MQTT add-on) discovered as `light.nodeid_24_dimmer`, without RGB option. In ZWAVE2MQTT add-on the light Type is Light Dimmer Switch-same as Fibaro Dimmer 2. At Home Assistant - Devices from the light node, there are `light_dim` and `light_rgb` devices, but I was not able to push `light_rgb`-get colors to Hassio. In add-on I can change colors, etc.. How can I change this? Dimmer and switches had been discovered okay.

**Comment by robertsLando** [comment]
I need to know in zwave2mqtt control panel the valueId of the value that you use to control the rgb in order to make it work. The valueid is at the right of every value label between ‘(‘ ‘)’. 

Daniel

**Comment by joselito11** [comment]
This?
```
{
  "type": "light",
  "object_id": "rgb",
  "discovery_payload": {
    "rgb_command_template": "{{ '#%02x%02x%02x00' | format(blue, green, red)}}",
    "rgb_command_topic": "homeassistant/nodeID_24/51/1/0/set",
    "rgb_state_topic": "homeassistant/nodeID_24/51/1/0",
    "rgb_value_template": "{{ value_json.value }}",
    "state_topic": "homeassistant/nodeID_24/51/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_nodeID_24"
      ],
      "manufacturer": "Zipato",
      "model": "0x0003",
      "name": "Bulb 2",
      "sw_version": "Unknown"
    },
    "name": "nodeID_24_rgb",
    "unique_id": "zwave2mqtt_nodeID_24_24-51-1-0"
  },
  "discoveryTopic": "light/nodeID_24/rgb/config",
  "values": [
    "51-1-0"
  ],
  "persistent": false,
  "id": "light_rgb"
}
```
```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "state_topic": "homeassistant/nodeID_24/38/1/0",
    "state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "command_topic": "homeassistant/nodeID_24/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_nodeID_24"
      ],
      "manufacturer": "Zipato",
      "model": "0x0003",
      "name": "Bulb 2",
      "sw_version": "Unknown"
    },
    "name": "nodeID_24_dimmer",
    "unique_id": "zwave2mqtt_nodeID_24_24-38-1-0"
  },
  "discoveryTopic": "light/nodeID_24/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "id": "light_dimmer"
}
```

**Comment by robertsLando** [comment]
@joselito11 Try now

**Comment by warcanoid** [comment]
@robertsLando still no RGB entity, just dimmer

**Comment by joselito11** [comment]
@robertsLando still no RGB, same as before

**Comment by robertsLando** [comment]
Actually this implementation should only allow you to set the rgb and not to control the light. Does the rgb works?

**Comment by joselito11** [comment]
No, just dim option

**Comment by iAutom8** [comment]
First off, Excellent project!

I appear to have a similar issue with my AEON ZW098.  I have Dimmer but no RGB.  Here are the discovery payloads in MQTT for it :

`homeassistant/light/Bunkie-LED/dimmer/config: {"schema":"template","brightness_template":"{{ (value_json.value / 99 * 255) | round(0) }}","state_topic":"zwave/Bunkie/LED/38/1/0","state_template":"{{ \"off\" if value_json.value == 0 else \"on\" }}","command_topic":"zwave/Bunkie/LED/38/1/0/set","command_on_template":"{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}","command_off_template":"0","device":{"identifiers":["zwave2mqtt_Bunkie-LED"],"manufacturer":"AEON Labs","model":"0x0062","name":"ZW098 LED Bulb","sw_version":"1.05"},"name":"Bunkie-LED_dimmer","unique_id":"zwave2mqtt_Bunkie-LED_6-38-1-0"}

homeassistant/light/Bunkie-LED/rgb/config: {"rgb_command_template":"{{ '#%02x%02x%02x00' | format(blue, green, red)}}","rgb_command_topic":"zwave/Bunkie/LED/51/1/0/set","rgb_state_topic":"zwave/Bunkie/LED/51/1/0","rgb_value_template":"{{ value_json.value }}","state_topic":"zwave/Bunkie/LED/51/1/0","device":{"identifiers":["zwave2mqtt_Bunkie-LED"],"manufacturer":"AEON Labs","model":"0x0062","name":"ZW098 LED Bulb","sw_version":"1.05"},"name":"Bunkie-LED_rgb","unique_id":"zwave2mqtt_Bunkie-LED_6-51-1-0"}

homeassistant/light/Bunkie-LED/rgb/config: {"rgb_command_template":"{{ '#%02x%02x%02x00' | format(blue, green, red)}}","rgb_command_topic":"zwave/Bunkie/LED/51/1/1/set","rgb_state_topic":"zwave/Bunkie/LED/51/1/1","rgb_value_template":"{{ value_json.value }}","state_topic":"zwave/Bunkie/LED/51/1/1","device":{"identifiers":["zwave2mqtt_Bunkie-LED"],"manufacturer":"AEON Labs","model":"0x0062","name":"ZW098 LED Bulb","sw_version":"1.05"},"name":"Bunkie-LED_rgb","unique_id":"zwave2mqtt_Bunkie-LED_6-51-1-1"}`

And in zwave2mqtt control panel I have:

`{
  "type": "light",
  "object_id": "rgb",
  "discovery_payload": {
    "rgb_command_template": "{{ '#%02x%02x%02x00' | format(blue, green, red)}}",
    "rgb_command_topic": "zwave/Bunkie/LED/51/1/1/set",
    "rgb_state_topic": "zwave/Bunkie/LED/51/1/1",
    "rgb_value_template": "{{ value_json.value }}",
    "state_topic": "zwave/Bunkie/LED/51/1/1",
    "device": {
      "identifiers": [
        "zwave2mqtt_Bunkie-LED"
      ],
      "manufacturer": "AEON Labs",
      "model": "0x0062",
      "name": "ZW098 LED Bulb",
      "sw_version": "1.05"
    },
    "name": "Bunkie-LED_rgb",
    "unique_id": "zwave2mqtt_Bunkie-LED_6-51-1-1"
  },
  "discoveryTopic": "light/Bunkie-LED/rgb/config",
  "values": [
    "51-1-1"
  ],
  "persistent": false,
  "id": "light_rgb"
}`

Let me know if there is anything else I can provide.

Thanks

**Comment by iAutom8** [comment]
I was reviewing my logs and found the following error for the RGB light setup.  In summary the error message is `required key not provided @ data['command_topic']` . From the Home Assistant [docs ](https://www.home-assistant.io/components/light.mqtt/) `command_topic` is required.

The RGB for these lights is the only thing not working in my setup using zwave2mqtt.  Hopefully, this information is helpful in resolving the issue.

Thanks!

```
2019-09-19 21:31:22 ERROR (MainThread) [homeassistant.components.mqtt.light]
Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': 
({'rgb_command_template': "{{ '#%02x%02x%02x00' | format(blue, green, red)}}", 
'rgb_command_topic': 'zwave/Bunkie/LED/51/1/0/set', 'rgb_state_topic': 'zwave/Bunkie/LED/51/1/0', 
'rgb_value_template': '{{ value_json.value }}', 'state_topic': 'zwave/Bunkie/LED/51/1/0', 'device': 
{'identifiers': ['zwave2mqtt_Bunkie-LED'], 'manufacturer': 'AEON Labs', 'model': '0x0062', 'name': 
'ZW098 LED Bulb', 'sw_version': '1.05'}, 'name': 'Bunkie-LED_rgb', 'unique_id': 'zwave2mqtt_Bunkie-
LED_6-51-1-0', 'platform': 'mqtt'},)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 66, in async_discover
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 287, in _exec
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 36, in validate_mqtt_light
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['command_topic']
```

**Comment by robertsLando** [comment]
@iAutom8 @joselito11 Please check my latest commit and tell me if n ow your rgb lights are working as expected :)

**Comment by iAutom8** [comment]
I rebuilt the Docker image following your instructions and now I see one device for the light and no error messages in the HA logs.  However you can see from the screenshot that there is no RGB options.  Also, I have an issue when I turn on the light I can't turn it off as it toggles itself back to off.  I'll trace the MQTT messages and see if anything is obvious later tonight

Thanks for the update.

![image](https://user-images.githubusercontent.com/20862130/65376570-8a394380-dc6f-11e9-9239-0177992fc0a8.png)

**Comment by robertsLando** [comment]
Please let me know if you see any error in hass logs or something else that could help me fix this

Daniel

**Comment by iAutom8** [comment]
There are no errors in the hass logs but realized last night that another ZWave switch and outlet are behaving the same now.   They were fine the night before.  When I turn them on they come on but then they toggle off in hass within a couple of seconds but actually stay on.   I had to create a hass script to turn them off.  I thought maybe this was an hass issue as I upgraded to the latest but I have another zwave2mqtt installation in the house with a switch that is working as it should using the same hass instance.  

I went ahead and reverted back to 2.0.3 and still have the same issue.  what is odd however the RGB light is off but showing as on in hass.  When I turn it off via hass it toggles back withing second to on again.

I will try tonight to remove the nodes and re-add them

**Comment by robertsLando** [comment]
Really strange behavior :( hope I didn’t break something but I haven’t changed anything about the on/off management of switches I will try to check 

Daniel

**Comment by iAutom8** [comment]
I got my toggles to stay.  I added MQTT to the hass logger and set it to info and found lots of the  following: 
```WARNING (MainThread) [homeassistant.components.mqtt] JSON result was not a dictionary```

Then I changed to debug and got:
```
DEBUG (MainThread) [homeassistant.components.mqtt] Received message on zwave/Bunkie/MultiSensor/49/1/3 (retained): b'8'
WARNING (MainThread) [homeassistant.components.mqtt] JSON result was not a dictionary
```

Then I remembered while trying to debug the RGB light I had changed the Payload Type in zwave2mqtt to "Just value" to simplify the output.  Now that I changed it back to "Entire Z-Wave value Object" things started to work again.   Changing it to "JSON Time-value" also works ok.

Can I suggest updating the documentation to reflect that the Payload cannot be "Just value" in the   [Home Assistant section.](https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta)

Now I will try the latest code again to see where we are at wit the RGB light issue.

Thanks

**Comment by iAutom8** [comment]
Here is the latest log entries using the latest code.  I am getting the Toggle issue still.  It sends the ON but it is not getting a state back but is getting a brightness level.  Below the log entries is the new Hass Device JSON from zwave2mqtt.  Is it possible that the `state_topic` and `brightness_state_topic` should be different?  They are both set to `zwave/Bunkie/LED/38/1/0`.   

Still no RGB options.

Let me know what you need.

```
[homeassistant.components.mqtt] Transmitting message on zwave/Bunkie/LED/38/1/0/set: ON
[homeassistant.components.mqtt] Received message on zwave/Bunkie/LED/38/1/0: b'{"time":1569200155872,"value":99}'
[homeassistant.components.mqtt] Received message on zwave/Bunkie/LED/38/1/0: b'{"time":1569200155909,"value":99}'
[homeassistant.components.mqtt] Received message on zwave/Bunkie/LED/51/1/0: b'{"time":1569200156602,"value":"#000000FF00"}'
[homeassistant.components.mqtt] Received message on zwave/Bunkie/LED/38/1/0: b'{"time":1569200156637,"value":99}'
[homeassistant.components.mqtt] Received message on zwave/Bunkie/LED/51/1/0: b'{"time":1569200156918,"value":"#000000FF00"}'
```



```
{
  "type": "light",
  "object_id": "rgb_dimmer",
  "discovery_payload": {
    "state_topic": "zwave/Bunkie/LED/38/1/0",
    "command_topic": "zwave/Bunkie/LED/38/1/0/set",
    "brightness_state_topic": "zwave/Bunkie/LED/38/1/0",
    "brightness_command_topic": "zwave/Bunkie/LED/38/1/0/set",
    "on_command_type": "first",
    "state_value_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "brightness_value_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "rgb_command_template": "{{ \"#%02x%02x%02x\" | format(blue, green, red)}}",
    "rgb_command_topic": "zwave/Bunkie/LED/51/1/0/set",
    "rgb_state_topic": "zwave/Bunkie/LED/51/1/0",
    "rgb_value_template": "{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}",
    "device": {
      "identifiers": [
        "zwave2mqtt_Bunkie-LED"
      ],
      "manufacturer": "AEON Labs",
      "model": "0x0062",
      "name": "ZW098 LED Bulb",
      "sw_version": "1.05"
    },
    "name": "Bunkie-LED_rgb_dimmer",
    "unique_id": "zwave2mqtt_Bunkie-LED_6-38-1-0"
  },
  "discoveryTopic": "light/Bunkie-LED/rgb_dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "id": "light_rgb_dimmer"
}
```

**Comment by robertsLando** [comment]
@iAutom8 About the payload type I had made a fix some moths ago to support all type of payloads but I just realised it was bugged and I have fixed it in latest commit. 

Now about the main issue:

> Is it possible that the state_topic and brightness_state_topic should be different? They are both set to zwave/Bunkie/LED/38/1/0

The `light` state shows if light is `on` or `off`. Unfortunally I have not many zwave device to test and in the one I have I saw that there was only the dimmer to set the light brightness and the color option without any switch to turn it on/off, so I have try to fix this in hass by set the light state based on the brightness intensity `state_value_template: {{ \"off\" if value_json.value == 0 else \"on\" }}` and it was working well in the dimmer version without rgb, I don't know why here doesn't work as expected. The hardest part was the rgb template, I wasn't able to find a way to extract r g b values from hex string sent by zwave, now I have successfully parsed it using the template `"rgb_value_template": "{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}"` and no error is thrown in hass but rgb still doesn't show up in hass ui. I need some help here :(

**Comment by iAutom8** [comment]
I hope to get back to this soon.

**Comment by mihalski** [comment]
Has anyone else made any progress with this? I just paired my ZW098 bulbs via zwave2mqtt and discovered the same issue you're all discussing.

Although it would be nice to have the rib control, I'd be happy to just start with a working switch for the lights so that Home Assistant can see that the light is on.

Here is my discovery template if it helps:

```json
{"state_topic":"zwave2mqtt/5/38/1/0","command_topic":"zwave2mqtt/5/38/1/0/set","brightness_state_topic":"zwave2mqtt/5/38/1/0","brightness_command_topic":"zwave2mqtt/5/38/1/0/set","on_command_type":"first","state_value_template":"{{ \"off\" if value_json.value == 0 else \"on\" }}","brightness_value_template":"{{ (value_json.value / 99 * 255) | round(0) }}","rgb_command_template":"{{ \"#%02x%02x%02x\" | format(blue, green, red)}}","rgb_command_topic":"zwave2mqtt/5/51/1/0/set","rgb_state_topic":"zwave2mqtt/5/51/1/0","rgb_value_template":"{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}","device":{"identifiers":["zwave2mqtt_downlight_alcove"],"manufacturer":"AEON Labs","model":"0x0062","name":"ZW098 LED Bulb","sw_version":"Unknown"},"name":"downlight_alcove_rgb_dimmer","unique_id":"zwave2mqtt_downlight_alcove_5-38-1-0"}
```

Regards,
Michal

**Comment by iAutom8** [comment]
I have not had a chance to get back to it myself.  Not sure when I will be able to debug this some more but open to trying any suggestions.  Work seems to have taken all my free time lately.

**Comment by johntdyer** [comment]
looks like im in the same lot... anything i can do to help test?

**Comment by robertsLando** [comment]
After many tries I think that it is more like an hass bug or something hass related because now no error is thrown in hass but nothing works at the same time

Daniel

**Comment by robertsLando** [comment]
Anyone that could try to open an issue on Home assistant forum looking for help?

**Comment by robertsLando** [comment]
@iAutom8 any news?

**Comment by jwalker343** [comment]
@robertsLando and @johntdyer I was able to fix this in my setup after several hours of beating me head against the keyboard. I have 3 Aeotec ZW098 LED Bulbs that all work as expected now.

In the "HASS Device JSON" (Discovery template?) from the zwave2mqtt control panel, I changed these two lines:
```diff
{
  "type": "light",
  "object_id": "rgb_dimmer",
  "discovery_payload": {
    "state_topic": "zwave2mqtt/livingrm_lamp/38/1/0",
    "command_topic": "zwave2mqtt/livingrm_lamp/38/1/0/set",
    "brightness_state_topic": "zwave2mqtt/livingrm_lamp/38/1/0",
    "brightness_command_topic": "zwave2mqtt/livingrm_lamp/38/1/0/set",
    "on_command_type": "first",
-    "state_value_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
+    "state_value_template": "{{ \"OFF\" if value_json.value == 0 else \"ON\" }}",
    "brightness_value_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
-    "rgb_command_template": "{{ \"#%02x%02x%02x\" | format(blue, green, red)}}",
+    "rgb_command_template": "{{ \"#%02x%02x%02x\" | format(red, green, blue)}}",
    "rgb_command_topic": "zwave2mqtt/livingrm_lamp/51/1/0/set",
    "rgb_state_topic": "zwave2mqtt/livingrm_lamp/51/1/0",
    "rgb_value_template": "{{ value_json.value[1:3] | int(0, 16) }},{{ value_json.value[3:5] | int(0, 16) }},{{ value_json.value[5:7] | int(0, 16) }}",
    "device": {
      "identifiers": [
        "zwave2mqtt_livingrm_lamp"
      ],
      "manufacturer": "AEON Labs",
      "model": "0x0062",
      "name": "ZW098 LED Bulb",
      "sw_version": "1.05"
    },
    "name": "livingrm_lamp_rgb_dimmer",
    "unique_id": "zwave2mqtt_livingrm_lamp_12-38-1-0"
  },
  "discoveryTopic": "light/livingrm_lamp/rgb_dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": true,
  "id": "light_rgb_dimmer"
}
```

**Comment by robertsLando** [comment]
I think hass has made some change because as I remember the old payload_on and payload_off where `on` and `off`, can someone confirm this? I would like to know that this doesn't breaks some existing configuration

**Comment by jwalker343** [comment]
I'm all for making sure this does not break anybody's config!

According to the [docs](https://www.home-assistant.io/integrations/light.mqtt/#payload_on) on home-assistant.io, `payload_on` and `payload_off` defaults to `ON` and `OFF`. 
The Docs also specify that all values in Home-Assistant are [case-sensitive](https://www.home-assistant.io/docs/configuration/yaml/#upper-and-lower-case).

So it does seem like this brings the template values in-line with home-assistant's defaults.

**Comment by robertsLando** [comment]
@jwalker343 I know now hass works with ON and OFF but my question is if this is a new change in hass latest releases beause if I fix this I could break old hass instances...
