### ISSUE TITLE
[question] - -e Docker Variables available

### ISSUE THREAD

**Issue by jaburges** [OpenZWave/Zwave2Mqtt#680]
Unraid uses a pretty cool UI (Community Applications - which are basically docker containers deployed via the UI).

It allows the specification of the port, the volumes etc, but also some environment variables.

Do you surface up -e Network_Key for example? It would be useful to specify that (and maybe any other useful variables) for a user to carry out a one click install.

Most valuable reason for this is the automatic updating of the docker containers. 
I've kicked off a Community App request [here](https://github.com/selfhosters/unRAID-CA-templates/issues/173)

**Comment by robertsLando** [comment]
Hi @jaburges ! I could make the support for that but why supply network key from env var instead of provide it from the UI? For security purposes?

**Comment by jaburges** [comment]
in UnRaid UI you can add these items so the Z2M starts with the right key

**Comment by robertsLando** [comment]
@jaburges I understand this but you can also provide it from the UI, this is why I'm asking the pro/cons by add it using env vars

**Comment by jaburges** [comment]
I think the preferred way for Unraid users is to specify everything possible in the UI with -e / ENV variables.

If it's a lot of work, I would not bother. If it's easy it will open your solution up to more Unraid users.

**Comment by robertsLando** [comment]
Configuration are a lot, create an env var for each one would be a lot of work and I sincerly still don't understand the advantage of this. If you simply run z2m with Unraid then you go to localhost:8091 and configure it from the UI why would you need to specify things from env? 

I would use env vars for the port of the server (there is already an env var for that) and other server specific configuration. Also adding the controller key would be easy but it can be configured from the ui so I'm not sure if it's useful

**Comment by jaburges** [comment]
in terms of security the qt-openzwave docker has the option to add the network_key as an ENV.

i get your point, and you maybe able to just set up an Unraid template (for updating without the ENV variables)
i'll close this

**Comment by robertsLando** [comment]
Open an issue for that, it's a very easy feature to add I will make it once I come back from holidays :)

**Comment by robertsLando** [comment]
@jaburges just submitted a feat for this
