### ISSUE TITLE
[bug] Logs are flooded with `z2m:Gateway no custom devices sources found`

### ISSUE THREAD

**Issue by chilicheech** [OpenZWave/Zwave2Mqtt#686]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt docker: 4.0.2

**Describe the bug**
Logs are being flooded with:
```
z2m     | 2020-08-24 10:20:02.717 Detail, Node002,   Received: 0x01, 0x04, 0x01, 0x13, 0x01, 0xe8
z2m     | 2020-08-24 10:20:02.718 Detail, Node002,   ZW_SEND_DATA delivered to Z-Wave stack
z2m     |   z2m:Gateway no custom devices sources found +4ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +2ms
z2m     |   z2m:Gateway no custom devices sources found +3ms
z2m     |   z2m:Gateway no custom devices sources found +6ms
z2m     | 2020-08-24 10:20:02.835 Detail, Node002,   Received: 0x01, 0x07, 0x00, 0x13, 0x53, 0x00, 0x00, 0x0d, 0xb5
z2m     | 2020-08-24 10:20:02.835 Detail, Node002,   ZW_SEND_DATA Request with callback ID 0x53 received (expected 0x53)
```

**To Reproduce**
1. Start the container and observe the logs

**Expected behavior**
Either to not flood the logs or not check for customDevices every few milliseconds!

**Additional context**
This may be related to changes introduced by #670, #675, and #679

**Comment by chilicheech** [comment]
@pdbogen can you please take a look?

**Comment by robertsLando** [comment]
I think it is caused by ozwlog file, ozw appends logs to that file and the watch is set to data directory and when ozw writes a log it triggere the watch function, you should only check for creation/rename events and not file append to try load custom devices when watching directory 

---

Daniel

**Comment by pdbogen** [comment]
Yep, that sounds likely.

Probably the only sane change here is to suppress the repeated log messages, or skip the log entirely. node does not provide an implementation of `fs.watch` that allows for only receiving certain events.

**Comment by pdbogen** [comment]
Even when watching a directory, node does not tell us about `append`, only `replace` and `create`, and either one of those could be an event we care about. It also does not guarantee that it will provide a filename, though _in theory_ we could opportunistically use the filename to exit earlier when it's present and not one of the two we care about.

But, this is still a lot of extra logic hanging off ozw writing to its cache. 

A somewhat larger change that would solve this more neatly would be to save the "configuration files" i.e. `customDevices.js` / `.json` in a different directory than we save actual state information like OZW cache. Thoughts?

**Comment by chilicheech** [comment]
What I don't get is why it's watching the directory? Can it not instead watch just the 2 files in question?

If there's no way around this I would like to propose we implement a switch to turn this feature off. Having Z2M watch the files while I'm debugging something is super useful and I really appreciate it. However, once I'm done debugging I don't need it to keep watching the file.

**Comment by pdbogen** [comment]
@chilicheech nodejs fs.watch implementation can't watch files that don't exist, so we have to watch the directory to discover when/if the files get created. When they get created, the directory watches are stopped and file watches are started instead, until/unless the files are deleted.

We can definitely work around the log flooding; and I think the performance impact of the attendant FS calls should be relatively quite small.

Given this, would you still want it possible to turn this off?

**Comment by robertsLando** [comment]
> A somewhat larger change that would solve this more neatly would be to save the "configuration files" i.e. customDevices.js / .json in a different directory than we save actual state information like OZW cache

That's absolutely not an option, it would require users using docker to set up two volumes instead of one, also there should be a script on startup that checks if those file exists and in that case moves them to the correct directory, too much work for a simple and side case usage.

> If there's no way around this I would like to propose we implement a switch to turn this feature off

That's for sure a possible solution

> We can definitely work around the log flooding; and I think the performance impact of the attendant FS calls should be relatively quite small.

@pdbogen what do you think so?

**Comment by pdbogen** [comment]
> @pdbogen what do you think so?

My understanding is that ozw is probably only updating its cache every few seconds at the most. This is a lot of log messages, but the actual system calls should only be a couple failed `open` attempts. Two extra system calls every few seconds is not much load in my view.

I'll try to submit a patch later today to resolve the log spam, and also collect some `strace` data to directly observe what syscalls happen and how frequently, though that'll only be with me ~30 node network. I'll also add filename checks to skip extra work when we _know_ the change wasn't one of the two files of interest; though Node docs warn us this won't work in every case, and may not work at all on some platforms.

**Comment by robertsLando** [comment]
> 'll try to submit a patch later today to resolve the log spam, and also collect some strace data to directly observe what syscalls happen and how frequently, though that'll only be with me ~30 node network. I'll also add filename checks to skip extra work when we know the change wasn't one of the two files of interest; though Node docs warn us this won't work in every case, and may not work at all on some platforms.

:+1:

**Comment by chilicheech** [comment]
> We can definitely work around the log flooding; and I think the performance impact of the attendant FS calls should be relatively quite small.
> 
> Given this, would you still want it possible to turn this off?

I don't know how much impact this would have on performance. I would image it's little. I wonder if it has higher impact on something like a Raspberry Pi, but I don't know. That's why I suggested the ability to turn off that feature :)

**Comment by billimek** [comment]
It sounds like we have a handle on the root cause but just in case, I'm experiencing the same thing:  There is a dramatic increase in disk space used in `/usr/src/app/store/OZW_Log.txt`

![image](https://user-images.githubusercontent.com/6393612/91506611-8448db00-e8a0-11ea-8113-ee3e30a62bf2.png)

![image](https://user-images.githubusercontent.com/6393612/91506617-89a62580-e8a0-11ea-9209-ba453d72b499.png)
