### ISSUE TITLE
[question] very old PKG version, wiki lists v1.0.0 / openzwave 1.6?

### ISSUE THREAD

**Issue by Lyve1981** [OpenZWave/Zwave2Mqtt#69]
I researched that openzwave 1.4 is no longer maintained and won't get updates for future z-wave devices, but the install instructions still list that version. 
the latest bridge seems to be v2.xx but the installation mentions version 1.0.

Is there an updated installation tutorial or is the combination of 1.4 / 1.0 the only pair that works properly?

Would be nice if someone could shed some light into it, what to install at the moment.

**Comment by robertsLando** [comment]
Actually openzwave 1.6 is not fully supported by openzwave-shared that is the nodejs binding lib for openzwave. Once it will be ready I will update the docker image and everything else to use openzwave 1.6

Daniel
