### ISSUE TITLE
[bug] temperature unit confusion

### ISSUE THREAD

**Issue by pdbogen** [OpenZWave/Zwave2Mqtt#691]
I've definitely observed some issues with temperature units. I haven't studied the situation close enough to describe it coherently or to start to guess at a cause, but I'm going to open this issue and start collecting my direct observations in the hope of doing so.

1. On a temperature sensor, the number reported from the sensor is degrees fahrenheit, but z2m registers the unit to homeassistant as celsius. As a result HA applies `*9/5+32` to the value, so a sane value like 70F/21C becomes 158F/70C. Some time later this gets fixed (??) perhaps on re-discovery.

![image](https://user-images.githubusercontent.com/321591/91481810-ddd9e700-e859-11ea-9005-cc437e1489f2.png)

2. On a climate device, the `Heating 1` (8-67-1-1) user property _previously_ showed the unit as `C`. I provided a value in C (21). When the field updated it shows the _number_ converted to Fahrenheit (69), and _now_ shows the unit as `F`. On the same climate device, `Cooling 1` (8-67-1-2) has never been "set", and currently shows the unit as `C`.

![image](https://user-images.githubusercontent.com/321591/91481580-86d41200-e859-11ea-811f-0918dc7ec3ed.png)

I'll try to come up with more specific steps to reproduce, but perhaps this will spur some ideas?

**Comment by robertsLando** [comment]
@pdbogen I don't make any conversion on my side, I don't think it's a bug with z2m. I could point you to the code used to set the units: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L1194

**Comment by chilicheech** [comment]
I often see this issue too when I restart z2m. I'm not sure where the problem is. It could be an issue with the underlying libraries, we need to debug to find out the cause.
![Screen Shot 2020-08-28 at 12 46 00 PM](https://user-images.githubusercontent.com/732659/91612149-ab032200-e931-11ea-9720-679b292df447.png)

**Comment by robertsLando** [comment]
@chilicheech Does this happens in specific times or randomly?

**Comment by robertsLando** [comment]
Maybe the units are contained in a configuration command class (the value id starts with 112)? If so maybe that isn't refreshed? Just thoughts

**Comment by pdbogen** [comment]
I definitely don't think this is related to z2m doing a _conversion_, but I think it's reporting (or detecting!) the units incorrectly.

Hypothesis:

1. Zwave hardware sends a number that's fahrenheit degrees
2. z2m reports it to HomeAssistant as Celsius
3. HomeAssistant converts Celsius -> Fahrenheit, so now measurement is wrong, way too high

This happened to me with devices in a zwave network that I moved from HA. Same devices, same network. Problem never came up using HA's native zwave stuff, so either:

1. new version of ozw has a bug compared to the older version in HA native zwave
2. z2m is misbehaving here in a way that HA doesn't
3. HA has special code for detecting & fixing this situation (along the lines of "oh, this air temp sensor says an air temp of 70C, that's probably actually a F number...) but there _is_ reasonable overlap in temperatures so I doubt this.

**Comment by robertsLando** [comment]
What is strange to me is that it automatically fix, this means it's not something related to a wrong discovery payload or it would need a new discovey in order to fix, so the only thing that could cause this is a wrong value coming from ozw, as I said I'm not making any conversions on my side, I simply report values as they come from ozw

**Comment by ve6rah** [comment]
I'm not going to say for sure that this is your situation, but here's something I'm seeing which may give you a clue as to what's happening.
On my thermostat it is publishing changes to humidity (49-1-5) to the same topic as temperature (49-1-1) which results in a very similar graph. I originally also thought it was bouncing between celcius and farenheight until I did some careful conversions and figured out what was actually happening.

**Comment by robertsLando** [comment]
I think that #732 could fix this too
