### ISSUE TITLE
[bug] Missing config values for fibaro dimmer

### ISSUE THREAD

**Issue by bitdivision** [OpenZWave/Zwave2Mqtt#694]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 
- [x] https://github.com/hassio-addons/addon-zwave2mqtt

Zwave2Mqtt version: 4.0.2
Openzwave Version: 1.6.974

**Describe the bug**
For my Fibaro dimmer 2 device (FGD212). The UI is missing several configuration parameters.
![image](https://user-images.githubusercontent.com/205209/91641587-55a43f00-ea1d-11ea-8177-df80e4361a90.png)

Here is what I see listed under `config`:
![Screenshot_2020-08-29 Zwave To MQTT](https://user-images.githubusercontent.com/205209/91641557-17a71b00-ea1d-11ea-898c-45cdf9294afb.png)

This is missing a lot of configuration parameters which are listed in the XML file. See the OZW device file:
https://github.com/OpenZWave/open-zwave/blob/master/config/fibaro/fgd212.xml#L78

I have checked the other sections (User / System) and the parameters are not listed there either.

I have tried to set the value manually using MQTT by sending the value 1 to MQTT topic: `zwave/Dimmer/112/1/20/set`, but I am not seeing any confirmation of it being in the logs (only MQTT message received) and the device does not display the effects.

**To Reproduce**
1. Go to Node
2. Click on Config
3. Look for 112-1-20

**Expected behavior**
I would expect to see 112-1-20 value, but it's missing. This is the same for a lot of other parameters in the device XML file on OZW.

**Comment by robertsLando** [comment]
@bitdivision Missing config files means that them are missing on xml config file, you should submit a pr or open an issue on ozw repo for such things

**Comment by bitdivision** [comment]
Hi, what do I need to change in the device config file? The values are there in the ozw device XML file. See https://github.com/OpenZWave/open-zwave/blob/master/config/fibaro/fgd212.xml#L78

**Comment by robertsLando** [comment]
@bitdivision Try to enable auto update device db flag in zwave settings so, maybe you have an old device config file, remember also to trigger `refreshNodeIndo` against that node to apply the new configuration

**Comment by bitdivision** [comment]
Thanks @robertsLando. That solved it.

Sorry I bugged you about this!

**Comment by robertsLando** [comment]
Glad you fixed it :)
