### ISSUE TITLE
Device stop to work in HA after renaming Name/Location in Control Panel

### ISSUE THREAD

**Issue by ezeitoun** [OpenZWave/Zwave2Mqtt#699]
Hi,
Adding device works perfect, Shows in HA, Integration as well (when doing manual/cp/ha on/off it updates
on both), But when changing the Name/Location in Control Panel, Rarely the update gets to HA,
And the integration dies for that device (HA shows it switch off, but nothing happens and set back to On).

Looking on MQTT Explorer, Even when renaming the device, From time to time you will see the old name (DeviceID_x) appearing there.

**Comment by robertsLando** [comment]
@ezeitoun It's correct, you should rediscover it once you change it's name/location as it's name/location are part of it's topic.

For the old entities, you should use mqtt explorer to delete the retained topics if there are

**Comment by ezeitoun** [comment]
Thanks, Rediscover does partial help,
When its a simple switch, Everything is updated correctly,
When its a "Smart" Switch (which include sensors), The Switch entities of the device will be update,
The sensors wont be updated (will either remind with old name, or when deleted and rediscovered wont appear at all)

![Image 116](https://user-images.githubusercontent.com/57022870/91859395-67156300-ec38-11ea-8673-170fc1941a3d.jpg)

**Comment by robertsLando** [comment]
You have to press on rediscover node, have you pressed that?

**Comment by ezeitoun** [comment]
Yup, Rediscover Node bring only the Switch Entities, Not the Sensor ones.
On MQTT Explorer i do see the sensors are being created, So we are good on that part.
MQTT Explorer:
![Image 119](https://user-images.githubusercontent.com/57022870/91861004-51a13880-ec3a-11ea-99d3-804dfc5d810c.jpg)

Not sure if its an issue/bug or settings, Just in case..., My Settings are:
![Image 121](https://user-images.githubusercontent.com/57022870/91861447-ce341700-ec3a-11ea-8e24-76745c0fd569.jpg)


Thanks for the Help, Appreciate it!

**Comment by robertsLando** [comment]
@ezeitoun Could you please try to restart the application? 

Usually my suggestion is to first address all devices (give them the name/location and modify the discovery if needed) than store the device configuration of each node, when you change the name/location of a device usually by doing rediscover node it fix the new topics but if not an application restart should do it. Let me know and thanks for sponsoring my work :heart:

**Comment by ezeitoun** [comment]
Nothing like a good Restart! 8-)
(Not sure why the sensors are unknown as for status, but i dont think its related to you)
![Image 123](https://user-images.githubusercontent.com/57022870/91864945-dbeb9b80-ec3e-11ea-8a1c-c22b84568dc6.jpg)

Good Product + Great Support = Sponsoring, You Deserve it!

**Comment by robertsLando** [comment]
> Not sure why the sensors are unknown as for status 

Maybe they are the old ones?

**Comment by ezeitoun** [comment]
MQTT Retain did the job...
(well at least as soon as i modified i see the values)
 
Is there a document regarding all the settings to make sure i have the optimized configuration ?

**Comment by robertsLando** [comment]
@ezeitoun Here you find everything needed: https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta
