### ISSUE TITLE
First LZW30-SN Device works, Any additional same device wont.

### ISSUE THREAD

**Issue by ezeitoun** [OpenZWave/Zwave2Mqtt#704]
Hi,
Added LZW30-SN and tested, Works Perfect (Inclusion done in Security Mode),
The device recognized and works as expected (and secured value is true).

Adding any other LZW30-SN, in the same way, will result in "secured' value as false.
the device will react to on/off via the user setting or HA but none of the sensors will work in HA,
And when trying to use Debug on the control panel, no debug info is printed.
(if I will leave the device on debugging, and remove it, It will print debug info).

(All 3 devices are the same regarding the different versions fields)

![Untitled1](https://user-images.githubusercontent.com/57022870/92296029-3cf4c700-eefe-11ea-925c-2b757d7acf43.png)

**Comment by ezeitoun** [comment]
Upgraded the Firmware for on of the LZW30-SN, And now notifications works,
But still this doesnt explain why on the first device everything works great (with the old firmware)
and on the additional devices its not.

(Have you ever thought about OTA Upgrades via Zwave2MQTT? (Its simply a nightmare to upgrade with external tools))

**Comment by robertsLando** [comment]
Hi @ezeitoun ! Unfortunately based on my Zwave experience I can tell you that explain why a device is/isn't working is very hard, there are many things to check like the connectivity, device firmware, device configuration in OZW, compatibility issues, devices that doesn't respect zwave standards... 

The only things you can do to fix things is to always use latest device fw and latest devices db from OZW (check docker docs to see how to auto update ozw device db). And for sure always use latest z2m version :) 

If you also consider Hass, there there could be other issues as hass could break some device discovery in his updates. 

However about OTA updates, I have no Idea if they can be done from OZW, is there a command class for that? 

If so I would be glad to add such feature.

**Comment by ezeitoun** [comment]
Manage to reproduce it every time I remove all the 3 devices,
First device is recognized as Secure (even if i hit Cancel) and all other devices have an issue with notifications.
The only way to bypass this, Was to add the devices manually (outside of Zwave2Mqtt) to the stick
and continue to configure them within (all 3 devices are not secured with this is done).

Since the HA Add-On uses an older version of zwave2mqtt (3.2.2), we can drop it, I will try to request
an adaptation of the latest version to verify this again.

Thanks Again for the Help!

**Comment by ezeitoun** [comment]
Remove the ZWave2MQTT (3.2.2) Add-On from Hassio ,
Deployed a ZWave2MQTT 4.0.3 container, Issue is not reproducing.
Can be closed
