### ISSUE TITLE
Monoprice Door sensor open close attribute.

### ISSUE THREAD

**Issue by silfa718** [OpenZWave/Zwave2Mqtt#71]
Using Home Assistant discovery, the monoprice door sensor attribute for open close is not monitored. 

This is what needs to monitored:

{
    "value_id": "16-113-1-9",
    "node_id": 16,
    "class_id": 113,
    "type": "byte",
    "genre": "user",
    "instance": 1,
    "index": 9,
    "label": "Access Control",
    "units": "",
    "help": "",
    "read_only": true,
    "write_only": false,
    "min": 0,
    "max": 255,
    "is_polled": false,
    "value": 23
}

With value 23 for closed and 22 for open.

How do I add this so it can be discovered in Homeassistant.

**Comment by silfa718** [comment]
Figured it out:

```
{
  "type": "sensor",
  "object_id": "open_close",
  "discovery_payload": {
    "icon": "mdi:door-closed",
    "value_template": "{{ value_json.value }}",
    "state_topic": "homeassistant/Pantry/Door_Sensor/113/1/9",
    "json_attributes_topic": "homeassistant/Pantry/Door_Sensor/113/1/9",
    "device": {
      "identifiers": [
        "zwave2mqtt_Pantry-Door_Sensor"
      ],
      "manufacturer": "",
      "model": "",
      "name": "",
      "sw_version": "1.05"
    },
    "name": "Pantry-Door_Sensor_open_close",
    "unique_id": "zwave2mqtt_Pantry-Door_Sensor_16-113-1-9"
  },
  "discoveryTopic": "sensor/Pantry-Door_Sensor/open_close/config",
  "values": [
    "113-1-9"
  ],
  "persistent": true,
  "id": "sensor_open_close"
}
```

**Comment by robertsLando** [comment]
Will add this to auto discovered devices in next release. Thanks! 

Daniel

**Comment by silfa718** [comment]
Glad to help!

Is there a way to have the sensor return "Open" and "Closed". 
Right now is returns 22 or 23 and I have a template sensor that converts to "Open" and "Closed"

**Comment by robertsLando** [comment]
The only way is to manually edit the value template from hass devices table @silfa718

**Comment by robertsLando** [comment]
@silfa718 Could you tell me your device id please? I mean monoprice door manufacturer id product type etc..

**Comment by silfa718** [comment]
How do I find that? Do you need that link to the product page?

**Comment by robertsLando** [comment]
Add a value of monoprice door in gateway values table than export the json and look for that value entry it should have a property device_id

**Comment by silfa718** [comment]
When I go to the gatway to add "New Value", in the "New Items" window, my door sensor is not listed in the device drop down menu.

**Comment by 917huB** [comment]
`Device ID (114-1-3)`

<img width="824" alt="device-id" src="https://user-images.githubusercontent.com/22522964/63220336-c7268d80-c139-11e9-8226-aa114f187bfd.png">

**Comment by silfa718** [comment]
How did you get the device id?

**Comment by 917huB** [comment]
Go to ZWave2MQTT control panel > settings. 
Under Hass Discovery click 'new value' text
Device field = selected the incorrect device
Value = Device ID
topic = "monoprice door"
Save.
You should see the device list populate as per my screen shot above. 

I have some other oddities in my list, for example
![2019-08-19 22-45-58](https://user-images.githubusercontent.com/22522964/63320626-34b9f180-c2d3-11e9-83aa-4e817b7f9204.jpg)

**Comment by silfa718** [comment]
@917huB  thanks for the instructions.

Here is my list:
![Screenshot 2019-08-20 at 6 28 26 AM](https://user-images.githubusercontent.com/24217411/63340145-630bf100-c314-11e9-82ca-ff8a1b87ee66.png)

Node 16 is my door sensor, but doesn't have a product name, which doesn't show up under the device field drop down menu.
