### ISSUE TITLE
Can't upgrade past 3.4.0 > Lose all devices in HASS

### ISSUE THREAD

**Issue by Maes152** [OpenZWave/Zwave2Mqtt#716]
Hi,

I use zwave2mqtt (3.4.0) in docker and have enabled discovery in zwave2mqtt. 
HASS (0.114.4) & Zwave2mqtt have been working happily together for the better part of a year now. 

Unfortunately ever since the release of 4.0.0 and every subsequent release I cannot upgrade zwave2mqtt without losing every single device in home assistant (they are all marked as unavailable). 

Now I read something about birth/will topics being changed in 4.0.0 ([Click](https://github.com/OpenZWave/Zwave2Mqtt/pull/639) and [Click](https://github.com/OpenZWave/Zwave2Mqtt/issues/638))
Is this the reason everything breaks? How do I fix it? I can't find any instructions anywhere that guide me through this.

**Comment by robertsLando** [comment]
You should be able to change birth/will topics from hass mqtt configuration: https://github.com/OpenZWave/Zwave2Mqtt#robot-home-assistant-integration-beta

**Comment by Maes152** [comment]
Yep, that completely solved my problem. Thanks! 
Closing the issue...
