### ISSUE TITLE
Understanding "DELETE" Device from HASS Table[question] 

### ISSUE THREAD

**Issue by jamesarbrown** [OpenZWave/Zwave2Mqtt#717]
Hi,

I can not for the life of me delete a device, as on every reboot it reappears.

What is the correct process to delete a device from here that is honoured over a reboot?

![image](https://user-images.githubusercontent.com/891438/92642501-31c3e180-f2d8-11ea-92c3-f96ec5f7273f.png)

Thankyou

**Comment by robertsLando** [comment]
You have to make that device persistent and edit the hass device JSON (the textarea on the right side) and set a discovery payload of '{}' so the discovery of that device will fail
