### ISSUE TITLE
[bug] Ignored call to 'confirm()'

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#72]
**Version**

Build/Run method
- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.3
Openzwave Version: 1.4.1

**Describe the bug**
Clicking "Delete" on an HomeAssistant integration item does not work. 
An error is logged to the devtools console:
```
Ignored call to 'confirm()'. The document is sandboxed, and the 'allow-modals' keyword is not set.
deleteDevice @ ControlPanel.vue:827
click @ ControlPanel.vue?8440:1
e @ vue.esm.js:2141
Mi.e._withTask.r._withTask @ vue.esm.js:1926
```

**To Reproduce**
1. Go to a Node
2. Scroll to Home Assistant - Devices
3. Click on Delete
4. See error in console

**Expected behavior**
The item to be deleted from Home Assistant - Devices

**Comment by robertsLando** [comment]
Os?

Daniel

**Comment by robertsLando** [comment]
If you are running the app inside an ifrsme and you are using chromium web browser this is the fix: http://techneerajnandwana.blogspot.com/2015/10/error-ignored-call-to-alert-document-is.html?m=1

Daniel

**Comment by syphernl** [comment]
Ah yeah, that makes sense! I am using it from inside Home Assistant, but there is no way of adding that particular line to the iframes it generates. 

That explains why I was baffled yesterday that it didn't work anymore even though it worked fine. Previously I used the app directly in my browser rather than through the iframe feature of Home Assistant.

Guess that's something for them to fix right?

**Comment by robertsLando** [comment]
Yes should open an issue on hass addon! 

Daniel
