### ISSUE TITLE
[bug] Accented characters are not allowed for names and locations

### ISSUE THREAD

**Issue by besynnerlig** [OpenZWave/Zwave2Mqtt#720]
**robertslando/zwave2mqtt:4.0.3**

**Describe the bug**
Previously accented characters were allowed to name devices and places in the control panel GUI. Now, there's a message telling me "Only a-zA-Z0-9_- chars are allowed". 

Example: "Tvättstugan" mening "Laundry Room"

I believe åäöüéÅÄÖÜÉ are allowed in MQTT messages node names so I see no reason to prevent entering them in the GUI.

**Comment by robertsLando** [comment]
Just submitted a fix for this
