### ISSUE TITLE
How do I get zwave2mqtt to start at boot

### ISSUE THREAD

**Issue by SamuelCarson** [OpenZWave/Zwave2Mqtt#721]
I have zwave2mqtt running on a raspberry pi 3 B+. It was installed by compiling:

git clone https://github.com/OpenZWave/Zwave2Mqtt
cd Zwave2Mqtt
npm install
npm run build
npm start
Runs ok.
Tried pm2. It restarts z2m apparently from the wrong directory. At this point I'm stuck

**Comment by Korvenwin** [comment]
I'm running a packaged version on ubuntu server sucessfully, but I'm on the same problem. I'm trying to convert exec in a system service without success. Any sugestion?

**Comment by SamuelCarson** [comment]
You can try this. I could not get pm2 to run as a service.

Assuming that zwave2mqtt in installed in /home/pi/Zwave2Mqtt

cd /tmp
nano zwave2mqtt.service

    Description=Z-Wave to MQTT Gateway
    Documentation=https://github.com/OpenZWave/Zwave2Mqtt
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/home/pi/Zwave2Mqtt
    ExecStart=npm start
    ExecStop=npm stop 
    Restart=always

    [Install]
    WantedBy=multi-user.target

^xY(enter)

sudo cp /tmp/zwave2mqtt.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start zwave2mqtt
sudo systemctl status zwave2mqtt

If zwave2mqtt is running ok

sudo systemctl enable zwave2mqtt

will allow the service to start at boot

Note that sudo systemctl stop zwave2mqtt will stop zwave2mqtt but it's not pretty.

**Comment by robertsLando** [comment]
pm2 is the right tool for this. But I think you are setting a wrong cwd when you start the process. I suggest you to use an ecosystem.js file https://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by SamuelCarson** [comment]
Updated instructions to use pm2 running as a service.

Assuming that zwave2mqtt in installed in /home/pi/Zwave2Mqtt

Be sure zwave2mqtt is stopped both as service and as npm start.

cd /home/pi/Zwave2Mqtt
pm2 --name zwave2mqtt start npm -- start
pm2 ecosystem
pm2 save
pm2 startup systemd
copy, paste, and execute the resulting command

reboot and check everything starts as expected

**Comment by Korvenwin** [comment]
Any option to autostart a pkg version?

**Comment by robertsLando** [comment]
@Korvenwin The same, just use the binary name

**Comment by Korvenwin** [comment]
> 
> 
> Updated instructions to use pm2 running as a service.
> 
> Assuming that zwave2mqtt in installed in /home/pi/Zwave2Mqtt
> 
> Be sure zwave2mqtt is stopped both as service and as npm start.
> 
> cd /home/pi/Zwave2Mqtt
> pm2 --name zwave2mqtt start npm -- start
> pm2 ecosystem
> pm2 delete zwave2mqtt
> pm2 kill
> pm2 start ecosystem.config.js
> pm2 save
> pm2 startup systemd
> copy, paste, and execute the resulting command
> 
> reboot and check everything starts as expected

I'm trying pm2 and after 'pm2 start ecosystem.config.js' I get this errors:

[PM2] PM2 Successfully daemonized
[PM2][WARN] Applications index, service-worker not running, starting...
[PM2][ERROR] Error: Script not found: /home/janguita/Zwave2Mqtt/index.js
[PM2][ERROR] Error: Script not found: /home/janguita/Zwave2Mqtt/service-worker

I'm totally newbie to nodejs and much more to pm2.

**Comment by robertsLando** [comment]
@Korvenwin Could you paste here the content of you ecosystem.conig.js?

**Comment by SamuelCarson** [comment]
I can’t, I have gone to Docker. It is probably different for each system. It is generated by the ‘pm2 ecosystem’ command while the pm2 task is running.

**Comment by SamuelCarson** [comment]
I think this is normal.

**Comment by Korvenwin** [comment]
Finally, it is working smooth as a service. The problem was the enviroment variable of libraries. After add it to the .service file, it works flawlessly. This is the my final zwave2mqtt.service:

[Unit]
Description=zwave2mqtt
After=network.target

[Service]
Environment=LD_LIBRARY_PATH=/usr/local/lib64
ExecStart=/usr/bin/npm start
ExecStop=/usr/bin/npm stop
WorkingDirectory=/opt/zwave2mqtt
StandardOutput=inherit
StandardError=inherit
Restart=always
User=root

[Install]
WantedBy=multi-user.target
