### ISSUE TITLE
Multiple unique values on same mqtt topic [bug]

### ISSUE THREAD

**Issue by ve6rah** [OpenZWave/Zwave2Mqtt#729]
Version 3.2.2

Zwave2Mqtt version: 3.2.2
Openzwave Version: 1.6.974
**Describe the bug**
Using a CT-32 Zwave thermostat which publishes termperature on 49-1-1 and humidity on 49-1-5. These 2 unique values however are being sent to the same MQTT topic (thermostat/sensor_multilevel/instance_1_unknown)

**Expected behavior**
different unique values from different sources should never default to the same mqtt topic. (in this case temperature and humidity should be on different topics)

**Additional context**
in the "user" section of the control panel in zwave2mqtt you can see the 2 values on separate lines, temp shows 49-1-1 and humidity shows 49-1-5 (though both call themselves "instance 1: unknown") but unfortunately  on the MQTT server they use the same topic, overwriting each other with whichever one is more recent.

The "bug" goes beyond this one device, different unique values from different sources should never default to the same mqtt topic.

**Comment by robertsLando** [comment]
@ve6rah If you check docs you will see that the 'named topics' mode is not good to use, use gateway in valueId topic mode or manual
