### ISSUE TITLE
[feat] Show device name+location in manual config

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#73]
**Is your feature request related to a problem? Please describe.**
For some reason my device ID's in Home Assistant keep on changing. As recommended in previous ticket for this (and other) issues it would be better for my setup to switch to manual mode.

However, setting this up is rather difficult since I have multiple identical devices. Based on the "New Item" popup I cannot determine which sensor is which because it shows the product name which is not a unique value.

**Describe the solution you'd like**
It would be nice if there could be an extra line underneath the productname with the device name / location and device ID so that the appropriate one can be selected.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by robertsLando** [comment]
When adding values to the gateway values table it shows just one device for each type. This is to make it easier and faster to setup your network as If you have lot different kind of devices (light, light dimmers for example) you just need to add the values you want to bridge to mqtt and it will bridge those values for all the devices of that type.

**Comment by syphernl** [comment]
Ah that makes sense. 

However, what do you have to fill in for topic? I assumed this was the topic for the particular device (e.g. `device/livingroom_switch`, `device/bathroom_sensor`), but if it is for all types of that particular device what should you write there?

**Comment by robertsLando** [comment]
There you write the “value topic” it means that before that you will see in order:

<mqttPrefix>/<?deviceLocation>/<deviceTopic>/<valueTopic>

Device location will be added just if it is present

Daniel
