### ISSUE TITLE
[bug] Eurotronic Spirit - Manufacturer Specific mode break in MQTT

### ISSUE THREAD

**Issue by Micka41** [OpenZWave/Zwave2Mqtt#730]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.3
Openzwave Version: 1.6+ds-4

**Describe the bug**
For the Eurotronic Spirit module, the Mode parameter (64-1-0) is not sent in MQTT when it is in "Manufacturer Specific" but works in the other modes ("Off", "Heat", "Full Power" ...).
In MQTT reception, it is not possible to change the parameter to "Manufacturer Specific" while "Off", "Heat", "Full Power", ... are working.

**To Reproduce**
Change Mode to "Manufacturer Specific" of Eurotronic Spirit module in Zwave2Mqtt and see into MQTT Explorer the parameter (64-1-0) 

**Expected behavior**
See "Manufacturer Specific" into MQTT Explorer 

**Additional context**
Nothing

**Comment by robertsLando** [comment]
It's a device issue, not something related to z2m. I suggest to ask to device manufacturer or open this issue on OZW repo

**Comment by Micka41** [comment]
Ok, I modified the file cpp/src/command_classes/ThermostatMode.cpp in OpenZwave so that it works (suppression of the test bool validMode = false ...)

**Comment by robertsLando** [comment]
@Micka41 Glad you fixed it! I suggest to send a pr for that to OZW repo :)
