### ISSUE TITLE
[bug] Manual Config > New Item doesn't show all devices

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#74]
**Version**

Build/Run method
- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.1
Openzwave Version: 1.4.1

**Describe the bug**
It looks like the manual configuration ("New Value" popup) doesn't show all devices, it only shows one occurrence of each product (and not even, because I am missing some devices there as well, but they are "sleeping")

**To Reproduce**
1. Go to 'Settings > Gateway'
2. Click on 'New Value'
3. See missing devices / only unique product names instead of all devices.

**Expected behavior**
It showing all devices, not just one per product name.

**Additional context**
I have 21 devices in my network right now but only 6 show up in the list.

**Comment by robertsLando** [comment]
I mention the other answer, this should be a feature for users, not a bug

> When adding values to the gateway values table it shows just one device for each type. This is to make it easier and faster to setup your network as If you have lot different kind of devices (light, light dimmers for example) you just need to add the values you want to bridge to mqtt (for a light it will always be a switch for exmple) and it will bridge those values for all the devices of that type.
