### ISSUE TITLE
[question] 

### ISSUE THREAD

**Issue by sirsiegfrieds** [OpenZWave/Zwave2Mqtt#740]
Hey there,

i'm a new user of zwave2mqtt and i would had a Secure SRT-321 

https://static.webshopapp.com/shops/253891/files/178521659/manual-secure-srt321.pdf

And i do not understand how to make it work in a zwave2mqtt.yaml

I have those things for a fibaro:

  - platform: "mqtt"
    name: Zwave2mqtt_ZRL01 (Chauffage salon)
    state_topic: "zwave2mqtt/ZRL01/37/1/0"
    #state_off: "false"
    #state_on: "true"
    #availability_topic: "zwave2mqtt/ZRL01/status"
    #payload_available: "true"
    #payload_not_available: "false"
    command_topic: "zwave2mqtt/ZRL01/37/1/0/set"
    qos: 1
    payload_off: "false"
    payload_on: "true"
    #value_template: "{{ value_json.state_l1 }}"
    optimistic: false
    retain: true

But how to communicate with an srt to have information like

![image](https://user-images.githubusercontent.com/68698942/94049960-e7f9f180-fdd5-11ea-82af-020685674c19.png)

Heating state
Temperature
And set temperature to change the value in home assistant and put heater on ...

**Comment by robertsLando** [comment]
> And i do not understand how to make it work in a zwave2mqtt.yaml

There is no yml configuration here :confused: 
@sirsiegfrieds Could you better explain your problem? What values are missing?  What is not working?

**Comment by sirsiegfrieds** [comment]
Hey there,

I'm using z2mqtt in home assistant.
I want to have a dashboard for this thermostat.

There is several topic in this object, but i don't know the right configuration in a yaml
When i set a Temperature, i want to send the topic and recieve it in home assistant
Same for heating statut
etc etc.

But i'm beginner on that setting, and i could not find example on web.

It's for drive my heaters at home using node-red and some automations ...

Cordialement,

Mr Segura
________________________________
De : Daniel Lando <notifications@github.com>
Envoyé : jeudi 24 septembre 2020 06:17
À : OpenZWave/Zwave2Mqtt <Zwave2Mqtt@noreply.github.com>
Cc : Sir_SiegfriedS <sir_siegfrieds@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [OpenZWave/Zwave2Mqtt] [question] (#740)


And i do not understand how to make it work in a zwave2mqtt.yaml

There is no yml configuration here 😕
@sirsiegfrieds<https://github.com/sirsiegfrieds> Could you better explain your problem? What values are missing? What is not working?

**Comment by robertsLando** [comment]
Take a look to custom devices in readme. Climate devices need to be manually configured

**Comment by sirsiegfrieds** [comment]
Ok i will try to find it
________________________________
De : Daniel Lando <notifications@github.com>
Envoyé : vendredi 25 septembre 2020 08:39
À : OpenZWave/Zwave2Mqtt <Zwave2Mqtt@noreply.github.com>
Cc : Sir_SiegfriedS <sir_siegfrieds@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [OpenZWave/Zwave2Mqtt] [question] (#740)


Take a look to custom devices in readme. Climate devices need to be manually configured

**Comment by sirsiegfrieds** [comment]
Ok i think you are talking about this :
{ // Heatit Thermostat TF 021 (ThermoFloor AS)
    "type": "climate",
    "object_id": "thermostat",
    "values": ["64-1-0", "49-1-1", "67-1-1", "67-1-2"],
    "mode_map": {"off": "Off", "heat": "Heat (Default)", "cool": "Cool"},
    "setpoint_topic": { "Heat (Default)": "67-1-1", "Cool": "67-1-2" },
    "default_setpoint": "67-1-1",
    "discovery_payload": {
        "min_temp": 15,
        "max_temp": 30,
        "modes": ["off", "heat", "cool"],
        "mode_state_topic": "64-1-0",
        "mode_command_topic": true,
        "current_temperature_topic": "49-1-1",
        "current_temperature_template": "{{ value_json.value }}",
        "temperature_state_template": "{{ value_json.value }}",
        "temperature_command_topic": true
    }
}

I'm not enough good for use this in a yaml.
I want to have a visual in a lovelace card
and have the possibilité off using heating command for change statut of heaters :X

**Comment by robertsLando** [comment]
This is just to enable the discovery of your climate device, once it is discovered you can do what you want with it in hass

**Comment by sirsiegfrieds** [comment]
I have change of climate. It doesn't work like i want him to work :). So i have changed him :).
