### ISSUE TITLE
Updating Notification Type

### ISSUE THREAD

**Issue by mew0717** [OpenZWave/Zwave2Mqtt#747]
This is driving me mad..... I have a sensitive strips Z-wave door sensor.  It works great.  There are 3 notification types:
1. Binary Sensor Report
2. Notification Report
3. Basic Report.

For some reason, the sensor likes to switch which notification type it likes to use.  For a couple days, it used a notification report, so i built my Home assistant Yaml appropriately.  Then its switched (on it's own) to a binary sensor report. This was actually OK, because i was using a binary sensor and templates to make this work with the amazon echo.  Now it's back to a notification report type.

When I make the change in the UI and click the paper airplane button i see a message that says "Successfully call api setValue" but nothing appears to actually change.

Any idea what's going on there?

**Comment by robertsLando** [comment]
@mew0717 seems more like a device error then a z2m one. Anyway you can try to check if there is a device firmware update, or create automations for all type of reports so even if the notification changes it works anyway 

About the `Successfully call api setValue` that means you have call a setValue, you should then receive a `Value updated` notification that informs you that the value has also give a change feedback, if it doens't it means it hasn't change
