### ISSUE TITLE
[feat] Strongly default or hardcode "homeassistant" as discovery prefix

### ISSUE THREAD

**Issue by wfscot** [OpenZWave/Zwave2Mqtt#749]
I recently set up zwave2mqtt as my first mqtt integration for HA using the discovery features.  As I really didn't know much, I randomly selected "discovery" as the discovery prefix.  I'm now looking to integrate other stuff via mqtt and am finding that "homeassistant" is essentially the convention (for example, ring-mqtt).  This was supported via a brief discussion on Discord.  I'm now looking at changing  zwave2mqtt to use "homeassistant" as well.

IMO, it would be good to either warn users about using something other than "homeassistant" for the discovery prefix or disallow changing this altogether.

One alternative that I haven't explored is having multiple mqtt integrations running on HA, each with their own discovery prefix. This really seems unnecessarily burdensome, though.

Thanks!

**Comment by robertsLando** [comment]
If you check the readme on the 
Home Assistant integration (BETA) 


You will find this

---

Daniel

**Comment by wfscot** [comment]
Sorry if I missed that. I saw the note on homeassistant/status being the default birth/will topic, but I didn't see anything on the discovery prefix itself.  You're absolutely welcome to close this if it isn't worth discussing further.
