### ISSUE TITLE
[bug] Node keeps changing from name in Home Assistant

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#75]
**Version**

Build/Run method
- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2
Openzwave Version: 1.4.1

**Describe the bug**
Yesterday I added a [Sensative Strips](https://sensative.com/strips/guard/) to my network. Every time I reboot Z2M or Home Assistant my ID's keep on changing.

Sometimes the binary sensor is named `binary_sensor.woonkamer_magneetcontact_contact` based on the location and name of the device and other times it's named `binary_sensor.nodeid_50_contact`. 

I assume that there is a moment during the Z2M boot that it doesn't have the location and name, and bases its name on the ID instead. 

For some reason this only seems to happen with this particular device (last added), other devices (both battery-powered and mains powered) remain with the same name.

**To Reproduce**
I don't know how to reproduce this without this particular device.

**Expected behavior**
The ID of the device in Home Assistant should remain the same, if it keeps on changing its impossible to integrate it properly.

**Additional context**
I found this in the log of Home Assistant, it might explain what's happening:

```
2019-07-31 20:16:40 ERROR (MainThread) [homeassistant.components.mqtt] Exception in discovery_callback when dispatching 'mqtt_discovery_updated_('binary_sensor', 'nodeID_50 contact')': ({'payload_on': True, 'payload_off': False, 'value_template': '{{ value_json.value }}', 'device_class': 'door', 'state_topic': 'zwave/50/48/1/0', 'json_attributes_topic': 'zwave/50/48/1/0', 'device': {'identifiers': ['zwave2mqtt_nodeID_50'], 'manufacturer': 'Sensative AB', 'model': '0x0003', 'name': 'Strips-MAZW', 'sw_version': 'Unknown'}, 'name': 'nodeID_50_contact', 'unique_id': 'zwave2mqtt_nodeID_50_50-48-1-0', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/srv/hass/lib/python3.7/site-packages/homeassistant/components/mqtt/__init__.py", line 1046, in discovery_callback
    payload.pop(ATTR_DISCOVERY_HASH)
KeyError: 'discovery_hash'
```

**Comment by robertsLando** [comment]
It should not change as the node name is loaded on application init. I can't reproduce this bug in my instance

**Comment by syphernl** [comment]
For some reason it only happens with this particular device. It seems some of the sub-devices are using the _50 and others using the friendly name. I have adjusted the JSON to use the friendly name except now no data of the contact or battery sensor is being picked up by HASS (even though Z2M does notice the change).

**Comment by robertsLando** [comment]
@syphernl Did you fixed that? was it related to file permissions of the other issue?

**Comment by syphernl** [comment]
@robertsLando Seems to be working fine now for the past days. I did switch to manual mode but prior to that everything was working good. It appears to be related to the file permissions. If Z2M cannot write to the xml when a new device is being added this results in this type of odd behavior.

**Comment by robertsLando** [comment]
@syphernl Ok I will check this. Thanks :)
