### ISSUE TITLE
[bug] thermostat /set (e.g., /zwave2mqtt/8/67/1/1/set) ignores some values

### ISSUE THREAD

**Issue by pdbogen** [OpenZWave/Zwave2Mqtt#755]
**Version** 4.0.4

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.4
Openzwave Version: 1.6.1280

**Describe the bug**
An incoming value via mqtt is ignored if it's a decimal with a lot of places.

**To Reproduce**

```
$ docker exec -it mosquitto mosquitto_pub -t zwave2mqtt/8/67/1/1/set -m 28.4444
Oct 05 10:13:22 nuc docker[29982]: 2020-10-05T17:13:22.926Z z2m:Mqtt Message received on zwave2mqtt/8/67/1/1/set

$ docker exec -it mosquitto mosquitto_pub -t zwave2mqtt/8/67/1/1/set -m 28.444
Oct 05 10:13:32 nuc docker[29982]: 2020-10-05T17:13:32.910Z z2m:Mqtt Message received on zwave2mqtt/8/67/1/1/set
Oct 05 10:13:34 nuc docker[29982]: 2020-10-05T17:13:34.581Z z2m:Zwave zwave node 8: changed: 67-1-1:Heating 1:28 -> 28
```

**Expected behavior**
Any value that node can parse as a number should be sent to ZWave.

**Comment by pdbogen** [comment]
further assessment, I don't think the issue is on the mqtt side, I think it's on the zwave side. Here's a comparison of setting `28.4444` vs `28.444` directly on the object via z2m UI:

```
Oct 05 10:17:14 nuc docker[29982]: 2020-10-05T17:17:14.556Z z2m:App Zwave api call: setValue [ 8, 67, 1, 1, '28.4444' ]
Oct 05 10:17:14 nuc docker[29982]: 2020-10-05T17:17:14.564Z z2m:Zwave Success zwave api call setValue

Oct 05 10:17:25 nuc docker[29982]: 2020-10-05T17:17:25.705Z z2m:App Zwave api call: setValue [ 8, 67, 1, 1, '28.444' ]
Oct 05 10:17:25 nuc docker[29982]: 2020-10-05T17:17:25.708Z z2m:Zwave Success zwave api call setValue
Oct 05 10:17:27 nuc docker[29982]: 2020-10-05T17:17:27.399Z z2m:Zwave zwave node 8: changed: 67-1-1:Heating 1:28 -> 28
```

**Comment by robertsLando** [comment]
@pdbogen I think the device doesn't allow that number, even if you set it from the ui then it writes 28.

**Comment by pdbogen** [comment]
Yeah, the problem is that `28.4444` doesn't trigger an actual call to zwave stack at all but `28.444` _does_. I'd be happy if they both set 28.

HomeAssistant is sending `28.444444444444443` as a result of Fahrenheit to Celsius conversion.

**Comment by pdbogen** [comment]
or... maybe the zwave stack itself is treating this differently. :thinking: it could be a bug in openzwave itself, perhaps?

**Comment by robertsLando** [comment]
@pdbogen From what I can see I don't see any error here, what you could try to do is create a `parse receive` function to remove some decimals: https://github.com/OpenZWave/Zwave2Mqtt#gateway-values-table

Something like:
```js
return Number(value.toFixed(2));
```

**Comment by robertsLando** [comment]
@pdbogen Did you try with my suggestion?

**Comment by pdbogen** [comment]
I worked around it in my case by changing automations in question to publish mqtt directly with integer values instead of making HA climate changes.

I still intend to dig around and find out why the behavior differs for different numbers of decimal places, but I'm thinking maybe the issue is somewhere with ozw itself, or maybe even it's device-specific. I'll update this issue with any findings..

**Comment by robertsLando** [comment]
@pdbogen Ok closing this for now, feel free to comment if there are updates
