### ISSUE TITLE
[bug] Support for /dev/serial/by-path/

### ISSUE THREAD

**Issue by hmorkemo** [OpenZWave/Zwave2Mqtt#76]
**Version**

Build/Run method
- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
/dev/serial/by-path isn't supported by zwave. This is a problem since the ttyACMx port number may change after a reboot, and (at least for aeotec z-sticks), /dev/serial/by-id isn't able to separate between two sticks in the same computer.

**To Reproduce**
1. Assign a port to zwave2mqtt
2. Reboot
Sometimes it gets the same port number, sometimes it doesn't.

**Expected behavior**

**Additional context**

**Comment by sjorge** [comment]
Have you tried just pasting in the full path to the node in /dev/serial/by-path/... ?
On SmartOS the library used does not discover the ports so I have to manual specify the full path, it works fine afterwards.

**Comment by robertsLando** [comment]
@hmorkemo Did @sjorge suggeestion fixed your problem?

**Comment by hmorkemo** [comment]
I have tried pating the full by-path with no good effect. Someone in the hassio community says that the problem is docker-relateed, that docker cannot handle device names with : in them.

**Comment by plasticrake** [comment]
@hmorkemo I'm using docker like this and it works great:

from my `docker-compose.yml` file: 
```yml
devices:
    - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_612017D9-if00-port0:/dev/ttyACM0
```

**Comment by robertsLando** [comment]
Thanks @plasticrake . @hmorkemo Does the fix suggested works for you? 
Anyway this is not a problem related to my lib but something on docker side so I'm going to close this.
