### ISSUE TITLE
[bug] Unable to set icon for HASS integration

### ISSUE THREAD

**Issue by syphernl** [OpenZWave/Zwave2Mqtt#77]
**Version**

Build/Run method
- [ ] Docker
- [X] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2
Openzwave Version: 1.4.1

**Describe the bug**
If I set the icon to `mdi:flash` HASS is showing an error in the logs:
```
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['icon']
```

If I remove the `mdi:` prefix it shows something different:
```
voluptuous.error.MultipleInvalid: Icons should be specifed on the form "prefix:name" for dictionary value @ data['icon']
```

With either it won't create the items in HASS, they will be created once the icon field is empty.

**To Reproduce**
1. Set to manual mode
2. Configure a value with an icon set, `mdi:flash` for instance.
3. See that HASS is throwing an error.

**Expected behavior**
The icon to work, the item to be created properly.

**Additional context**

**Comment by robertsLando** [comment]
Could you tell me the valueid of the value you are tring to assign the icon?

**Comment by robertsLando** [comment]
If it is a binary sensor it's because [binarry sensors](https://www.home-assistant.io/components/binary_sensor.mqtt/) cannot have an icon property, you can just set a `device_class` to them to change the icon.

**Comment by syphernl** [comment]
I didn't know about the binary sensors. I initially configured an icon for everything. It included sensors but also for `switch` and `power`. None got an icon. The error did perhaps originate from setting it on a binary sensor?

**Comment by robertsLando** [comment]
Yes, fixed in last commit you see there. Can close this bug now

Daniel

**Comment by syphernl** [comment]
Awesome!

**Comment by robertsLando** [comment]
With “fixed” I mean that I have removed the possibility to set an icon for bisnary sensors, you should opt for a different device class that fits your needs based on the binary sensor. Check for hass binary sensor device classes for more info. 

Daniel
