### ISSUE TITLE
[bug] Lock "Alarm Level/Type additional sensors" are no more presented

### ISSUE THREAD

**Issue by alex-savin** [OpenZWave/Zwave2Mqtt#773]
Build/Run method
- [*] Docker

Zwave2Mqtt version: 4.0.4
Openzwave Version: 1.6.1280

**Describe the bug**
No more additional sensor for lock device (alarm_level/alarm_type)

**Expected behavior**
Based on these sensor that was possible to figure out what lock code had been used to unlock a lock and the state of a lock

**Comment by robertsLando** [comment]
@alex-savin Could you try to send a refresh node info command against the node? Do you have automatic zwave db updates on?

**Comment by alex-savin** [comment]
@robertsLando it doesn't help

**Comment by robertsLando** [comment]
Could you try to revert to a previous z2m version? I would like to know if something is broken, anyway if a value is missing it's more likely a problem on ozw side

**Comment by robertsLando** [comment]
@alex-savin Also firstly try to use latest 4.0.5 version that also has latest ozw stable version

**Comment by smitt04** [comment]
I am also experiencing this, This is the first time i have tried to use the library and it is missing those sensors which I can get using a different setup.

**Comment by robertsLando** [comment]
@smitt04 Can you try with: https://github.com/zwave-js/zwavejs2mqtt#why-zwavejs

**Comment by smitt04** [comment]
@robertsLando I tried the zwave-js and it seems like it can not communicate with the device for nodeinfo. I get these in the logs

```
[Node 008] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
```

I have tried excluding and re-including the node through zwave-js and that seems to add and remove the device, but it still can't query for nodeInfo

**Comment by robertsLando** [comment]
@smitt04 This is something we have to speak with @AlCalzone. Could you please set the loglevel to debug on zwave settings, enable log to file and send us the file? it should be stored in `bin` folder

**Comment by smitt04** [comment]
[zwave-1.log](https://github.com/OpenZWave/Zwave2Mqtt/files/5696752/zwave-1.log)

**Comment by AlCalzone** [comment]
@smitt04 thanks --> https://github.com/zwave-js/node-zwave-js/issues/1214

**Comment by smitt04** [comment]
@robertsLando @AlCalzone Not sure if we should move this issue to another ticket in zwavejs2mqtt

I got around to installing the node version of the package and installed the master of node-zwave-js and I get a new error now.

```
11:13:37.937 DRIVER » [Node 012] [REQ] [SendData]
                      │ transmit options: 0x05
                      │ callback id:      208
                      └─[SecurityCCNonceReport]
                          nonce: 0xbbb5595497ffecfc
11:13:37.944 SERIAL « [ACK]                                                                   (0x06)
11:13:37.950 SERIAL « 0x0104011301e8                                                       (6 bytes)
11:13:37.952 SERIAL » [ACK]                                                                   (0x06)
11:13:37.960 DRIVER « [RES] [SendData]
                        was sent: true
11:13:38.004 SERIAL « 0x01050013d00039                                                     (7 bytes)
11:13:38.005 SERIAL » [ACK]                                                                   (0x06)
11:13:38.007 DRIVER « [REQ] [SendData]
                        callback id:     208
                        transmit status: OK
11:13:38.013 DRIVER   Unexpected error during SerialAPI command: ZWaveError: Security CC requires a
                      nonce to be sent!
11:13:38.022 CNTRLR   [Node 012] Failed all interview attempts, giving up.
```

**Comment by AlCalzone** [comment]
That log snippet is not enough to diagnose. But yeah, that warrants a new issue in node-zwave-js

**Comment by smitt04** [comment]
Forgot to link the other issue https://github.com/zwave-js/node-zwave-js/issues/1219

**Comment by robertsLando** [comment]
Closing this in favor of that
