### ISSUE TITLE
/var/lib/docker/containers large log file[question] 

### ISSUE THREAD

**Issue by oddgili** [OpenZWave/Zwave2Mqtt#779]
Hi,
After have been running Z2M for about 2 weeks, the application stoppet working, apparently alive, but no traffic, the controller had filled all storage space. I found a log file in /var/lib/docker/containers/[directoryid]-json.log at 2.5 Gbyte, not a trivial thing on a Pibased controller with 8GB total storage. Digging into the file, this was log entries from Z2M, and after deletion of the file to recover, and disabling logging in Zwave2Mqtt in the Zwave config section, this still grows. 

Me not being familiar with docke may be the issue, but this was installed using the instruction on  the Z2M, so I guess it should work out of the box. It was installed with config files external, i.e. in /home/user/store.

I run the Zwave2Mqtt in a docker on a Acme CM3-Home (RPi based controller), replacing OpenHAB as the gateway to all my Zwave devices. With a local MQTT broker and a control system built with CDP Studio there is continous traffic affecting the Zwave devices. Z2M does just what I wanted, and especially the structured way to configure nodes is beautiful.

**Comment by robertsLando** [comment]
@oddgili Did you try to set log driver to none?

**Comment by oddgili** [comment]
Where would I do that? (The Looging switch in Zwave setting is off) The log grows by 1-2 MB by the hour.

**Comment by chrisns** [comment]
https://medium.com/@Quigley_Ja/rotating-docker-logs-keeping-your-overlay-folder-small-40cfa2155412 you can have docker limit/rotate for you

**Comment by robertsLando** [comment]
@oddgili That is just for openzwave library logging, z2m logging is another thing, as @chrisns said you can also opt for log rotation but IMO if you are using an rpi I suggest to disable logging driver and enable it just when you need to debug something to limit writes on the card (and make it last longer)

**Comment by oddgili** [comment]
Thank you, I might wondered if this was a "Docker" issue and not Z2M specific, but you probably just saved my day. (My house was unpleasantly cold the other day, and I live in Norway)

**Comment by robertsLando** [comment]
It's not an issue at all, you should always rotate your logs in any application to ensure this kinf of problems but I really suggest to disable them at all in a rpi with sd card :)

**Comment by chrisns** [comment]
further to @robertsLando comment, yeah thrashing the sd card will kill it, you can mount a ram disk and store logs there so you've got some persistence. it is sometimes handy to look back a bit and the logs will hang around till you reboot at the expense of some ram
