### ISSUE TITLE
[question] Liner garage door opener missing control

### ISSUE THREAD

**Issue by scadaguru** [OpenZWave/Zwave2Mqtt#79]
I am trying to move from Home Assistant zwave to zwave2mqtt and noticed I am not seeing control (cover) for liner GD00Z-4 garage door opener. I have same device working under Home Assistant which is also runs ozw 1.4 same as zwave2mqtt. I wonder that COMMAND_CLASS_BARRIER_OPERATOR (102) for Secure Barrier AddOn is missing in ozw? I have added that device as secure node and it works under Home Assistant.
I get only 3 sensors from zwave2mqtt as shown below:
    sensor.nodeid_35_alarm_level (zwave2mqtt_nodeID_35_35-113-1-0)
    sensor.nodeid_35_alarm_type (zwave2mqtt_nodeID_35_35-113-1-1)
    sensor.nodeid_35_alarm_burglar (zwave2mqtt_nodeID_35_35-113-1-10)

I found following line in the ozw_log.txt:
2019-08-04 19:09:51.798 Info, Node035,     Secure CommandClass 0x66 - NOT SUPPORTED

Doing further more research I found out that looks like openzwave latest release 1.6 has this fix from May 2019. Is there any possibilities that we can have zwave2mqtt to use latest 1.6 release?
Appreciate it.
Thanks

**Comment by robertsLando** [comment]
Hi @scadaguru. This project uses node-openzwave-shared as ozw wrapper library, it isn't ready yet for 1.6, once it will be ready I will update the docker image to use it. ATM you can do it if you want by creating a custom docker image with ozw 1.6

**Comment by scadaguru** [comment]
Thanks for the reply. I am not how to create custom docker of ozw 1.6 with zwave2mqtt, any direction to get started please? Appreciate it.

**Comment by robertsLando** [comment]
@scadaguru here: https://github.com/robertsLando/Zwave2Mqtt-docker#custom-builds

**Comment by scadaguru** [comment]
Thanks!

**Comment by jaburges** [comment]
@scadaguru did you ever figure this out?

I have edited the dockerfile to include the 'Dev' branch which contains the 0x66 secure Barrier class. 
wondered if you had any luck?

**Comment by scadaguru** [comment]
@jaburges I have not tried it yet. Once I get chance I will update with the results.
Thanks for the update.

**Comment by robertsLando** [comment]
Now you can use the “dev” tag on docker that has ozw 1.6 instead of 1.4

Daniel
