### ISSUE TITLE
[feat] More customisable MQTT topics

### ISSUE THREAD

**Issue by PhiSDev** [OpenZWave/Zwave2Mqtt#790]
**Is your feature request related to a problem? Please describe.**
I do have the problem of using the right topics. I would expect to have more flexibility choosing the topic of each node at least in the _Configured Manually_ - mode. At the moment it possible because of the restriction of the node location.

**Describe the solution you'd like**
As [HIVEMQ](https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/) suggests I would like to have an additional option to add a **groundfloor** or **firstfloor** topic level. At the moment I'm able to enter a location/topic in the node and a value topic in the configuration of MQTT. I suggest to have to suffix topic right after the main prefix or you can add something like a node group in the node configuration
An example would be
`home/groundfloor/<node_id>/status`
or 
`home/firstfloor/<node_name>/level`

Thanks!

**Comment by robertsLando** [comment]
@PhiSDev use location? If you set a location to a node that will be added to the topic (also check mqtt settings if this is enabled)

**Comment by PhiSDev** [comment]
@robertsLando Both is not possible because the form says:
`Only a-zA-Z0-9_- chars are allowed`

**Comment by robertsLando** [comment]
@PhiSDev  Ok sorry forgot about that regex, I could allow the / chars, but I would also like to know if you tried to add a location to the node, that should work. I mean if you add a location `firstfloor` and a node name `device` the topic will be

`<prefix>/firstfloor/device/<valueId>`

**Comment by PhiSDev** [comment]
@robertsLando 
No problem :)
This way of using the location does work. I prefer to group my devices into rooms as well. When I add `firstfloor` to location I have your solution. Do I wanna have a room as group as well I'm not able, because the value topic I can modify would end in a solution like `<prefix>/firstfloor/device/bath/level` in case of a value topic `bath/level`. 

Do you know what I mean?

**Comment by robertsLando** [comment]
I understand. I will submit a pr for this

**Comment by robertsLando** [comment]
Done

**Comment by PhiSDev** [comment]
Thank you very much!

**Comment by robertsLando** [comment]
You welcome :smile:
