### ISSUE TITLE
[bug] Rows per page on node list table is not working as intended

### ISSUE THREAD

**Issue by ahochsteger** [OpenZWave/Zwave2Mqtt#792]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
The drop-down in the footer of the node list always shows the default of "5, 10, 15, All" instead of the currently intended "10, 20, All".

**To Reproduce**
1. Open the Control Panel 
2. Click on the drop-down in the footer of the node table.
3. It currently shows the options "5, 10, 15, All"

**Expected behavior**
In the code the intended values seem to be "10, 20, All":
{code}:items-per-page-options="[10, 20, { text: 'All', value: -1 }]"{code}

**Additional context**
The syntax of setting this option is not correct, this should be used instead:
```json
:footer-props="{
    itemsPerPageOptions: [5, 10, 20, 50, 100, { text: 'All', value: -1 }]
}"
```
See <https://github.com/vuetifyjs/vuetify/issues/7700> for more information.

**Comment by robertsLando** [comment]
Vuetify break I think, I see you have a fix, PR?
