### ISSUE TITLE
[bug] Brightness set via mqtt is not the same value transmitted to LED strip

### ISSUE THREAD

**Issue by jtronicus** [OpenZWave/Zwave2Mqtt#811]
**Version**

Build/Run method
- [X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.5
Openzwave Version: 1.6.1392

**Describe the bug**
When setting the brightness for a zwave LED strip, the value set via mqtt is not the value passed to the device.  

**To Reproduce**
1. Pass a payload of 8 to node 40 (zwave/40/38/1/0/set) via mqtt
2. Observe value returned:
````
{
  "value_id": "40-38-1-0",
  "node_id": 40,
  "class_id": 38,
  "type": "byte",
  "genre": "user",
  "instance": 1,
  "index": 0,
  "label": "Level",
  "units": "",
  "help": "The Current Level of the Device",
  "read_only": false,
  "write_only": false,
  "min": 0,
  "max": 255,
  "is_polled": false,
  "value": 3,
  "lastUpdate": 1603765959250
}
````
3. zwave packet sniffer also confirms that a brightness value of 3 was actually transmitted:
![image](https://user-images.githubusercontent.com/46967605/97250486-4a725300-17c3-11eb-9c8a-dbb899720873.png)

**Expected behavior**
I am expecting the value 8 to be passed on the Multilevel Command Class.  It looks like the value passed via mqtt to zwave/40/38/1/0/set is being scaled to value/255*99 (8 / 255 * 99 = 3)

**Additional context**
Changing the value with the OZW control panel works as intended, it is only values passed via mqtt set topic that are experiencing this issue.

**Comment by robertsLando** [comment]
@jtronicus Do you have hass discovery enabled? If so it's due to this: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/Gateway.js#L618

**Comment by jtronicus** [comment]
Yes, I did have hass discovery enabled (but I wasnt actually using that feature).  Disabling it resolved the issue.  Thanks!
