### ISSUE TITLE
[bug] MQTT offline, reconnecting, connected, ...

### ISSUE THREAD

**Issue by Jeoffreybauvin** [OpenZWave/Zwave2Mqtt#814]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: latest
Openzwave Version: 1.6.0

**Describe the bug**
Following #813, I move the stick to another host. Everything is working fine, my devices are not dead anymore, but I have a lot of these in my logs :

```
zwave2mqtt    |   z2m:Mqtt MQTT client closed +1ms
zwave2mqtt    |   z2m:Mqtt MQTT client reconnecting +500ms
zwave2mqtt    |   z2m:Mqtt MQTT client connected +6ms
zwave2mqtt    |   z2m:Mqtt MQTT client offline +501ms
zwave2mqtt    |   z2m:Mqtt MQTT client closed +1ms
zwave2mqtt    |   z2m:Mqtt MQTT client reconnecting +501ms
zwave2mqtt    |   z2m:Mqtt MQTT client connected +6ms
zwave2mqtt    |   z2m:Mqtt MQTT client offline +503ms
zwave2mqtt    |   z2m:Mqtt MQTT client closed +0ms
zwave2mqtt    |   z2m:Mqtt MQTT client reconnecting +502ms
zwave2mqtt    |   z2m:Mqtt MQTT client connected +5ms
zwave2mqtt    |   z2m:Mqtt MQTT client offline +503ms
zwave2mqtt    |   z2m:Mqtt MQTT client closed +1ms
zwave2mqtt    |   z2m:Mqtt MQTT client reconnecting +501ms
zwave2mqtt    |   z2m:Mqtt MQTT client connected +6ms
zwave2mqtt    |   z2m:Mqtt MQTT client offline +503ms
zwave2mqtt    |   z2m:Mqtt MQTT client closed +0ms
zwave2mqtt    |   z2m:Mqtt MQTT client reconnecting +502ms
```

And I have a lot of messages coming to zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-broker/status : 

![image](https://user-images.githubusercontent.com/701928/97989140-62a72b00-1dde-11eb-825f-9aae08ee6d70.png)

My mosquitto broker is working fine, I have a lot of clients on it...

**To Reproduce**
1. Launch zwave2mqtt

**Expected behavior**
Stable connexion ? 

**Additional context**

**Comment by robertsLando** [comment]
@Jeoffreybauvin I usually have expected this behaviour when there are multiple clients connected with the same id to the broker, do you have multiple instances of z2m running or some other client connected to the broker with the same client id?

**Comment by Jeoffreybauvin** [comment]
Hi @robertsLando 

Indeed, I had two clients connected with the same id.  Is there a way to use a different id ?

**Comment by robertsLando** [comment]
Change the name on mqtt settings :)

**Comment by Jeoffreybauvin** [comment]
Indeed, perfect :). 

Thanks @robertsLando  !
