### ISSUE TITLE
[bug] node-openzwave-shared that works with ozw 1.6 has various issues when devices timeout

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#82]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master @ 20190805
Openzwave Version: 1.6.848

**Describe the bug**
While trying to trouble shoot #58 more, I noticed the following after swapping to a new controller (Aeotec ZW090):

After including a device, all currently setting seem to be read properly.
After moving the device in this case a Aeotec ZW116 switch, and restarting zwave2mqtt.

Everything worked, but the VerifyChange property did not get applied. I also tried to enable poll. Same effect. I did notice that the node timed out while queuing at the startup and it loadsd date from the cache.

After including a new one of the same type/model, because I wanted to rule out a bad device...
This device got included fine and had the default settings, and I configured the device the same way.

While restarting zwave2mqtt I also wiped the full store folder to start fresh, I then noticed both switches timed out and they did not get required for the current on device config.

I verified this by doing the configuration again and restarting, I think this time it restored the active settings from the ozwcache after the timeout. Wiping the cache confirmed this as they were showing defaults again after a restart. (But the device still had the good config.)

Another node that was in range got the config restore from the device itself again.

I’m thinking this and the not applying things like Poll or VerifyChange might be related.
Some event is probably not triggers or the commands do fire but don’t make it to the device because of the timeout.

**To reproduce**
- configure a device
- (add some override like poll/VerifyChange)
- move the device where it is sometimes not responding due to our of range or interference
- wipe the ozwcache
- restart zwave2mqtt
- device config is back to default instead of loaded from device 
- (poll/verifychange are not applied)

**Expected behavior**
Devices that timeout or are not reachable, to be required once they come back.

**Additional context**
I’m not a 100% sure on this after going to the logs as they were a bit of a mess, but could this make sense?

If so I will try to break it down and collect some fresh logs this weekend.
Sadly the device have really bad interference in this appartment.

**Comment by sjorge** [comment]
If this makes sense, or seems possible we can probably close #58 until this is resolved.

**Comment by robertsLando** [comment]
@sjorge Thanks for the detailed explanation but sincerly I have no idea about this... I never changed the code about verifyChanges so if it was working and now it is not it is most probably related to underlying libs

**Comment by sjorge** [comment]
That seems most likely yeah as only old zwave2mqtt 1.0.3 with old node-openzwave-shared against old openzwave work for enablePoll and verifyChange...

**Comment by robertsLando** [comment]
@sjorge In order to fix this you should use `requestConfigParams` api
