### ISSUE TITLE
[bug] Measured temperature offset 128 not allow to set air temperature

### ISSUE THREAD

**Issue by PavelD** [OpenZWave/Zwave2Mqtt#820]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.6
Openzwave Version: 1.4.1

**Describe the bug**
The Air temperature is read only when set to external sensor.

**To Reproduce**
1. Go to EUROtronic EUR_SPIRITZ Wall Radiator Thermostat.
2. Check the 49-1-1:Air Temperature. It's read only value.
3. Change 112-1-8:Measured Temperature Offset:0 -> 128 (external sensor)
4. Try to update 49-1-1:Air Temperature.
-- The update is not possible even if 49-1-1:Air Temperature should be possible to update from external sensor.

**Expected behavior**
The step 4 should allow to update temperature. 

**Additional context**
I'm not sure if this use case should work exactly in the way as described.
Workaround exists. It is more counting, but it is possible to set correct delta for the sensor based on the external sensor value in 112-1-8:Measured Temperature Offset.

**Comment by robertsLando** [comment]
@PavelD Hi PavelD! If the value is reported as read-only it means ozw is reporting it to me as it,did you try to open an issue on ozw repo?

**Comment by robertsLando** [comment]
Also I see you are using ozw 1.4 that could have some issues with latest z2m version, I suggest to update to ozw 1.6 and retry

**Comment by PavelD** [comment]
Hi Robert,

Thanks for your answer. I'm using your image robertslando/zwave2mqtt:latest and the version of z2m i find out from the docker file present on that place (https://hub.docker.com/r/robertslando/zwave2mqtt/dockerfile).

Here is what i'm currently running:
$ docker images | grep zwave2mqtt
robertslando/zwave2mqtt            latest              2f9529847871        5 days ago          191MB

I didn't open any other issue for this problem yet. For the z-wave technology i'm just normal user :-/ I'm trying to set external sensors for the first time and I have no clue if I'm trying to do it correctly. So first steps were to the administration to try update of the Air find out what exactly i need to change in order to see altered `Air Temperature` state as vendor user manual is not covering this use case at all.

**Comment by robertsLando** [comment]
> I'm using your image robertslando/zwave2mqtt:latest and the version of z2m i find out from the docker file present on that place

Ok so I think you forgot to edit the openzwave version in your issue :) It's 1.6 not 1.4.

> So first steps were to the administration to try update of the Air find out what exactly i need to change in order to see altered Air Temperature state as vendor user manual is not covering this use case at all.

As I said in my previous comment if this value is reported as read-only it means that Openzwave (the library that I use to communicate with the controller) is sending me that value as read-only value. So the problem should be there

**Comment by PavelD** [comment]
So sorry. I grep the logs again and i see it now. Version is 1.6.

2020-11-06T07:23:14.869Z z2m:Zwave Zwave connected, Openzwave version: 1.6.0

**Comment by PavelD** [comment]
I will open issue in OpenZWave/open-zwave. Thanks for your time!

**Comment by robertsLando** [comment]
Sorry I just checked again your issue, the command class 49 is `COMMAND_CLASS_SENSOR_MULTILEVEL` and it's obiviously read only. You should check for `COMMAND_CLASS_THERMOSTAT_SETPOINT` in the ui in order to set a value
