### ISSUE TITLE
[bug] Brightness and power on templates cause 100% brightness to exceed valid brightness values

### ISSUE THREAD

**Issue by ingenium13** [OpenZWave/Zwave2Mqtt#822]
**Version**

Build/Run method
- [ X] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.5
Openzwave Version: 1.6.1392

**Describe the bug**
The hass json for Leviton DZ6HD-1BZ Decora 600W Smart Dimmer has templates that cause 100% brightness to exceed the max value for Home Assistant. 100% brightness is converted to a value of 258, but HA only accepts 0-255. This is because the calculation divides the percent by 99 instead of 100:

```
{
  "type": "light",
  "object_id": "dimmer",
  "discovery_payload": {
    "schema": "template",
    "brightness_template": "{{ (value_json.value / 99 * 255) | round(0) }}",
    "state_topic": "homeassistant/bedroom/38/1/0",
    "state_template": "{{ \"off\" if value_json.value == 0 else \"on\" }}",
    "command_topic": "homeassistant/bedroom/38/1/0/set",
    "command_on_template": "{{ ((brightness / 255 * 99) | round(0)) if brightness is defined else 255 }}",
    "command_off_template": "0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xead14a91_node3"
      ],
      "manufacturer": "Leviton",
      "model": "DZ6HD-1BZ Decora 600W Smart Dimmer (0x0001)",
      "name": "bedroom",
      "sw_version": "1.13"
    },
    "name": "bedroom_dimmer",
    "unique_id": "zwave2mqtt_0xead14a91_3-38-1-0"
  },
  "discoveryTopic": "light/bedroom/dimmer/config",
  "values": [
    "38-1-0"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "light_dimmer"
}
```

**To Reproduce**
Set the dimmer to 100% brightness, and HA shows the brightness attribute to be 258

**Expected behavior**
100% brightness should be 255, not 258.

**Additional context**
Home Assistant itself seems to be fine with this and doesn't throw an errors, but it causes issues with other integrations which expect the brightness to be 0-255. For example, power menu buttons from the Android app will not function if brightness is above 255. Manually updating the hass json to use 100 instead of 99 corrects the issue.

**Comment by robertsLando** [comment]
Hi @ingenium13 ! AFAIK that template has always work, at least until now, could be that if I fix that for you it could break existing templates, what about manually edit it in hass devices table based on your needs? Or even better if you have lot of this devices add the desired template to customDevices.json (in the correct format) and it will be applied to all

**Comment by ingenium13** [comment]
The Home Assistant docs specify that brightness should be a value between 0-255 https://www.home-assistant.io/integrations/light/ The current template results in a brightness between 3 and 258. While Home Assistant itself seems to accept 258, other things that integrate with Home Assistant do not. For example, this bug I filed against the Home Assistant Android app https://github.com/home-assistant/android/issues/1179

Is there a reason that 99 was chosen instead of 100?

**Comment by robertsLando** [comment]
> If I change the template on my end, will this persist across upgrades of the zwave2mqtt docker container?

If you store it in customDevices.js it will persist, yes

> Is there a reason that 99 was chosen instead of 100?

Yes but now sincerly I don't remember, when we firstly integrate light dimmers there was some bugs and that template was the final fix. Maybe @jshridha could tell you more

**Comment by ingenium13** [comment]
Is there any documentation for customDevices.js? All I've found are a couple bug reports, but I think I can mostly figure it out from those.

I guess my question is, what parts of the hass json have to be added? Some subset of the discovery payload? If so, what is required and what is auto populated? Can I just have the parts that I want to change as an override (basically the two templates)? Or do I need to add everything (ie, it entirely replaces rather than just overlays the existing one)?

**Comment by jshridha** [comment]
Regarding the 99 value: for the GE/jasco dimmers, sending 99 causes the device to go back to the brightness level it was at prior to being turned off. I'm not sure how the Leviton dimmers work regarding their state after they've been turned off.

**Comment by ingenium13** [comment]
> Regarding the 99 value: for the GE/jasco dimmers, sending 99 causes the device to go back to the brightness level it was at prior to being turned off. I'm not sure how the Leviton dimmers work regarding their state after they've been turned off.

For Leviton and Innovelli de

**Comment by robertsLando** [comment]
> Is there any documentation for customDevices.js? All I've found are a couple bug reports, but I think I can mostly figure it out from those.

It's explained on readme: https://github.com/OpenZWave/Zwave2Mqtt#custom-components
