### ISSUE TITLE
[bug] Gateway - Values Table (Configured Manually). Some devices don't show up in pull down

### ISSUE THREAD

**Issue by tommyjlong** [OpenZWave/Zwave2Mqtt#824]
**Version**
v4.0.5

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 4.0.5
Openzwave Version: 1.6.1392

**Describe the bug**
After upgrading to v4.05/1.6.1392, All my devices have been rediscovered and show up in the Control Panel.
All the devices of interest in the Control Panel have their "Type" "Product", etc.  filled out.  Each device's set of classes ("User" "Configuration", "System") seem to have been discovered properly as well.

Gateway Config:
  Settings->Gateway Type = Configured Manually, Payload Type = Just Value.

In the Gateway settings there is a Table with entries where an entry consists of "Devices" with "Value", "Topic" ,etc.
I want to add a new entry, but the Pull Down list doesn't contain the device I'm looking for. 

For most of my existing G/W Table entries, the "Device" column shows the Device ID in brackets along with the associated product string. Ex. [134-100-258] ZW100 MultiSensor 6 (AEON Labs).
   When adding an entry in the G/W Table, these devices show up in the Device Pull down menu OK.
   Exception: I have two devices that are the same (only difference is node-id), Neither have an existing entry in the Table.  When attempting to add a new entry only one of them shows up in the Device Pull Down, the second device DOES NOT show up in the Pull Down. 

The next problem involve a couple of (battery operated) devices in my existing G/W Table entries still exist but under the "Device" column they only show the Device ID.  The brackets around the Device ID are missing as well as the associated product string is missing.
      Example: 134-130-258
   When adding an entry in the G/W Table, these devices DO NOT show up in the "Device" Pull down menu
      What I expect to find is [134-130-258] ZW130 Wallmote Quad (AEON Labs)
   Similarly can not edit one of these problem existing entries because the "Device", "Value" "Device Class" is missing (but the "Topic" is present).  BTW these existing entries still continue to work as far as MQTT is concerned.

**Comment by robertsLando** [comment]
> I have two devices that are the same (only difference is node-id), Neither have an existing entry in the Table. When attempting to add a new entry only one of them shows up in the Device Pull Down, the second device DOES NOT show up in the Pull Down.


A device is added when it's on `ready` state. Are your devices `ready` on gateway table?

Source: https://github.com/OpenZWave/Zwave2Mqtt/blob/master/lib/ZwaveClient.js#L472

**Comment by tommyjlong** [comment]
How would one go about determining if a device is ready?

**Comment by robertsLando** [comment]
@tommyjlong It's the driver that reports it as ready, for sleeping devices it could take very long time to be ready

**Comment by tommyjlong** [comment]
OK..my battery devices all of a sudden now show up in the G/W Table Device Pull down.  The only device that does not show up is the second of two Aeotec Range Extenders (these are the ones that only differ by node-id).  I will play with it some more and report back.

**Comment by robertsLando** [comment]
Ok let me know so

**Comment by tommyjlong** [comment]
It looks like by performing a Request Node Info, one can find out if a device is **ready**.

Here is a (very) shortened version of the log outputs I conducted on the two identical AEOTEC Range Extenders (node 10 and 11 respectively).  Notice the last line showing the devices as ready:
```
Nov 11 17:07:52 NUC node[15833]: 2020-11-11T22:07:52.967Z z2m:App Zwave api call: refreshNodeInfo [ 10 ]
Nov 11 17:07:53 NUC node[15833]: 2020-11-11T22:07:53.028Z z2m:Zwave Success zwave api call refreshNodeInfo
....
Nov 11 17:07:54 NUC node[15833]: 2020-11-11T22:07:54.785Z z2m:Zwave node 10 ready: Aeotec Limited - ZW189 Range Extender 7 (Generic Repeater)
```


```
Nov 11 17:11:58 NUC node[15833]: 2020-11-11T22:11:58.813Z z2m:App Zwave api call: refreshNodeInfo [ 11 ]
Nov 11 17:11:58 NUC node[15833]: 2020-11-11T22:11:58.876Z z2m:Zwave Success zwave api call refreshNodeInfo
....
Nov 11 17:11:59 NUC node[15833]: 2020-11-11T22:11:59.529Z z2m:Zwave node 11 ready: Aeotec Limited - ZW189 Range Extender 7 (Generic Repeater)
```
Yet there is only one entry in the G/W Table Device Pulldown for these two devices:
`[881-189-260] ZW189 Range Extender 7 (Aeotec Limited)`

**Comment by robertsLando** [comment]
> Yet there is only one entry in the G/W Table Device Pulldown for these two devices:

If they have the same device id it's correct that there is only one entry. There is 1 for each device, if you have 2 identical devices you will always see only one there

**Comment by tommyjlong** [comment]
OK.  Thanks for your help.
And thanks a bunch for your work on this project 👍

**Comment by robertsLando** [comment]
@tommyjlong Glad you like it hope you have fixed your problem :)
