### ISSUE TITLE
No Option to setup serial port in zwave menu

### ISSUE THREAD

**Issue by Diddlik** [OpenZWave/Zwave2Mqtt#829]
I have installed everything in the docker according to the instructions

> version: '3.7'
> services:
>   zwave2mqtt:
>     container_name: zwave2mqtt
>     image: robertslando/zwave2mqtt:dev
>     restart: always
>     tty: true
>     stop_signal: SIGINT
>     networks:
>       - zwave
>     devices:
>       - "/dev/ttyACM0:/dev/ttyACM0"
>     volumes:
>       - ./store:/usr/src/app/store
>       - ./openzwave:/usr/local/etc/openzwave
>     ports:
>       - "8091:8091"
> networks:
>   zwave:

After startup I have no menu in the GUI to define serail port for zwave

![grafik](https://user-images.githubusercontent.com/6010713/98918709-3c644800-24ce-11eb-99d7-55c78990fe98.png)

What did I do wrong during the installation?

**Comment by robertsLando** [comment]
@Diddlik Did you try to expand the zwave menu? there should be an arrow on the right to expand that

**Comment by Diddlik** [comment]
ooo, no, i am so stupid...now i have it, thank you
