### ISSUE TITLE
[bug] we do not handle a vlaue of type 'short' correctly.

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#83]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master @ 20190805
Openzwave Version: 1.6.848

**Describe the bug**
Once of the devices I have is missing configuration in OpenZwave, while in the progess of writing a config file for it. I noticed values of type`short` are not handled properly.

**To Reproduce**
Per the manual, parameter 10 should be `short`:
https://manuals.fibaro.com/content/manuals/en/FGWOEF-011/FGWOEF-011-T-EN-v1.0.pdf

![param10](https://imgur.com/PXCOp6e.png)

```xml
    <Value type="short" index="10" genre="config" label="LED frame - power limit" value="36800" min="500" max="36800" size="4">
      <Help>This parameter determines maximum active power. Exceeding it results in the LED frame flashing violet. Function is active only when parameter 11 is set to 8 or 9.
500-36800 (50.0-3680.0W, step 0.1W) - power threshold</Help>
    </Value>
```

With `short` (above) it shows up as a negative value, when I switch to `int` (below) it shows up correctly with the default value of '36800'

```xml
    <Value type="int" index="10" genre="config" label="LED frame - power limit" value="36800" min="500" max="36800" size="4">
      <Help>This parameter determines maximum active power. Exceeding it results in the LED frame flashing violet. Function is active only when parameter 11 is set to 8 or 9.
500-36800 (50.0-3680.0W, step 0.1W) - power threshold</Help>
    </Value>
```

I think it might be a signed vs unsigned issues here, not sure if is in zwave2mqtt or in node-shared-openzwave. But accoriding to https://github.com/OpenZWave/open-zwave/wiki/Adding-Devices a `short` is the correct type to use as it more closely matches the range. 

```
o int - A integer can represent a number from 0 to 4294967295
o short - A Short can represent a number from 0 to 65535
```

**Expected behavior**
Values of type short to be disaplyed correctly.

**Additional context**
n/a

**Comment by robertsLando** [comment]
@sjorge You should submit a PR on openzwave to fix the file configuration [there](https://github.com/OpenZWave/open-zwave/tree/master/config/fibaro)

**Comment by sjorge** [comment]
I'm not sure the configuration file is wrong (as it does not exist yet, I did also ask for help writing this specific one on the ozw mailing list.)

The device manual in this case says the value has a min/max within the '0-65535' (short) vs '0-4294967295' (int) and the Adding-Devices page, seems to indicate you should pick the one closely matching the value range. Which makes sense as if you are only every going to store 0-5000, no need to waste space with an int.

If there is no special handling of the between int and short in z2m, it's probably a bug for the node bindings.

**Comment by robertsLando** [comment]
Nope I never change values types on my side

Daniel
