### ISSUE TITLE
Stored configuration doesn't apply after restart

### ISSUE THREAD

**Issue by homected** [OpenZWave/Zwave2Mqtt#837]
I removed some node values from Zwave devices to publish only the node values I have interest. To do this, I delete the Id I don't need and then set STORE when I have the list of values I want to publish. But when I restart the Zwave2mqtt, all id appear again and to let the configuration as I want I have to import the nodes.json. There is any way to set this configuration persistent after a restart?

**Comment by robertsLando** [comment]
You mean hass discovery values?

**Comment by homected** [comment]
Thanks Daniel, disable discovery is the solution for me. I think this option is not covered in the documentation.

Regards.

**Comment by robertsLando** [comment]
Will fix docs so :) Also keep an eye on the next version of z2m here: https://github.com/zwave-js/zwavejs2mqtt

**Comment by homected** [comment]
Sorry Daniel, but disable discovery is not the solution, after restart the homeassistant devide appear duplicated.

**Comment by robertsLando** [comment]
> Sorry Daniel, but disable discovery is not the solution, after restart the homeassistant devide appear duplicated.

Did you stored the hassDevice? If you check hass devices table, the persistent column says `Yes`? Also check if the discovery is retained and if so disable the retained discovery and delete the retained message from your broker

**Comment by homected** [comment]
I attach some images to try to explain the problem, sorry for my english. I removed the homeassistant devices that I don't need from the table and then I push store. If I reboot the raspberry pi, once Zwave2Mqtt is available but Zwave network devices are not yet discovered I can check that the table is as I want, check this image:
![image](https://user-images.githubusercontent.com/2371734/100253921-ff726980-2f41-11eb-9adc-6c83e14c3ab3.png)

But after some minutes when the zwave nodes are ready (or loaded) the table shows again the entries I deleted, see this image:
![image](https://user-images.githubusercontent.com/2371734/100254535-ba026c00-2f42-11eb-8ff2-1587f0797d26.png)

The last three nodes are the nodes I have already deleted. And all the nodes from the table are published to the MQTT broker.

Then I delete again the last three nodes and disable discovery and press store, This is the image for this moment:
![image](https://user-images.githubusercontent.com/2371734/100255003-43b23980-2f43-11eb-8f27-cd89db38daaa.png)

Now I reboot, and wait to Zwave2Mqtt is available but prior the zwave network is loaded the node appear like in this image:
![image](https://user-images.githubusercontent.com/2371734/100255364-af94a200-2f43-11eb-8392-3ac7e6a1b028.png)

It seems ok, but the zwave network is not loaded yet. After few minutes when the zwave is loaded the node table shows duplicate entries:
![image](https://user-images.githubusercontent.com/2371734/100255758-38abd900-2f44-11eb-958c-dd442023bffa.png)

Up to now, before I use the disable discovery option, when I reboot I wait to the zwave network be ready and then I import a nodes.json file with the desired nodes configuration, but at this moment all the entries of the table I don't want are already published to the mqtt broker and homeassistant discover it.

So i have interest if there is the possibility to keep the nodes.json for avoid to import the nodes.json everytime I reboot.

Regards

**Comment by robertsLando** [comment]
> I removed the homeassistant devices that I don't need from the table and then I push store

Wrong, you don't have to remove them, you have to disable the discovery or they will be discoverd again on next app boot

**Comment by homected** [comment]
But I If I don't remove the home assistant devices entries from the table, all the entries are published to the mqtt broker, not?

**Comment by robertsLando** [comment]
> But I If I don't remove the home assistant devices entries from the table, all the entries are published to the mqtt broker, not?

Nope if they are disabled :) I need to have them there with the `ignoreDiscovery` set to true to know I don't have to discover them

**Comment by homected** [comment]
I don't understand, I tested some configurations and the only way to don't publish all the endpoints (the entries in the table) is remove those I have no interest from the table, but after a restart all the entries are reloaded and due to this all off them are again published. You said me that set DISABLE DISCOVERY and STORE, if I do without all the entries of the table because I deleted some of them for not to be published, after restart in the table appears entries duplicated and these duplicated entries are also published. I don't delete any of the entries in the table and set DISABLE DISCOVERY and STORE, after reboot all the entries in the table are again published. So I rebuild the question, 

is possible to not publish some of the entries of the table and keep this configuration after a reboot?

**Comment by robertsLando** [comment]
@homected I have found where the bug could be, let me submit a fix for this now

**Comment by robertsLando** [comment]
@homected Wait an hour or less for the docker build then retry this :)

**Comment by homected** [comment]
> @homected Wait an hour or less for the docker build then retry this :)

I don't use docker, I update from github to its latest version, so Zwave2mqtt is now at version 4.1.0. I try different setups and this one have the behaviour I want.

![image](https://user-images.githubusercontent.com/2371734/100917148-0e739180-34d7-11eb-83fe-db65a659a8a0.png)

To get this, first I need to delete the entries I want to publish (yes, I have to delete the ones I want to publish), so the table has only the entries I don't want, then set disable discovery and store. When I reboot, the deleted entries are discovered and are published while the disabled entries are not published.

For me maybe is not the logical way to setup this behaviour but it works.

You told previously about https://github.com/zwave-js/zwavejs2mqtt is better than zwave2mqtt?

Thanks for your support.

**Comment by robertsLando** [comment]
> You told previously about https://github.com/zwave-js/zwavejs2mqtt is better than zwave2mqtt?

It is but it'a a work in progress :) it has some new fetaures and it's more stable z2m

> For me maybe is not the logical way to setup this behaviour but it works. The entries published are these with Persistent=No and Discovery=Enabled.

I know this, sorry, I will try to make it more easy to use.

**Comment by homected** [comment]
You don't have to say sorry, I'm thankful to you for your support and the efforts you used for this problem.

I'll keep an eye on zwavejs2mqtt although zwave2mqtt is working fine for me.
