### ISSUE TITLE
[question] Get Zwave2Mqtt version over MQTT

### ISSUE THREAD

**Issue by Diddlik** [OpenZWave/Zwave2Mqtt#846]
Is it possible to send a version of currently installed zwave2mqtt to mqtt?

The Idea is to create one atomation / notification if there are a new version

**Comment by robertsLando** [comment]
@Diddlik Actually it's not possible but it's easy to implement. Anyway I would like all users to start moving to https://github.com/zwave-js/zwavejs2mqtt/ so I'm focusing there for new fetaures. If I implement it there could you use it?

**Comment by Diddlik** [comment]
Hi Daniel
am on zwavejs since yesterday. So far all good.
Yes, I would like to use it there. Ideal would be a topic with the current version and the currently available master/dev. But the current one would be very helpful.

Thank you

**Comment by robertsLando** [comment]
@Diddlik Let me move this there so :)

**Comment by robertsLando** [comment]
@Diddlik I cannot move the issue to that repo, can you recreate the issue there please?

**Comment by Diddlik** [comment]
done
