### ISSUE TITLE
[question] How to request latest value, or force refresh of current value

### ISSUE THREAD

**Issue by dhritzkiv** [OpenZWave/Zwave2Mqtt#848]
For background, I'm setting up zwave2mqtt to work with the [mqtthing plugin for homebridge](https://github.com/arachnetech/homebridge-mqttthing#readme).

If I'm connecting the mqtthing plugin (client) to the mqtt broker after zwave2mqtt has been running, what's the best way for mqtthing to be made aware of devices' current latest/values.

Listening to a topic (e.g. `ozw/2/38/1/0`, where `ozw` is my mqtt prefix) only picks up future value changes.

Is there a way to trigger a changed message with the current value? I'm hopping to include the pub command in the start up section, as detailed [here](https://github.com/arachnetech/homebridge-mqttthing/blob/master/docs/Configuration.md#publishing-values-on-start-up)

**Comment by robertsLando** [comment]
@dhritzkiv YOu should use `retain` flag for such purposes

**Comment by dhritzkiv** [comment]
This did the trick!
