### ISSUE TITLE
[question] zwave2mqtt only responding to published mqtt set values after manually switching device or setting user value via zwave2mqtt UI

### ISSUE THREAD

**Issue by gjermy** [OpenZWave/Zwave2Mqtt#850]
Hi,

I have a behaviour with a couple devices that I can't understand or debug.

For a couple of devices on the system, zwave2mqtt doesn't respond to or even log anything when values are published to the 'set' topic... until either the device is switched manually (e.g. at wall switch) or via the zwave2mqtt web UI by doing a set of the value within 'User' part of the device's values. 

After the first manual update zwave2mqtt responds and logs the change seen on the set topic and actions the sets.

However if zwave2mqtt restarted I'm back to the behaviour of not responding to or logging changes on the set topic, until a manual change - e.g. via the zwave2mqtt UI->control panel->select node->values.. User->level  type value and click arrow.

My zwave2mqtt gateway settings is "Configured Manually" and "Entire Z-Wave value object".

I've got hass connected to mqtt server - but can reproduce the issue by publishing messages on the 'set' topic using e.g. MQTT-explorer also.

So in the logs I see no "message received" lines for the devices having problems until the first switch via the UI - the UI triggered switch show in logs like so (here setting value of a dimmer to 0 to switch light off). 

```
zwave2mqtt_1     |   z2m:App Zwave api call: setValue [ 3, 38, 1, 0, '0' ] +27s
zwave2mqtt_1     |   z2m:Zwave Success zwave api call setValue  +2s
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-27:Ultraviolet:0 -> 0 +1s
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 38-1-0:Level:99 -> 0 +112ms
```

After that point I can use hass or mqtt-explorer to switch the device and zwave2mqtt responds an in logs I see for example whilst changing the dimmer's value from 0 to 99 and back again... but I was performing same actions in hass an same publish in mqttexplorer before the manual set with no lines like below showing in log.

```
zwave2mqtt_1     |   z2m:Mqtt Message received on hawthorn21zwave2mqtt/Studio/StudioMainLight/Level/set +7m
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 38-1-0:Level:0 -> 99 +1s
zwave2mqtt_1     |   z2m:Zwave zwave node 2: changed: 50-1-32:Exporting:false -> false +111ms
zwave2mqtt_1     |   z2m:Zwave zwave node 2: changed: 50-1-8:Power:0 -> 0 +4ms
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 39-1-0:Switch All:Disabled -> Disabled +928ms
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-1:Temperature:10.3 -> 10.3 +1s
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-3:Luminance:0 -> 18 +3s
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-5:Relative Humidity:58 -> 58 +2s
zwave2mqtt_1     |   z2m:Mqtt Message received on hawthorn21zwave2mqtt/Studio/StudioMainLight/Level/set +8s
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-27:Ultraviolet:0 -> 0 +3s
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 38-1-0:Level:99 -> 0 +111ms
zwave2mqtt_1     |   z2m:Zwave zwave node 5: changed: 37-1-0:Switch:false -> false +1s
zwave2mqtt_1     |   z2m:Zwave zwave node 2: changed: 50-1-32:Exporting:false -> false +2s
zwave2mqtt_1     |   z2m:Zwave zwave node 2: changed: 50-1-8:Power:0 -> 0 +3ms
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 39-1-0:Switch All:Disabled -> Disabled +474ms
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-1:Temperature:10.3 -> 10.2 +1s
zwave2mqtt_1     |   z2m:Mqtt Message received on hawthorn21zwave2mqtt/Studio/StudioMainLight/Level/set +8s
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-3:Luminance:18 -> 0 +3s
zwave2mqtt_1     |   z2m:Zwave zwave node 3: changed: 38-1-0:Level:0 -> 99 +110ms
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-5:Relative Humidity:58 -> 59 +649ms
zwave2mqtt_1     |   z2m:Zwave zwave node 4: changed: 49-1-27:Ultraviolet:0 -> 0 +3s
```

As mentioned, if I restart zwave2mqtt I'm back to not having the hass actions or mqtt-explorer publishes noticed.

I've got two plug sockets and an in-wall dimmer behaving like this.
- TZ68 On/Off Switch Socket (TKB Home)
- TZ69 Smart energy plug in switch (TKB Home)
- AD146 In wall Dimmer Module (Everspring)

However have an in-wall on-off which is working without needing the manual poke.
- AN179 In wall ON/OFF Module (Everspring)

I've tried with poll true and false in the device's setup under gateway but doesn't seem to make a difference.

Would appreciate any ideas on what to try or what may be mis-configured.

Please let me know what other info would be useful to provide.

**Comment by robertsLando** [comment]
Hi @gjermy , so this happens only after restarts right? But you mean after an application restart or a restart from settings? Did you tried with https://github.com/zwave-js/zwavejs2mqtt?

**Comment by gjermy** [comment]
Hi @robertsLando - really sorry but I think I may have been using an old version.

I was running via docker(-compose) using robertslando/zwave2mqtt:latest - and I was sure I'd done a docker pull of latest, but maybe that hadn't worked. Or I'd mistakenly pulled on laptop rather than ssh to pi. The pi had been half set up a while previous.

I've tried pinning to a more recent image than I'd originally taken (robertslando/zwave2mqtt:4.0.5) and the issue is resolved. So unless its an issue since 4.0.5 it seems fixed. I can try pinning really the latest release later after work.

(I should really have always prefered pinning an explicit release - not so controlled just using :latest as you need to remember / be certain the state of the machine rather than just inspecting the config.)

> so this happens only after restarts right?
> But you mean after an application restart or a restart from settings?
Yes - only happened after restarts - its like the manual switch causes a subscribe to correct topic at that point which hadn't been subscribed without that happening.
When I say restart I mean the container - "docker-compose restart mqtt2zwave" (or docker-compose down then up).

Note - I now see a 
`zwave2mqtt_1     |   z2m:Mqtt Subscribing to <mytopleveltopic>/+/+/+/set`
in the logs which wasn't there in whatever version I was accidentally running.

>> Did you tried with https://github.com/zwave-js/zwavejs2mqtt?
No! I didn't know that project existed - but will take a look at migrating anyway if that is the way forward - thanks for the pointer!

Many thanks for you help and this project. I will close this - if I find it happens again or on a newer version I can request a re-open.

**Comment by robertsLando** [comment]
@gjermy I suggest you to consider switching to zwavejs implementation as I will add new features only on that one :)
