### ISSUE TITLE
regarding setValue API calls from MQTT

### ISSUE THREAD

**Issue by IATLLC** [OpenZWave/Zwave2Mqtt#859]
Hello,
I have installed the OpenZWave/Zwave2Mqtt on my ubunto 20.04 laptop to do development for my raspberry pi as a Zwave hub. I have a thermostat that is recognized in the control panel and will let me control it just fine from the control panel. I set a temperature setpoint for the heater click the update arrow and it calls the setValue API and updates the value. I can see from the terminal output the API call and what arguments it is using.  Easy peasy. Here is what it outputs for the API call:

z2m:APP Zwave api call: setValue [ 4, 67, 1, 1, '60 ]

It is successful and updates the setpoint correctly every time. (picture will be attached for this.

So here is my issue. I have a program written in python for taking a pressing of a button in tkinter and writting a value to my mosquitto MQTT broker that the z2m is interacting with. Based on the installation and use instructions I define the following topics in my class.

self.zwave_setValue_api_topic="zwave2mqtt/_EVENTS/ZWAVE_GATEWAY-Enterprise/api/setValue/set"
self.zwave_api_setValue_response="zwave2mqtt/_EVENTS/ZWAVE_GATEWAY-Enterprise/api/setValue"

I then have part of my python script write to that topic with the following dict converted to Json object script. (it is down and dirty right now, I am just trying to get the API call right, not get it to grab anything but a hardcoded value right now.)

_#create a python dict
            self.zwave_setValue_set_setpint_on_dict={
                                                      "args": [4, 67, 1, 1, '69' ]
                                                    }
        
            #create a Json object
            self.zwave_setValue_set_setpoint_json = json.dumps(self.zwave_setValue_set_setpint_on_dict)
            #print it out for debug purposes
            print(self.zwave_setValue_set_setpoint_json)

            #publish it to the setValue API topic for zwavw2mqtt
            self.client.publish(self.zwave_setValue_api_topic, self.zwave_setValue_set_setpoint_json)
        _ 
The python side works just fine, the button is pressed, that part of the script is ran, and the value is published to the correct path, and I see that from both the MQTT broker and also from the terminal showing the output from z2m. The issue is that it doesn't do anything in the Zwave2MQTT side. It just says it received the message on the terminal screen, but there is no response message sent to the zwave2mqtt/_EVENTS/ZWAVE_GATEWAY-Enterprise/api/setValue topic, and the setpoint doesnt actually change.

Am I misunderstanding how this is supposed to work, being able to write to the MQTT broker to make the API call? Am I structuring the Json object incorrectly? In other words is this my fault it isn't working, or is there something going on with the zwave2mqtt app itself? I am attaching some photos showing the receipt of the message, my setup, etc. 

This first one shows that the message was received by z2m:MQTT:

![Screenshot from 2020-12-25 11-52-32](https://user-images.githubusercontent.com/70731780/103141187-1fff2200-46ae-11eb-8b87-c9d1a5a0c127.png)

This one shows the API call from the control panel when I set it from there and that it works:

![Screenshot from 2020-12-25 12-00-22](https://user-images.githubusercontent.com/70731780/103141188-22fa1280-46ae-11eb-8744-94c5227738ed.png)

This one shows the script and the output from the terminal showing that the message was posted to the MQTT broker but I haven't received anything from the MQTT broker indicating there was any sort of response at all:

![Screenshot from 2020-12-25 12-03-03](https://user-images.githubusercontent.com/70731780/103141189-255c6c80-46ae-11eb-9760-f84dc95eadb4.png)

This last one shows the MQTT setup in the control panel if that helps. 

![Screenshot from 2020-12-25 12-12-04](https://user-images.githubusercontent.com/70731780/103141190-268d9980-46ae-11eb-9e3a-3998cd909e7f.png)

**Comment by robertsLando** [comment]
The payload looks good, the topic too as it is received as shown in the logs. Are you able to set breakpoints in the code? I suggest you to set a break on mqttclient message received. Otherwise, this project is going to be replaced by: https://github.com/zwave-js/zwavejs2mqtt

If you just started with z2m I suggest to start with that :)

**Comment by IATLLC** [comment]
Ok thanks, I will switch over to the other project and give that a go. Thanks for the response.
