### ISSUE TITLE
How to configure Node config options for a ZWave device which supports configuration?

### ISSUE THREAD

**Issue by t00** [OpenZWave/Zwave2Mqtt#861]
After reinstalling Home Assistant I thought Zwave2Mqtt is architecturally a better approach allowing separation of device handling and automation. Problem is that my Aeotec Gen5 Meter is sending too much information and this can be configured using ZWave node configuration as described on Home Assistant ZWave integration guide [here](https://community.home-assistant.io/t/aeon-labs-aeotec-home-energy-metre-monitor-uk-eu/30111/10). Configuration does two things: fetches a list of configuration options allowed by the node and provides a way to set a value for each of the options.

How similar configuration can be performed on a node when it is added through Zwave2Mqtt? I was looking for the answer on several forums and surprisingly could not find even a reference so either it is a problem too obvious for anyone but me to notice or it is just not supported and would be a feature request...

**Comment by robertsLando** [comment]
@t00 Just select the node from the table of control panel and all its configuration values will be displayed on node tab

**Comment by t00** [comment]
@robertsLando It looks like these options are not available on the node tab:
![zwave2mqtt_node_config](https://user-images.githubusercontent.com/1933165/103217727-36f17e80-4911-11eb-9fe2-c78a3fd9716c.png)

There are indeed ZWave settings like power level or others, "Configuration" section is empty though. There is no per-option list or a dropdown with options to select i.e. 101 as in the guide linked in the OP.

Could this be related to warnings present in the log, one per each value being processed?

`OpenZWave Warning, Localization::GetGlobalLabel: No globalLabelLocalizationMap for Index Instance`

**Comment by t00** [comment]
Please also see the bottom of the list showing first 10 of 20 entities in the meter with one example config on the right.
![zwave2mqtt_node_config_entities](https://user-images.githubusercontent.com/1933165/103218390-c2b7da80-4912-11eb-9a3e-d33fcf45988a.png)

**Comment by t00** [comment]
I might also add Configuration -> Refresh Values shows a popup "Successfully call api requestAllConfigParams " but nothing changes on screen.

**Comment by robertsLando** [comment]
@t00 Could you also try with https://github.com/zwave-js/zwavejs2mqtt?

**Comment by t00** [comment]
@robertsLando Thanks, I will give it a go. The localization problem I mentioned earlier - is there something I could do to set locale of Zwave2Mqtt once it's installed, maybe this prevents configuration and out of all options I would love to make Zwave2Mqtt working.

**Comment by t00** [comment]
@robertsLando I checked zwavejs2mqtt and it works as expected:

![image](https://user-images.githubusercontent.com/1933165/103262167-f9860300-499b-11eb-9571-005148df4d56.png)

This means there are 2 potentially related issues:
1. Not working locale causing excessive OpenZWave logging of values
2. Configuration not showing available settings for Aeotec Gen 5 meter

Would you like me to report these separately or you'd prefer changing this one to an issue?

**Comment by t00** [comment]
It would also be great if zwavejs2mqtt provided a Home Assistant Supervised plugin as if I understood correctly it is the future of ZWave development for HA?

Consider adding a docker-compose.yml to README so people using supervised can still add zwavejs2mqtt to their setup manually:

```
version: '3.7'
services:
  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:dev
    restart: always
    tty: true
    stop_signal: SIGINT
    networks:
      - hassio
    devices:
      - '/dev/ttyACM0:/dev/ttyACM0'
    volumes:
      - ./store:/usr/src/app/store
    ports:
      - '8091:8091'
networks:
  hassio:
    external: true

```

**Comment by robertsLando** [comment]
> Home Assistant Supervised plugin

Could you tell me more about this? I dunno what you mean here.

> This means there are 2 potentially related issues:

I'm not the author of OZW, also I dunno how it works at low level as I never studied its source code so I cannot help to debug your problem I'm sorry. If it works with zwavejs2mqtt just use that one or no?

**Comment by t00** [comment]
Home Assistant Supervised is just a new name for Hassio setup available for a custom OS (i.e. Debian) rather than using Home Assistant OS but the plugin would work for both HA OS and HA Supervised - it is all more confusing than necessary to me as well. I was just referring to an alternative to OZW plugin https://github.com/hassio-addons/addon-zwave2mqtt but using zwavejs2mqtt instead of OZW.

For now zwave2mqtt works great for me - all features there and it's independent of HA - so I will keep using it.

Regarding OZW locale - the error suggests that locale is not initialised in the docker image, I don't know why and possibly plugin (url above) is to blame.

**Comment by robertsLando** [comment]
@t00 Ok I can ask to the author of zwave2mqtt addon to create one for zwavejs2mqtt

**Comment by robertsLando** [comment]
@t00  https://github.com/hassio-addons/addon-zwave2mqtt/issues/70
