### ISSUE TITLE
[suggestion] Consider Opening up the Wiki for contributions?

### ISSUE THREAD

**Issue by scyto** [OpenZWave/Zwave2Mqtt#862]
**Is your feature request related to a problem? Please describe.**
Getting started with this project is effing hard - the readme.md is uweildly for a noob and contains getting started, development, and other topics all over the place - for example the docker instructions are spread out.  (i only found the zwave database comments on like my 10th past, and i had to use some random google article to tell me what to edit in the UI (like what the heck should one put for setting in ZWAVE etc).

**Describe the solution you'd like**
Open up the wiki page to allow others to contribute documents that can reduce the burden on the readme.md

**Describe alternatives you've considered**
keep as is and no one helps ;-)

**Additional context**
I am happy to consolidate the current docker info onto a docker page and bring it together with some basics of what to do once running,

**Comment by scyto** [comment]
given i only just got the memo on zwavejs2mqtt i just switched to that (was easy as i only one device included, lol).
offer still stands on the docker / wiki docs.  For example this works, i have no idea if it is right / ideal / best..... but happy to learn and document for others :-)

![image](https://user-images.githubusercontent.com/11369180/103393736-255ad300-4ad9-11eb-92a9-02d969fcef70.png)

**Comment by robertsLando** [comment]
I have an open pr on zwavejs to move docs to GitHub docs :) stay tuned

**Comment by scyto** [comment]
Cool, awesome project by the way!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by robertsLando** [comment]
@scyto DOcs available to https://zwave-js.github.io/zwavejs2mqtt/
