### ISSUE TITLE
I have integrated a Schlage FE599 and having MQTT issues

### ISSUE THREAD

**Issue by ml8208** [OpenZWave/Zwave2Mqtt#864]
Hello,

I have connected a Schlage FE599 with Zwave2MQTT and can control the lock perfectly from the zwave control panel. When I do change the lock from unlocked or vice versa it writes the correct true or false value to the MQTT topic. 

The issue I am having is controlling the lock at all from MQTT. if I publish to that same topic the true false value that I am changing in Zwave2mqtt the lock doesn't change state. I can control other devices like dimmer switches through this same Zwave2MQTT integration via MQTT and don't run into any issues. 

Do i need to do anything setup wise on Zwave2MQTT to control a secure Zwave device from MQTT? Or do any other solutions come to mind?

Thank You!

**Comment by robertsLando** [comment]
Could you give a try to 

https://github.com/zwave-js/zwavejs2mqtt

**Comment by ml8208** [comment]
So using that other zwavejs2mqtt tool I get A lot more information about the Zwave devices on the network and am still able to control the lock from Zwave control panel. 

None of the MQTT topics seem to be displaying any fields like Set to change dimmer brightness for example or to lock or unlock. 

What can I try from here?

**Comment by robertsLando** [comment]
@ml8208 YOu can find everything in docs: https://zwave-js.github.io/zwavejs2mqtt/#/

Check https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=set-values
