### ISSUE TITLE
[question] Scenes from z-wave.me zme_wcd2 

### ISSUE THREAD

**Issue by haavardNO** [OpenZWave/Zwave2Mqtt#865]
I am trying to get a z-wave.me wall controller to work with scenes.
I have been able to get it to work in the HA hub that I am coming from, but after transitioning to zwave2mqtt and Home Assistant, I am struggling with this device.

I am able to add with no problems, but it only shows up with a dimmer and battery. I have configured it to send scenes, but cant see anything meaningful in mqtt explorer. I am quite new to this, so fumbling a bit in the dark.
Anyone that can point me in the right direction on how to get this and similar devices to work (with scenes)?

![Skjermbilde 2021-01-04 kl  08 15 02](https://user-images.githubusercontent.com/27728530/103510188-fc359c00-4e64-11eb-9b62-25c7ce9e4d45.png)
![Skjermbilde 2021-01-04 kl  08 15 46](https://user-images.githubusercontent.com/27728530/103510235-14a5b680-4e65-11eb-8987-07e2c86be869.png)

**Comment by robertsLando** [comment]
@haavardNO Have you tried with https://github.com/zwave-js/zwavejs2mqtt?

**Comment by haavardNO** [comment]
@robertsLando , no I have not tried with that version. Sorry for the noob question but what is the difference?
I am running it in docker on a rpi.

**Comment by robertsLando** [comment]
It doesn't use OZW but zwavejs, a new driver, in the near future that will replace this project and this will be archived

**Comment by haavardNO** [comment]
Ok, I understand. I spent some time reading about it yesterday as well. And you confirmed my understanding.
I now have about 40 nodes running in zwave2mqtt that is discovered by Home Assistant. Will it be a smooth transition if I install zwavejs2mqtt? Or do I have to update all the "mapping" of devices?

**Comment by robertsLando** [comment]
@haavardNO It would require some work, all devices should be discovered as before (expect rgb lights for now) but they will have different entity names in some cases and the topics will change. If zwave2mqtt works for you I suggest to wait, I'm speaking with hass core team about an hass addon that will communicate directly with zwavejs2mqtt to create entities (like ozw daemon does now with ozw beta integration)

**Comment by haavardNO** [comment]
@robertsLando It is working good now, except for scene controllers. 
What timeframe are we talking about when moving to zwavejs2mqtt? When could this new communicating be available?

**Comment by robertsLando** [comment]
@haavardNO Don't know, could be some weeks or some months.

**Comment by haavardNO** [comment]
After some more testing I decided to move my network to zwavejs2mqtt. Looks like there is somethings that is not optimal there also, but the performance is much better.
