### ISSUE TITLE
[question] Webinterface missing after update

### ISSUE THREAD

**Issue by raymonvdm** [OpenZWave/Zwave2Mqtt#867]
I have update my Zwave2Mqtt from version 3.4.0 to 4.1.1 using these steps

```
cd /home/homeassistant/
mv Zwave2Mqtt Zwave2Mqtt.old

git clone https://github.com/OpenZWave/Zwave2Mqtt
cd Zwave2Mqtt
npm install
npm run build

cp /home/homeassistant/Zwave2Mqtt.old/store .

npm start
```
But now i`m missing the static files which seem to be needed for http://192.168.1.2:8091/ to be working. 
```
/home/homeassistant/Zwave2Mqtt/dist/
```

**Comment by robertsLando** [comment]
@raymonvdm Could you try using https://github.com/zwave-js/zwavejs2mqtt?

**Comment by raymonvdm** [comment]
> @raymonvdm Could you try using https://github.com/zwave-js/zwavejs2mqtt?

What are the difference`s between these?

**Comment by robertsLando** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/why

**Comment by raymonvdm** [comment]
Not really helping this rookie to understand :-) , but i have cloned the git in a new Zwave2MQTT folder to keep my local wiki relevant and it seems to be working. As i understand this is a new approach of getting Zwave to speak MQTT but with bypassing OpenZwave?

Maybe the approuch helps me to get rid of some strange Z-Wave issues with some devices, for example a not working FireAngel Z-Wave module.

**Comment by robertsLando** [comment]
@raymonvdm Sorry, the difference is that it doesn't require ozw and we are switching to that for the future

**Comment by raymonvdm** [comment]
I understand and i think it is a good way to go. 

But now i`m still experiencing some issues

- I`m missing the logging to file but i found that i should wait for https://github.com/OpenZWave/Zwave2Mqtt/issues/418
- Restart of HomeAssistant leaves me with unavailble devices until i save a setting in the webinterface of ZwaveJS2MQTT
- Notify from Fibaro Universal Binary Sensor is not picked on button press and neather is the temp sensor which is connected to it.
- Notify from Fibaro FGS221 is working in most case (one unit is failing but might be unit related) so some notify from the endpoints is working

**Comment by robertsLando** [comment]
@raymonvdm I don't plan to make those changes in this project, the logging has been improved in the last one I mentioned

**Comment by raymonvdm** [comment]
I`m sorry, it is better to respond to the other project with my questions
