### ISSUE TITLE
[feat] Add support for '/' in MQTT prefix

### ISSUE THREAD

**Issue by kipe** [OpenZWave/Zwave2Mqtt#874]
**Is your feature request related to a problem? Please describe.**
Currently the prefix for MQTT topics only allows "a-z", "A-Z", "0-9", and "_". With the current prefix limitations, it's not possible to just subscribe to `zwave2mqtt/+/#` (for example, using `zwave2mqtt/uuid` as prefix). This would be useful when implementing a server with multiple zwave2mqtt instances connected, allowing the prefix to differentiate instances from each other.

**Describe the solution you'd like**
By allowing "/" as part of prefix, it would be possible use prefixes such as `zwave2mqtt/55976116-d9f0-4c16-891c-e6bd771f550d`. This would allow for more simple listener subscriptions.

**Describe alternatives you've considered**
Currently I'm subscribing to each "prefix-topic" separately, using prefixes like `zwave2mqtt-55976116-d9f0-4c16-891c-e6bd771f550d`. This requires subscriptions to each instance of zwave2mqtt separately.

**Comment by robertsLando** [comment]
@kipe COuld you use: https://github.com/zwave-js/zwavejs2mqtt?

**Comment by robertsLando** [comment]
I can implement it there if you want

**Comment by kipe** [comment]
@robertsLando Thank you, I just started using Z-Wave in general yesterday, so changing to zwavejs2mqtt is no issue. Actually that was my plan anyways, once I stumbled upon it :)

**Comment by robertsLando** [comment]
Open the issue there, will check it later :)
