### ISSUE TITLE
[question] cannot get zwave2mqtt to save changes

### ISSUE THREAD

**Issue by SmartHomeNewbie** [OpenZWave/Zwave2Mqtt#877]
Hello

Ive got some fibaro motion sensors where iam trying to change things like sensitivity in the configuration tab of the node.
the first sensor i've had success chaning some parameters a week or two ago but when im trying now it keep jumping back to default, i guess i must be doing something wrong since it worked for me before?

**Comment by robertsLando** [comment]
@SmartHomeNewbie Could you provide the log output?

**Comment by SmartHomeNewbie** [comment]
Im running in docker, is it the log from portainer you would like to see? else can you specify a bit more, im a newb
[log.txt](https://github.com/OpenZWave/Zwave2Mqtt/files/5821704/log.txt)
had to copy it into a txt file because i dont know how to download it

**Comment by robertsLando** [comment]
@SmartHomeNewbie that's from Zwave2Mqtt, this is zwaveJS2mqtt


Please install the right package and retry :)

**Comment by robertsLando** [comment]
Ops sorry I thought this question was on the other side. Please use this: https://github.com/zwave-js/zwavejs2mqtt

**Comment by SmartHomeNewbie** [comment]
i should use that docker image instead?

**Comment by robertsLando** [comment]
yep
