### ISSUE TITLE
[bug] cannot add multiple entries to gateway table

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#88]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: master @ 20190808
Openzwave Version: 1.6.848

**Describe the bug**
It is impossible to add multiple entries to the t able on the gateway tab. 
Hitting save between each entry does not help either.

**To Reproduce**

[See video](https://imgur.com/aKd586S)

**Expected behavior**
I expect to be able to add multiple entries as I want to manually map only the few parameters/values I am interested in to a fixed and readable mqtt topic

**Comment by robertsLando** [comment]
Really strange... Try this (remember to rebuild)

**Comment by robertsLando** [comment]
Could you also check the console log for errors ?

**Comment by robertsLando** [comment]
@sjorge Now I have fixed, was a typo

**Comment by sjorge** [comment]
Doesn't seem fixed, double checked that I pulled in all changes and rebuild everything.

**Comment by sjorge** [comment]
https://youtu.be/NriB_iJsJ84?t=125

**Comment by sjorge** [comment]
Exact same effect I can only add the main sensor none of the other properties work.

**Comment by robertsLando** [comment]
If you are using chrome open browser console logs and check for errors there. That’s strange :(

Daniel

**Comment by robertsLando** [comment]
Try this please: In Settingns.Vue https://github.com/OpenZWave/Zwave2Mqtt/blob/9424118ffd0c62937f98c9208d6b04692d94a7ab/src/components/Settings.vue#L518

setTimeout(() => {
this.editedValue = Object.assign({}, this.defaultValue);
this.editedIndex = -1;
}.bind(this), 300);

Add ‘.bind(this)’ there

Daniel

**Comment by sjorge** [comment]
This is what I got in the firefox console it seems to hit a null value:
```
ReferenceError: "isSensor is not defined"
    deviceClasses DialogGatewayValue.vue:150
    VueJS 3
        get
        evaluate
        Fe
    render DialogGatewayValue.vue:1
    VueJS 7
        _render
        mount
        get
        run
        Ae
        Zt
        Yt
    exports _invoke.js:5
    <anonymous> _task.js:35
    y _task.js:21
    b _task.js:25
vue.esm.js:1841
    VueJS 10
        zt
        Nt
        Rt
        _render
        mount
        get
        run
        Ae
        Zt
        Yt
    exports _invoke.js:5
    <anonymous> _task.js:35
    y _task.js:21
    b _task.js:25
```

**Comment by sjorge** [comment]
When I try to apply your change I get this when doing the rebuild:

```
ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Settings.vue
Module build failed: SyntaxError: Unexpected token, expected , (521:7)

  519 |         this.editedValue = Object.assign({}, this.defaultValue);
  520 |         this.editedIndex = -1;
> 521 |       }.bind(this), 300);
      |        ^
  522 |     },
  523 |     deviceName(deviceID) {
  524 |       var device = this.devices.find(d => d.value == deviceID);

 @ ./src/components/Settings.vue 3:0-108 4:0-121
 @ ./src/router/index.js
 @ ./src/main.js

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zwave2mqtt@2.0.2 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zwave2mqtt@2.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-08T19_43_28_789Z-debug.log
```

**Comment by robertsLando** [comment]
Ok found the bug. Forgot the previous one, remove the “.bind(this)” and fix in this line:

https://github.com/OpenZWave/Zwave2Mqtt/blob/master/src/components/dialogs/DialogGatewayValue.vue#L155

Add “this.” Before “isSensor”: “this.isSensor(...”

Daniel

**Comment by sjorge** [comment]
Yep, the 2nd change works!

**Comment by robertsLando** [comment]
Sorry for that, now should be fixed
