### ISSUE TITLE
[question] Does zwave2mqtt support symlinks?

### ISSUE THREAD

**Issue by HWL1968** [OpenZWave/Zwave2Mqtt#882]
Hi all,

I am using zwave2mqtt on a raspberry pi and it is working fine.

Now I try to get the system working while using a symlink (to ensure the tty* device doesn't change when the system has to be rebooted. My symlink is: /dev/ttyUSB_ZWave -> ttyACM0

However: I noticed I couldn't get the symlink working (using other software, like domoticz, the symlink works so no issue with that). The symlink is up, the device is working, when using the direct referral (ttyACM0) all is working fine. 

Is a symlink being supported? Or are only certain symlink names supported? 

Best regards,

HWL

**Comment by HWL1968** [comment]
1 addition: I noticed just now the following:
- export the settings (under settings tab)
- edit the configuration by hand and changing the device to the symlink
- uploading the configuration again
- saving

And now the symlink seems to stick. ???

**Comment by robertsLando** [comment]
@HWL1968 Why are you using symlinks? Anyway I suggest you to switch to: https://github.com/zwave-js/zwavejs2mqtt

**Comment by HWL1968** [comment]
Thx for your swift respons.

Reason for using symlinks: when restarting the Pi it is not assured that the tty* device gets the same name and therefor I would have to reconfigure. (has happened a number of times. Yesterday (due to a restart after a power outage) it changed from ttyACM0 to ACM3 and thus zwave2mqtt stopped working. a restart fixed it (changed back to ACM0). Then I wondered why I didn't use the symlink and this issue appeared. If you know a better way to avoid this, I would be happy to use it.

Why not zwavejs2mqtt? I tried it (an alpha version) but wasn't able to get it working on the pi. I saw there is a RC available, will give it a try in due time. The installation manual is quite difficult, do you have an update for the pi?

**Comment by robertsLando** [comment]
@HWL1968 Why don't use docker? ALso about the names of ttys, you can write an UUDEV rule in order to keep the name always the same

**Comment by HWL1968** [comment]
I am not that familiar with docker, what I have seen: you have to pass the device name which would still be ACM0. If this would be the symlink, how is it being treated within the container? ACM0 again?

Regarding UUDEV rules: I am not familiar with them, will have a look. Thx for pointing out.

Also had a look just now at zwavejs2mqtt: can you help me pointing out the installation steps? Couldn't find them but know they have been there. Probalby my fault. Best regards.

**Comment by robertsLando** [comment]
@HWL1968 Installing zwavejs2mqtt is really simple. You just need to have nodejs installed on your rpi and then clone and build the repo: 

```
git clone https://github.com/zwave-js/zwavejs2mqtt
cd zwavejs2mqtt
npm install
npm run build
npm start
```

CHeck docs: https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/quick-start

**Comment by robertsLando** [comment]
@HWL1968 About udev rule check: https://unix.stackexchange.com/questions/66901/how-to-bind-usb-device-under-a-static-name

**Comment by HWL1968** [comment]
@robertsLando: thx for pointing out to udev. That is the way I defined the link to the ZWave controller (I now realize I pointed in the wrong direction as you probably understood 'ln ... '. This way it is being persisted after a reboot and works fine. Can it be that the name is being checked on a certain format? /dev/ttyUSB_ZWave is maybe not an ideal name?
I tried using zwavejs2mqtt running in a docker container. Installed pretty smooth now, thanks for creating. Awesome. I have to dig into it to adjust the configuration while migrating from zwave2mqtt towards the js based version. 
Regarding the original question: my udev config is:
SUBSYSTEM=="tty", ATTRS{idVendor}=="0658", ATTRS{idProduct}=="0200", SYMLINK+="ttyUSB_ZWave", GROUP="dialout", MODE="0666"
Any suggestion how to solve this one? (downloading the config / changing / uploading) still works in the docker container. But the --device=/dev/ttyUSB_ZWave still doesn't work. Probably my fault, but I still don't get the problem.

**Comment by robertsLando** [comment]
@HWL1968 What's the error you get?

**Comment by robertsLando** [comment]
Maybe you have to add your user to `dialout` group

**Comment by HWL1968** [comment]
The issue is, it doesn't stick. When I leave the screen, it changes back to the last setting (yes,, I pressed 'save' :-) ). No error is shown.

I checked the groups pi belongs to (zwave2mqtt and docker both run under pi)... Is member of dialout.

**Comment by robertsLando** [comment]
Try to export the settings, manually add the path in the json then import and save

**Comment by HWL1968** [comment]
Yep, that's working and then it sticks. For now no issue further issue. Noticed it already as mentioned. I was just wondering of there is some kind of check on the name of the device. For me: this is further no issue. (both: zwave2mqtt and zwavejs2mqtt). It was merely a question. Thx for your support.
