### ISSUE TITLE
FGBS001 status changed not relayed to MQTT

### ISSUE THREAD

**Issue by reiniertc** [OpenZWave/Zwave2Mqtt#886]
I have several fibaro FGBS001 sensors added to zwave2mqtt.
If I look at the debug info in zwave2mqtt I can see that sensor changes are happening in zwave:
```
OpenZWave Detail, Node025, Received: 0x01, 0x0d, 0x00, 0x04, 0x00, 0x19, 0x07, 0x60, 0x0d, 0x02, 0x02, 0x20, 0x01, 0x00, 0xa4
OpenZWave Detail,
OpenZWave Info, Node025, Received a MultiChannelEncap from node 25, endpoint 2 for Command Class COMMAND_CLASS_BASIC
OpenZWave Info, Node025, Received Basic set from node 25: level=0. Treating it as a Basic report.
```

Also when I inspect the node, I see this (seems fine to me):
```
{
  "type": "binary_sensor",
  "object_id": "contact",
  "discovery_payload": {
    "payload_on": true,
    "payload_off": false,
    "value_template": "{{ value_json.value }}",
    "device_class": "door",
    "state_topic": "zwave/trapkast/alarm_ab/48/1/0",
    "json_attributes_topic": "zwave/trapkast/alarm_ab/48/1/0",
    "device": {
      "identifiers": [
        "zwave2mqtt_0xd105a054_node25"
      ],
      "manufacturer": "FIBARO System",
      "model": "FGBS001 Universal Binary Sensor (0x1002)",
      "name": "trapkast-alarm_ab",
      "sw_version": "2.01"
    },
    "name": "trapkast-alarm_ab_contact",
    "unique_id": "zwave2mqtt_0xd105a054_25-48-1-0"
  },
  "discoveryTopic": "binary_sensor/trapkast-alarm_ab/contact/config",
  "values": [
    "48-1-0"
  ],
  "persistent": false,
  "ignoreDiscovery": false,
  "id": "binary_sensor_contact"
}
```

But when I check the MQTT trafic in MQTT explorer, there is no MQTT sent when I open/close the contact that is attached to the sensor. The sensors are on/off, so I would expect a result like 

Do I have to configure something to get it to work? Or is this a bug?

ps: (zwave is running fine, mqtt is running fine also)

**Comment by robertsLando** [comment]
@reiniertc Please switch to https://github.com/zwave-js/zwavejs2mqtt

**Comment by reiniertc** [comment]
You suggested me to do the same for another issue (which I solved). But as ling as there is no out of the box install option for home assistant, that’s a no go for me.

I’m looking for an answer to my question “ Do I have to configure something to get it to work? Or is this a bug?”

is there anyone that
Can help me with that?

**Comment by reiniertc** [comment]
well, never mind my questions. Yesterday I installed Portainer in Home Assistant and installed a container with zwavejs2mqt. That worked within 15 minutes and my FGBS001 seems to work fine now :-)
