### ISSUE TITLE
Device discovery and enumeration differs from Zwave SDK PC Controller

### ISSUE THREAD

**Issue by embcla** [OpenZWave/Zwave2Mqtt#888]
Hello

I've got into this because I bought an Aeotec ZW095 Home Energy Meter and, after pairing, it wouldn't accept any command nor send status reports.

Aeotec support had me do stuff with the SDK PC Controller, and the more I fiddle with it the more I realize that when I pair the device via zwave2mqtt, the device does not appear to have all the features and settings as when it's paired via PC Controller.
Unfortunately pairing with PC Controller is not going to work with Home Assistant, as in that case the link in MQTT is not created and I can't find a way to have it created manually.

The stick is an Aeotec gen5.
I want to help isolate what's going on, but I'm not entirely sure how this all works.
If somebody could point me into the right direction I would really appreciate it.

For example: is there a way to get an updated xml from PC Controller and put that into ozw? Would that fix the issues?

**Comment by robertsLando** [comment]
Could you try to use zwavejs2mqtt instead?

**Comment by embcla** [comment]
Eventually I'm going to need the zw2mqtt embedded in HomeAssistant.
For this test I'm going to attempt running the js version in docker on windows and pass the usb stick to it.
Will report back

**Comment by embcla** [comment]
First image is the ZW095 HEM added by zwavejs2mqtt. Added with secure option.
![image](https://user-images.githubusercontent.com/54371771/106137004-642c8900-616a-11eb-8a5c-4694725d4293.png)

Second image is the ZW095 HEM added via PC Controller 5
![image](https://user-images.githubusercontent.com/54371771/106137156-9e962600-616a-11eb-98e8-06249724623a.png)

As you can see there is much more available with PC Controller 5, the command classes are more and there is even security enabled while it wasn't showing for the zwavejs2mqtt even though I had asked for it.

**Comment by robertsLando** [comment]
@embcla By looking at your image seems the version you are running is an old one. Could you try to use the `dev` tag instead to see if it works better?

**Comment by embcla** [comment]
I just pulled it from dockerhub with latest, I'll pull dev

**Comment by embcla** [comment]
So I managed to get it working with zwavejs2mqtt-dev

A few questions now:
1) how long until dev trickles down to latest
2) how long until zwavejs2mqtt is fully integrated into HA (I saw the new repos have been created, but the addon isn't available yet)
3) in case such issues arise, what is the lag between HA and zwavejs2mqtt-dev?

**Comment by robertsLando** [comment]
`dev` points to master branch, `latest` to latest release. TOday I just made I new release so if you pull latest you should be able to see the same as `dev`. 

About the other questions, there is a work in progress, you will see everyhing in next days/weeks
