### ISSUE TITLE
devices doesn't appear on home assistant?[question] 

### ISSUE THREAD

**Issue by ibrahim405** [OpenZWave/Zwave2Mqtt#889]

**Comment by robertsLando** [comment]
Switch to zwavejs2mqtt

**Comment by ibrahim405** [comment]
ok i installed it but same problem no device appear i think the problem in the mqtt cofiguration
`mqtt:
  discovery: true
  discovery_prefix: zwave
  broker: core-mosquitto
  birth_message:
    topic: 'hass/status' # or homeassistant/status if z2m version >= 4.0.0
    payload: 'online'
  will_message:
    topic: 'hass/status' # or homeassistant/status if z2m version >= 4.0.0
    payload: 'offline'
`

**Comment by robertsLando** [comment]
Enable hass discovery in settings

**Comment by ibrahim405** [comment]
it did not work i dont know the reason

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106083410-235e5100-6125-11eb-8ac2-be4dacb4d043.png)

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106083485-412bb600-6125-11eb-986c-bd789e21ae0c.png)
![image](https://user-images.githubusercontent.com/76870757/106083510-4be64b00-6125-11eb-83f3-5aedbb79dcbb.png)
![image](https://user-images.githubusercontent.com/76870757/106083619-7932f900-6125-11eb-8da5-f7a55d14d4c3.png)

**Comment by ibrahim405** [comment]
i use aeotic zwave stick 7 but it works fine with the zwave2mqttjs but nothing appears in the home assistant

**Comment by robertsLando** [comment]
@ibrahim405 Mqtt settings? Is the broker connected?

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106143188-1704e300-617b-11eb-827b-397a840e9e1d.png)

**Comment by ibrahim405** [comment]
![image](https://user-images.githubusercontent.com/76870757/106143308-461b5480-617b-11eb-8249-2b0254438dfd.png)

**Comment by ibrahim405** [comment]
sorry i toke wrong screenshot ...........

**Comment by robertsLando** [comment]
@ibrahim405 I suggest to enable the clean flag on the broker. BTW is the mqtt client connected?

**Comment by ibrahim405** [comment]
how do i know is mqtt client is working

**Comment by ibrahim405** [comment]
done i found the url in the log of the mosquitto broker
thanks alot
