### ISSUE TITLE
[feat] Toggle to include/exclude 'location' from mqtt topic.

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#89]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to skip the 'location' part of the mqtt topic but still have a name and location set for when changing things inside the z2m web interface.

So the topic would look like `<prefix>/<node>/<param>/...

**Describe the solution you'd like**
An additional toggle box above the table 'Add location to mqtt topic' or similar that is true by default would work well.

**Describe alternatives you've considered**
Current workaround is not setting a location and set a name to <location>_<device> this works. But node names get long

**Comment by robertsLando** [comment]
@sjorge Why this? I mean why set a node location and don't add a location to the topic? That should help you to better understand where your values comes from

**Comment by robertsLando** [comment]
> Current workaround is not setting a location and set a name to _ this works. But node names get long

Why node names get long? Just choose shorter node names?

**Comment by sjorge** [comment]
It’s handy to have the information available in z2m where I configure the nodes, but the mqtt messages are processed by stuff that has no need for the info. Having a short mqtt topic that is just the node, param and value is nice and simple.

~ sjorge

**Comment by robertsLando** [comment]
Done
