### ISSUE TITLE
[question] Availability state not set in HA

### ISSUE THREAD

**Issue by william57m** [OpenZWave/Zwave2Mqtt#894]
Hi,

I have a question about the availability in HA. When zwave2mqtt is down, my devices still appears as "available" in HA, they are not greyed out, is there an option to support that?

I know that in zigbee2mqtt, the payload of the devices contains the `availability_topic` which is checking `zigbee2mqtt/bridge/state`.

I tried to do the same in zwave2mqtt by setting the `availability_topic` of my component in "Hass Device Json" but I'm not able to do it properly because the message of `zwave2mqtt/_CLIENTS/ZWAVE_GATEWAY-Mosquitto/status` contains a timestamp, and I'm not able to map the correct value to check if it's true or false. Is there another way to do that?

Would it be possible to embed the `availability_topic` by default in the components?

Thanks

**Comment by robertsLando** [comment]
Switch to: https://github.com/zwave-js/zwavejs2mqtt

Oopen a feature request there if it's not implemented. Also if used with hass I suggest ot give a try also top the integrated zwavejs server with the new hass zwavejs addon

**Comment by william57m** [comment]
Can you tell me what's the difference? Is this version deprecated? (or just for openzwave). Why should I use zwavejs instead? Just trying to understand the benefit.

**Comment by robertsLando** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/getting-started/why
