### ISSUE TITLE
Mesh not drawn correctly when removed node is part of mesh [bug]

### ISSUE THREAD

**Issue by ratsputin** [OpenZWave/Zwave2Mqtt#895]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: Latest
Openzwave Version: 1.6.1789

**Describe the bug**
A node that was previously at address 18 (AEON Labs ZW095 Home Energy Meter Gen5), was removed and is now at 27 is still showing as a neighbor on five nodes at its old address.  Healing the network nor forcing the nodes in question to rebuild their neighbor list has resolved this issue.

Unfortunately, this breaks the Network Graph function badly resulting in random behavior.

**To Reproduce**
I don't know that this is a common behavior but now that my network is in this state, the Network Graph always provides random results.

**Expected behavior**
Unknown/removed nodes still reported as neighbors in the Z-Wave network topology should be mapped appropriately in the network mesh and labeled as "Unknown" or "Removed" as appropriate.

**Additional context**
Topology reported from OZWCP:
```
topo: node=1 6,7,8,9,10,12,15,25,27,30,31,32,33
topo: node=6 1,8,9,12,15,18,26,27,33
topo: node=7 1,8,9,10,25
topo: node=8 1,6,7,9,10,12,15,18,25,26,27
topo: node=9 1,6,7,8,10,12,15,25,26,27,30,31,32
topo: node=10 1,7,8,9,12,15,25
topo: node=12 1,6,8,9,10,15,18,25,27,33
topo: node=15 1,6,8,9,10,12,18,25,26,27,33
topo: node=24 9,25,30,31
topo: node=25 1,7,8,9,10,12,15,18,24,27,28,29,30,31,33
topo: node=26 6,8,9,15,27,33
topo: node=27 1,6,8,9,12,15,25,26,32,33
topo: node=28 25
topo: node=29 25,30
topo: node=30 1,9,24,25,29,31,32
topo: node=31 1,9,24,25,30,32
topo: node=32 1,9,27,30,31
topo: node=33 1,6,12,15,25,26,27
```
Note that 18 shows up as a neighbor to 6, 8, 12, 15, and 25 but not as an active node in the topology.  I realize this may be an edge case; however, I've tried factory-resetting the node in question with no success.  Presumably, this is a bug in the particular device's firmware.  It appears my only alternative is to rebuild my network from scratch.  I have to assume that if this has happened to me it likely has happened to someone else as well, though.

**Comment by robertsLando** [comment]
Switch to https://github.com/zwave-js/zwavejs2mqtt

**Comment by ratsputin** [comment]
Are there any instructions on how to migrate from zwave2mqtt and setup zwavejs2mqtt?  I have no interest in running under docker.

**Comment by robertsLando** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/guide/migrating

**Comment by ratsputin** [comment]
Thank you very much, sir.  Your effort on this is greatly appreciated.  Without your hard work, I'd be stuck on SmartThings.
