### ISSUE TITLE
[bug] 'status' topic send for battery devices

### ISSUE THREAD

**Issue by sjorge** [OpenZWave/Zwave2Mqtt#91]
**Version**

Build/Run method
- [ ] Docker
- [ ] PKG
- [X] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2-master
Openzwave Version: 1.6

**Describe the bug**
I have manual topic configuration enabled, but for my battery device it sends an additonal one that I did not configure 'status' every time the device wakes up.

**To Reproduce**
- configure a few manual topics
- wait for a battery device to wake up

**Expected behavior**
I did not expect to see these 'status' topics.

**Comment by robertsLando** [comment]
Would you like a toggle to disable status updates?

**Comment by sjorge** [comment]
That would work yes!

**Comment by robertsLando** [comment]
Done
