### ISSUE TITLE
[question] Danfoss LC13 not discovering all values

### ISSUE THREAD

**Issue by Wojcioo** [OpenZWave/Zwave2Mqtt#911]
Hello
I have 3 different Danfoss Living Connect Z Thermostat. For two of them all values are identified properly and I can see them in the ZWaveJS2MQTT Control Panel. This are:
climate_thermostat
sensor_battery_level
binary_sensor_battery_islow

But for one I can only:
sensor_battery_level
binary_sensor_battery_islow

I've installed this on RPI3 using this instruction: https://flemmingss.com/how-to-set-up-zwavejs2mqtt-on-a-raspberry-pi-and-integrate-it-with-home-assistant/
My question is, how can I get the other values to show up as home assistant devices?
Cheers,

![image](https://user-images.githubusercontent.com/33394332/108202562-96a22400-7121-11eb-9da3-318aedd1bb24.png)
![image](https://user-images.githubusercontent.com/33394332/108202581-9e61c880-7121-11eb-8a97-5716120088f6.png)

**Comment by robertsLando** [comment]
@Wojcioo Could you open the issue in  the correct repo? This is the old zwave2mqtt.

https://github.com/zwave-js/zwavejs2mqtt
