### ISSUE TITLE
[bug]Danalockv3 recognized as Keypad --> no lock function (Home-Assistant)

### ISSUE THREAD

**Issue by thundergreen** [OpenZWave/Zwave2Mqtt#93]
**Version**
latest
Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

**Describe the bug**
I successfuly added my Danalockv3 to Zwave2Mqtt but it entities won't be lock but only sensors (batteery sensor and binary sensor)

**To Reproduce**
add danalock v3 and see it shows as Keypad

**Expected behavior**

**Additional context**

**Comment by thundergreen** [comment]
additional infor..

After playing a bit around and searching. I found this:

![image](https://user-images.githubusercontent.com/13320319/62827076-58d94c80-bbc8-11e9-8bd7-6281039edacc.png)
under USER of the node i can control the lock but it won't be added for home assistant.

This might be the bug?

**Comment by robertsLando** [comment]
@thundergreen check it now

**Comment by thundergreen** [comment]
Will check this. Has it been pushed already as I am using it with home-assistant. The sensor shows the state of the lock. But let me check this first and I'll report
