### ISSUE TITLE
[question] OpenZwave 1.6 support?

### ISSUE THREAD

**Issue by Lionel642** [OpenZWave/Zwave2Mqtt#94]
Hi;

if I clone, the project, build it and run it, using my also build from clone version of OpenZwave (1.6 head), I see all nodes as dead (I copied the ozw cfg file from version 1 store to this version store folder before starting).

Whereas if I use the version 1 of Zwave2Mqtt downloaded from a zip file, then I can see almost all my nodes as alive and it's working. But it is using version 1.4 of OpenZwave lib and I think the device library has been updated since.

Can the documentation be less confusing about which version of libopenzwave to use?

Thanks, good product, only ZWave stuff, perfect, exactly what I needed (was using node-red before, but hard to manage the nodes with it (no way to add a device etc..)).

Lionel

**Comment by fracarvic** [comment]
Hi, I have version 2.0.2 working perfectly with OpenZwave1.6.

 I'm using node docker image (based on debian) with openzwave.com packages (1.6.878), and build project with npm, and all seems ok.

**Comment by robertsLando** [comment]
@Lionel642 the project is still using version 1.4 of openzwave in docker image but the devices db is fetched from master so it is the latest. The reason why it is not using 1.6 is because 1.6 has been released in latest months and not all things are ready yet oin ozw shared that is the nodejs wrapper for ozw

**Comment by sjorge** [comment]
Same from my experience, 1.4 is overall pretty stable. With 1.6 I am still having a lot of issues, although it is improve thanks to bugs reports and quick fixes from @robertsLando.

So if you see particular things that are broken, it might be worth filing bugs.

**Comment by Fishwaldo** [comment]
Regarding comments around using config files from master. That will not work. The config files formats are different between 1.4 and 1.6. Things will break.

**Comment by rafale77** [comment]
Tried a few things. I tested all from 1.4 and though it is stable, I am missing a few device support, my thermostat for example would be  missing the heat setting. I tried to build with 1.6 which seems to work but as reported above, now I seem to be unable to save the device configuration in store as each reboot or the controller or even pushing a save configuration on the controller would wipe everything.

**Comment by sjorge** [comment]
For my experience it is currently all BitSet values (#90) that are missing, I also noticed that for some reason the valuesare not properly queried from the device at startup. So some always report default. While others read the data from the cache file. I haven't dug further into this as the BitSet one is giving me to many issues and I reverted to z2m 1.0.3 + OpenZwave 1.4 for the time being.

If you have specific issues, it's worth filing seperate bugs for those or commenting on existing ones if they are already open. Although some thing seem to be because the node binding have not caught up yet.

**Comment by electrofloat** [comment]
I'm a bit confused here. @robertsLando is saying still using 1.4 but the device db is fetched from master. @Fishwaldo is saying using config files from master won't work.

So which one is true then?

**Comment by robertsLando** [comment]
Actually the latest image on docker is using config files from the 1.4 branch.

Daniel

**Comment by petergebruers** [comment]
@electrofloat - For reference, this change @robertsLando did, was mentioned a while ago here:

https://github.com/OpenZWave/Zwave2Mqtt/issues/123#issuecomment-534914575

There's some more information about versions there.

**Comment by electrofloat** [comment]
@robertsLando I see. Then I assume this issue will be the reference for 1.6 update, so I remain subscribed here. Thanks!

@petergebruers Thanks!

**Comment by gertvdijk** [comment]
I'm using the 2.0.6-dev Docker image (which is running OZW 1.6) and it feels a lot more stable in my (small) network than the 2.0.6 image (with 1.4). With 1.4 many Z-Wave network messages seem to be lost (10-50% depending on position of the moon) and state updates rarely reach HA properly with Aeotec devices spraying lots of messages on every state change.

From my experience with an Aeotec Z-Wave USB stick and mostly Aeotec Nano products:
- Home Assistant 0.103 native (OZW 1.4): unusable
- Z-Wave2MQTT 2.0.6 (OZW 1.4): unstable, but a bit better than HA native
- Z-Wave2MQTT 2.0.6-dev (OZW 1.6): fine! Just a few delayed messages here and there.

**Comment by robertsLando** [comment]
@gertvdijk Thanks for the feedback!
