### ISSUE TITLE
[bug] HA intergation / MQTT not retained

### ISSUE THREAD

**Issue by pbathuk** [OpenZWave/Zwave2Mqtt#97]
**Version**

Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 2.0.2
Openzwave Version: 1.4.1

**Describe the bug**
When I have z-wave docker already running (built off the latest commit) and restart the Homeassistant docker the auto discovery does not work and all items appear missing, until I either restart the z-wave docker or go into the config and press save to restart the discovery.

**To Reproduce**
1. Launch z-wave with HA discovery turned on
2. Let HA find the devices
3. Restart just HA (docker)
4. HA will show the items as missing

**Expected behavior**
I would expect that the settings be retained in Mqtt by default so that it persists across HA reboots.

**Additional context**
I am running all items in dockers, incase that makes a difference with mosquito Mqtt broker

**Comment by mattgruter** [comment]
@pbathuk Could you check that you have the `Retain` flag checked in the Configuration->MQTT section? Without that option, a restart of HA would show your observed behavior.

**Comment by pbathuk** [comment]
I'll check as soon as I'm back on my home network :)
Thanks

**Comment by pbathuk** [comment]
I just checked and retain is turned on Under that setting menu.

**Comment by mattgruter** [comment]
Thanks for checking.
Does home-assistant MQTT configuration include these lines?

```
mqtt:
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
```

Which version of home-assistant are you using?

**Comment by pbathuk** [comment]
I'm on home assistant 97.2.
I don't have the birth / will messages, I setup z-wave through the interface, should I manually add the above to my config?

**Comment by pbathuk** [comment]
So I can confirm adding Mqtt in the config & having the above with retain: true worked perfectly.

However one thing to note: I have my homeassistant topic setup as 
homeassistant

However for auto discovery to work I have to use 
hass

`discovery_prefix: homeassistant                                                 
   birth_message:
    topic: 'hass/status'
    payload: 'online'
    retain: true
    qos: 2
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    retain: false
    qos: 2                                                                         
`

**Comment by pbathuk** [comment]
I'll close this, however might want to have a note that Mqtt must be manually setup and Hass topic used for the birth / will. :)

**Comment by mattgruter** [comment]
You're right. The topic prefix should be changed to `homeassistant/` to reflect the default configuration of home assistant (https://www.home-assistant.io/docs/mqtt/discovery/).
Thanks for testing and pointing this out.
