### ISSUE TITLE
GE Smart Motion Switch, no motion sensor in Home Assisant

### ISSUE THREAD

**Issue by silfa718** [OpenZWave/Zwave2Mqtt#98]
**Version**

Build/Run method
- [x ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

Zwave2Mqtt version: 1.2.3
Openzwave Version: 1.4.1

I have a GE Smart Motion Switch:

The motion sensor of this switch is not discovered in Home Assistant. What gets discovered is 2 alarm_burgalr and 2 alarm_levels, and 2 switches.

I get this from the json file export from the gateway: "device":"99-12338-18765"

**Comment by robertsLando** [comment]
What is the id of the value? @silfa718

**Comment by silfa718** [comment]
value_id":"112-1-6"

**Comment by robertsLando** [comment]
112 class is for configuration values that's why it isn't discovered. You have to manually add it

**Comment by Seb788** [comment]
I have the GE smart motion dimmer, 
and the motion is reported on  113-1-10 for me, (burglar).
8 = motion
0 and 254 = no motion.

**Comment by silfa718** [comment]
Thanks Seb788, mine is a motion switch not a dimmer.

**Comment by Seb788** [comment]
You are right, it is not discovered, 
What I was looking at in HA is the sensor I had previously manually added.

**Comment by silfa718** [comment]
Can you share the JSON code you used to add it.

**Comment by Seb788** [comment]
I created a binary sensor in HA.

`- platform: template
  sensors:
    computer_room_motion_sensor:
      friendly_name: "Computer Room Motion"
      device_class: motion
      entity_id:
        - sensor.computer_room_motion_template
      value_template: >-
        {{states("sensor.computer_room_motion_template") |float == 8 }}`

**Comment by Seb788** [comment]
And also this sensor in HA
```
  - name: computer_room_motion_template
    platform: mqtt
    state_topic: "zwave/computer_room_light/motion"

```

**Comment by silfa718** [comment]
Thanks for the detailed answer.

> I did not used the discovery hass table,
> I manually added it the gateway table instead.
> ```

Can you share your setting for adding motion to the gateway table.

**Comment by Seb788** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/17815212/63638422-cfecf700-c644-11e9-805b-a1060e11d25b.png)

![image](https://user-images.githubusercontent.com/17815212/63638437-0c205780-c645-11e9-95ba-f54bfe8c4d9b.png)

**Comment by silfa718** [comment]
Yes.

Why would you pick "Burglar" instead of "motion" for the value.

**Comment by Seb788** [comment]
I don't have a motion option,
I get 2 instance of burglar, they both report motion with 8 as value.
